### ISSUE TITLE
Enable read_csv to interpret "Infinity", "+Infinity" and "-Infinity" as floating point values

### ISSUE THREAD

**Issue by cbare** [pandas-dev/pandas#10065]
The strings "Infinity", "+Infinity" and "-Infinity" are commonly used to represent infinite floating point values. It would be great for pandas pd.read_csv to correctly interpret these strings as infinite floating point values or to take a parameter "inf_values" analogous to "na_values" that would allow the caller to specify what they require.

**Comment by jreback** [comment]
``inf/-inf`` case insensitive are already accepted. These are standard.

**Comment by cbare** [comment]
We're reading CSVs produced by Java, which stringifies infinite values as "Infinity" and "-Infinity".

Am I be looking in the right place if I'm poking around in [maybe_convert_numeric()](https://github.com/pydata/pandas/blob/master/pandas/src/inference.pyx#L505).

**Comment by jreback** [comment]
Here is where it would need to be changed: https://github.com/pydata/pandas/blob/master/pandas/parser.pyx#L1474

I think you might just be able to short-circuit with a ``strncasecmp`` (to only compare first n characters), then to compare versus a hash table of allowed values. These c-functions are used because this is a very perf intensive part of the code (iow its hit a lot), so would need some testing to make sure perf is ok.
