### ISSUE TITLE
REGR: indexing with dictionary elements

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#10219]
xref #9877 

regression from 0.16.0

```
df = pd.DataFrame(columns=['A','B'])
df.ix['test1', 'A'] = dict({'1':'test2'})
```

**Comment by jreback** [comment]
@cpcloud

**Comment by jreback** [comment]
@cpcloud if you can have a look

**Comment by jreback** [comment]
@cpcloud ?

**Comment by jreback** [comment]
@cpcloud if you have a chance

**Comment by oguzhanogreden** [comment]
This issue is still present:

```
df = pd.DataFrame(columns=['A','B'])
df.loc['test1', 'A'] = dict({'1':'test2'})
```

I'll try to tackle this soon. A reasonable solution seems like the following:

- if the indexer points to one cell, store `dict`,
- otherwise follow dictionary assignment behavior defined [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#attribute-access).

**Comment by mroeschke** [comment]
Looks like `ix` is removed now so not sure if this is an issue anymore so closing
