### ISSUE TITLE
Feature Request: Add support for 'Allow Large Results' to BigQuery connector

### ISSUE THREAD

**Issue by ptthompsonzul** [pandas-dev/pandas#10474]
gbq.py currently returns an error if the result of a query is what Google considers to be 'Large'.  The google api allows jobs to be sent with a flag to allow large results.  It would be very beneficial to provide this as an option in the BigQuery connector.

**Comment by jorisvandenbossche** [comment]
cc @jacobschaer @sean-schaefer

**Comment by parthea1** [comment]
I've made in improvement to the ``to_gbq`` function in Pull Request #10857 . The pull request hasn't been merged, but keep an eye on it.

The improvement is to add an argument ``destination_table`` to the ``to_gbq`` function  , so that you can redirect the results of a query directly to a BigQuery table instead of a pandas DataFrame. When the ``destination_table`` is specified, I set allowLargeResults to true.

**Comment by jacobschaer** [comment]
Agree with @parthea1 - the reason we didn't add it originally was because we didn't want to support creating tables. Also, we were concerned about how to do this in an intuitive way for users who aren't very familiar with BigQuery. When reading results you are also writing them...

**Comment by parthea** [comment]
@jreback Can this be closed, or do you expect a PR for this?

See my related PR here: #11209

**Comment by jreback** [comment]
moved issue to https://github.com/pydata/pandas-gbq/issues/15
