### ISSUE TITLE
pandas.read_sql_table doesn't support Oracle Synonyms

### ISSUE THREAD

**Issue by amueller** [pandas-dev/pandas#11669]
From what I can see `read_sql_table` has everything necessary to connect to an Oracle database using an SQLAlchemy connection. Unfortunately, it doesn't support `oracle_resolve_synonyms`. http://docs.sqlalchemy.org/en/latest/dialects/oracle.html#synonym-dblink-reflection That means it's not possible to use synonyms for table names, which I think is pretty common in oracle databases.

It would be cool to add this. How hard would that be? I can work on a PR.

**Comment by OmerJog** [comment]
was this resolved?

**Comment by amueller** [comment]
I have no idea. I'm not even sure whose database that was. Feel free to close if it's too obscure.

**Comment by OmerJog** [comment]
@jreback is there something to do here? There isn't much info

**Comment by jreback** [comment]
no this is out of scope

**Comment by sbhoek** [comment]
I agree with amueller. It is logical to add such a feature. Just finished solving problems because it is not possible to indicate "oracle_resolve_synonyms" when invoking df.to_sql(...). FYI: I tried to write to a synonym and I got the following error back from Oracle: "ORA-00955: name is already used by an existing object". Unfortunately, 15 extra lines of code instead of 1 elegant line. Please open this issue again. I can provide you with more information.
