### ISSUE TITLE
Docstring on Styler.apply{,map} is confusing

### ISSUE THREAD

**Issue by pwaller** [pandas-dev/pandas#12148]
[Right now it says](https://github.com/pydata/pandas/blob/564166529071d33844712ab6038f6a237ddcb8f1/pandas/core/style.py#L357):

``` python
    def apply(self, func, axis=0, subset=None, **kwargs):
        """
        Apply a function column-wise, row-wise, or table-wase,
        updating the HTML representation with the result.
        .. versionadded:: 0.17.1
        Parameters
        ----------
        func: function
        axis: int, str or None
            apply to each column (``axis=0`` or ``'index'``)
            or to each row (``axis=1`` or ``'columns'``) or
            to the entire DataFrame at once with ``axis=None``.
        subset: IndexSlice
            a valid indexer to limit ``data`` to *before* applying the
            function. Consider using a pandas.IndexSlice
        kwargs: dict
            pass along to ``func``
        Returns
        -------
        self
        Notes
        -----
        This is similar to ``DataFrame.apply``, except that ``axis=None``
        applies the function to the entire DataFrame at once,
        rather than column-wise or row-wise.
        """
```

I spent ages trying to figure out how to feed any kind of function into this, only to eventually find the [Styler's docstring](https://github.com/pydata/pandas/blob/564166529071d33844712ab6038f6a237ddcb8f1/pandas/core/style.py#L68-L77):

``` python
    """
    Notes
    -----
    Most styling will be done by passing style functions into
    ``Styler.apply`` or ``Styler.applymap``. Style functions should
    return values with strings containing CSS ``'attr: value'`` that will
    be applied to the indicated cells.
    If using in the Jupyter notebook, Styler has defined a ``_repr_html_``
    to automatically render itself. Otherwise call Styler.render to get
    the genterated HTML.
    """
```

Really, the docstring of apply should state that the passed function should return CSS to be applied to the element. Otherwise, it just sounds like something which modifies the data before it is presented.

My use case is that I have a column full of [`uncertainties.ufloat`](https://pythonhosted.org/uncertainties/user_guide.html), and I want to convert them to a particular convenient string representation before they are formatted in a HTML table. I still can't figure out how to cleanly do this...

**Comment by pwaller** [comment]
I think the offending phrase is `"updating the HTML representation with the result"`, which really, I would think meant the resulting HTML content, not the style.

**Comment by TomAugspurger** [comment]
Agreed that the docs could be better here. I originally didn't include any examples since the return value is just `self`, and you wouldn't actually see anything. Might not hurt take an example from the [example notebook](http://pandas.pydata.org/pandas-docs/version/0.17.1/style.html), interested in submitting a fix?

And for your problem with the `ufloat`s, that's just a design error on my part. I'lll get a PR up soon with a `Styler.format` method that will be what you want. You pass in your regular string formatting template, e.g. `df.style.format({':.2%'}`).

**Comment by pwaller** [comment]
@TomAugspurger I actually want to make the format of the ufloat prettier, that is to write a "±" instead of "+/-", so will it be possible to do that too? (e.g, if the parameter passed to format is a callable, run that to format the string).

**Comment by TomAugspurger** [comment]
Yeah, it will take a callable or a string format spec. I think in this case you could So if your uncertainly column is called `margin` you'd have `df.style.format({'margin': '±{.2f}'})` and that will be applied to the column (assuming the `uncertainties` package has hooked up `__format__` to work like that, I haven't tried). Otherwise you can use a callable taking a single value and returning a string.

**Comment by pwaller** [comment]
(Re: your edit, yep, it's `nominal_value ± std_dev`. Maybe this can be achieved with `{.nominal_value:.2f} ± {.std_dev:.2f}`, but it is still nice to have the flexibility of calling arbitrary functions for formatting).
