### ISSUE TITLE
DOC: creating CONTRIBUTING.md from contributing.rst

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12375]
## Pandas Issue Submission Template

This template will help you and us respond to your issues in an efficient and timely manner.
Please fill out all sections and use [github markdown for code blocks](https://help.github.com/articles/basic-writing-and-formatting-syntax/)
#### output of `pd.show_versions()`

so this is what the new ISSUE_TEMPLATE looks like its in `.github/ISSUE_TEMPLATE.md`. Furthermore, now the CONTRIBUTING.md shows up when you create a new issue.

**Comment by jreback** [comment]
of course stylistic changes are welcome :)

there is a PULL_REQUEST.md template we can add as well.

**Comment by jreback** [comment]
I think the CONTRIBUTING.md should simply be: http://pandas.pydata.org/pandas-docs/stable/contributing.html but would have to do this as part of the doc-building process? (e.g. convert the .rst to .md)?

@jorisvandenbossche @TomAugspurger ?

**Comment by TomAugspurger** [comment]
I don't think we need the sentence with "This template will help you...", people will get used to these. Best to keep the boilerplate to a minimum. Could probably scrap the "Please fill out" as well.

Maybe instead of "Actual Behavior" we have "Code Example" or something that really drives home the point that we want a copy-pastable example possible.

Something like:

---

## Code Sample

```python
# A copy-pastable example if possible:
```

## Expected Output

## Versions

Output of `pd.show_versions()`

--- 


The pull request template could have check boxes for

- [ ] Closes #xxxx
- [ ] `git diff upstream/master | flake8 --diff`
- [ ] whatsnew entry

**Comment by jreback** [comment]
ok updated. feel free to mod

**Comment by jreback** [comment]
I have changed this to be a doc generation step to make CONTRIBUTING.md from contributing.rst. This would have to be an external step we only do when we make changes to contributing.rst.

**Comment by jorisvandenbossche** [comment]
Closing this in favor of https://github.com/pandas-dev/pandas/issues/15349
