### ISSUE TITLE
DOC: add IndexSlice docstring + add to api docs

### ISSUE THREAD

**Issue by eontwosixt** [pandas-dev/pandas#12508]
Hello Developers,

I could not find any information about "Pandas.IndexSlice" function in API Reference.There is only one example  at this [link](http://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced-mi-slicers) . I want to filter the pivot table  as in Excel.But i am confused to using between loc(slice(...)) and IndexSlice.Please could you show some practical easy methods  to filter the pivot table.

Thank you very much...

**Comment by jorisvandenbossche** [comment]
Can you give a very concrete example of a dataframe and what you want to achieve? (by the way, for usage questions, something like StackOverflow is often a easier platform to get help) 
Further, everything you can do with ``IndexSlice``, you can also do without it using a more verbose syntax (eg `slice(None)` instead of `:`). 

But indeed, `IndexSlice` should be added to the api overview

**Comment by eontwosixt** [comment]
I had a question on [this link](http://stackoverflow.com/questions/35734146/how-to-filter-values-with-the-spesific-index-in-pivot-table-multidimensional-da/35735000#35735000) in stackover forums.Also I want to filter the multiple index integer values .For example , on 1999 and 2000 years , A country 's Commodity - Transaction and  Quantity  values.
