### ISSUE TITLE
CLN: internal array detection

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12764]
so need to add some functions to replace lots of instance checking for compat in `core/common.py`

```
def is_array_like(arr):
    return isinstance(arr, np.ndarray)
```

analagously to `is_list_like` functions.

These will isolate code changes later.

**Comment by shoyer** [comment]
There are important differences between being a `numpy.ndarray`, and being "array like." The later category arguably includes lots of non-ndarray subclasses such as those from dynd, dask.array, xarray and even Series/DataFrame/Index. So we need to be very clear what we mean by this term. @njsmith makes a further distinction between "array like" and "duck arrays", though I'm fuzzy on the details (he thinks one is a stricter category, though I can't remember which).

I don't think this is a good idea if it's simply an alias for `isinstance(..., np.ndarray)`. It would be another matter if this means checking for duck-type compatibility in some way.

**Comment by njsmith** [comment]
In the numpy documentation and elsewhere, array-like means "thing you can pass to `np.array`". So lists are array-like for example.

This is really different from duck-array, which is our current not-very-established terminology for "thing that quacks like an array" (ie attempts to implement the same API so code can be written which is oblivious to whether it's using a real ndarray or a duck array.) It's something of a hypothetical/aspirational category right now.

The two categories overlap but are distinct -- lists can be array like but are definitely not duck arrays. Sparse or out of core arrays might be duck arrays (they support numpy style indexing and so forth), but could decide they don't want to support `__array__` because making it easy to implicitly instantiate the whole array in memory would be bad. (Scipy.sparse is explicitly written this way.)

That function is just `is_array`, or maybe `is_anyarray` if you want to match `asanyarray`. There's no like about it :-)

**Comment by mroeschke** [comment]
In `pandas/core/inference.py` there's `def is_array_like(obj) -> bool:` which I think captures the spirit of the issues.

Going to close, but happy to reopen if I misunderstood
