### ISSUE TITLE
COMPAT: statsmodels 0.8 release 

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13523]
https://groups.google.com/forum/m/?pli=1#!topic/pystatsmodels/VT24vE45oog

is out in pre release - would be nice to test with pandas (master and release) and report any issues
should also add to the ci once released

https://github.com/statsmodels/statsmodels/

**Comment by jreback** [comment]
cc @jseabold 
cc @josef-pkt
@TomAugspurger

**Comment by TomAugspurger** [comment]
Our (minimal) tests is `stats/tests` all pass for me on statsmodels RC1.

Slightly OT, but I intend to finish up the migration of all the pandas stats stuff to statsmodels in the next couple weeks. I don't think there's much to be done on the pandas side other than deleting code (in .20 maybe?).

**Comment by jreback** [comment]
@TomAugspurger yes. that sounds right about the migration. Though IIRC PanelOLS is not implemented in statsmodels

**Comment by jorisvandenbossche** [comment]
Is there anything more that needs to be done here? Or can this be closed?

**Comment by josef-pkt** [comment]
statsmodels includes pandas 0.18.1 on TravisCI tests, and we are all green there.
I don't know about pandas master.

**Comment by jreback** [comment]
@josef-pkt about what is your schedule for 0.8.0?

**Comment by jreback** [comment]
@josef-pkt do you have a pre-release from conda channel / wheel?

**Comment by josef-pkt** [comment]
(After coming back from vacation I couldn't get my mind away from vector autoregression, so I only started seriously to work on release preparation again last week.)

The rc1 has been on pypi for a while, but all changes since then are in master. I hope to finish up most things and backports by the end of this week, which would mean that the release will be next week.

I'm not involved in conda packaging, but I don't think we have anything there. @TomAugspurger was authoring a conda-forge recipe, as far as I could see.

**Comment by TomAugspurger** [comment]
Conda forge only does official releases at the moment. 
I believe PyPI just has windows wheels atm. We'll need to update the repo with Matthew Brett's Multibuild to get Linux and Mac wheels up. 

Tom

**Comment by jreback** [comment]
closing this we don't have a dependency on statsmodels anymore!
