### ISSUE TITLE
Row based style.apply doesn't modify background colors

### ISSUE THREAD

**Issue by shri** [pandas-dev/pandas#13657]
#### Code Sample, a copy-pastable example if possible

``` py
# add color gradient to column(s)
import numpy as np
import math
from pandas import *
from IPython.display import display, HTML

# color gradient
COLORS = ["#F1F2B5", "#CCD7A5", "#A7BC96", "#82A186", "#5D8677", "#386B67", "#135058"]

# rows/columns to skip applying gradient to
SKIPROWSORCOLUMNS = ["Day","Users"] 

# index in row or columns to skip
SKIPINDICES = [0,1]

# dataframe to operate on
df = DataFrame([["Monday",100,.65,.39,.33],["Tuesday",120,.45,.32,.31],["Wednesday",150,.75,.33,.30]])
df.columns = ["Day","Users","M1","M2","M3"] #column headers

# takes dataframe and colors
# returns colormap
def applyColorGradient(data, colors=COLORS, skiprowsorcolumns=SKIPROWSORCOLUMNS, skipindices=SKIPINDICES):
  numberOfColors = len(colors)
  i = 0
  maxNumberUnset = True
  maxNumber = 0
  while (i < len(data)):
    if (i not in skipindices):
      if(maxNumberUnset):
        maxNumber = data[i]
        maxNumberUnset = False
      else:
        current = data[i]
        if(current > maxNumber):
          maxNumber = current
    i = i + 1
  name = data.name
  dontskip = data.name not in skiprowsorcolumns
  colorArray = [colors[int(math.floor(value/maxNumber*(numberOfColors-1)))] if dontskip and index not in skipindices else '' for index,value in enumerate(data)]
  print(colorArray)
  colorSeries = pandas.Series(["background-color:" + color if color else '' for color in colorArray], name=data.name)
  display(colorSeries)
  return colorSeries


# applying colorgradient to dataframe
gradientdf = df.style.apply(applyColorGradient, axis=1) #0 is used for columns

# display table
display(gradientdf) #0 is used for columns



```
#### Expected Output

With axis = 0, this manages to give each cell a background color that is indicated. When I change this to a row based function, this doesn't color any of the cells, even though the color series are coming in. Is this a bug or am I doing something wrong?
## INSTALLED VERSIONS

commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-91-generic
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8

pandas: 0.17.1
nose: None
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.23.5
numpy: 1.10.4
scipy: 0.17.1
statsmodels: 0.6.1
IPython: 4.2.0
sphinx: None
patsy: 0.4.1
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: None
tables: None
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
Jinja2: None

**Comment by shri** [comment]
It looks like removing the pandas.Series fixed things

**Comment by TomAugspurger** [comment]
It's a bit hard to say, but I think your example will work if you remove the `Series` construction entirely.

```
colorSeries = pandas.Series([...])  # just return the list here
```
The key part is you need the output labels to match the input labels. `Series.apply`, which is used inside `Styler.apply` automatically handles the labels for you, which is why this isn't documented explicitly, but perhaps we can add a note.

**Comment by attack68** [comment]
the heart of this issue is the following code lines:

```        
if axis is not None:
    result = data.apply(func, axis=axis, result_type="expand", **kwargs)
    result.columns = data.columns
```

The `DataFrame.apply` method is asymmetric in how it deals with broadcasting labels to the index or the columns:

```
>>> df = pd.DataFrame([[1,2], [3,4]], index=["a", "b"], columns=["x", "y"])

>>> df.apply(lambda s: ["one", "two"], axis=0)
     x    y
a  one  one
b  two  two

>>> df.apply(pd.Series(["one", "two"], index=["c", "d"]), axis=0)
     x    y
c  one  one
d  two  two
```

Along axis=0, the native index is maintained unless overwritten by the function result object.

```
>>> df.apply(lambda s: ["one", "two"], axis=1, result_type="expand")
     0    1
a  one  one
b  two  two

>>> df.apply(pd.Series(["one", "two"], index=["c", "d"]), axis=1, result_type="expand")
     c    d
a  one  one
b  two  two
```
Along axis=1 (with result_type=expand), the native index is overwritten by RangeIndex unless overwritten by the function result object.

Therefore the `Styler` code manually updates the column names of the result to be equivalent to incoming data.

The alternative of using result_type=broadcast does nothing other than generate problems and not solve the issue.
