### ISSUE TITLE
to_html ignores na_rep when float_format set

### ISSUE THREAD

**Issue by paulperry** [pandas-dev/pandas#13828]
#### Code Sample, a copy-pastable example if possible

http://stackoverflow.com/questions/23700835/pandas-to-html-no-value-representation

df = pd.DataFrame([['A',1.2225],['A',]], columns=['Group','Data'])
df.to_html(na_rep="Ted",float_format='{0:.2f}'.format)
#### Expected Output

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Group</th>
      <th>Data</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td> A</td>
      <td>1.22</td>
    </tr>
    <tr>
      <th>1</th>
      <td> A</td>
      <td> Ted</td>
    </tr>
  </tbody>
</table>

## INSTALLED VERSIONS

commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.2
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by sinhrks** [comment]
Thanks.  Looks to be caused by around here.

When no ``formatter`` is specified, ``float_format`` is being used ignoring ``na_rep``. PR is appreciated.

- https://github.com/pydata/pandas/blob/4c2840e1b055771e740c8096a295ba6136d8302d/pandas/formats/format.py#L1994

- https://github.com/pydata/pandas/blob/4c2840e1b055771e740c8096a295ba6136d8302d/pandas/formats/format.py#L2111
