### ISSUE TITLE
BUG: unstack(fill_value) does nothing when unstacking multiple columns

### ISSUE THREAD

**Issue by jzwinck** [pandas-dev/pandas#13971]
In #9746 we got a `fill_value` argument for `pd.unstack()`.  But it does nothing if we unstack multiple levels at once:

```
df = pd.DataFrame({'x':['a', 'a', 'b'], 'y':['j', 'k', 'j'], 'z':[0, 1, 2], 'w':[0, 1, 2]})
df.set_index(['x', 'y', 'z']).unstack(['x', 'y'], fill_value=0)
```

That gives:

```
     w          
x    a         b
y    j    k    j
z               
0  0.0  NaN  NaN
1  NaN  1.0  NaN
2  NaN  NaN  2.0
```

It should give zeros instead of NaN.

Pandas 0.18.1.

**Comment by jreback** [comment]
multiple unstacks are fraught with issues, see #9023 and #11847

```
In [19]: df = pd.DataFrame({'x':['a', 'a', 'b'], 'y':['j', 'k', 'j'], 'z':[0, 1, 2], 'w':[0, 1, 2]})
    ...: df.set_index(['x', 'y', 'z']).unstack('x', fill_value=0).unstack('y', fill_value=0)
    ...: 
    ...: 
Out[19]: 
   w         
x  a     b   
y  j  k  j  k
z            
0  0  0  0  0
1  0  1  0  0
2  0  0  2  0
```

I'll mark it, but its a rabbit hole.

**Comment by kordek** [comment]
Unstacking is inconsistent since ``_unstack_frame`` is used if column name is passed to ``unstack()`` and ``_unstack_multiple`` if the list is passed. Maybe it would be OK to play a little and make it more consistent? Or there is some reason (which I am not aware of), for this (almost) complete separation?
