### ISSUE TITLE
BUG: conversion precision on Timedeltas

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14156]
I think this is rounding prematurely, though not entirely sure. Could also just be loss of precision when converting from a float -> int64.

```
In [12]: pd.to_datetime(1434743731.8770001,unit='s')
Out[12]: Timestamp('2015-06-19 19:55:31.877000')

In [13]: pd.to_datetime(1434743731.8770001,unit='s').value
Out[13]: 1434743731877000000

In [14]: (pd.Timestamp('2015-06-19 19:55:15.877000')+pd.Timedelta('1us')).value
Out[14]: 1434743715877001000

```

**Comment by jorisvandenbossche** [comment]
Copying from #19680 

It happens in this function:

```
In [126]: pd._libs.tslibs.timedeltas.cast_from_unit(1.5e-6, 's')
Out[126]: 2000
```

because we round at 6 decimals:

https://github.com/pandas-dev/pandas/blob/405ed25b214740f2e0457ee84007567072b6fd18/pandas/_libs/tslibs/timedeltas.pyx#L210-L212

https://github.com/pandas-dev/pandas/blob/405ed25b214740f2e0457ee84007567072b6fd18/pandas/_libs/tslibs/timedeltas.pyx#L234

Not fully sure why we choose 6 decimals to be allowed, and not 9 in case of 's' (and 6 in case of 'ms', 3 for 'us', ..)

**Comment by Sup3rGeo** [comment]
Isn't this the same as #12690?

**Comment by jorisvandenbossche** [comment]
Indeed, will close the other in favor of this one. Thanks for noticing!
