### ISSUE TITLE
Pandas can read first 216 lines, but not first 217 lines.

### ISSUE THREAD

**Issue by alexanderwhatley** [pandas-dev/pandas#14566]
Posted on Stackoverflow: [Tested](http://stackoverflow.com/questions/40290262/pandas-fails-to-read-past-216th-line-of-jagged-text-file/40290886#40290886) on Python 2.7, 3.5 - Pandas 0.18.1.

Given the following file: https://gist.github.com/alexanderwhatley/e07af297b1a10cd5cb57c7b75ee7f229, I tried reading the first 216 lines which worked, and then the first 217 lines, which failed. Since 216 does not seem to be a special number, it seems like this may be an issue with Pandas, and not with the file.....

`>>> df = pd.read_table("test.txt", names = range(2000), nrows = 216)
>>> df = pd.read_table("test.txt", names = range(2000), nrows = 217)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexwhatley/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/alexwhatley/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 321, in _read
    return parser.read(nrows)
  File "/Users/alexwhatley/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 815, in read
    ret = self._engine.read(nrows)
  File "/Users/alexwhatley/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1314, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 805, in pandas.parser.TextReader.read (pandas/parser.c:8748)
  File "pandas/parser.pyx", line 839, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:9208)
  File "pandas/parser.pyx", line 881, in pandas.parser.TextReader._read_rows (pandas/parser.c:9731)
  File "pandas/parser.pyx", line 868, in pandas.parser.TextReader._tokenize_rows (pandas/parser.c:9602)
  File "pandas/parser.pyx", line 1865, in pandas.parser.raise_parser_error (pandas/parser.c:23325)
pandas.io.common.CParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.`

**Comment by stonebig** [comment]
in pure number of bytes, it's not far from 256K... maybe it didn't detect the line return ?

**Comment by dhimmel** [comment]
Hey @alexanderwhatley I noticed your [`genes.tsv`](https://gist.github.com/alexanderwhatley/e07af297b1a10cd5cb57c7b75ee7f229) file is from MSigDB. As I [discovered for myself recently](https://thinklab.com/discussion/msigdb-licensing/108 "MSigDB licensing on Thinklab"), MSigDB has a draconian license that likely forbids your sharing of the data via a gist. The relavant section of [the license](http://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/License_info "The GSEA software and the Molecular Signatures Database License") is:

> 2.2 No Sublicensing or Additional Rights. In no event shall LICENSEE sublicense or distribute, in whole or in part, the PROGRAM, modifications, BUG FIXES, or the DATABASE, without prior permission from MIT. LICENSEE agrees not to allow any non-employee of LICENSEE to access, view, or use the PROGRAM or the DATABASE, unless such person is an independent contractor performing services on behalf of LICENSEE. LICENSEE agrees not to put the PROGRAM or the DATABASE on a network, server, or other similar technology that may be accessed by any individual other than the LICENSEE.

Note that this license applies restrictions beyond copyright, since it's a contractual agreement between the licensee and MIT. Therefore, fair use is not a consideration here.

Not that I'm saying that you should take down your gist or this pull request -- obviously there's value in both. I just want to highlight a potential application that MIT technically precludes with their licensing of publicly funded research.

**Comment by alexanderwhatley** [comment]
Hey dhimmel, good catch, I was not aware of that restriction. I updated the file by deleting the gene names and adding placeholders in place of each gene name. Thanks.

**Comment by dhimmel** [comment]
@alexanderwhatley another note is that the file is not tabular -- each row has a different length.

Here's a function I wrote for reading GMT files:

```python
def read_gmt(path):
    """Generate rows from a .gmt file."""
    read_file = open(path)
    reader = csv.reader(read_file, delimiter='\t')
    for row in reader:
        name = row[0]
        description = row[1]
        genes = set(row[2:])
        yield name, description, genes
    read_file.close()
```

I'd recommend using something like this rather than `pandas.read_table`.

> I updated the file by deleting the gene names and adding placeholders in place of each gene name. Thanks.

The revision history still has the infringing material. Not saying you should delete, just letting you know.

**Comment by jorisvandenbossche** [comment]
@alexanderwhatley Is the current file available on the link you gave above (https://gist.github.com/alexanderwhatley/e07af297b1a10cd5cb57c7b75ee7f229) still valid? As this only contains one single huge row.

**Comment by dhimmel** [comment]
@jorisvandenbossche use the [version-specific link](https://gist.github.com/alexanderwhatley/e07af297b1a10cd5cb57c7b75ee7f229/e89f6da38d97ce39be08de8ae9b3531deb3018e0) to see the file corresponding to the original post.

I haven't looked too much into this issue, although the file is not a table (it's ragged -- different row lengths), so I'm not sure this issue is worth looking into.

**Comment by jorisvandenbossche** [comment]
@dhimmel I am not going to look for a fix myself, but just want to make sure that there enough info for someone to work on it. Otherwise it should be closed. Thanks for the link to the original file.

It seems it has something to do with the number of columns. @alexanderwhatley if you pass less column names (you only have maximum , it works:

```
In [25]: pd.read_csv("https://gist.githubusercontent.com/alexanderwhatley/e07af297b1a10cd5cb57c7b75ee7f229/raw/e89f6da38d97ce39be08de8ae9b3531deb3018e0/genes.txt", 
                     sep="\t", names=range(2000), header=None)
...
ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.

In [26]: pd.read_csv("https://gist.githubusercontent.com/alexanderwhatley/e07af297b1a10cd5cb57c7b75ee7f229/raw/e89f6da38d97ce39be08de8ae9b3531deb3018e0/genes.txt", 
                     sep="\t", names=range(500), header=None)
Out[26]: 
                                                  0    \
0                     KEGG_GLYCOLYSIS_GLUCONEOGENESIS   
1                        KEGG_CITRATE_CYCLE_TCA_CYCLE   
....
```

**Comment by mroeschke** [comment]
Closing as this appears to work now
