### ISSUE TITLE
Segfault on Linux with 0.19.1

### ISSUE THREAD

**Issue by matthew-brett** [pandas-dev/pandas#14726]
I'm getting a segfault on my Linux machines with the following:

```
from datetime import datetime
import pandas.tseries.offsets as offsets
from pandas.tslib import Timestamp

dt = datetime(2011, 1, 1, 9, 0)
tz = 'dateutil/Asia/Tokyo'
offset_s = offsets.LastWeekOfMonth(n=1, weekday=5)
expected = Timestamp('2011-01-29 09:00:00')
expected_localize = expected.tz_localize(tz)
result = Timestamp(dt, tz=tz) + offset_s
expected_localize = expected.tz_localize(tz)
```

Here's a script to reproduce on a clean debian-stable docker container:

```
docker run --rm -ti -v $PWD:/io debian:stable /bin/bash
```

```
apt-get update
apt-get install -y wget python-minimal
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install pandas
cat > pandas_segfault.py << EOF
from datetime import datetime
import pandas.tseries.offsets as offsets
from pandas.tslib import Timestamp

dt = datetime(2011, 1, 1, 9, 0)
tz = 'dateutil/Asia/Tokyo'
offset_s = offsets.LastWeekOfMonth(n=1, weekday=5)
expected = Timestamp('2011-01-29 09:00:00')
expected_localize = expected.tz_localize(tz)
result = Timestamp(dt, tz=tz) + offset_s
expected_localize = expected.tz_localize(tz)
EOF
python pandas_segfault.py
```

Segfault from manylinux wheel up on pypi, and install from source of 0.19.1  . No segfault from current master.

Worth a point release to fix?

**Comment by jorisvandenbossche** [comment]
@matthew-brett Thanks for reporting. See also https://github.com/pandas-dev/pandas/issues/14621, which is probably the same issue and is indeed already fixed in master. Workaround for now is to use an older version of dateutil or just to use `'Asia/Tokyo'` instead of `'dateutil/Asia/Tokyo'`.

We are certainly planning a 0.19.2 release, and are also going to include python 3.6 compat in that.
