### ISSUE TITLE
DOC: Exponentially Weighted Windows page not showing formulas

### ISSUE THREAD

**Issue by flaviodrt** [pandas-dev/pandas#15469]
The Exponentially Weighted Windows page is not rendering the formulas in LaTeX format.
http://pandas.pydata.org/pandas-docs/stable/computation.html#exponentially-weighted-windows

**Comment by chris-b1** [comment]
Thanks for the report.  Seemed to work as of 0.18.1.  @jorisvandenbossche any ideas?
http://pandas.pydata.org/pandas-docs/version/0.18.1/computation.html#exponentially-weighted-windows

**Comment by jorisvandenbossche** [comment]
Probably the reason was just that I did something wrong when building those docs at the time of release (didn't configure my latex well or so). In any case, the `pngmath` sphinx extension was deprecated, and we switched to using mathjax (no latex required anymore) in #15618 so that also fixes this issue.

**Comment by jorisvandenbossche** [comment]
I could update the current stable docs though, to fix this there as well.

**Comment by jreback** [comment]
docs are renders nicely!

related example http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.ewm.html#pandas.DataFrame.ewm

should we change the doc string to render with the formulas as well?

of course the text based might not be as nice then

is the link at the end rendered correctly? (it is fully written out is that how we do it)?
