### ISSUE TITLE
Update plotting functions to use the new Matplotlib default styles

### ISSUE THREAD

**Issue by apcamargo** [pandas-dev/pandas#15495]
In version 2.0.0, Matplotlib introduced several changes in it's default style. Pandas plotting functions should be updated to use the new style.

http://matplotlib.org/users/dflt_style_changes.html

**Comment by jorisvandenbossche** [comment]
Can you give specific examples of where the plot needs to be updated? I don't think we are using much hard-coded style elements in the plot method.

If you are talking about the documentation (http://pandas.pydata.org/pandas-docs/stable/visualization.html), we are already using the `style` support of matplotlib, but using the 'ggplot' style instead of the default (but that is just for the docs, not for the default that users get when plotting). So for this, we could indeed switch to the default style again now this has been improved.

**Comment by apcamargo** [comment]
One thing that I've noticed is that Pandas doesn't use the new behavior for axis limits:

Pandas:
![pandas](https://cloud.githubusercontent.com/assets/22940964/23305377/447bf42c-fa7d-11e6-8d2f-46a2aba318ef.png)

Matplotlib:
![matplotlib](https://cloud.githubusercontent.com/assets/22940964/23305376/447b70ce-fa7d-11e6-92f6-9ca0d578ffc9.png)

**Comment by jorisvandenbossche** [comment]
@apcamargo Thanks for the example.

Pandas does a `set_xlim` based on the data when plotting (see https://github.com/pandas-dev/pandas/blob/1400305899d55bee21253952de9f6f0cf245b089/pandas/tools/plotting.py#L1749), although I am not sure why this was initially done. 
I thought this was because matplotlib did not do that automatically when you added more lines to an `ax`, but that does not seem to be the case (unless that was the case for older matplotlib versions).

cc @TomAugspurger @sinhrks do you know the reason(ing) for updating the xlims based on the data?

**Comment by TomAugspurger** [comment]
> I thought this was because matplotlib did not do that automatically when you added more lines to an ax, but that does not seem to be the case (unless that was the case for older matplotlib versions).

I think that's correct. IIRC this was changed in MPL 1.5ish. We could probably skip the `set_xlim` on newer version of matplotlib.

**Comment by jorisvandenbossche** [comment]
@apcamargo Interested to make a PR to change this? 
If you have other examples where we conflict with the new defaults, that is also always welcome

**Comment by TomAugspurger** [comment]
FYI I think [this](
http://matplotlib.org/users/prev_whats_new/whats_new_1.5.html#interactive-oo-usage)
is the relevant change in matplotlib.

**Comment by jorisvandenbossche** [comment]
In that whatsnew entry, they talk about 'interactive usage', so will that updating of the axes not be the case in non-interactive usage? That's not fully clear to me, but important for pandas I think if we could remove the `set_xlim`. 
I just tried, but still get updated xlims when not displaying the figure in the notebook but just saving it.

**Comment by apcamargo** [comment]
So, to fix this the line `ax.set_xlim(left, right)` in plotting.py should be deleted. I've tested this change and the issue was fixed.
Should this behavior depend on the Matplotlib version?

**Comment by TomAugspurger** [comment]
> Should this behavior depend on the Matplotlib version?

Yep. It should be in an `if` block that only applies to older versions. I think something like

```python
if not self.mpl_ge_1_5_0():
    ax.set_xlim(left, right)
```

should work.

**Comment by jorisvandenbossche** [comment]
We could also only do this for 2.0 and above to be safe (for lower versions it would also not have any impact, since the default xlim would be the same as what pandas now does).

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/16600
