### ISSUE TITLE
API/DEPR: deprecate SparseSeries.from_coo and accept in constructor

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15634]
xref #15497 

using ``SparseDataFrame`` as the model.

**Comment by jreback** [comment]
cc @kernc

**Comment by kernc** [comment]
So how would this work? The exact same functionality as currently in `.from_coo` which assigns a multiindex? Note, series from_coo is currently different from any series sliced from a sparse data frame:
```py
>>> spm = scipy.sparse.coo_matrix(np.eye(5))

>>> pd.SparseSeries.from_coo(spm)
0  0    1.0
1  1    1.0
2  2    1.0
3  3    1.0
4  4    1.0
dtype: float64
BlockIndex
Block locations: array([0], dtype=int32)
Block lengths: array([5], dtype=int32)

>>> pd.SparseSeries.from_coo(spm.tocsr()[0].tocoo())  # first row only
0  0    1.0
dtype: float64
BlockIndex
Block locations: array([0], dtype=int32)
Block lengths: array([1], dtype=int32)

>>> pd.SparseDataFrame(spm).iloc[0]  # first row sliced from df
```

**Comment by jreback** [comment]
Looking at this again, I think we should just fully deprecate this method. You can do the exact same thing with ``SparseDataFrame`` and its more natural. Though I can see a MultiIndex with a set of data is pretty much what COO is.

I could see ``SparseSeries`` accepting a 1-d sparse structure though (is there a concept in scipy)?

Maybe have a read in the original issue and see that the use was.

**Comment by kernc** [comment]
> a MultiIndex with a set of data is pretty much what COO is

But that's an implementation detail of what is generally an arbitrary n-d structure. `(row, col), value` triplets could be just as well (or better) be represented with a non-sparse Series.

> I could see SparseSeries accepting a 1-d sparse structure though (is there a concept in scipy)?

All scipy sparse matrces are `ndim == 2`. Since `spm.mean(0)` is a 1x5 matrix, we still might accept such a matrix in the constructor when any dimension has length 1. Will prepare something. Is it too late to get it in v0.20.0?

-----

`to_coo`/`from_coo` introduced in PR https://github.com/pandas-dev/pandas/pull/9076 fixing https://github.com/pandas-dev/pandas/issues/8048.
The main use case seems to have been the use of [`SparseSeries.unstack()` to shape the MultiIndex sparse series into a sparse data frame](https://github.com/pandas-dev/pandas/issues/8048#issuecomment-52427404). So indeed, using the frame is more natural.

**Comment by jreback** [comment]
@kernc yeah the more I look at this the more I think we should just remove these from ``Series`` entirely. Is there truly a useful case for having them on ``Series``?

**Comment by jreback** [comment]
> Will prepare something. Is it too late to get it in v0.20.0?

yes; to the extent that something is a true bug fix or simply an enhancement it can go in a point release (e.g. 0.20.1)
