### ISSUE TITLE
BUG: scatter plot with categorical data raises KeyError

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#16199]
```python
df = pd.DataFrame({'x':[1,2,3,4], 'y':pd.Categorical(['a', 'b', 'a', 'c'])})
df.plot(x='x', y='y', kind='scatter')
```

raises `KeyError: 'y'`, while the column certainly exists, which can be very confusing. 
Without the scatter (just `df.plot(x='x', y='y')`), it raises the more informative `TypeError: Empty 'DataFrame': no numeric data to plot`

**Comment by stangirala** [comment]
@jorisvandenbossche Seems like a simple fix that would check the types of x and y at https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_core.py#L831?

**Comment by TomAugspurger** [comment]
@stangirala it may have to be earlier, somewhere around https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_core.py#L335

The issue is we drop non-numeric columns fairly early on, and by the type you get to https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_core.py#L831, the `data` passed to that method already doesn't have the categorical column.

The cleanest way might be to modify `MPLPlot._compute_plot_data` to check if `self.x` and `self.y` are not in `numeric_data` before setting `self.data = numeric_data`.

**Comment by stangirala** [comment]
@TomAugspurger I see. But it looks like PlanePlot has checks on x and y and not MPLPlot, https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_core.py#L770. The error in the code sample above passes the check in MPLPlot at https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_core.py#L335 because x is numeric. So the check would go in PlanePlot right?

**Comment by jorisvandenbossche** [comment]
@stangirala Another interesting area to contribute, however a much bigger issue, is to actually better support categorical data (as the above example *could* work)

**Comment by stangirala** [comment]
@jorisvandenbossche Maybe you can open a new issue for it? :D It seems like we would have a flag for most plots that would wholesale convert categorical data to a label-to-integer mapping?

But I don't think it would make much sense for a scatter plot that requires an inherent ordering. But having equivalent categorical plots is a good idea, for example parallel_sets, https://github.com/pandas-dev/pandas/issues/12341

**Comment by jorisvandenbossche** [comment]
There are already some issues about it, eg #12341 

> But I don't think it would make much sense for a scatter plot that requires an inherent ordering.

Do you mean you think it won't make sense for a scatter plot to support categorical data? I think it could make sense, where you basically use the underlying codes of the categorical as the values to plot

**Comment by stangirala** [comment]
Oh I meant would someone want a scatter plot for categorical data when most of the times the categories don't have an ordering? I mean in such case won't someone want to use a box plot for example assuming y data is numeric and x is categorical?

**Comment by TomAugspurger** [comment]
supporting categorical in `scatter` would be nice when you have a single observation per category. More like a dot plot.

**Comment by stangirala** [comment]
@TomAugspurger I see, a dot plot would make sense. I don't see an issue for this, do I open one?

**Comment by TomAugspurger** [comment]
We can use https://github.com/pandas-dev/pandas/issues/9069 I think.
