### ISSUE TITLE
BUG: Index.insert should coerce to the appropriate type

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16277]
xref to #14535 (PR to fix, but stale)

```
# NG, must be float dtype
pd.Index([1]).insert(1, 1.0)
# Int64Index([1, 1], dtype='int64')

# NG, must be object dtype
pd.DatetimeIndex(['2011-01-01']).insert(1, 1)
# TypeError: cannot insert DatetimeIndex with incompatible label
```

Expected
```
pd.Index([1]).insert(1, 1.0)
# Float64Index([1.0, 1.0], dtype='float64')

pd.DatetimeIndex(['2011-01-01']).insert(1, 1)
# Index([2011-01-01 00:00:00, 1], dtype='object')
```

**Comment by jreback** [comment]
cc @gfyoung @toobaz if you have interest

**Comment by gfyoung** [comment]
How functional is the patch by @sinhrks ?

**Comment by jreback** [comment]
yes it's prob almost there

**Comment by jbrockmendel** [comment]
OK to just fix or need a deprecation cycle?

- IntervalIndex raises on mismatch
- PeriodIndex casts to object on mismatch (not even trying to cast strings, which is inconsistent with other setitem-like methods)
- DTI/TDI cast to object when they see a str (not even trying to cast), otherwise raises on mismatch
- CategoricalIndex raises on mismatch
- NumericIndex if anything try _too_ hard to cast, e.g. inserting True will cast to 1, which I think it should not.

**Comment by jbrockmendel** [comment]
after #40096 all thats left is IntervalIndex (and some tuple cases)

**Comment by jbrockmendel** [comment]
IntervalIndex now does this too, though not sure when that change was made.  Closing as complete.
