### ISSUE TITLE
0.20.0 documentation styling and javascript assets are broken

### ISSUE THREAD

**Issue by pwaller** [pandas-dev/pandas#16352]
I followed the [WhatsNew](http://pandas.pydata.org/pandas-docs/version/0.20.0/whatsnew.html) link for version 0.20.0 from the [Releases](https://github.com/pandas-dev/pandas/releases/tag/v0.20.0) page, and faced a page with no style (expand details below to see screenshot).

<details>

![image](https://cloud.githubusercontent.com/assets/438648/26036976/fd3f61d0-38d8-11e7-81db-cb72f6f87a92.png)

</details>

---

The reason seems to be that the webserver is misconfigured, for instance, the [following link](http://pandas.pydata.org/pandas-docs/version/0.20.0/_static/jquery.js) (a dependency of `whatsnew.html`) loads HTML, and not javascript:

```
$ curl -si http://pandas.pydata.org/pandas-docs/version/0.20.0/_static/jquery.js | head -n20
HTTP/1.1 200 OK
Server: nginx/1.0.5
Date: Sun, 14 May 2017 19:13:54 GMT
Content-Type: text/html
Content-Length: 25789
Last-Modified: Fri, 05 May 2017 21:21:06 GMT
Connection: keep-alive
Accept-Ranges: bytes

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-27880019-2']);
```

**Note**: I realise that the latest stable docs don't have this problem, but I thought this was worth reporting nonetheless.

**Comment by jorisvandenbossche** [comment]
The reason for that is because we used the wrong links in that announcement. It should be http://pandas.pydata.org/pandas-docs/version/0.20/whatsnew.html instead of http://pandas.pydata.org/pandas-docs/version/0.20.0/whatsnew.html, and that link should work fine normally.

The reason we didn't update it is because then the sha256 hash of the zip archives of the release also change, although probably since there is already 0.20.1, it would not give much problems to update the links now (@TomAugspurger ok to change?)
