### ISSUE TITLE
Pandas read_csv out of memory even after adding chunksize

### ISSUE THREAD

**Issue by gk13** [pandas-dev/pandas#16537]
#### Code Sample, a copy-pastable example if possible

```python
dataframe = pandas.read_csv(inputFolder + dataFile, chunksize=1000000, na_values='null', usecols=fieldsToKeep, low_memory=False, header=0, sep='\t')
tables = map(lambda table: TimeMe(foo)(table, categoryExceptions), dataframe)

def foo(table, exceptions):
    """
    Modifies the columns of the dataframe in place to be categories, largely to save space.
    :type table: pandas.DataFrame
    :type exceptions: set columns not to modify.
    :rtype: pandas.DataFrame
    """
    for c in table:
        if c in exceptions:
            continue

        x = table[c]
        if str(x.dtype) != 'category':
            x.fillna('null', inplace=True)
            table[c] = x.astype('category', copy=False)
    return table
```
#### Problem description
I have a 34 GB tsv file and I've been reading it using pandas readcsv function with chunksize specified as 1000000. The coomand above works fine with a 8 GB file, but pandas crashes for my 34 GB file, subsequently crashing my iPython notebook.

**Comment by jreback** [comment]
pls show ``pd.show_versions()``.

if the above is all you are doing, then it should work. exactly where does it run out of memory?

**Comment by gk13** [comment]
I'm running it on a Jupyter notebook, and it crashes (Kernel dies) after processing 124 chunks of this data.

**Comment by gk13** [comment]
There is no Error in the output, the notebook crashes before that

**Comment by TomAugspurger** [comment]
Not to be pedantic, but are you sure your file is tab-separated? I've had an issue where I passed the wrong separator, and pandas tried to construction a single giant string which blew up memory.

**Comment by gk13** [comment]
Yes , I verified that too, it's tab separated :)

**Comment by gk13** [comment]
The same function worked for a 8 GB version of the file

**Comment by jreback** [comment]
@gk13 you would have to show more code. It is certainly possible that the reading part is fine, but your chunk processing blows up memory.

**Comment by gk13** [comment]
Ive updated the code below. It blows up after processing foo 124 times

**Comment by jreback** [comment]
this keeps the reference around, you an ``gc.collect()`` or better yet is not to even use ``inplace``.

**Comment by gk13** [comment]
I tried gc.collect() before returning from foo, didn't help.

**Comment by gk13** [comment]
Any other suggestions?

**Comment by ukirik** [comment]
Not sure if it's exactly the same issue but I am having similar problems as well. I think there is something fishy with the chunking of csv_reader. Similar to gk13, I have a large text file (tab separated), which gets processed in chunks (of 50 000 lines), so that at no point does the data frame get too big (i.e. I do no concat or similar operation on df). The parser class accumulates whatever relevant into into a list of tuples, which naturally grows in size, but not into absurdity.

```
def main():

    infile = os.path.join(args.input_folder, args.file)
    with open(infile, 'r') as f:
        parser = MyAwesomeParser()
        reader = pd.read_csv(f, delimiter='\t', iterator=True)

        first_chunk = reader.get_chunk(size=50000)
        df = pd.DataFrame(first_chunk)
        # Creates valid column names for pandas
        colnames = [col.strip().replace(" ", "_") for col in df.columns]

        loop = True
        while loop:
            df.columns = colnames
            loop = processChunk(df, parser, args.sorted)
            df = pd.DataFrame(reader.get_chunk(size=50000))

        outputResults(parser)
```

The problem is that the last iteration of `get_chunk()` throws a memory error, even though there is plenty of memory available (which I double check both by debug lines and activity monitor in OSX).

```
ufuk:~/Projects/HMM/refactored> python parseMQ.py -i ../ck_data/ -f sorted2.txt --sorted -o ../ck_data/ -d
Data Frame:   72,910,244
Parser    :          641
Enter to continue...
Data Frame:   65,268,283
Parser    :   66,197,268
Enter to continue...
Data Frame:   62,163,630
Parser    :  120,607,510
Enter to continue...
Data Frame:   60,731,871
Parser    :  169,141,939
Enter to continue...
Data Frame:   58,699,563
Parser    :  215,870,535
Enter to continue...
Data Frame:   57,685,443
Parser    :  258,074,342
Enter to continue...q^CTraceback (most recent call last):
  File "parseMQ.py", line 355, in <module>
    main()
  File "parseMQ.py", line 176, in main
    loop = processChunk(df, parser, args.sorted)
  File "parseMQ.py", line 190, in processChunk
    input("Enter to continue...")
KeyboardInterrupt
```

To narrow it down I have run the same script on a trimmed version of the file (below) without changing a line of code. As you can see with a larger file, the script reads much more data without having any memory problems. 

```
ufuk:~/Projects/HMM/refactored> head -n 100010 ../ck_data/sorted2.txt > ../ck_data/sorted2_short.txt
ufuk:~/Projects/HMM/refactored> python parseMQ.py -i ../ck_data/ -f sorted2_short.txt --sorted -o ../ck_data/ -d
Data Frame:   72,910,244
Parser    :          641
Enter to continue...
Data Frame:   65,268,283
Parser    :   66,197,268
Enter to continue...
Data Frame:       11,269
Parser    :  120,607,510
Enter to continue...
Traceback (most recent call last):
  File "parseMQ.py", line 355, in <module>
    main()
  File "parseMQ.py", line 177, in main
    df = pd.DataFrame(reader.get_chunk(size=50000))
  File "/Users/ufuk/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 972, in get_chunk
    return self.read(nrows=size)
  File "/Users/ufuk/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 939, in read
    ret = self._engine.read(nrows)
  File "/Users/ufuk/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1508, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 848, in pandas.parser.TextReader.read (pandas/parser.c:10415)
  File "pandas/parser.pyx", line 895, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:11084)
StopIteration
```

Just for the record, I have updated pandas to the latest version (0.20.3) via conda update, which does not change the behaviour in any way. Neither does setting ` low_memory=False` for `reader`. FWIW I am inclined to think that it's an issue regarding the estimation of `dtype`s but I am not entirely sure. It's also possible I am missing a much simpler point somewhere. 

@gk13 : Not that it answer your question specifically regarding pandas and csv_reader but one suggestion is to pre-filter and pre-sort (if relevant) columns, using command-line tools like `cut`or `awk` and `sort`, prior to reading the csv file. Using that strategy I could reduce the file size from 20+ GB to approx 4GB, which makes everything a bit more manageable.

**Comment by gfyoung** [comment]
@gk13 : I'm in agreement with @TomAugspurger that your file *could* be malformed, as you have not been able to prove that you were able to read this otherwise (then again, what better way is there to do it than with `pandas` 😄 ).

Why don't you do this:

Instead of reading the entire file into memory, pass in `iterator=True` with a specified `chunksize`.  Using the returned iterator, called `.read()` multiple times and see what you get with each chunk.  Then we can confirm whether your file is in fact formatted correctly.

**Comment by lsilva6851** [comment]
I've solved the memory error problem using chunks AND low_memory=False

```
chunksize = 100000
chunks = []
for chunk in pd.read_csv('OFMESSAGEARCHIVE.csv', chunksize=chunksize, low_memory=False):
    chunks.append(chunk)
df = pd.concat(chunks, axis=0)
```

**Comment by junijor0** [comment]
I've solved the memory error problem using smaller chunks (size 1). It was like 3x slower, but it didn't error out. low_memory=False didn't work

```
chunksize = 1
chunks = []
for chunk in pd.read_csv('OFMESSAGEARCHIVE.csv', chunksize=chunksize):
    chunks.append(chunk)
df = pd.concat(chunks, axis=0)
```

**Comment by stock-ds** [comment]
axis=0 - add/append new rows
axis=1 - add/append columns

**Comment by mroeschke** [comment]
Seems like the debugging efforts in the original question stalled while others have had success with using `concat` with `chunks` and `low_memory=False`. Will tag as a usage question and close.

**Comment by 16bc** [comment]
I have the same problem with big csv-file (~10gb)
As current row number increases, pd consumes more and more memory.
In example below term with exit code 137 without reaching print()

> for chunk in pd.read_csv(filename, sep='\t', quoting=3, chunksize=100,
                   on_bad_lines='warn', engine='python',
                   skiprows=332_200_000, _# for my 32gb mem & 2gb swap this value - is my error threshold_
                   na_values=r'\N'):
>print("test")

I found that it's not the file size that matters, but the row number on which the particular memory size overflows: different files produce an error on the same row numbers. This also excluding incorrect parsing case.
Chunksize no matter. Change Engine no solve this.

**Comment by micomahesh1982** [comment]
i do have the same scenario and getting "Python Error: <>, exitCode: <139>" . does anybody have any resolution. kindly help me.
