### ISSUE TITLE
Type changing when extracting rows of a dataframe

### ISSUE THREAD

**Issue by jlopezpena** [pandas-dev/pandas#16552]
```python
import pandas as pd
a = pd.DataFrame(data = [[1, 2, 1.0],
                         [2, 3, 2.1]])

# Mixed int and float types
print(a.dtypes)
# Extracting a row changes all the types to float
b = a.loc[0]
# All the elements are float now!
print([type(x) for x in b])
```
#### Problem description

If a dataframe contains mixed `int` and `float` types, extracting a row converts all the
elements to floats, instead of respecting the proper one.

This has bitten me a couple of times when saving dataframe contents to mongo documents
(one document per row).

Is this desired behaviour?

**Comment by jorisvandenbossche** [comment]
Yes, this is the expected behaviour. Accessing a row like that gives you a Series, and a Series always has a single dtype. So in this case it upcasts all elements to float (and not to object and keeping the original types)

If you want to do something row by row (and when this is inevitable), I would rather suggest to use eg `itertuples`, which does not convert each row to a Series, and thus preserves original dtypes.

**Comment by TomAugspurger** [comment]
You could `.astype` everything to object ahead of time.

```
a.astype(object).loc[1]
```

will have a mix of (python) integers and floats. But FYI, this will in general be slow if you do any other operations (maybe not a concern if it's a single row), and if you do any pandas operations on that, they could be cast back to floats.
