### ISSUE TITLE
[BUG] ValueError: Invalid frequency: AS-JAN

### ISSUE THREAD

**Issue by kuraga** [pandas-dev/pandas#16631]
#### Code Sample, a copy-pastable example if possible

```python
import pandas
pandas.Period('2014-03', freq='M').to_timestamp(freq='AS')
```

#### Problem description

```
ValueError: Invalid frequency: AS-JAN
```
(but works well since `freq='A'`)

#### Expected Output

```python
Timestamp('2014-01-01 00:00:00')
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-24-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: ru_RU.UTF-8
LOCALE: ru_RU.UTF-8

pandas: 0.20.1
pytest: None
pip: 9.0.1
setuptools: 35.0.2
Cython: None
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 6.0.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
I think you may be confused about the difference between `Timestamp`s and `Period`s. Your code sample uses a `Period`,  but your expected output shows a `Timestamp`.

The `S` / `E` modifiers (start and end) don't apply to `Periods` since the represent a span of time, an entire year or month or whatever. Timestamps are instants in time, so the need to specify whether it's the Start or End. So this is correctly raising an error (which could probably be improved, if you're willing to submit a pull request.)

**Comment by kuraga** [comment]
Ok, sorry, thanks!

**Comment by kuraga** [comment]
@TomAugspurger I was confused because I have applied `freq` in `to_timestamp` not `Period`. But yes, it was silly to check `AS` but not `AE`...

**Comment by kuraga** [comment]
Really, should `to_timestamp` convert to any point  of such perios (start, end), shouldn't it?

**Comment by TomAugspurger** [comment]
Not sure what you mean, can you provide an example? There is the `how` argument on `Period.to_timestamp` that controls which endpoint to use.

**Comment by kuraga** [comment]
Understood.
