### ISSUE TITLE
BUG / ENH: Implement groupby_helper funcs for int

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#16676]
From #15091 (at <a href="https://github.com/pandas-dev/pandas/commit/0281886fbdf0d1837c2af08af15949c1d98bf612">028188</a>):

~~~python
from pandas import DataFrame
df = DataFrame([[1, 2, 11111111111111111]], columns=['index', 'type', 'value'])
df.pivot_table(index='index', columns='type', values='value')
type                   2
index                   
1      11111111111111112
~~~

When we pivot, we have to aggregate the values we group together by the `index` and `columns` parameters.  When we specify `mean` as the aggregator, we eventually get around to calling `_get_cython_function`, which searches for an implemention of `mean` in `groupby.pyx` for integers.  However, `groupby_helper.pxi` only defines them for floats, so the data is then cast to `float` for aggregating before being reconverted back to `int` in the final result, leading to the mysterious increment due to rounding.

Had there been an implementation of `mean` for `int`, then this wouldn't happen.  However, implementing `mean` for `int` isn't straightforward because we can't guarantee returning `int` as the `float` implementations can't guarantee returning `float` without losing precision (which is the contract in the `groupby_helper.pxi` template).

**Comment by jreback** [comment]
so this is actually straightforward. we add a groupby_mean that accepts int, but *returns* float.

**Comment by gfyoung** [comment]
I wish it was that simple, though even when implementing those functions, I still see rounding issues, as can be seen from an attempted patch off of <a href="https://github.com/pandas-dev/pandas/commit/5bf7f9a4ff6968fd444fa7098f8dc95586591994">5bf7f9</a>:

[group-mean-patch](https://github.com/pandas-dev/pandas/files/1390120/0001-Add-group_mean-functions-for-int-dtypes.txt)

**Comment by jbrockmendel** [comment]
im not clear on what the ask is here.  @gfyoung what would the suggested helper(s) be doing?

**Comment by rhshadrach** [comment]
In the case the input is an integer (`is_integer_dtype)` and the output is not, we downcast. I think instead, users should be expecting mean to always produce floats. This downcasting is done for any op, and other ops (e.g. a UDF) that produces floats could produce unexpected results. Plus, this is value-dependent behavior.

Removing the downcasting leads to 26 failed test. I haven't looked into these yet to see if there are any surprises, or if they are all just because of the dtype change for mean.

Marking this as a good first issue for investigation. The downcasting to remove is done in the code below. Once removed, try fixing up the tests and see if there are any cases where not downcasting leads to unexpected / undesirable results.

https://github.com/pandas-dev/pandas/blob/db27c36272fc3d7ce76cfecbeaa1eac704c2644a/pandas/core/reshape/pivot.py#L175-L195
