### ISSUE TITLE
COMPAT: 32-builds segfault, xref #17040

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17063]
xref #17040
 
ok this is causing the 32-bit builds to segfault

https://travis-ci.org/MacPython/pandas-wheels/jobs/256710160

**Comment by jreback** [comment]
cc @jeffknupp 
cc @gfyoung

**Comment by jeffknupp** [comment]
@jreback @gfyoung OK, was able to get a 32 bit VM going and reproduce and fix the crash (it _was_ the `size_t` after all, since `*cough*`that's what we should be using for these types because that's what `malloc()` expects `*cough*` we were passing the function that calls `malloc()` an `int64_t` but silently (on 64-bit systems) casting to `size_t`... There be dragons.

Also some slight issues with the format strings for error messages that I'm not happy about the solution for, but everything seems to work.

@jreback do you want me to open a new PR or push another change against the existing one?

**Comment by jreback** [comment]
open a new or pls (to close this issue)

**Comment by jeffknupp** [comment]
Opened #17071

**Comment by gfyoung** [comment]
Alright, let's see what the MacPython has to say...

**Comment by gfyoung** [comment]
The latest build <a href="https://travis-ci.org/MacPython/pandas-wheels/builds/257532322">here</a> shows all green, so it appears the segfault has been patched!  Thanks again, @jeffknupp !
