### ISSUE TITLE
astype documentation lacks a section about the copy parameter

### ISSUE THREAD

**Issue by prcastro** [pandas-dev/pandas#17359]
The `astype` method of both [DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.astype.html) and [Series](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.astype.html) don't include an explanation about the `copy` parameter in 'parameters' session.

**Comment by gfyoung** [comment]
@prcastro : Thanks for reporting this!  We just added a section to the issues template about checking the docs on `master` at https://pandas-docs.github.io/pandas-docs-travis.

If you look at the corresponding links for <a href="https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.astype.html">DataFrame</a> and <a href="https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.Series.astype.html">DataFrame</a>, you will see that we have addressed your issue already 👍 

See #17203 for the changes.  Closing since this issue has already been resolved.  Will re-open if you have any other concerns related to the `copy` parameter.
