### ISSUE TITLE
BUG: After reindex(),  astype() raises exception for categorical series

### ISSUE THREAD

**Issue by junjiecai** [pandas-dev/pandas#17444]
Hi 

I meet an unexpected behavior for  categorical series

After reindex() a categorical series, astype() will raise Exception

For example, code below raise ValueError: Wrong number of dimensions

```python
s = Series([1, 2, 3], index = [2, 0, 1])
(s.astype('category')
 .reindex([0, 1, 2])
 .astype(str))

```
However, if I reindex() first then set the series categorical, astype() works as expected.
Code below works fine

```python
s = Series([1, 2, 3], index = [2, 0, 1])
(s.reindex([0, 1, 2])
 .astype('category')
 .astype(str))
```

I think both code should behave the same way

**Comment by jreback** [comment]
hmm this is a bug, not sure exactly, but I think something is getting created in an odd way.

**Comment by alanbato** [comment]
I'm looking into it, and it seems that the bug is due to its `CategoricalBlock` step having `ndim` evaluating to `2`, whereas its `values.ndim` evaluate to `1`. I think it has to do with how a `Block` object has an ndim of `2` by default.
Maybe we aren't sending the ndim parameter and we should, or is this supposed to be correct?

**Comment by mroeschke** [comment]
Looks to work on master. Could use a test.

```
In [30]: s = Series([1, 2, 3], index = [2, 0, 1])
    ...: (s.astype('category')
    ...:  .reindex([0, 1, 2])
    ...:  .astype(str))
Out[30]:
0    2
1    3
2    1
dtype: object

In [31]: pd.__version__
Out[31]: '0.26.0.dev0+565.g8c5941cd5'
```
