### ISSUE TITLE
Tons of Test Errors with 0.20.3 and 0.21.0.dev0 Python 3.6.3

### ISSUE THREAD

**Issue by jmwoloso** [pandas-dev/pandas#17824]
#### Code Sample, a copy-pastable example if possible

```python
nosetests -v pandas

```
#### Problem description

I installed 0.20.3 and then also tried 0.21.0.dev0 and there are a ton of tests that fail for both versions on python3.6.3.

#### Expected Output
All tests passing, I suppose.
#### Output of ``pd.show_versions()``

[paste the output of ``pd.show_versions()`` here below this line]

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-32-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.21.0.dev
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.5.0
Cython: 0.27.1
numpy: 1.13.3
scipy: 0.19.1
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.1.14
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
pandas_gbq: None
pandas_datareader: None

[pandas_dev.txt](https://github.com/pandas-dev/pandas/files/1367499/pandas_dev.txt)

**Comment by gfyoung** [comment]
@jmwoloso : Thanks for reporting this!  `nosetests` is not recommended for running tests because we are using the `pytest` framework.  Give it a go with that tool first.

Afterwards, I would suggest you ensure that you have your testing environment properly setup.  Sometimes local failures are due to machine differences (e.g. rounding precision), which are beyond our control in many cases.

Finally, we do in fact have a test environment already for `3.6.3`, which you can find here:

https://travis-ci.org/pandas-dev/pandas/jobs/285402021

Closing as we do have this Python version covered.  However, we'll be happy to address further questions regarding your local setup if need be.
