### ISSUE TITLE
Using Pandas 0.21 auto-detection of dates fails in pyplot

### ISSUE THREAD

**Issue by guivo** [pandas-dev/pandas#18192]
Using the following code

plt.plot(pd.to_datetime(np.linspace(1501288700, 1501290000, 10), unit='s'), np.arange(10))
plt.show()

I obtain different result using 0.20 or 0.21.

Using the code above with Pandas 0.20 the plot automatically identifies that the X axes contains dates. While using pandas 0.21 this, or other attempts, to force the X axes to show dates in the axes. The two plots have been attached and as you can notice one has show the datetiem as "%d %H:%M", as expected, while the 2nd made with the latest package shows integers.

All the other packages are unchanged.

![pandas20](https://user-images.githubusercontent.com/33522004/32613812-20f92b40-c56c-11e7-9c9f-2e56eb13509a.png)
![pandas21](https://user-images.githubusercontent.com/33522004/32613813-212ded58-c56c-11e7-8900-d71ea9009e0b.png)

**Comment by TomAugspurger** [comment]
This was an intentional change to not import matplotlib when pandas is imported. You can either use `Series/DataFrame.plot`, or explicitly register the pandas converters. (you can search around for duplicate issues for more  info).

See https://github.com/matplotlib/matplotlib/issues/9610 for a longer discussion.
