### ISSUE TITLE
read_qvd would be nice to have

### ISSUE THREAD

**Issue by radewagen** [pandas-dev/pandas#18259]
Hi,

a lot of data is stored in .qvd files and it would be nice to read a QVD into a Pandas Dataframe, e.g.:

```
import pandas as pd
pd.read_qvd("filename")
```
More information about QVD files:
http://help.qlik.com/en-US/sense/3.2/Subsystems/Hub/Content/Scripting/work-with-QVD-files.htm

I believe to support QVD is difficult, since it is proprietary, but since you managed Excel, I hope it is possible. :)

**Comment by jreback** [comment]
this is out-of-scope for pandas proper. an external package certainly could be supported (e.g. like tableau is supported).

**Comment by jreback** [comment]
no averse that this is a proprietary format. The main issue is lack of widespread use. If lots of clamoring for formats like this, we can reconsider.

**Comment by radewagen** [comment]
I understand that it does not have a high priority, but at least in the corporate world there are a lot of use cases where QlikView is involved and an easy import/export with QVD would be awesome.

**Comment by jorisvandenbossche** [comment]
It is not only the question about high priority, it also a question about limiting the scope of core pandas (because the bigger it gets, the more difficult to maintain). 
But as @jreback said, the best way to go it to implement an external package that provides a `read_qvd`. That will be useful for all people wanting this functionality. And can eventually also show that it is used a lot and then become an optional dependency of pandas.
