### ISSUE TITLE
Deprecate Tick?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18772]
What can tick do that Timedelta can’t? I guess normalize? But tick with normalize=true doesn’t make a ton of sense...

**Comment by chris-b1** [comment]
Practically speaking, nothing that I'm aware of, but I'm not sure that means it should be removed.  

At least my understanding of the `Tick` hierarchy is so that the DateOffset hierarchy provides a uniform interface for both fixed & relative offsets.  

For instance, without `Tick`, these two ops would return different types for the metadata, which isn't great?

```python
pd.date_range('2014-01-01', freq='5B', periods=10).freq
Out[100]: <5 * BusinessDays>

pd.date_range('2014-01-01', freq='D', periods=10).freq
Out[101]: <Day>
```

**Comment by jbrockmendel** [comment]
Well BusinessDays isn't a tick, so that isn't redundant.

I agree this is likely not worth the backward-compat trouble.
