### ISSUE TITLE
Value in column with only 1 row returns False instead of True

### ISSUE THREAD

**Issue by ruben-aghayan** [pandas-dev/pandas#18855]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd

c = pd.DataFrame([[1,2],], columns = ['c1', 'c2'])
1 in c.c1

new_row = {'c1':3,
'c2':4}
c = c.append(new_row, ignore_index=True)
1 in c.c1

observed output:
In [282]: c = pd.DataFrame([[1,2],], columns = ['c1', 'c2'])
     ...: 1 in c.c1
     ...:
Out[282]: False

In [283]: new_row = {'c1':3,
     ...:             'c2':4}
     ...: c = c.append(new_row, ignore_index=True)
     ...: 1 in c.c1
     ...:
Out[283]: True

```
#### Problem description
Checking for a value in a column reports False when there is only one row (which has that value).

#### Expected Output
If that column ( of a single value) has that value, it should return True

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
In [284]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.20.3
pytest: 3.2.1
pip: None
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.3
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by fergaljamesoconnor** [comment]
The _contains_ method for a NDFrame checks in the _info_axis for that NDFrame. What this means is that it's checking the generic, range-based index for your series. 

So for the case where it returns False, it is looking over an index with only 0 in in, and doesn't find a matching 1. 

In the case where it returns True, it is looking over an index containing 0 and 1 and returns True.

Basically, the in operator matches against values in the index, rather than the actual data contained in the series and the code snippets above seem to be functioning as intended.

**Comment by ruben-aghayan** [comment]
Wow yes I see now. Thank you for the explanation, don't know how I missed it.
