### ISSUE TITLE
Building docs fails with the latest version of sphinx

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#19742]
It seems like one week ago sphinx 1.7.0 was released, and the version of numpydoc included with pandas is not compatible with it (it uses the `sphinx.util.compat` which has been deprecated).

Anaconda already includes sphinx 1.7.0, which is used by default. As in `requirements_dev.txt` sphinx is specified without version, after following the instructions in the contributing documentation, building the documentation fails.

I assume that numpydoc has been modified, if included in the repository instead of being added as a dependency. So, may be a quick solution is to specify `sphinx==1.6.7` in `requirements_dev.txt`.

Happy to contribute a pull request, if you can clarify what needs to be done.

**Comment by TomAugspurger** [comment]
See  https://github.com/pandas-dev/pandas/pull/19687 and https://github.com/pandas-dev/pandas/issues/18147

We're currently blocked by an IPython release to fix an issue with newer versions of the IPython directive. I thought we already pinned sphinx in our requirements_dev, but apparently not. We want to pin to sphinx 1.5.*, since 1.6 has a regression slowing down the API docs.

Alternatively, we could backport @jorisvandenbossche's fix to IPython and vendor that? I think pinning is best for now.

**Comment by jcontesti** [comment]
When I install the build dependencies with pip, I get the following error:

`python -m pip install -r ci/requirements_dev.txt`
`Invalid requirement: 'sphinx=1.5*'`
`= is not a valid operator. Did you mean == ?`

Simply changing `sphinx=1.5*` with `sphinx==1.5.*` solves the issue.

Let me know if a can contribute with a PR.

**Comment by TomAugspurger** [comment]
Sorry about that @jcontesti. I think https://github.com/pandas-dev/pandas/pull/19687 is already addressing this.
