### ISSUE TITLE
Classes should maintain a registry of accessors

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19963]
Dask would like to inherit the accessors registered by `register_*_acessor`. This would be much easier if the `regiser_*_accessor` methods added the name of the accessor to a (private) class variable.

It seems like we have use of it in pandas as well: https://github.com/pandas-dev/pandas/pull/19960/files#r171815351

**Comment by WillAyd** [comment]
I could be coming way out of left field on this one but were metaclasses ever given consideration for the accessors? It seems like using them instead of decorators would still allow you to register the methods you need on a subclass, but at the same time give give you access to that registered metadata without having to store it in a private variable in the subclass

**Comment by TomAugspurger** [comment]
I think storing the registry as a private var on the class having the
accessor attached strikes a nice balance between simplicity and usability.
