### ISSUE TITLE
Confusing - rolling min( ) function "accepting" objects

### ISSUE THREAD

**Issue by gojandrooo** [pandas-dev/pandas#20244]
#### Code Sample, a copy-pastable example if possible

```python
s = pd.Series([3,1,2,'x','y','z'])

s.rolling(2).min()

0    3
1    1
2    2
3    x
4    y
5    z
dtype: object

```
#### Problem description

Should raise an exception because the series contains objects. Instead, function returns the series.

**Comment by jorisvandenbossche** [comment]
Thanks for the report! 

This is certainly a bug, as it is not even calculating a minimum for the numerical values. Didn't look in detail, but I suppose this is due to the automatic skipping of non-numerical columns. 
In case of a DataFrame that is useful:

```
In [3]: pd.DataFrame({'a': [1,2,3,4], 'b':[1,2,'a', 'b']}).rolling(2).min()
Out[3]: 
     a  b
0  NaN  1
1  1.0  2
2  2.0  a
3  3.0  b
```

but in case of a Series, just passing it through makes less sense.

**Comment by jorisvandenbossche** [comment]
Related issues: https://github.com/pandas-dev/pandas/issues/18129, https://github.com/pandas-dev/pandas/issues/15085

**Comment by ihsansecer** [comment]
This is working fine on master

```python
>>> pd.DataFrame({'a': [1,2,3,4], 'b':[1,2,'a', 'b']}).rolling(2).min()
     a
0  NaN
1  1.0
2  2.0
3  3.0
```

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/pull/27044 was just merged
