### ISSUE TITLE
DOC: file IO in doctest examples

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#20302]
In several docstrings we write some data to a temporary file to illustrate reading / writing functionality. 

However, this leaves behind those files when running the docstest, which is not ideal.

@TomAugspurger  from https://github.com/pandas-dev/pandas/pull/20208#pullrequestreview-103076879

> We can
>
> - convert this to a regular code-block
> - Use `io.StringIO`, which is uglier but doesn't leave behind a file
> - Add a bit to `os.remove('test.csv')`

**Comment by TomAugspurger** [comment]
> what do you mean with "convert this to a regular code-block

Yep. That "avoids" the problem by not actually running the doctest :)

I think the best is to just `os.remove('test.csv')` at the end. It's just one extra line to import and one to cleanup.

**Comment by jorisvandenbossche** [comment]
> I think the best is to just os.remove('test.csv') at the end. It's just one extra line to import and one to cleanup.

Yes, that is probably the easiest

**Comment by jreback** [comment]
yep agreed using the remove is pretty idiomatic (and its not in that many places anyhow)

**Comment by mroeschke** [comment]
The approach in https://github.com/pandas-dev/pandas/pull/44711 was to skip the lines that will actually write a file and validate that docstrings don't leave leftover files.

This was done due to a flaky segfault in the CI in during docstring validation which was suspected to be because of leftover files: https://github.com/pandas-dev/pandas/issues/44590

Since this has a consistent behavior now, closing, but happy to reopen if there are other considerations.
