### ISSUE TITLE
ExtensionArray.__fillna__ should not use lib.is_scalar

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20411]
`lib.is_scalar` is a bit too strict for the check we do in https://github.com/pandas-dev/pandas/blob/7273ea0709590e6264607f227bb8def0ef656c50/pandas/core/arrays/base.py#L272. For example, it doesn't condisder `ipaddress.IPv4Address` as a scalar.

```python
In [1]: from pandas._libs import lib

In [2]: import ipaddress

In [3]: lib.is_scalar(ipaddress.IPv4Address(1))
Out[3]: False
```

Replacing that check with a `hasattr(value, '__len__')` should be sufficient.

**Comment by jorisvandenbossche** [comment]
The same for geopandas.

However, in general, also the `len` check might not always be good, because eg for geopandas a MultiLineString has a length .. . Or for the json-array, a dict also has a length.

This might not be easy to solve in general, it's mainly due to our flexible API where we need to interpret a lot about what is passed in ..

**Comment by jorisvandenbossche** [comment]
Actually, even simpler example where a length check will not work: strings. 
(but of course, for only this one it would be easy to add to an additional check)

**Comment by TomAugspurger** [comment]
Hmm hadn't thought that through.

Perhaps we require that `ExtensionArray.fillna(array)` requires `array` to be an instance of the ExtensionArray? That should remove all ambiguity, at the cost of requiring `IPArray([]).fillna(['192.168.1.1'])` to be written as `IPArray([]).fillna(IPArray(['192.168.1.1']))`.

**Comment by jorisvandenbossche** [comment]
> at the cost of requiring IPArray([]).fillna(['192.168.1.1']) to be written as IPArray([]).fillna(IPArray(['192.168.1.1'])).

But in this case you can still fill with `IPArray([]).fillna('192.168.1.1')` (filling with a scalar) ?

But such a requirement might be a good idea. Or we could also check it being "array-like" (check if is has a shape and if that shape matches). 
In the current implementation, I don't think that a list (instead of array) would work anyhow, because we apply a boolean mask on it?

**Comment by TomAugspurger** [comment]
is_array_like seems to be what we want, since we do use boolean masking on
it.
