### ISSUE TITLE
Export the data frame to excel file with password protection

### ISSUE THREAD

**Issue by chavan-vjti** [pandas-dev/pandas#20546]
Hello all,

I deal with huge data of shape **[5331334 rows x 221 columns]** even greater than this.

I'm just looking for password protection to excel file, exported from such data frame.

Thank you!

**Comment by WillAyd** [comment]
I don't think this is possible in pandas because it's not consistently supported by the underlying engines. See this about xlsxwriter for instance:

https://github.com/jmcnamara/XlsxWriter/issues/284

If using openpyxl your best bet may be to get the book attribute of your writer and try setting the password directly on that object instead. The below links may be of help:

https://pandas.pydata.org/pandas-docs/stable/io.html#writing-excel-files
https://openpyxl.readthedocs.io/en/2.5/protection.html

**Comment by jreback** [comment]
out of scope
