### ISSUE TITLE
DOC: let’s add these reshaping visuals to the docs

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#20898]
https://jalammar.github.io/visualizing-pandas-pivoting-and-reshaping/

**Comment by TomAugspurger** [comment]
Yes, these are quite nice. cc @jalammar. Could you add a license to those? Perhaps one of the creative commons licenses (with attribution)?

**Comment by jalammar** [comment]
Oh yeah! And I'd love to do the PR for this. Where is the best place? Can I add them to the [Reshaping and Pivot Tables guide](https://pandas.pydata.org/pandas-docs/stable/reshaping.html)?

**Comment by TomAugspurger** [comment]
Yeah, that'd be best. Probably at the start of each section?

How large are each of the mp4s? If they're too large, we may want to host
them on our server, instead of putting them in the main git repo.

**Comment by jalammar** [comment]
Sounds great. 

Oh the files are PNGs. There's only one MP4, but just a teaser, so not sure if it belongs to the docs. It's 764 KB, however.

I would like to also upload the Keynote file I used to create those somewhere -- just so anyone can update or create more for other functions as necessary. Should that go on the server rather than the repo? It's 750 KB

**Comment by jalammar** [comment]
PR created. How does this look?
