### ISSUE TITLE
BUG/API: Index constructor does not enforce specified dtype 

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#21311]
#### Code Sample, a copy-pastable example if possible

Manually specifying a dtype does not garantuee the output is in that dtype. Eg with Series if incompatible data is passed, an error is raised, while for Index it just silently outputs another dtype:

```python
In [11]: pd.Series(['a', 'b', 'c'], dtype='int64')
...
ValueError: invalid literal for int() with base 10: 'a'

In [12]: pd.Index(['a', 'b', 'c'], dtype='int64')
Out[12]: Index(['a', 'b', 'c'], dtype='object')

```

**Comment by jschendel** [comment]
xref https://github.com/pandas-dev/pandas/pull/21254#discussion_r191658787

Meant to create an issue similar to this for the `Categorical` --> `Interval` case:
```python
In [2]: cat = pd.Categorical([pd.Interval(0, 1), pd.Interval(1, 2), pd.Interval(0, 1)])

In [3]: pd.Index(cat, dtype='interval')
Out[3]: CategoricalIndex([(0, 1], (1, 2], (0, 1]], categories=[(0, 1], (1, 2]], ordered=False, dtype='category')
```

This happens because the `Index` code is structured so that categorical takes precedence over interval:
https://github.com/pandas-dev/pandas/blob/c85ab083919b59ce84c220d5baf7d34ff4a0bcf2/pandas/core/indexes/base.py#L262-L273

The code above could be restructured so that the `dtype` argument, if present, takes precedence over the type of `data`.

Not immediately sure what the fix for other scenarios entails, as `Categorical` and `Interval` are a bit of a special case.
