### ISSUE TITLE
DEPR: _timelex is deprecated in dateutil

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#21322]
See: https://github.com/pandas-dev/pandas/issues/21137

The question is: how exactly do we replicate the functionality?

**Comment by jorisvandenbossche** [comment]
scipy -> dateutil?

**Comment by gfyoung** [comment]
> scipy -> dateutil?

@jorisvandenbossche : Good catch 😄

**Comment by jreback** [comment]
cc @pganssle

**Comment by pganssle** [comment]
To be clear, `_timelex` is not deprecated in `dateutil`, it's private. If you need that functionality I recommend copy-pasting it or using @jbrockmendel's sleek new implementation (https://github.com/dateutil/dateutil/pull/732). `dateutil` is under a permissive license so the only requirement is that you retain the copyright notice (which I can't waive, unfortunately, because I'm not the original author of `_timelex`). When some form of `_timelex` is eventually made public, you can switch to that.

**Comment by gfyoung** [comment]
@pganssle : 

> To be clear, _timelex is not deprecated in dateutil, it's private.

Ah, thank you for clarifying that.  Admittedly, the message associated with the `DeprecationWarning` had a little bit a cognitive dissonance.

> Do you have a timeline by any chance for making `_timelex` public?  If it's not on the horizon, we could copy-paste as an immediate fix (@jreback , we do that with `clipboard` IINM).

**Comment by jreback** [comment]
@gfyoung I would just in-line the code from above

**Comment by jbrockmendel** [comment]
> Do you have a timeline by any chance for making _timelex public? 

There's some discussion in dateutil#729.  Short answer: "no".

> If it's not on the horizon, we could copy-paste as an immediate fix

Definitely should use the version in dateutil#732 as it is much simpler and more performant.  I think even that can be pared down to a single call to `re.findall`.

**Comment by gfyoung** [comment]
@jbrockmendel : Thanks for clarification!  Since you're working directly on this, you probably would know best as to when we should port over a copy of the implementation.
