### ISSUE TITLE
ENH: use interface library for ExtensionArrays

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#21373]
http://interface.readthedocs.io/en/latest/

looks pretty reasonable
cc @llllllllll @ssanderson

**Comment by ssanderson** [comment]
I'd be happy to see pandas using interface. It's a pretty lightweight dependency, and we've been using it fairly happily for internal projects at Quantopian for while now.

One thing that might be worth thinking about is what using interface would mean for cross-pandas-version compatibility for ExtensionArray authors. If pandas added a new required method/attribute to the ExtensionArray interface, for example, would you want older versions of ExtensionArray-implementing packages to crash at import time if they're run in an enviroment with a newer version of pandas? That might be preferable to crashing later at "runtime" when pandas tries to call a method that's not defined, but we should make sure that that's the behavior we want here.

**Comment by jorisvandenbossche** [comment]
> One thing that might be worth thinking about is what using interface would mean for cross-pandas-version compatibility for ExtensionArray authors.

I think we want that extension authors can implement ExtensionArrays that are compatible with multiple versions of pandas. Of course you can still add or not a method to the class based on the pandas version, but that makes it a bit more complex.

However, the restriction on the exact signature seems more annoying when we change that between versions.

(so it seems `interface` is maybe more suited to be used *within* package)

**Comment by ssanderson** [comment]
Interface doesn't necessarily require the *exact* signature to match: it requires that the implementation method can be called in any way that would be a valid call for the method declared in the interface. So, for example, your implementation can add an additional parameter to the method if it provides a default:

```python
In [1]: from interface import *

In [2]: class IFoo(Interface):
   ...:     def method(self, a, b):
   ...:         pass
   ...:

In [3]: class Impl(implements(IFoo)):
   ...:     def method(self, a, b, c=3):
   ...:         pass
In [4]:
```
but this will cause an error:

```python
In [4]: class Impl(implements(IFoo)):
   ...:     def method(self, a, b, c):
   ...:         pass
   ...:
   ...:
---------------------------------------------------------------------------
InvalidImplementation                     Traceback (most recent call last)
... (stack trace omitted)
InvalidImplementation:
class Impl failed to implement interface IFoo:

The following methods of IFoo were implemented with invalid signatures:
  - method(self, a, b, c) != method(self, a, b)
```

**Comment by ssanderson** [comment]
I think the interesting question w/r/t cross-version compatibility is **when** you want an error to be raised if an ExtensionArray implementation doesn't match the required interface. Do you want that to be an import-time failure, or a runtime failure? 

If you control both the implementation and the interface, my experience has generally been that you want to be informed about failures as early as possible, because that reduces the possibility for latent bugs lurking in untested codepaths. 

Things get a little murkier once you start splitting implementations and interfaces across libraries. Turning a bad implementation into a runtime failure means that a user can't use *any* features of the broken library, even though it might be the case that only *some* of the features are actually broken. Some users might be happy to make that trade-off in exchange for extra safety guarantees (it's probably the trade-off that I would want if I wrote an ExtensionArray that was used at Quantopian for example), but others might prefer if we were less strict.

**Comment by jbrockmendel** [comment]
closeable?
