### ISSUE TITLE
how to specify more flexible boundaries for fillna

### ISSUE THREAD

**Issue by changhiskhan** [pandas-dev/pandas#2138]
stop filling across day boundaries, hour boundaries, etc etc

**Comment by VelizarVESSELINOV** [comment]
:+1: fillna limit = number of samples is a very simplistic solution.

Very often the limit should be applied to the index values, especially when the index is not regular sampled like TimeStamp or distance.

Example of limit 20 seconds or 20 centimeters, not 20 samples because the index is not mandatory to be constant.

``interpolate`` is partially managing some of the resampling method are using the index value, but the limit is still integrer with number of samples.

**Comment by Compro-Prasad** [comment]
Some example would be helpful

**Comment by MarcoGorelli** [comment]
> Some example would be helpful

indeed - closing then
