### ISSUE TITLE
Missing dependency for sphinxcontrib-spelling

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#21396]
```
(pandas-dev) [mgarcia@xps doc]$ python make.py --num-jobs=8
Running Sphinx v1.7.5

Extension error:
Could not import extension sphinxcontrib.spelling (exception: No module named 'sphinxcontrib.spelling')
```
#### Problem description

In #21109 the package `sphinxcontrib-spelling` has been added to the sphinx configuration, but the package has not been included in the `conda` or `pip` dependencies. This is making the documentation script crash.

**Comment by datapythonista** [comment]
Seems like `sphinxcontrib-spelling` is available in conda and pip, but it requires `pyenchant` which is not available in the main channels of conda. Also, the versions I found seem to be conflicting with `pyarrow`.

@FabioRosado can you please provide more information on which dependencies you installed (which versions) and from which channels?

**Comment by FabioRosado** [comment]
Hello @datapythonista, I forgot to add the requirements on the txt file my apologies.
I don't use conda so when I installed the sphinx extension all I did was `pip install sphinxcontrib-spelling` and everything worked fine, I got no conflicts with pyarrow when I tried to install the library.

As for pyenchant not being available in the main channels of conda, I tried running the spelling extension without pyenchant installed and everything worked fine - which is odd since the documentation says it uses pyenchant to produce a report showing misspelt words.  Perhaps if pyenchant is not installed the extension will just write the misspelt words on a text file?

**Comment by datapythonista** [comment]
Thanks for the info @FabioRosado, and no worries for the missing requirements. It was a cool and complex PR, easy to forget some detail.

I'd say that you had already `pyenchant` installed, or that `pip` installs it when installing `sphinxcontrib-spelling`. I'm using `conda` and I get:

```
(pandas-dev) [mgarcia@xps doc]$ python make.py --num-jobs=8
Running Sphinx v1.7.5

Extension error:
Could not import extension sphinxcontrib.spelling (exception: No module named 'enchant')
```

**Comment by FabioRosado** [comment]
Yeah my bad I forgot to activate the virtualenv that's why it wasn't showing on my pip list haha

I don't use conda so I'm not sure if there is a workaround this issue. It seems you can download the pyenchant file, could this be a possible solution? Also, not sure if it matters but pyenchant is now unmaintained

**Comment by jorisvandenbossche** [comment]
BTW, this also broke our travis doc build, since it is of course needed there as well.

**Comment by jreback** [comment]
let’s revert this for now
leave the actual spelling fixes of course

**Comment by jorisvandenbossche** [comment]
No need to revert I think, we can leave the `python make.py spelling` there, for if you have it installed. Just need a try except in conf.py

**Comment by FabioRosado** [comment]
I will start working on Part 2 of this PR so I'll add the try there if its alright with everyone
