### ISSUE TITLE
`con` argument of `pandas.to_sql`

### ISSUE THREAD

**Issue by Gee0802** [pandas-dev/pandas#21615]
```python
import pandas as pd
import pymysql


conn = pymysql.connect(user='root', password='123456', db='test', charset='utf8')
df1 = pd.read_sql('select * from videos limit 100', conn)
df1.to_sql('video2', conn)

```
as you can see above, with a pymysql connection, `pd.read_sql` works fine, but `pd.to_sql` will raise an Error:
```python
DatabaseError: Execution failed on sql 'SELECT name FROM sqlite_master WHERE type='table' AND name=?;': not all arguments converted during string formatting
```
i have searched for reason, it looks like the `con` argument of `pandas.to_sql` must be sqlalchemy.engine.Engine or sqlite3.Connection,. why doesn't it support pymysql.connection as `pd.read_sql` do?

**Comment by jorisvandenbossche** [comment]
> it looks like the con argument of pandas.to_sql must be sqlalchemy.engine.Engine or sqlite3.Connection,

That is correct, as the documentation states.

>  why doesn't it support pymysql.connection as pd.read_sql do?

This is because `slqalchemy` provides us all the handling of database flavor specificities, on which we rely to make `to_sql` work for all database flavors that `sqlalchemy` supports. 
For reading queries (not tables), however, there is almost nothing database specific (the only thing the connection needs to support is a `execute` and `fetchall`), so the sqlite based version also works for other flavors.

**Comment by Gee0802** [comment]
i get it, thanks for your answer very much!

**Comment by hytzngoka** [comment]
i cant connect to sqlaclhemy engine
