### ISSUE TITLE
CLN/API: is_string_dtype should infer

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#21653]
The string detection routines are a bit odd, they work with arrays & not list-likes. We should change the impl to ``infer_dtype`` which already does the correct things.

```
[5]: from pandas.core.dtypes.common import is_string_like_dtype, is_string_dtype

In [2]: is_string_like_dtype(np.array([b'foo']))                  
Out[2]: True

# should work
In [3]: is_string_like_dtype([b'foo'])          
Out[3]: False

# should work
In [4]: is_string_like_dtype(np.array(['foo', 'bar'], dtype=object))
Out[4]: False

In [6]: is_string_dtype(np.array(['foo', 'bar'], dtype=object))                    
Out[6]: True

# should work
In [7]: is_string_dtype(['foo', 'bar'])                        
Out[7]: False
```
We should also consolidate these into a single ``is_string_dtype`` if possible (this might be tricky though).

**Comment by jorisvandenbossche** [comment]
I don't think `is_string_like_dtype` needs to change, because it is exactly meant to only check for actual numpy string types (although the name could be better). 

I agree in principle on `is_string_dtype`, but I am not sure it is that easy to do. I mean that this would need a check of each current usage in the codebase to see whether it actually needs strings or if it actually meant to check for general object dtype.

It might be easier (short term) to rename the current one and add a new one that is stricter and that we can start using where we know we really want strings.

**Comment by jbrockmendel** [comment]
not sure about this.  why infer for string but not others?

**Comment by jorisvandenbossche** [comment]
>  why infer for string but not others?

Because strings is the only one (before StringDtype, at least) that doesn't have its own dtype, and you basically need to infer to know if you have strings or not. 

But as I said above: not sure we should do this. And certainly now we have StringDtype, and this will become the default at some point, it will become less of an issue.

**Comment by mroeschke** [comment]
Sounds like there's overall not much support to go down this route, so going to close. But happy to revive if things are reconsidered
