### ISSUE TITLE
upsampling MultiIndex DataFrame extremely inefficient

### ISSUE THREAD

**Issue by steve-lorimer** [pandas-dev/pandas#21707]
#### Code Sample

```python
import pandas
import numpy
import datetime

index = pandas.date_range(start=datetime.date(2011,1,1), end=datetime.date(2018,1,1))
cols  = list('ABCDEFG')

# create panel
pnl   = pandas.Panel(items=index, 
                     major_axis=cols, 
                     minor_axis=cols, 
                     data = numpy.random.rand(2558,7,7))

# upsample from daily to minutely, time how long it takes
now = datetime.datetime.now()
pnl = pnl.resample('T').ffill()
print(datetime.datetime.now() - now)

# create multiindex dataframe
df = pandas.DataFrame(index=pandas.MultiIndex.from_product([index, cols]), 
                      columns=cols, 
                      data = numpy.random.rand(17906,7))

# upsample from daily to minutely, time how long it takes
now = datetime.datetime.now()
df = df.groupby(pandas.Grouper(freq='T', level=0)).ffill()
print(datetime.datetime.now() - now)
```

#### Problem description

Attempting to upsample on the datatime index of a MultiIndex DataFrame hangs indefinitely. Memory usage increases until a `MemoryError` is thrown

Doing the same operation on the deprecated `Panel` is both quick and memory efficient

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS ------------------ commit: None python: 3.6.5.final.0 python-bits: 64 OS: Linux OS-release: 4.15.0-23-generic machine: x86_64 processor: x86_64 byteorder: little LC_ALL: None LANG: en_US.UTF-8 LOCALE: en_US.UTF-8
pandas: 0.22.0
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.14.4
scipy: None
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by Liam3851** [comment]
@skebanga As a workaround, use:
```
df.unstack().resample('T').pad().stack(dropna=False)
```

On my PC your Panel example took 669 ms, the above df call took 4.2 seconds. Not quite as fast as Panel but hopefully usable for your purposes as opposed to running into MemoryError. 

Note that Panel was deprecated because the N>2-dimensional case was considered scope for the [xarray ](http://xarray.pydata.org/en/stable/) project. You may wish to consider xarray for your use case if you want 3-D numeric data similar to the deprecated numeric Panel. The equivalent call there would be

```
import xarray as xr
xarr = xr.DataArray(numpy.random.rand(2558,7,7),
                               coords={'index':index, 'cols':cols},
                               dims=['index', 'cols', 'cols'])
xarr.resample(index='T').pad()
```
On my box that takes 873 ms, similar to Panel. See [this doc](http://xarray.pydata.org/en/stable/pandas.html#panel-transition) for more details.

**Comment by lukemanley** [comment]
Added `Closing Candidate` label as I do not see the Memory error on the `DataFrame` portion of the OP. It runs quickly for me.
