### ISSUE TITLE
test_info_repr failing locally

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#21746]
OSX py2.7

```
def test_info_repr(self):
        max_rows = 60
        max_cols = 20
        # Long
        h, w = max_rows + 1, max_cols - 1
        df = DataFrame({k: np.arange(1, 1 + h) for k in np.arange(w)})
        assert has_vertically_truncated_repr(df)
        with option_context('display.large_repr', 'info'):
            assert has_info_repr(df)
    
        # Wide
        h, w = max_rows - 1, max_cols + 1
        df = DataFrame({k: np.arange(1, 1 + h) for k in np.arange(w)})
>       assert has_horizontally_truncated_repr(df)
E       assert False
E        +  where False = has_horizontally_truncated_repr(    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18... 59  59  59  59  59  59  59  59  59  59  59  59  59  59  59  59  59  59  59  59)

pandas/tests/io/formats/test_format.py:1601: AssertionError
```

**Comment by gfyoung** [comment]
@jbrockmendel : When the migration away from Python 2.x, I'm inclined to not be super concerned about this, especially since we do test 2.x (on Linux though).

Nevertheless, should still inquire: when did this start happening?

**Comment by jbrockmendel** [comment]
> when did this start happening?

Pretty sure I've been ignoring this for weeks.

**Comment by gfyoung** [comment]
cc @jreback

**Comment by jbrockmendel** [comment]
FWIW just got the same test failure on ubuntu, still 2.7

**Comment by earwig** [comment]
(This is the only test currently failing for me when I run pytest on pandas off the binary Linux wheel on Python 2.7. It's clearly a benign failure, but as the only one failing, it seems reasonable to fix.)

At a glance, looks like test_info_repr assumes that the default value for the max_columns config option is 20, but this is only true if you're not running in a terminal ([see here](https://github.com/pandas-dev/pandas/blob/c9e8f59668b63738cccb913f837c529887097da1/pandas/core/config_init.py#L318)). I suspect this wasn't noticed because other people may be running their tests from outside a terminal? Anyway, the issue was introduced by c9e8f59668b63738cccb913f837c529887097da1. The most reasonable solution seems to be to wrap the `assert has_horizontally_truncated_repr(df)` in an `option_context` setting `display.max_columns` to `max_cols`.
