### ISSUE TITLE
Allow different methods of correlation when using corrwith

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#21925]
Hi,

The `corr` method for DataFrames is exceedingly useful, especially since one can specify methods other than the Pearson correlation.  I think it would be nice if this same argument were available when using `corrwith`.  Perhaps there is another workaround, but right now if one wants to calculate all the Spearman (say) correlations with a specific variable, it seems necessary to calculate the full Spearman correlation matrix and subset to the column you care about.

Thanks.

**Comment by WillAyd** [comment]
Seems reasonable - PRs are always welcome

**Comment by samwaterbury** [comment]
Looks like the `corr` algorithms are written in Cython but `corrwith` uses a Python implementation of the Pearson calculation. Should be easy enough to add the other coefficient options to the `corrwith` method but they should probably use Cython implementations too since Spearman and Kendall are relatively complex calculations.

I can take a look at this and see if the algorithms that `corr` uses can also be reused by `corrwith` in some way, shouldn't be too tricky
