### ISSUE TITLE
Avoid memory error and reduce the processing time

### ISSUE THREAD

**Issue by chavan-vjti** [pandas-dev/pandas#21979]
#### Code Sample, a copy-pastable example if possible

```python

temp_list = [i for i in range(1, 1441)]

df_daypart = pd.DataFrame(columns=temp_list)

 for index, row in df_1.iterrows():
    for element in temp_list:
        if element == row['begin_day_part']:
            for item in range(row['begin_day_part'], row['end_day_part']+1):
                df_daypart.loc[index, item] = 60
            print "Time required " + str(datetime.now() - temp_time)
            break


```
#### Problem description
So, I have a DataFrame(df_1) with shape as (3785649, 5) somewhat like below

Household | Individual | Channel | begin_day_part | end_day_part
-- | -- | -- | -- | --
123 | 1 | ABC | 657 | 687
456 | 1 | DEF | 705 | 706
789 | 1 | ABC | 706 | 761
1122 | 1 | DEF | 761 | 762
1455 | 1 | ABC | 762 | 769
1788 | 1 | DEF | 769 | 770
2121 | 1 | ABC | 770 | 794
2454 | 1 | DEF | 795 | 797
2787 | 1 | ABC | 797 | 798
3120 | 1 | DEF | 798 | 799
3453 | 1 | ABC | 799 | 800
3786 | 1 | DEF | 800 | 815
4119 | 1 | ABC | 825 | 826
4452 | 1 | DEF | 826 | 892
4785 | 1 | ABC | 892 | 893
5118 | 1 | DEF | 893 | 894
5451 | 1 | ABC | 894 | 927
5784 | 1 | DEF | 927 | 928
6117 | 1 | ABC | 928 | 933

I want to add some fixed value in a rows of dataframe (df_daypart) where loop starts from df_1['begin_day_part] upto df_1['end_day_part].

Since, it's big data the looping takes 30 minutes and sometime I face 'Memory Error' too.
Therefore, I'm looking for a way by which I can eliminate 'memory Error' completely and if possible reduce processing time to 10 minutes.

Right solution is always welcome. 

Thanks in advance!

**Comment by WillAyd** [comment]
Not sure I entirely understand what you are looking for but you have quite a few options at your disposal. The best is probably to build a list of the values you want and construct the DataFrame from there at the very end instead of trying to insert values one by one

That said, this is more of a usage question so you'd be better off asking this on a Q&A site like StackOverflow. This issue tracker is used for bug reports and enhancement requests
