### ISSUE TITLE
API: Have pd.pivot mirror pivot instead of pivot_simple

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#22116]
To pivot, there's currently:

`pd.pivot_table / df.pivot_table`
https://github.com/pandas-dev/pandas/blob/d30c4a0696d5fbdc3c7ce36a9b9b19224a557e09/pandas/core/reshape/pivot.py#L28

`df.pivot`
https://github.com/pandas-dev/pandas/blob/d30c4a0696d5fbdc3c7ce36a9b9b19224a557e09/pandas/core/reshape/reshape.py#L386

`pivot_simple` (Importable at the top level as `pd.pivot`)
https://github.com/pandas-dev/pandas/blob/d30c4a0696d5fbdc3c7ce36a9b9b19224a557e09/pandas/core/reshape/reshape.py#L411

I'm not sure why `pd.pivot` currently doesn't mirror `df.pivot` like how `pd.pivot_table` mirrors `df.pivot_table`, but it would clearer if these were in sync.

**Comment by gfyoung** [comment]
cc @jreback

**Comment by mroeschke** [comment]
There's also a quote in `reshaping.rst` that doesn't seem to be true:

> To reshape the data into this form, we use the DataFrame.pivot() method (also implemented as a top level function pivot())

but `pivot()` that is referred above uses the `pivot_simple` implementation instead of the `pivot` implementation.

**Comment by jorisvandenbossche** [comment]
Reopening this one instead of opening a new issue. 

So PR https://github.com/pandas-dev/pandas/pull/22209 changed the top-level `pd.pivot` to match the behaviour of `DataFrame.pivot`. This is however a breaking change, so I think we should discuss in more detail if we want this, and if so, at least deprecate the current behaviour.

One option is to deprecate the current behaviour (and from the passed values, I think we should be able to infer if the old or new behaviour is wanted).

But, we maybe first need to discuss if we want to fully deprecate the old behaviour.

**Comment by TomAugspurger** [comment]
Anyone have thoughts here? Is this blocking for 0.24.0?

**Comment by jreback** [comment]
not blocking

**Comment by mroeschke** [comment]
Closing as this change has persisted since 0.24.0 and no complaints so far.
