### ISSUE TITLE
.head() method for Styler

### ISSUE THREAD

**Issue by jnothman** [pandas-dev/pandas#22302]
#### Problem description

Currently it is convenient to experiment with adding styling to a DataFrame in Jupyter. But if the DataFrame is large, rendering time is slow.

`Styler.head()` would be very useful to just display a fraction of the DataFrame.

#### Expected Output

Styler.head(n) would display the first n rows of the table with the assigned styles.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
LOCALE: en_AU.UTF-8

pandas: 0.23.1
pytest: 3.4.0
pip: 18.0
setuptools: 37.0.0
Cython: 0.27.3
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 5.1.0
sphinx: 1.6.2
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: 2.4.0
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.3
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jnothman** [comment]
I changed my mind. In most cases it would be more useful to call `dostuff(dataframe.head().style)` than to use `dostuff(dataframe.style).head()`

**Comment by aaronbarzilai** [comment]
I actually think it would be great to have .head() and similar work. I am a styler newbie, but have a function that returns a formatted Dataframe styler. Would love to be able to work with it in the same way I work with a DataFrame in general, but have the styles be retained each time I refer to the DataFrame(e.g. set styles once , then call .loc for different slices one at a time instead of having to set the style each time I slice it) 

Any chance you could reopen this? Thanks!

**Comment by TomAugspurger** [comment]
I think part of the reason I didn't implement it initially was because it'd be unclear if the conditional formatting should be applied on just the first `n` rows, and then displayed, or whether the conditional formatting should be applied to the entire frame, and then the first `n` rows displayed.

@aaronbarzilai I don't know if it works for your use-case, but you might want to investigate `Styler.export` and `Styler.use`: http://pandas-docs.github.io/pandas-docs-travis/style.html#Sharing-Styles

**Comment by aaronbarzilai** [comment]
Thanks, I thought about the SHaring Styles.

Totally get your point.  I think my main request, and get this could be far
off in dev plan, is I'd like to be able to set a table;s styling properties
once and have them used throughout my code/notebook without having to call
anything else.  For this feature request, I think you'd only apply the
formatting once on the table as is and then it would stay linked to the row
(index), not recalc'd for the slice you display.

Thanks for the prompt response and considering it. I really appreciate it.

Thanks,
Aaron
