### ISSUE TITLE
Clarify is_bool_indexer for Extension dtypes

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22326]
What do we want here?

```python
In [1]: import pandas as pd

In [2]: pd.core.common.is_bool_indexer(pd.Categorical([True, True]))
Out[2]: False
```

working around this in https://github.com/pandas-dev/pandas/pull/22325/

**Comment by TomAugspurger** [comment]
Likewise for `is_bool_dtype`.

**Comment by jorisvandenbossche** [comment]
Should we have something similar on the dtype as for numeric data? (the `ExtensionDtype._is_numeric` added recently) To indicate a certain dtype is considered boolean? 

Because otherwise those inspection functions would need to know how to inspect the dtype (for categorical checking the dtype of the categories). 

I am only a bit worried about a possible proliferation of such attributes .. 

(now, categorical with boolean categories also doesn't sound that useful. We could also say we require an actual boolean dtype to do boolean indexing)

**Comment by TomAugspurger** [comment]
I suppose this is what the `.kind` attribute is for?

Right now `Categorical.dtype.kind` is always `O`:

```python
In [8]: pd.Categorical([True, False]).dtype.kind
Out[8]: 'O'
```

If we changed that to be `.categories.dtype.kind` we wouldn't need a `._is_boolean`, though we would need to implement a `BooleanIndex`.
