### ISSUE TITLE
CategoricalBlock.array_dtype out of date?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#22381]
`CategoricalBlock.array_dtype` returns `np.object_`, but the docstring describes `array_dtype` as "the dtype to return if I want to construct this block as an array".  Shouldn't the array constructed now be `Categorical`?  In which case, shouldn't the dtype here be `self.dtype`?  (which matches the base class, and in fact makes the attribute unnecessary)

**Comment by jorisvandenbossche** [comment]
Depends on what kind of array? (numpy ndarray or EA?)

The only place where I see this used in `internals` is 

https://github.com/pandas-dev/pandas/blob/70e6f7c3ce7aca9a0ee08bacb2fe0ad85db02d88/pandas/core/internals/managers.py#L138

where in any case it is required to be a numpy dtype (and not extension dtype). So apparently this path is not hit with ExtensionBlock (where array_dtype is an EAdtype, otherwise it would fail). So from that, I think Categorical is actually more correct, apart from that it doesn't seem used anyway.

It would be good to investigate which path hits it, and see if it is possible to get there with an extension array.

**Comment by jbrockmendel** [comment]
> Depends on what kind of array? (numpy ndarray or EA?)

Yah, a lot of things seem to have this characteristic.  This is part of the motivation for #22388.

> So from that, I think Categorical is actually more correct, apart from that it doesn't seem used anyway.

Agreed.
