### ISSUE TITLE
read_csv reference cites two different default delimiters

### ISSUE THREAD

**Issue by jazzlw** [pandas-dev/pandas#22448]
In the [reference for the pandas.read_csv function ](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html), the prototype function shows that the default value for sep is `sep=', ',` (notice the space after the comma).

In the detailed description, it says that the default is 

> `sep : str, default ‘,’`

with no space after the comma, which is how the function behaves (comma space separators lead to columns with leading whitespace).

I would have done this as a pull request but I couldn't find the source for the doc page.

**Comment by WillAyd** [comment]
Hmm the docs are autogenerated from the call signature in the source (click on "[source]" in the docs to jump right there). 

Not sure why that space would be there though as it's not in the source for that function. There may be some undesired replacement for commas going on during generation here, especially since that is what's used to actually separate the keywords.

Investigation and PRs are welcome

**Comment by SamWheating** [comment]
Hi, I've started investigating this and noticed that the same can be seen on [the docs for DataFrame.to_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html). 

I'll start looking into the document generation process as suggested.

**Comment by jbrockmendel** [comment]
These now match, closing.  We can re-open if i missed something.
