### ISSUE TITLE
Bug in the api pandas.get_dummies()

### ISSUE THREAD

**Issue by anuraagrijal3138** [pandas-dev/pandas#22616]
In pandas.get_dummies, dtype attribute does not work. Please help!

pd.get_dummies(pd.Series(list('abc')), dtype=float)
TypeError: get_dummies() got an unexpected keyword argument 'dtype'

**Comment by WillAyd** [comment]
The most likely culprit is that you don't have a recent enough version of pandas since this argument was added in v0.23.0. However there isn't enough information here to say for sure so if that doesn't resolve it please refer to the contributing guide on how to open bug reports:

https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests
