### ISSUE TITLE
pd.Timestamp.today() / pd.to_datetime('today') returns date with time information

### ISSUE THREAD

**Issue by charlesoblack** [pandas-dev/pandas#22711]
Calling **pd.Timestamp.today()** or **pd.to_datetime('today')** returns both the date and time information. This is unexpected behavior since the time information should be returned with **.now()** or **'now'**, respectively, while the **.today()** and **'today'** should trim to simply the date information.

Example code:

```python
import pandas as pd
print(pd.Timestamp.today())
print(pd.to_datetime('today'))
```

#### Expected Output

pd.Timestamp('2018-09-14 00:00:00')

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
byteorder: little
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 39.0.1
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by mroeschke** [comment]
`Timestamp` (and `pd.to_datetime` since it will return a `Timestamp` with a scalar) follows `datetime.datetime` which returns the time component.

```
In [5]: pd.__version__
Out[5]: '0.24.0.dev0+576.g08bd3e378'

In [6]: datetime.today()
Out[6]: datetime.datetime(2018, 9, 14, 9, 47, 8, 954017)

In [7]: pd.Timestamp.today()
Out[7]: Timestamp('2018-09-14 09:47:10.760985')

In [8]: pd.to_datetime('today')
Out[8]: Timestamp('2018-09-14 09:47:12.977463')
```

So this is the intended behavior and [documented](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Timestamp.today.html) as such. In general `Timestamp`s follow `datetime.datetime` as closely as possible, so it's not ideal to change `'today'`s behavior in this case.

**Comment by charlesoblack** [comment]
Then why is there both .today() and .now()? I fail to see the difference
here.

**Comment by mroeschke** [comment]
This is from the [`datetime.now`](https://docs.python.org/2/library/datetime.html#datetime.datetime.today) docs which `Timestamp` follows:

>  If optional argument tz is None or not specified, this is like today()

**Comment by charlesoblack** [comment]
Ah, gotcha. Thank you! Is there an alternative then for getting today's
date?

**Comment by mroeschke** [comment]
If you want an actual `date` object there's a `.date()` method.

Otherwise there's also a [normalize](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Timestamp.normalize.html#pandas.Timestamp.normalize) method for `Timestamp` that will truncate the time to midnight leaving the year/month/date

**Comment by charlesoblack** [comment]
Perfect. Thank you!
