### ISSUE TITLE
read_html substitutions

### ISSUE THREAD

**Issue by AnnaSou** [pandas-dev/pandas#22732]
Hello All,

I have a link from which I need to get the data (basically the whole table)

https://cdaw.gsfc.nasa.gov/CME_list/radio/waves_type2.html

But there is no < table > tag, so read_html does not work.

![screen shot 2018-09-15 at 9 55 10 pm](https://user-images.githubusercontent.com/43326583/45602876-c9490f00-b9f3-11e8-9092-17c1959afdc1.png)

Are there any substitutions for read_html?

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.93-linuxkit-aufs
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 40.0.0
Cython: 0.28.5
numpy: 1.13.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.6
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by WillAyd** [comment]
For usage questions like this you'd be much better off asking on Gitter or SO, especially since the latter is oriented towards the Q&A format. There's more than likely quite a few approaches here which can be discussed better on that site.

This board is typically reserved for bug reports and enhancements which this doesn't really fall under; closing as a result
