### ISSUE TITLE
Custom Dtypes and `T`

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#22792]
I created a custom Array called ```GeoArray(NumPyBackedExtensionArrayMixin)```.

When I try to dump out my custom array, I get the following error:

```
builtins.AttributeError: 'GeoArray' object has no attribute 'T'
```

What does `T` have to be?  How do I define it?

**Comment by TomAugspurger** [comment]
> When I try to dump out my custom array,

What do you mean dump out?

`.T` is an alias of `.transpose()`.

**Comment by achapkowski** [comment]
I mean save the dataframe to an HDF5 table.

**Comment by achapkowski** [comment]
Where should I define transpose on the on my ```NumPyBackedExtensionArrayMixin(ExtensionArray):``` or on my `GeoArray` class?

**Comment by TomAugspurger** [comment]
Serializing extensions arrays is basically unsupported right now (though pickle usually works). See https://github.com/pandas-dev/pandas/issues/20612, and if you're interested in working on it let us know. It can be done for specific readers / writers in separate PRs.

`.T` / transpose isn't part of the EA interface and I don't think we'll include it, since it doesn't make sense for EAs.
