### ISSUE TITLE
lib.is_scalar misses PEP 3141 numbers

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#22903]
Looking at `np.isscalar`'s docstring I see:

```
    NumPy supports PEP 3141 numbers:

    >>> from fractions import Fraction
    >>> isscalar(Fraction(5, 17))
    True
    >>> from numbers import Number
    >>> isscalar(Number())
    True
```

pandas `lib.is_scalar` doesn't recognize Number or Fraction.

**Comment by jbrockmendel** [comment]
Same function, yes

**Comment by brute4s99** [comment]
@jbrockmendel ok, the problem is something like this :-

The function is currently limited to the dtypes specified [here](PyObject_TypeCheck).
This is backed by my findings upon close looks to the [is_scalar definition for pandas](https://github.com/pandas-dev/pandas/blob/9caf04836ad34ca17da7b86ba7120cca58ce142a/pandas/_libs/lib.pyx#L107), 
So I need to simply add entries for some more dtypes.
> Currently `Number` and `Fraction`.
As seen within [CPython's codebase](https://github.com/python/cpython/blob/9012a0fb4c4ec1afef9efb9fdb0964554ea17983/Include/datetime.h#L186), the underlying functionality *might be* same as comparing through `type` function.

**Comment by brute4s99** [comment]
I'll just call np.isscalar() ! :smile:

**Comment by brute4s99** [comment]
Yay! 🍻
