### ISSUE TITLE
Wish: Input / output for Open Document Spreadsheet (ODS)

### ISSUE THREAD

**Issue by lbeltrame** [pandas-dev/pandas#2311]
It would be nice to have, along with XLS and XLSX, also support for ODS (used notably by OpenOffice.org and Libreoffice, but not only that). 

The main problem I saw is that there's a plethora of libraries to handle that: however not sure which is the "best" one (with a licensing that would fit with pandas).

**Comment by davidovitch** [comment]
I would like to give an update on the current status. My [fork](https://github.com/davidovitch/pandas) can currently read ODF ODS files, but writing is not implemented yet. The corresponding pull request is still pending review, and it has been a lot more work than I originally anticipated.

Just a few days ago I bumped into yet another library to read/write spreadsheet: [pyexcel](https://github.com/chfw/pyexcel). What is different about this library is that it aims at creating a single API for all the different read/write libraries, and it builds on all the existing libraries out there (ezodf, xlrd, etc). This is actually kind of similar to what pandas currently has, and to what I am trying to extend in PR #9070. So I am wondering, would it make sense to use a single API library (with optional dependencies to all the relevant readers/writers for the different spreadsheet types) instead of developing something similar, but tailored to pandas use case? I am speculating that a lot of code in io/excel.py could be removed when relying on pyexcel, but it adds yet another dependency. At this stage I am not sure how all different edge cases on data types and other magic happening inside the spreadsheet interpretation differs between the current pandas implementation and pyexcel.

**Comment by davidovitch** [comment]
The ods reader is not ready for the upcoming 0.17 release. PR #9070 is closed (see the PR for a technical discussion), and a new improved PR will be made by someone at some point in the future. I have a working version in the [ezodf_reader](https://github.com/davidovitch/pandas/tree/ezodf_reader) branch of my pandas fork in case someone wants to have a look at it. Suggestions and improvements are welcome :-)

**Comment by H0R5E** [comment]
@davidovitch thanks for your efforts! Its a shame that that reading and writing to ODF is not better supported in python, otherwise I'm sure this would be less of an ordeal.

**Comment by PBrockmann** [comment]
Working on how to structure data for paleoclimatology community, I would like to promote ODS as the standard format.  Then of course, pandas with this possible reading and writing at ODS format would become the natural way for IO and start nice analysis.

+2 and more for this feature that seems so closed to be released.

**Comment by naught101** [comment]
You should almost certainly be using netcdf for paleoclimate data. It's more or less industry standard. Checkout the python package 'xray' for a nice way to interface with it.

On 3 November 2015 12:30:20 am AEDT, Patrick Brockmann <notifications@github.com> wrote:
>Working on how to structure data for paleoclimatology community, I
>would like to promote ODS as the standard format.  Then of course,
>pandas with this possible reading and writing at ODS format would
>become the natural way for IO and start nice analysis.
>
>+2 and more for this feature that seems so closed to be released.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pydata/pandas/issues/2311#issuecomment-153016604

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PBrockmann** [comment]
@naught101: I know quite well netCDF format and all its different conventions like CF (Climate and Forecast) widely used in the Earth System Modelling community but it seems that the PaleoClimate one has also good argument to keep working with others standard. An article that is under discussion describes this motivation. Read https://www.authorea.com/users/17200/articles/19163/_show_article and please feel free to contribute it.  
In my understanding, the data themselves are not problematic, the difficulty comes more from the metadata that are in many aspect hierachical. Netcdf attributs are in this case not very well designed.
On this other hand, describe those metadata with a simple spreadsheet with a dotted notation in an open source format like ODS (I will do a proposition in this way) could be interesting because it will not radically change the behaviour of PaleoClimate scientists that widelly work with spreadsheets.
All this, to say that if pandas could allow IO from ODS, it could be a good motivation to start their analysis with pandas.

**Comment by shoyer** [comment]
@PBrockmann If your metadata is hierarchical, maybe it would be appropriate to use the hierarchical features of netCDF4/HDF5? Just a thought. In any case, I think we agree regardless that ODS support would be valuable for pandas.

**Comment by hnykda** [comment]
Is there any progress on this? Thanks

**Comment by jreback** [comment]
@hnykda there is a PR #9070 that is not far away, but needs some work if you'd like to pick it up.

**Comment by hnykda** [comment]
Will take a look at it. Thank you for pointing it out.

**Comment by jameserrico** [comment]
On a similar note has anyone considered Google Sheets?  There are some limits to the size of a sheet (http://gappstips.com/google-sheets/google-spreadsheet-limitations/) that probably make it only usable for some cases but there are quite a lot of datasets that would fit within this restrictions and the ease of collaboration with Sheets is nice.

**Comment by detrout** [comment]
@jameserrico There's a library https://github.com/embr/gcat that can read from google drive. I have a fork that I updated to work with python3 https://github.com/detrout/gcat but upstream hasn't merged the pull-request

It knows how to return pandas data frames. I.e. I have some code like this:
```python
    book = gcat.get_file(book_name, fmt='pandas_excel')
    experiments = book.parse('Experiments', header=0)`

**Comment by detrout** [comment]
I have a standalone reader styled like pandas.io.excel with tests.
https://github.com/detrout/pandasodf

It uses odfpy as that seems like its still maintained. Any comments, or should I try reformatting into a pull request creating  pandas/io/odf.py?

I thought the .read_odf method seemed more reasonable, than overloading .read_excel

**Comment by naught101** [comment]
> I thought the .read_odf method seemed more reasonable, than overloading .read_excel 

Makes sense. Perhaps there could be a `read_spreadsheet` that calls `read_csv`, `read_excel`, `read_odf` etc, depending on the extension?

**Comment by detrout** [comment]
@naught101 The general reader might have some difficulties since there are differences in what the various formats support. CSV/TSV only have a single table, while Excel & ODF can have multiple tables per file. 

Also I'm currently contemplating passing the raw odfpy xml cell node for the converters callable, so those would be quite difficult to write if you didn't know the source file type.

**Comment by davidovitch** [comment]
> I thought the .read_odf method seemed more reasonable, than overloading .read_excel

@detrout FYI, maybe things have changed since, but at the time of PR #9070 there was a very clear decision by the pandas devs not to do that and to keep ```read_excel``` for the Excel and Open Document Format families.

**Comment by H0R5E** [comment]
Great to see the ODF reader implemented. Well done! I'm not sure this should have been closed though, as writing still isn't supported.

**Comment by jreback** [comment]
i would open a new issue for write support (if it’s really needed)
