### ISSUE TITLE
BUG: Series.ne() returns False for both NaN value even if something is passed to fill_value

### ISSUE THREAD

**Issue by kbhutani0001** [pandas-dev/pandas#23130]
```


# importing pandas module  
import pandas as pd  
  
# importing numpy module 
import numpy as np 
  
# creating series 1 
series1 = pd.Series([70, 5, 0, 225, 1, 16, np.nan, 10, np.nan]) 
  
# creating series 2 
series2 = pd.Series([27, np.nan, 2, 23, 1, 95, np.nan , 3, 19]) 

#NaN replacement
replace_nan=5

#calling and returning to result variable
result=series1.ne(series2,fill_value=replace_nan)

#display 
result 


```
Series.ne() returns False if value at the index in both series is NaN even if some value is passed to fill_value parameter. 
As in above example, after replacement, condition should be 5 != 5 which should return False. But output was True.

Expected Output:

0     True
1    False
2     True
3     True
4    False
5     True
6     False
7     True
8     True
dtype: bool

Returned Output: 
0     True
1    False
2     True
3     True
4    False
5     True
6     True
7     True
8     True
dtype: bool

**Comment by dsaxton** [comment]
Based on the documentation it appears the null filling only applies to one of the Series, so the actual operation being performed would be np.nan != 5 and not 5 != 5.

**Comment by kbhutani0001** [comment]
Okay maybe that's right but in the other similar methods like .le() .ge()
and .lt the null filling is applicable to both of the series.

**Comment by jbrockmendel** [comment]
This is the expected behavior.  Per the docstring:

```
    If data in both corresponding Series locations is missing
    the result of filling (at that location) will be missing.
```

(im going to write `ser1 = series1[5:]`, `ser2 = series[5:]` for brevity)

so when you do `ser1.ne(ser2, fill_value=5)`, the NaN on `ser2[8]` gets filled, but the NaNs in `ser1[6]` and `ser2[6]`, so the comparison in location 6 is `cmp(NaN, NaN)`, which for `!=` is `True` and is `False` for all other comparison ops.

Closing as correct-as-is.  We can re-open if you think this merits further discussion.
