### ISSUE TITLE
CI: Test failures on numpydev

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23172]
e.g. https://travis-ci.org/pandas-dev/pandas/jobs/441869826

I can reproduce these locally.

I just restarted the latest build on master to ensure that they're present there.

**Comment by TomAugspurger** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/441766904

**Comment by TomAugspurger** [comment]
git bisect points to https://github.com/numpy/numpy/commit/607842ab59b0479c485eb6fa30778f47dccc224a (cc @shoyer) 

I'm just running `pytest pandas/pandas/tests/test_multilevel.py::TestMultiLevel::test_frame_group_ops[True-True-1-0-skew]
`

**Comment by TomAugspurger** [comment]
Looking at the diff, nothing really jumps out. If it helps debug at all, that test is parametrized across a bunch of things. Just `skew` and `mad` fail.

**Comment by TomAugspurger** [comment]
A not really minimal example of what changed is

```python
In [22]: df = pd.DataFrame([[1, 2], [3, 4]], columns=pd.MultiIndex.from_tuples([('A', 1), ('A', 2)]))

In [23]: df.skew(level=1, axis=1)
Out[23]:
1    0   NaN
1   NaN
dtype: float64
2    0   NaN
1   NaN
dtype: float64
dtype: object

```

Previously that was

```python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame([[1, 2], [3, 4]], columns=pd.MultiIndex.from_tuples([('A', 1), ('A', 2)]))

In [3]: df.skew(level=1, axis=1)
Out[3]:
    1   2
0 NaN NaN
1 NaN NaN

```

**Comment by TomAugspurger** [comment]
@shoyer do you have any guesses about why this would have been broken by 
https://github.com/numpy/numpy/commit/607842ab59b0479c485eb6fa30778f47dccc224a?

If not, I'll revisit this tomorrow.

**Comment by shoyer** [comment]
The main thing that commit changes is that NumPy functions like `np.sum()` are now defined with decorators, so they point to wrappers generated with `functools.wraps`.

Since pandas isn't using `__array_function__` yet, I have two guesses about what could be going wrong here (but neither feel especially likely):
1. pandas does some sort of deep-introspection on NumPy function objects that apparently no longer works.
2. the [dispatcher](http://www.numpy.org/neps/nep-0018-array-function-protocol.html#finding-arguments) for some NumPy function is broken, at least when called by pandas (e.g., it's trying to iterate over some object that isn't iterable), and then pandas catches that error and creates an object with the wrong type.

Probably the best place to start would be with the definition of the `skew` implementation in terms of NumPy functions.

**Comment by shoyer** [comment]
I think the most likely culprit for this is that these changes to NumPy break `inspect.getargspec` and `inspect.getfullargspec`. This gets called internally in pandas [here](https://github.com/pandas-dev/pandas/blob/145c2275e3560edc30ff418a57df67ba3c4c30d6/pandas/core/apply.py#L127), which I'm pretty sure is in the code path for these method calls.

**Comment by shoyer** [comment]
Nevermind that -- my proposed NumPy patch didn't fix this failure in pandas, so probably something else is going on.

**Comment by shoyer** [comment]
I figured it out! The cause is https://github.com/numpy/numpy/issues/12263

After applying the NumPy fix (https://github.com/numpy/numpy/pull/12280), the pandas test suite outputs the following warning:
```
$ pytest "pandas/tests/test_multilevel.py::TestMultiLevel::test_frame_group_ops[True
................................... -True-1-0-skew]"
================================================ test session starts =================================================
platform darwin -- Python 3.6.4, pytest-3.9.1, py-1.5.3, pluggy-0.8.0
hypothesis profile 'ci' -> timeout=5000, suppress_health_check=[HealthCheck.too_slow], database=DirectoryBasedExampleDatabase('/Users/shoyer/dev/pandas/.hypothesis/examples')
rootdir: /Users/shoyer/dev/pandas, inifile: setup.cfg
plugins: hypothesis-3.79.0
collected 1 item

pandas/tests/test_multilevel.py .                                                                              [100%]

============================================= slowest 10 test durations ==============================================
0.05s setup    pandas/tests/test_multilevel.py::TestMultiLevel::test_frame_group_ops[True-True-1-0-skew]
0.03s call     pandas/tests/test_multilevel.py::TestMultiLevel::test_frame_group_ops[True-True-1-0-skew]

(0.00 durations hidden.  Use -vv to show these durations.)
================================================== warnings summary ==================================================
/Users/shoyer/dev/pandas/pandas/core/groupby/generic.py:432: FutureWarning: arrays to stack must be passed as a sequence. Support for non-sequence iterables is deprecated as of NumPy 1.16 and will raise an error in the future. Note also that dispatch with __array_function__ is not supported when arrays are not provided as a sequence.
  stacked_values = np.vstack(map(np.asarray, values))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================================== 1 passed, 1 warnings in 0.17 seconds ========================================
```

It looks like my second diagnosis above was mostly correct: the dispatcher for `vstack()` exhausted the generator from `map`, which then resulting in a very indirect error because pandas catches the resulting `ValueError`:
https://github.com/pandas-dev/pandas/blob/da9d85122a5b36b89fffa8f86ef768db20fc64c0/pandas/core/groupby/generic.py#L428-L432

**Comment by TomAugspurger** [comment]
Wow, thanks for tracking that down :)

I'll make time next week to get us running on NumPy dev again (we fail errors from NumPy on our numpydev build).
