### ISSUE TITLE
Giving Userwarning for labelling columns in 'name' attribute of read_csv

### ISSUE THREAD

**Issue by PawarKishori** [pandas-dev/pandas#23299]
#### Code Sample, a copy-pastable example if possible

```python

df= pd.read_csv(filename, sep='\t',names=['PID','WORD','-','POS','-','-','PID-WITH','RELATION','-','-'])


```
#### Problem description
The input csv file in my case is actually a tab separated file.
I am getting a UserWarning after following the syntax provided in the documentation. This is indicatinf me, that I will get error in future. What will be that?

#### Expected Output

No warnings should occur

<details>

/lib/python3.6/site-packages/pandas/io/parsers.py:678: UserWarning: Duplicate names specified. This will raise an error in the future.
  return _read(filepath_or_buffer, kwds)

</details>

**Comment by WillAyd** [comment]
This isn't clear what the issue is and the example is not self contained, so it's not something we can really look at.

If you can provide the information required in the contributing guide on bug reports inclusive of the minimally reproducible example feel free to reopen

https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests
