### ISSUE TITLE
memory usage after writing then reading a multi-indexed dataframe from an hdf5 increases dramatically

### ISSUE THREAD

**Issue by headdab** [pandas-dev/pandas#23369]
#### Code Sample, a copy-pastable example if possible

```python
#!/usr/bin/env python

import numpy as np
import pandas as pd

index = pd.MultiIndex.from_product([list(range(10000)), list(range(10))])
df = pd.DataFrame(np.random.rand(100000, 10), index=index, columns=list(range(10)))
df = (df * 3840).astype(np.int16)
df.info()

sdf = df.sample(1000)
sdf.info()

with pd.HDFStore('test.h5') as h5:
    h5['sdf'] = sdf

sdf = pd.read_hdf('test.h5', 'sdf')
sdf.info()
```

#### Problem description

The memory used by a multi-indexed dataframe increases dramatically after writing to and reading it back from an hdf5 data file.

#### Expected Output

```
class 'pandas.core.frame.DataFrame'>
MultiIndex: 100000 entries, (0, 0) to (9999, 9)
Data columns (total 10 columns):
0    100000 non-null int16
1    100000 non-null int16
2    100000 non-null int16
3    100000 non-null int16
4    100000 non-null int16
5    100000 non-null int16
6    100000 non-null int16
7    100000 non-null int16
8    100000 non-null int16
9    100000 non-null int16
dtypes: int16(10)
memory usage: 2.6 MB

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, (6381, 5) to (7551, 4)
Data columns (total 10 columns):
0    1000 non-null int16
1    1000 non-null int16
2    1000 non-null int16
3    1000 non-null int16
4    1000 non-null int16
5    1000 non-null int16
6    1000 non-null int16
7    1000 non-null int16
8    1000 non-null int16
9    1000 non-null int16
dtypes: int16(10)
memory usage: 100.7 KB

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, (6381, 5) to (7551, 4)
Data columns (total 10 columns):
0    1000 non-null int16
1    1000 non-null int16
2    1000 non-null int16
3    1000 non-null int16
4    1000 non-null int16
5    1000 non-null int16
6    1000 non-null int16
7    1000 non-null int16
8    1000 non-null int16
9    1000 non-null int16
dtypes: int16(10)
memory usage: 421.0 KB
```

- Note that the sparse version before writing to an hdf5 file uses 100kB, but it uses 421kB after I reread it from the hdf5 file.  This is over 4X the original memory usage.

- As a note, the original array uses 2.6 MB to store 100000 * 10 * 2 = 2MB of array data (30% overhead), the sparse version before writing uses 100.7kB to store 1000*10*2 = 20kB of array data (400% overhead), and the final version, after rereading from the hd5 file uses 421kB to store 20kB of data (
2000% overhead).

- A simpler, non-multiindex case gave the same result before and after writing the data to an hdf5 file, with about 30% overhead.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS                
------------------                
commit: None                      
python: 3.6.3.final.0             
python-bits: 64                   
OS: Linux                         
OS-release: 4.13.0-41-generic     
machine: x86_64                   
processor: x86_64                 
byteorder: little                 
LC_ALL: None                      
LANG: en_US.UTF-8                 
LOCALE: en_US.UTF-8               

pandas: 0.23.4                    
pytest: None                      
pip: 10.0.1                       
setuptools: 32.3.1                
Cython: None                      
numpy: 1.14.5                     
scipy: 1.1.0                      
pyarrow: None                     
xarray: None                      
IPython: 6.4.0                    
sphinx: None                      
patsy: None                       
dateutil: 2.7.3                   
pytz: 2018.5                      
blosc: None                       
bottleneck: None                  
tables: 3.4.4                     
numexpr: 2.6.8                    
feather: None                     
matplotlib: 2.2.2                 
openpyxl: None                    
xlrd: None                        
xlwt: None                        
xlsxwriter: None                  
lxml: None                        
bs4: None                         
html5lib: 1.0.1                   
sqlalchemy: None                  
pymysql: None                     
psycopg2: None                    
jinja2: 2.10                      
s3fs: None                        
fastparquet: None                 
pandas_gbq: None                  
pandas_datareader: None           
</details>

**Comment by gfyoung** [comment]
@headdab : Thanks for the report!  Just to double check, is round-trip being respected when you do the read / write to / from HDF5?  Perhaps something in the internals is causing the representation to be less efficient or compact.

**Comment by headdab** [comment]
I'm not sure what you mean by round-trip?
Do you mean is the data correct?

The output shows that the number of size of the underlying data elements in the same ...

**Comment by gfyoung** [comment]
Yes, i.e.:

~~~python
sdf1 = df.sample(1000)  # original DataFrame
...
sdf2 = pd.read_hdf('test.h5', 'sdf')  # read-in DataFrame

import pandas.util.testing as tm
tm.assert_frame_equal(sdf1, sdf2)
~~~

I also wonder if it has to deal with the fact that you're using `int16` (our support for that data type is deliberately pretty thin).  What happens if you use `int32` or `int64` instead?

**Comment by headdab** [comment]
It appears that this has nothing to do with the data type.  Consider the slightly simplified version of the code above, with a round-trip check.

```
#!/usr/bin/env python

import numpy as np
import pandas as pd

index = pd.MultiIndex.from_product([list(range(10000)), list(range(10))])
df = pd.DataFrame(np.random.rand(100000, 10), index=index, columns=list(range(10)))

sdf1 = df.sample(1000).astype(np.int8)
with pd.HDFStore('test.h5') as h5:
    h5['sdf'] = sdf1
sdf2 = pd.read_hdf('test.h5', 'sdf')

sdf1.info()
sdf2.info()

import pandas.util.testing as tm
tm.assert_frame_equal(sdf1, sdf2)
```
where I tried many different data types instead of int16 for sdf1.  I got the following results:

```
type    before after data
--------------------------------
int8    90.9   411.2 10
int16   100.7  421.0 20
int32   120.2  440.5 40
int64   159.3  479.6 80
float64 159.3  479.6 80
```
- `before` is the size of sdf1
- `after` is the size of sdf2
- `data` is the storage required for the data itself

If you subtract `data` from `before` and `after`, you get a fixed value of about 80k for before and 400k for after, so the expansion is not in the data itself, its likely in the data structures used internally for hdf5 data.  I think this is important.  There appears to be lots of support for sparse vectors, to minimize the memory footprint, but then much of this appears to be squandered away.

Writing the same data to a csv and reading it back only  consumes 93.8kB (it infers int64 so it doesn't matter what format its stored as.

**Comment by jreback** [comment]
this is correct. before you are saving it, the indexing tables are NOT created. When you read it back, they are on the read-back (mainly because a reindex is done internally). This is basically lazy creating of the indexes.

so here's your example
```
(pandas) bash-3.2$ ipython
Python 3.6.3 |Anaconda, Inc.| (default, Dec  5 2017, 17:30:25) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np
   ...: import pandas as pd
   ...: 
   ...: index = pd.MultiIndex.from_product([list(range(10000)), list(range(10))])
   ...: df = pd.DataFrame(np.random.rand(100000, 10), index=index, columns=list(range(10)))
   ...: df = (df * 3840).astype(np.int16)
   ...: df.info()
   ...: 
   ...: sdf = df.sample(1000)
   ...: sdf.info()
   ...: 
   ...: with pd.HDFStore('test.h5') as h5:
   ...:     h5['sdf'] = sdf
   ...: 
   ...: sdf2 = pd.read_hdf('test.h5', 'sdf')
   ...: sdf2.info()
   ...: 
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 100000 entries, (0, 0) to (9999, 9)
Data columns (total 10 columns):
0    100000 non-null int16
1    100000 non-null int16
2    100000 non-null int16
3    100000 non-null int16
4    100000 non-null int16
5    100000 non-null int16
6    100000 non-null int16
7    100000 non-null int16
8    100000 non-null int16
9    100000 non-null int16
dtypes: int16(10)
memory usage: 2.6 MB<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, (2671, 4) to (3612, 5)
Data columns (total 10 columns):
0    1000 non-null int16
1    1000 non-null int16
2    1000 non-null int16
3    1000 non-null int16
4    1000 non-null int16
5    1000 non-null int16
6    1000 non-null int16
7    1000 non-null int16
8    1000 non-null int16
9    1000 non-null int16
dtypes: int16(10)
memory usage: 100.7 KB
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, (2671, 4) to (3612, 5)
Data columns (total 10 columns):
0    1000 non-null int16
1    1000 non-null int16
2    1000 non-null int16
3    1000 non-null int16
4    1000 non-null int16
5    1000 non-null int16
6    1000 non-null int16
7    1000 non-null int16
8    1000 non-null int16
9    1000 non-null int16
dtypes: int16(10)
memory usage: 421.0 KB
``

before writing to disk
````
In [2]: sdf.info()
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, (2671, 4) to (3612, 5)
Data columns (total 10 columns):
0    1000 non-null int16
1    1000 non-null int16
2    1000 non-null int16
3    1000 non-null int16
4    1000 non-null int16
5    1000 non-null int16
6    1000 non-null int16
7    1000 non-null int16
8    1000 non-null int16
9    1000 non-null int16
dtypes: int16(10)
memory usage: 100.7 KB

In [3]: sdf2.info()
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, (2671, 4) to (3612, 5)
Data columns (total 10 columns):
0    1000 non-null int16
1    1000 non-null int16
2    1000 non-null int16
3    1000 non-null int16
4    1000 non-null int16
5    1000 non-null int16
6    1000 non-null int16
7    1000 non-null int16
8    1000 non-null int16
9    1000 non-null int16
dtypes: int16(10)
memory usage: 421.0 KB
```

```
In [4]: sdf[0]
```
do *any* indexing, this creates the c-structures underlying MI

after read
```
In [5]: sdf.info()
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, (2671, 4) to (3612, 5)
Data columns (total 10 columns):
0    1000 non-null int16
1    1000 non-null int16
2    1000 non-null int16
3    1000 non-null int16
4    1000 non-null int16
5    1000 non-null int16
6    1000 non-null int16
7    1000 non-null int16
8    1000 non-null int16
9    1000 non-null int16
dtypes: int16(10)
memory usage: 420.7 KB

In [6]: sdf2.info()
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, (2671, 4) to (3612, 5)
Data columns (total 10 columns):
0    1000 non-null int16
1    1000 non-null int16
2    1000 non-null int16
3    1000 non-null int16
4    1000 non-null int16
5    1000 non-null int16
6    1000 non-null int16
7    1000 non-null int16
8    1000 non-null int16
9    1000 non-null int16
dtypes: int16(10)
memory usage: 421.0 KB

```

**Comment by gfyoung** [comment]
@jreback : Ah, interesting...to what extent is this behavior documented?

**Comment by jreback** [comment]
i am not sure what needs to be documented here; this is actually an implementation detaik

**Comment by gfyoung** [comment]
Ah, okay, fair enough.  Just checking.
