### ISSUE TITLE
Timestamp and DatetimeIndex construct different timezones

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23815]
Question in the form of an issue: is this a bug?

```python
In [37]: pd.Timestamp('2000', tz='US/Central').tz == pd.DatetimeIndex(['2000'], tz='US/Central').tz
Out[37]: False
```

This leads to strange things like 

```python
In [38]: idx = pd.date_range('20170101', periods=4, tz='US/Pacific')

In [39]: idx[0].tz == idx.tz
Out[39]: False
```

**Comment by TomAugspurger** [comment]
DatetimeIndex (via, DatetimeArrayMixin) goes

```python
        tz = timezones.maybe_get_tz(tz)
        result._tz = timezones.tz_standardize(tz)
 ```

`Timestmamp.__new__` seems to use a tzinfo object.

So it seems like I should be using `_libs.tslibs.timezones.tz_compare`, rather than `==`.

**Comment by mroeschke** [comment]
These are expected to be unequal due to pytz semantics.

For a pytz timezone with a `Timestamp`, we are only dealing with one date, so we can confidently know which side of DST border the date lies and can use the DST informed tzinfo instance (CST-1 day).

For a pytz timezone with a `DatetimeIndex`, we are potentially dealing with 1+ dates where a mix of dates can lie on either side of the DST border. Therefore we cannot easily use one pytz timezone instance to represent all these dates and just default to the "first" pytz instance for a timezone (LMT-1 day)

**Comment by TomAugspurger** [comment]
Fun... I'll try to turn this into a new docs section in http://pandas-docs.github.io/pandas-docs-travis/timeseries.html#working-with-time-zones

Should we add `tz_compare` to our public API, as the recommended way to compare to tz objects?

**Comment by mroeschke** [comment]
Yeah clarifying this pytz idiosyncrasy in the docs would be a nice addition.

@jbrockmendel is the spec for `tz_compare` to see if timezone objects represent the same timezone or to check if two timezone instances are the same?

**Comment by jbrockmendel** [comment]
To see if they represent the same timezone.

**Comment by mroeschke** [comment]
Gotcha. My impression was that `tz_compare` was a utility for the internals, but I guess if users may find it useful then we can expose it as a toplevel `"pd.tz_compare"`. Probably would need a lot more tests though to nail down the spec.

**Comment by jorisvandenbossche** [comment]
See also https://github.com/pandas-dev/pandas/issues/17572 and https://github.com/pandas-dev/pandas/issues/18595 where this has been discussed before.
