### ISSUE TITLE
Unexpected DataFrame.groupby.apply miscalculation

### ISSUE THREAD

**Issue by liu-hanwen** [pandas-dev/pandas#23834]
Using `DataFrame.groupby.apply()` and make a copy of one of the columns may have unexpected result.
#### Code Sample
```python
import pandas as pd
data_list = [
    ['Class A', '1'],
    ['Class A', '5'],
    ['Class B', '7'],
    ['Class B', '2'],
    ['Class C', '3'],
    ['Class C', '9']
]
df = pd.DataFrame(data=data_list, columns=['Class', 'Number'])
def func_(x):
    x['Temp'] = x['Number']
    x['Comment'] = x['Temp'].apply(lambda y: y + ' is a number')
    x = x.drop(columns=['Temp'])
    return x
result = df.groupby(['Class']).apply(func_)
```
#### Problem description

If I try to make a copy of one of the columns and drop it after using it in `DataFrame.groupby.apply()`, the result is unexpected. The result is filled with first group's duplications.

I have done some tests and found that it is a very special case:
  - If I make a copy of table in the apply function (x = x.copy()), the result will be expected.
  - If I drop the 'Temp' column by using `inplace=True`, the result will be expected.
  - If the length of each group is not equal, the result will be expected.

I knew it may not be a good way to add or drop columns in apply function, but I think it is still a bug.

#### Expected Output

Class | Number | Comment
-- | -- | --
Class A | 1 | 1 is a number
Class A | 5 | 5 is a number
Class B | 7 | 7 is a number
Class B | 2 | 2 is a number
Class C | 3 | 3 is a number
Class C | 9 | 9 is a number

#### Unexpected Output

Class | Number | Comment
-- | -- | --
Class A | 1 | 1 is a number
Class A | 5 | 5 is a number
Class A | 1 | 1 is a number
Class A | 5 | 5 is a number
Class A | 1 | 1 is a number
Class A | 5 | 5 is a number

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: zh_CN.UTF-8

pandas: 0.23.0
pytest: 3.5.1
pip: 18.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
I agree that your implementation of adding / dropping columns does seem a little weird, there definitely seems to be some massive aliasing going on behind the scenes, which is unusual...

cc @jreback

**Comment by WillAyd** [comment]
Is there a practical reason for coding the UDF in this fashion? Agree it looks buggy but it's also a rather convoluted example which could be expressed without the addition and dropping of columns.

In any case investigation and PRs are always welcome

**Comment by lordgrenville** [comment]
I've encountered the same bug, which I can reproduce with a slightly simpler example (an abstraction of my real-life use case). This astonished me when I discovered it; seems like an pretty big issue. Thankfully @liu-hanwen's solution of adding a copy statement at the top works.

Example:

```
data = [
    ['A', 1],
    ['A', 1],
    ['B', 0],
    ['B', 1],
    ['C', 0],
    ['C', 0],
]
df = pd.DataFrame(data, columns=['class', 'status'])

def my_func(x):
    # x = x.copy()
    x.loc[-1] = x.iloc[0].copy()
    x.loc[-2] = x.iloc[0].copy()
    x.loc[-2, 'status'] = 0
    x.loc[-1, 'status'] = 1
    x = x.sort_index()
    if not x.status.is_monotonic:
        x['status'] = 0
    return x.iloc[2:,:]

df.groupby('class').apply(my_func)


```
Current output:

|       |   | class | status |
|-------|---|-------|--------|
| class |   |       |        |
| A     | 0 | A     | 1      |
|       | 1 | A     | 1      |
| B     | 0 | A     | 1      |
|       | 1 | A     | 1      |
| C     | 0 | A     | 1      |
|       | 1 | A     | 1      |

Expected (obtained by uncommenting the copy at the beginning):

|       |   | class | status |
|-------|---|-------|--------|
| class |   |       |        |
| A     | 0 | A     | 1      |
|       | 1 | A     | 1      |
| B     | 2 | B     | 0      |
|       | 3 | B     | 0      |
| C     | 4 | C     | 0      |
|       | 5 | C     | 0      |

I believe what triggers this is altering the index of the original group.

Another interesting point is what happens when we add print statements in two places:

```
def my_func(x):
    x.loc[-1] = x.iloc[0].copy()
    x.loc[-2] = x.iloc[0].copy()
    x.loc[-2, 'status'] = 0
    x.loc[-1, 'status'] = 1
    print(x.name)
    x = x.sort_index()
    if not x.status.is_monotonic:
        x['status'] = 0
    print(x.name)
    return x.iloc[2:,:]

df.groupby('class').apply(my_func)
```
The first works, the second triggers an `AttributeError`(!) implying that `x` is no longer the group(?)

**Comment by WillAyd** [comment]
Changing a frame (or any container in Python really) while iterating over it is not supported

**Comment by lordgrenville** [comment]
Fair enough, although failing when the frame is changed within `groupby-apply` rather than silently returning distorted data would be much more helpful.
