### ISSUE TITLE
Clarify how to cite pandas in scientific papers

### ISSUE THREAD

**Issue by JoKeyser** [pandas-dev/pandas#24036]
Dear developers,
first thank you for your great work.

I'd like to reference my use of pandas in my scientific work, but have been unable to find a recommendation how to cite this.
I'm aware of https://pandas.pydata.org/talks.html, but the "papers" seem to refer to conference proceedings (slides) that lack a publisher, and seem out-dated?

Maybe something similar to [SciPy's recommendations](https://www.scipy.org/citing.html) could be added?

**Comment by TomAugspurger** [comment]
The paper linked from 
https://www.scipy.org/citing.html is the correct one. We could update the link from talks. That’ll be in the pandas-website repository.

**Comment by JoKeyser** [comment]
@TomAugspurger thanks for the fast response.

So the correct bibtex entry is:
```bibtex
@InProceedings{ mckinney-proc-scipy-2010,
  author    = { Wes McKinney },
  title     = { Data Structures for Statistical Computing in Python },
  booktitle = { Proceedings of the 9th Python in Science Conference },
  pages     = { 51 - 56 },
  year      = { 2010 },
  editor    = { St\'efan van der Walt and Jarrod Millman }
}
```

I guess the only issue then is/was the dead link on https://pandas.pydata.org/talks.html to http://jarrodmillman.com/scipy2010/pdfs/mckinney.pdf when it should link to http://conference.scipy.org/proceedings/scipy2010/pdfs/mckinney.pdf

An editor asked for a publisher, but then I'll just reply that there is no one with that role.

**Comment by JoKeyser** [comment]
@mroeschke yes, I think it's helpful to include it anywhere an author would look after it. Over in the `R` world, most packages come with their `citation` command, which makes it very convenient (and thus likely) to be cited correctly.

Not sure whether such a discussion belongs here, but it seems to me that also the work since 2010 could be included into an "official" reference recommendation?

**Comment by ivalaginja** [comment]
Does pandas have a DOI for native software citation, like matplotlib? See [here](https://zenodo.org/record/3264781#.XWs-Yy2ZOX0), where I can get a bibtex entry for native software citation, depending on the version I use or a concept DOI.

**Comment by JoKeyser** [comment]
Pandas could also get a Research Resource Identifier (RRID), see e.g. [matplotlib (RRID:SCR_008624)](https://scicrunch.org/resources/Any/record/nlx_144509-1/SCR_008624/resolver?q=matplotlib&l=matplotlib). The RRIDs of the software I used was requested in a review process by the [European Journal of Neuroscience](https://www.fens.org/EJN/).

**Comment by TomAugspurger** [comment]
I don't think pandas has either of those.

**Comment by ivalaginja** [comment]
Would the `pandas` team consider obtaining a DOI?

Trying to establish citation principles that will give everyone due credit, as well as create traceable records of a work unit like a piece of software, the [FORCE11 Software Citation Working Group](https://www.force11.org/about) published a [paper presenting software citation principles](https://www.force11.org/software-citation-principles). This includes the need to cite the software product directly, *additionally* to software papers (see section 6.2):
> 6.2 **Software papers.** Currently, and for the foreseeable future, software papers are being published and cited, in addition to software itself being published and cited, as many community norms and practices are oriented towards citation of papers. [...] **the software itself should be cited on the same basis as any other research product; authors should cite the appropriate set of software products**. If a software paper exists and it contains results (performance, validation, etc.) that are important to the work, then the software paper should also be cited. We believe that a request from the software authors to cite a paper should typically be respected, and the paper cited **in addition** to the software.

A DOI makes native software citation possible.

Since `pandas` is one of the more frequently used packages in many sciences, giving people the opportunity to stick to this citation recommendation might spread this best practice in the community. It would be great to see this included and move towards this as a general standard in citing software. It sure adds to the maintenance overhead of the software, but I would recommend considering it.

**Comment by TomAugspurger** [comment]
Sure. What all does that involve? With
https://guides.github.com/activities/citable-code/ it seems like we can
just use Zenodo and each release gets its own DOI?

**Comment by ivalaginja** [comment]
Yup, that's exactly it. While Zenodo is by far not the only solution, it's definitely one of the most widely used ones and the hook with GitHub is super simple.

Yes, each release will get its own DOI so that people can cite specifically the software in the state it was in when they used it. On top of that, each software package also gets a so called "Concept DOI", which will always refer to the latest release, and the user can chose which one to cite.

The last thing would then be to add an encouragement to cite the software DOI to the citation instructions given for the software. I just realized that this repo doesn't have a `CITATION.txt` or similar in the first place, nor are there citation instructions in the readme, so it might be worth adding that in general - adding both a citation for the software itself, as well as any papers that should be cited.

**Comment by TomAugspurger** [comment]
Cool, thanks. I'll see about adding the Zendo GitHub integration.

One final question, (since you seem to be familiar with this :smile:) If we add a CITATION.txt or a badge to the README, does it have to be updated with each release? Or is their some kind of living "master" DOI that refers to pandas, in addition to the per-release DOIs?

**Comment by ivalaginja** [comment]
Yes, that would be the "concept DOI"! You can chose to have that in the CITATION.txt or in the badge and then you don't have to worry about updating that :) You can find more on the DOI business here:
http://help.zenodo.org/#versioning

At one point you can also expect the user to know or at least research what they're doing, so sticking in the "overall" DOI (i.e. Concept DOI) should be more than fine.

**Comment by TomAugspurger** [comment]
Perfect, thanks.

@jreback @jorisvandenbossche I've requested access to add the Zenodo GitHub application to pandas-dev.

**Comment by jreback** [comment]
all sgtm

**Comment by matchings** [comment]
Has pandas obtained a DOI or RRID yet? I would like to properly cite, in addition to the paper citation

**Comment by matchings** [comment]
ah, I have found the DOI here: https://zenodo.org/record/3630805#.XjI9CyOIYdU

**Comment by ivalaginja** [comment]
Cool, so the only thing they're missing are citation instructions in their repository, or anywhere really. Maybe time to make a `citation.txt` file in the repo? @TomAugspurger

**Comment by TomAugspurger** [comment]
I thought we had one somewhere on the website.

**Comment by ivalaginja** [comment]
Here?
https://pandas.pydata.org/index.html

I browsed through all the pages but couldn't find any, maybe I was searching in the wrong place?

**Comment by dvaitkus3** [comment]
https://www.scipy.org/citing.html#pandas  has a link out to the SciPy2010 conference proceedings with Bibtex entry

**Comment by ivalaginja** [comment]
So I guess now that pandas has a way to cite the native software itself, is there a way to get that updated to include that as well?

**Comment by JoKeyser** [comment]
It seems to me, now that the [DOI](https://zenodo.org/record/3630805#.XjI9CyOIYdU) exists, this is a more proper way to cite than the link at https://www.scipy.org/citing.html#pandas. If this is correct, the latter link should be updated.
And to make it easy for people to cite, it would be nice to provide a file in the repo, and maybe a `<package>.__citation__` variable.

**Comment by ivalaginja** [comment]
Absolutely, the Scipy link should be updated. However, I would be hesitant to delete the pandas paper  from any citation instructions, since especially scientists usually get more credit for papers than software. That's a decision that the pandas team will have to make internally. And yes, I would update the "cite" section on https://pandas.pydata.org as well.
Personally, I recommend a plain `.txt` files on the repo that also includes the citations in the bib format, but obviously any format will work as long as it is easy to find.

**Comment by jreback** [comment]
happy to take a PR to add a. txt for citation purposes (likely numpy / scipy have an example of how this could look)

**Comment by ivalaginja** [comment]
Interestingly, none of them do, as the scientific community often relies more on paper citations than actually giving credit to the software and its writers themselves (find the problem there :P).
There is a fitting package called [sherpa](https://github.com/sherpa/sherpa) that has a nice example of a `CITATION` file [on their repo on the master branch](https://github.com/sherpa/sherpa/blob/master/CITATION).

Full disclosure, I also talked to them about including the native software citation additionally to the bib entries for the papers, which is currently [in this PR](https://github.com/sherpa/sherpa/pull/634/files).

**Comment by mroeschke** [comment]
Note our citation page is here: https://pandas.io/about/citing.html

Still could update with the DOI and possibly add a `citiation.txt`

**Comment by ivalaginja** [comment]
I submitted a PR with #32388 to get things going.

**Comment by MPvHarmelen** [comment]
> Note our citation page is here: https://pandas.io/about/citing.html
> 
> Still could update with the DOI and possibly add a `citiation.txt`

The link is dead. This is the up-to-date url: https://pandas.pydata.org/about/citing.html

**Comment by mroeschke** [comment]
Given that we have https://pandas.pydata.org/about/citing.html, I think that's sufficient for now. Going to close, but if we want to reference this in other ways we can open a new issue for it

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
```
% This file was created with Citavi 6.8.0.0

@inproceedings{McKinney.2010,
 author = {McKinney, Wes},
 title = {Data Structures for Statistical Computing in Python},
 pages = {56--61},
 bookpagination = {page},
 publisher = {SciPy},
 series = {Proceedings of the Python in Science Conference},
 editor = {{van der Walt}, St{\'e}fan and Millman, Jarrod},
 booktitle = {Proceedings of the 9th Python in Science Conference},
 year = {2010},
 abstract = {In this paper we are concerned with the practical issues of working with data sets common to finance, statistics, and other related fields. pandas is a new library which aims to facilitate working with these data sets and to provide a set of fundamental building blocks for implementing statistical models. We will discuss specific design issues encountered in the course of developing pandas with relevant examples and some comparisons with the R language. We conclude by discussing possible future directions for statistical computing and data analysis using Python.},
 doi = {10.25080/Majora-92bf1922-00a},
 booksubtitle = {SciPy 2010},
 eventtitle = {Python in Science Conference},
 venue = {Austin, Texas},
 eventdate = {June 28 - July 3 2010}
}



```
