### ISSUE TITLE
Dataframe.assign performance

### ISSUE THREAD

**Issue by bnouvelbmll** [pandas-dev/pandas#24145]
#### Dataframe.assign performance

```python
import pandas as pd
import numpy as np
import time

def inplace_assign(df, **kwargs):
    for k, v in kwargs.items():
        df[k]=v
    return df

def functional_assign(df, **kwargs):
    ndf=df.copy(deep=False)
    return inplace_assign(ndf, **kwargs) 

if __name__=="__main__":
    N = 2 * 1000 * 1000
    df = pd.DataFrame(dict(a=np.zeros((N,)),b=np.arange(N), e=np.zeros((N,)), f=np.zeros((N,)),  g=np.zeros((N,)),  h=np.ones((N,)), i=np.ones((N,))))
    
    
    ta=0
    for i in range(10):
        t0 = time.time()
        for i in range(10):
            df.assign(c=df['b']*2)
        ta+=(time.time()-t0)
    print("PANDAS ASSIGN", ta)    

    
    ta=0
    for i in range(10):
        t0 = time.time()
        for i in range(10):
            functional_assign(df,c=df['b']*2)
        ta+=(time.time()-t0)
    print("FUNC ASSIGN", ta)
```
#### Problem description

Running the code fragment below on my computer outputs the following
```
# Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
# pandas 0.23.4
PANDAS ASSIGN 1.5809710025787354
FUNC ASSIGN 0.43369007110595703
```

This suggests to me that assigns may be slower than it needs to be. 

Obviously, no-one really expects a simple alternate implementation of assign to beat the default implementation of a standard library unless there is something that I is overseen / a signficant drawbacks in the alternative implementation. I imagine that there may be reason for current choices. 

Although this has never been my understanding, I imagine that some users may consider that returning a new dataframe may mean a deep copy, and that may explain why current implementation is slower.
Ultimately, the pros and the cons of this alternative implementation certainly need to be considered too. 
If the speed up is confirmed (for different data and architecture), I imagine it may be good to change default implementation or to have an option offered when doing "assign" to eventually benefit from a faster implementation depending behaviour desired by user(deep/shallow copy)

Note: This can may be related to :
https://github.com/pandas-dev/pandas/issues/22126

**Comment by TomAugspurger** [comment]
Your assign is basically the same as pandas.

What version of python? I don't see the perf difference between

```python
In [9]: def f(df, **kwargs):
   ...:     df = df.copy()
   ...:     for k, v in kwargs.items():
   ...:         df[k] = v
   ...:

In [10]: %timeit f(df, c=df['b'] * 2)
50.4 ms ± 305 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [11]: %timeit df.assign(c=df['b'] * 2)
51.6 ms ± 438 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

keep in mind that python < 3.5 does a sort on the keys to ensure a deterministic insert order.

**Comment by bnouvel-wio** [comment]
Tom thank for the swift reply.

Pandas your code is different from mine: as copy is deep by default.
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.copy.html
My previous code (sent with my work account) was shallow copy.


I am using conda python 3.6.0.
I have also tried the code on my personal laptop. I have similar performance gap with different version of python and pandas.
```
PANDAS ASSIGN 2.0934243202209473
FUNC ASSIGN 0.5120208263397217
# Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
# with pandas 0.23.0
```
Obviously the performance gap can depends on the size of the dataframe and the size of the data to be copied..

PS: Sorry for confusion reusing "i" the two imbricated loops in previous code fragment, using "i" and "j" doesn't change the nature of the issue. Timeit seemed more ideal but for some probably reason it ran out of memory with timeit so I preferred manual implementation.

**Comment by TomAugspurger** [comment]
Ah, I see.

DataFrame.assign has to copy the data. It shouldn't mutate the input in place.

**Comment by bnouvel-wio** [comment]
There is "mutate inplace" with "functional_assign" (This is not "in_place assign" ).  "functional_assign" . Yes, ithe same instance of the data series is reused in a different dataframes, however I estimate it should be the expected for assign. It would be similar as taking slice on a numpy array, you have a new instance of a numpy.arra,  you have is a new "view," and you don't copy the data unless you code ".copy()" on the view of the array. It allows programmers to control performance and number of copies, and code to ends up running naturally MUCH faster. Obviously, the semantics need to be clear to every one, but my feeling  is that most programmers don't expect a "new dataframe" to mean a deep copy of their entire dataframe. And they rather avoid doing a copy of large tables, each time they try to adjunct a derived column on a dataframe.

**Comment by TomAugspurger** [comment]
I don't follow exactly what your proposing, but it sounds like you're
expecting some kind of copy on write behavior?
Pandas doesn't have that (yet).

Regardless, after

```python
df2 = df.assign(a=b)
```

the expectation is that any further (inplace) modifications to `df2` will
not be reflected in `df`.

But you are of course welcome to avoid the copies by assigning directly.

**Comment by bnouvel-wio** [comment]
Tom thanks for the swift reply again.

Now, I am still under the impression that current implementation should be called "assign_and_copy" and that assign should not copy the entire the data. I am not convinced that most developers are expecting that all operations on a dataframe would to lead to a deep copy of the entire data. Operations such as 'renaming' the columns, adding, subsetting columns or rows slicing are somehow expected to be just modification of a "view" of the data and should not  lead to unnecessary copies of the data. 
For instance, as a programmer I expect the following : 
```
df.iloc[100:1000]
df[["a", "b", "c"]]
df.assign(b=df['a'])
df.rename({'a':'aa'}, axis='columns')
```
to be constant time operation (or eventually linear on df['a'] for the assign - because of eventual re-indexing issue) . If all these operations imply a deep copy and are there for linear with the size of the entire df, I think many programmers are going to stop to use pandas very quickly.

In your example, a functional programmer would normally not modify the underlying data of df or df2. In the case, this would start to do in-place modification, he should only be fair to ask for a copy 
to ensure there is no side effect. 
Now, let's assume that we are of a different opinion, and that we think that the programmer should not do the copy explicitly, then I imagine that it would still be possible to improve massively performance by implement a read-only views with copy-on-write when accessed for in-place modification. 
Efficient programming with pandas should be possible independently of the style. I should not have to change from functional style to imperative style to ensure efficiency on assign.

**Comment by jreback** [comment]
virtually all operations in pandas copy - with the exception of inpkace indexing

this is a very clear idiom and is not going to change

**Comment by bnouvel-wio** [comment]
But with c-o-w, performance can be improved without any change of the idiom ?

**Comment by jreback** [comment]
maybe but that’s out of scope for pandas for the near future

**Comment by bnouvel-wio** [comment]
Sure, it is certainly a significant change - thanks again for swift replies.
