### ISSUE TITLE
tz-aware DatetimeIndex intersection raises AttributeError when values are the same but tz differs

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24362]
```python
In [25]: a = pd.date_range('2000', periods=4, tz="US/Central")

In [26]: a & a.tz_convert("US/Eastern")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-d8e6c109715c> in <module>
----> 1 a & a.tz_convert("US/Eastern")

~/sandbox/pandas/pandas/core/indexes/base.py in __and__(self, other)
   2221
   2222     def __and__(self, other):
-> 2223         return self.intersection(other)
   2224
   2225     def __or__(self, other):

~/sandbox/pandas/pandas/core/indexes/datetimes.py in intersection(self, other)
    575             result = Index.intersection(self, other)
    576             result = self._shallow_copy(result._values, name=result.name,
--> 577                                         tz=result.tz, freq=None)
    578             if result.freq is None:
    579                 result.freq = to_offset(result.inferred_freq)

AttributeError: 'Index' object has no attribute 'tz'

```

If the values differ, no error is raised

```python
In [27]: a & a._time_shift(1).tz_convert("US/Eastern")
Out[27]:
DatetimeIndex(['2000-01-02 01:00:00-05:00', '2000-01-03 01:00:00-05:00',
               '2000-01-04 01:00:00-05:00'],
              dtype='datetime64[ns, US/Eastern]', freq='D')

```

**Comment by cbertinato** [comment]
It looks like the issue here is that, initially, the DTIs are not equal nor are their dtypes because of the different timezones, so they both converted to `Index`.

https://github.com/pandas-dev/pandas/blob/08c920eab602dac261b8fe55ffe439593c095e12/pandas/core/indexes/base.py#L2388

This actually starts in the intersection method for DTI, but gets dropped into the `Index` intersection method when it is determined that they're not equal.

Is the expected behavior that, in this case of the intersection, the DTIs are considered equal if the underlying indices are equal, regardless of timezone?

If so, then we can make a change to the equality check in the DTI intersection method.

**Comment by jbrockmendel** [comment]
for other intersection-like operations with mixed timezones we convert to UTC (in particular im thinking of `NDFrame._align_frame`).  would that be a better behavior than returning object-dtype?

**Comment by jbrockmendel** [comment]
or even convert `other` to `self`'s tz might make more sense.  when i patch this to just return object dtype:

```
>>> a & a.tz_convert("US/Eastern")
Index([2000-01-01 00:00:00-06:00, 2000-01-02 00:00:00-06:00,
       2000-01-03 00:00:00-06:00, 2000-01-04 00:00:00-06:00],
      dtype='object')
```

i.e. we get an object index of Timestamps that are all the same tz

**Comment by jbrockmendel** [comment]
This now returns an object-dtype Index.  The analogous union also returns object dtype, but has a deprecation saying it will be UTC in a future version.  We probably should do the same for all setops right?
