### ISSUE TITLE
ExtensionArray/Index/Series.repeat signature

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24413]
In https://github.com/pandas-dev/pandas/pull/24395/ @jschendel mentioned that 

> I think this could be restricted to repeat(self, repeats, axis=None) but I opted to match on the least restrictive function signature instead.

I agree and I think we should do that.

**Comment by jreback** [comment]
agree here as well.

**Comment by jschendel** [comment]
Sounds good.  Worth noting that this is would be identical to the signature for [`numpy.repeat`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.repeat.html), which makes sense to match.  Was a little confused as to why we were using `*args` and `**kwargs`, but went with it since it was the existing convention.  Can get to this in the next couple days.
