### ISSUE TITLE
pd.reaad_sql

### ISSUE THREAD

**Issue by anhuaxiang** [pandas-dev/pandas#24422]
**mysql** 
![image](https://user-images.githubusercontent.com/26645743/50413105-b55d4680-0847-11e9-9962-8a109f4fb178.png)

**pandas**
`pd.read_sql('select * from table1, table2', conn)`  or `pd.read_sql('select * from table1, table2 where table1.mid=table2.mid', conn)`

**result**
![image](https://user-images.githubusercontent.com/26645743/50413390-d3c44180-0849-11e9-88a8-589adc5b1152.png)
or
![image](https://user-images.githubusercontent.com/26645743/50413416-09692a80-084a-11e9-8c27-2cccdc0eab90.png)

**Comment by WillAyd** [comment]
Hmm not clear on what the issue is. Please refer to the contributing guide for pandas on how to submit bug reports. If you can provide a reproducible example and clarify the issue feel free to reopen.

https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests
