### ISSUE TITLE
TST: Split test_excel into sub test files

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#24472]
Logical follow up to https://github.com/pandas-dev/pandas/pull/24423/files#r244284618

cc @gfyoung

**Comment by stevenbw** [comment]
Hi @WillAyd, is this issue still open? If so I would be interested in giving it a shot :)

**Comment by WillAyd** [comment]
@stevenbw for sure - PRs are always welcome!

**Comment by stevenbw** [comment]
@WillAyd Just want to make sure I am interpreting this correctly. The only change is to move the `TestXlrdReader` class into its own file from test_excel?

**Comment by WillAyd** [comment]
At the very least want to create a sub directory for excel which has a base.py and an xlrd.py which logically separate the tests. There may be other logical organization points so if you have ideas on that certainly open to it. 

Cc @gfyoung if you have any other thoughts to offer

**Comment by gfyoung** [comment]
@WillAyd : I think you explained it pretty well here!

@stevenbw : Just a point of guidance.  The idea is to hopefully create smaller, more modular tests in the spirit of `pytest`, hence why we would like to split the tests up instead of having one massive file.

There might also be opportunities to leverage more `pytest` idiom such as fixtures and parameterizations, but we can cross that bridge later if need be.

**Comment by stevenbw** [comment]
@WillAyd @gfyoung thanks for your help. I have split the file in two as you suggested, just reviewing before I open a PR. There could be an opportunity to separate the `openpyxl` tests out.

As @gfyoung said, it may be worthwhile undertaking the bigger task of refactoring the test files to a more functional style rather than class based.
