### ISSUE TITLE
Crosstab Preserves Dtypes release note

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24789]
The note at http://pandas.pydata.org/pandas-docs/version/0.24.0rc1/whatsnew/v0.24.0.html#crosstab-preserves-dtypes seems incorrect (it's a code block instead of an ipython block, but after making that change and running it).

On master, I get the same output as 0.23.4

0.23.4

```python
In [1]: import pandas as pd; import numpy as np

In [2]: df = pd.DataFrame({'a': [1, 2, 2, 2, 2],
   ...:                    'b': [3, 3, 4, 4, 4],
   ...:                    'c': [1, 1, np.nan, 1, 1]})
   ...:
   ...: pd.crosstab(df.a, df.b, normalize='columns')
   ...:
Out[2]:
b    3    4
a
1  0.5  0.0
2  0.5  1.0
```

master

```python
In [98]: df = pd.DataFrame({'a': [1, 2, 2, 2, 2],
   ....:                    'b': [3, 3, 4, 4, 4],
   ....:                    'c': [1, 1, np.nan, 1, 1]})
   ....:

In [99]: pd.crosstab(df.a, df.b, normalize='columns')
## -- End pasted text --
Out[4]:
b    3    4
a
1  0.5  0.0
2  0.5  1.0

```

@jbrockmendel this came from https://github.com/pandas-dev/pandas/pull/22019. Do you know if the note is obsolete, or has there been a regression?

**Comment by jbrockmendel** [comment]
> this came from #22019. Do you know if the note is obsolete, or has there been a regression?

I'm not aware of an intentional change making it obsolete, so I guess it counts as a regression.  That said, the behavior change in this note was a side-effect of #22019, not at all part of the intention.  It looks like the edits that #22019 made in tests.frame.test_axis_select_reindex and tests.reshape.test_pivot are no longer necessary.  I'd say revert those, remove the note, and call it a win.
