### ISSUE TITLE
AttributeError: module 'pandas.io.formats' has no attribute 'style'

### ISSUE THREAD

**Issue by nuistzhou** [pandas-dev/pandas#24884]
https://github.com/pandas-dev/pandas/blob/0409521665bd436a10aea7e06336066bf07ff057/pandas/io/formats/style.py#L496-L501

I am using the Pandas version 0.23.4.
When I call pandas.io.formats.style.Styler.clear(), it gives the error:  "AttributeError: module 'pandas.io.formats' has no attribute 'style'".
However, I could find the 'style.py' under the Pandas installation folder.

**Comment by TomAugspurger** [comment]
A few things.

1. `pandas.io.formats.style` isn't imported with `import pandas`. You'd need `import pandas.io.formats.style`, but
2. After that, `Styler.clear()` won't work because it's called on instances of the styler object. Something like `Styler().clear()` would work. But,
3. You probably don't want that either. Typically you create these frame a DataFrame.

```python
In [8]: df = pd.DataFrame({"A": [1, 2]})

In [9]: df.style
Out[9]: <pandas.io.formats.style.Styler at 0x10b9b6ba8>

In [10]: df.style.clear()
```

**Comment by nuistzhou** [comment]
Oh, cool.
BTW, I forgot to mention that what I need is to unbold the headers when using the to_excel() method. However, the code `df.style.clear()` seems does not work.

**Comment by WillAyd** [comment]
@nuistzhou you should take a look at #22773 and #22759 which may yield insights on what you are trying to do. Specifically with the former we could use some help on documentation
