### ISSUE TITLE
RLS: 0.24.x

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#24949]
Tracking issue for 0.24.1

**Comment by jreback** [comment]
@pandas-dev/pandas-core  so it is *very* important to tag *before* you merge to a backport branch, otherwise the auto-backport-bot won't be triggered, e.g. we want to see something like #24961. Please make sure that these pass and then merge them (or you will need to manually fixup / merge to the backport branch).

**Comment by jorisvandenbossche** [comment]
I created the branch, so from now on, if you label a PR with 0.24.1 *before* merging, a backport PR will be created automatically if possible (and if not possible, a label will be added).

**Comment by jorisvandenbossche** [comment]
And since Jeff and I already had some discussion about it :) 

IMO, we should not be backporting too much, but limit ourselves to regressions and important bug fixes. 

Backporting any tiny doc fix / bug fix is simply a) more work, and b) gives a higher risk of also breaking something unneeded.

**Comment by TomAugspurger** [comment]
Thought on doing a 0.24.1 soonish? Tracking a few regressions

- https://github.com/pandas-dev/pandas/issues/24939
- https://github.com/pandas-dev/pandas/issues/24959

I'd like to include https://github.com/pandas-dev/pandas/pull/24964 as well (probably not a regression in 0.24, but I think important to have working, since that's hurting our import times).

any others?

**Comment by jreback** [comment]
we need to wait a few weeks - not worth it to do for these minor things

**Comment by h-vetinari** [comment]
+0.5 for a fast release to fix the regressions before they got much chance to be relied on.

**Comment by jorisvandenbossche** [comment]
+1 on doing quick releases with regression fixes, if it is not a lot of work. 
Certainly for the intersection sort behaviour it would be good to do this as fast as possible

**Comment by TomAugspurger** [comment]
I'd like to do a release in the next day or two. What are peoples thoughts? (I'll be busy next week, and unable to do the release myself. Others could, but I think getting a release out soon with the fixes for `iteritems` and the index setops is important).

Right now we have a decent number of issues on the [0.24.1 milestone](https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.24.1), which I'm going through.

**Comment by jorisvandenbossche** [comment]
I think only the regressions + the setops default change that are in the 0.24.1 milestone are important. +1 to do a release shortly.

**Comment by TomAugspurger** [comment]
I'd like to do a release tonight if possible, with the following issues resolved

- https://github.com/pandas-dev/pandas/issues/24959
- https://github.com/pandas-dev/pandas/issues/24969

Any objections? Any other blockers?

**Comment by TomAugspurger** [comment]
Tagging in about 5 hours from now.

**Comment by TomAugspurger** [comment]
Waiting on https://github.com/pandas-dev/pandas/pull/25085 to pass CI, then merging and tagging.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger Thanks a lot for the release!

One thing I noticed: due to the way we do the backporting now, the actual contributors don't get acknowledged: http://pandas.pydata.org/pandas-docs/version/0.24.1/whatsnew/v0.24.1.html. That section is quite useless/misleading now, so I would either update it manually or remove it. 
In general, I think it could be solved by the bot using co-authors: https://github.com/MeeseeksBox/MeeseeksDev/issues/35

**Comment by jorisvandenbossche** [comment]
(repurposed this issue for a potential next 0.24.2)

**Comment by jorisvandenbossche** [comment]
We already have a nice set of changes in 0.24.x, so shall we try to do a 0.24.2 release this week? 

I have a little bit of time to look at some of the remaining open issues, but not that much. @TomAugspurger would you have a bandwidth to do a release? Otherwise I might be able to do early next week.

For the remaining open issues, I would certainly try to fix #25193 (the pip install problem), and some of the others seem to have a relatively straightforward fix (eg #25077, #25403).

**Comment by TomAugspurger** [comment]
I likely won't have time this week. Possibly next week if needed (though
it'd be good to exercise the release scripts on a machine other than my own
:).

**Comment by jorisvandenbossche** [comment]
Will be tagging 0.24.2 this afternoon (trying out the release scripts now)

**Comment by jorisvandenbossche** [comment]
MacWheels tests are failing: https://travis-ci.org/MacPython/pandas-wheels/builds/505474702 (on python 3.6 a stata failure, and on python 2.7 numpy ufunc tests). 
I am in a workshop during the day, so if somebody has time to look at it, certainly welcome (otherwise I will look at it this evening).

**Comment by simonjayhawkins** [comment]
> on python 2.7 numpy ufunc tests

#25186 fixes

**Comment by TomAugspurger** [comment]
Picking up the remaining release items now.

TODO:

- [ ] Fix MacPython wheels (#25186)
- [ ] Upload to PyPI
- [ ] Build & upload pdf docs
- [ ] symlink 0.24 -> 0.24.2
- [ ] update website
- [ ] Announce

**Comment by simonjayhawkins** [comment]
@TomAugspurger #25186 only for the numpy ufunc. there is still the stata issue.

**Comment by TomAugspurger** [comment]
Thanks. Still investigating, but it's possibly a flaky test: https://github.com/pandas-dev/pandas/issues/25707

**Comment by jorisvandenbossche** [comment]
All wheels are uploaded, and website symlink is changed.
