### ISSUE TITLE
Add back third level to documentation TOC tree

### ISSUE THREAD

**Issue by neili02** [pandas-dev/pandas#25131]
I use the online docs quite a bit and am wondering what is the rationale for the new format of the Table of Contents. The new format nicely compresses the main TOC tree into reasonable starting groups, however it detrimentally removes a third level of the tree that is very useful for quickly identifying and navigating to subsections of individual User Guide main topics.

For example the new format now only has `User Guide>MultiIndex / Advanced Indexing`

`MultiIndex / Advanced Indexing` itself is a very long page, as are most others, with many different sub-topics. Previously these subtopics were listed as part of the TOC tree. I hope this third level will return as one now has to scroll through lengthy pages to try and find desired content. This can be particularly painful depending on the device from which you access the docs.

Can't the third level be added as an expansion of the tree that occurs upon click? This would allow the new compact organization to be maintained.

What I had in mind is just to add back the additional level that was previously present. For example:

User Guide now  expands to reveal:

```
User Guide
      IO Tools (Text, CSV, HDF5, …)
      Indexing and Selecting Data
      MultiIndex / Advanced Indexing
```

Clicking on MultiIndex/ Advanced Indexing should show as previously

```
User Guide
      IO Tools (Text, CSV, HDF5, …)
      Indexing and Selecting Data
      MultiIndex / Advanced Indexing
            Hierarchical indexing (MultiIndex)
                ...
            Advanced indexing with hierarchical index
                ...
```
Thanks for all the work being done to maintain and improve this great tool.

**Comment by dpitch40** [comment]
I will second this.

My team recently upgraded the version of Pandas we use, and while the improved functionality of the module itself is great, I'm finding the docs annoying to use. Previously the sidebar index showed (if anything) too much; now it shows too little. Compare, for example, the Essential Basic Functionality docs in [0.20.3](http://pandas.pydata.org/pandas-docs/version/0.20/basics.html) vs. [0.24.0](http://pandas.pydata.org/pandas-docs/version/0.24/getting_started/basics.html). The 0.20.3 version is a little long, but makes it fairly easy to navigate to any part of the lengthy page to find the section you need. The index for 0.24.0, only shows links that were already on the front page and is virtually useless for navigating the page I find myself in.

On the other hand, the index for the [0.20.3 API Reference doc page](http://pandas.pydata.org/pandas-docs/version/0.20/api.html) is actually longer than the page itself (at least on my browser, due to wrapping) and thus equally useless for navigation, and I find the [0.24.0 version](http://pandas.pydata.org/pandas-docs/version/0.24/reference/index.html) more useful.

**Comment by jorisvandenbossche** [comment]
@dpitch40 I fully agree. See also https://github.com/pandas-dev/pandas/pull/25134. I think the best solution is what I wrote in the last paragraph of the comment in https://github.com/pandas-dev/pandas/pull/25134#issuecomment-461359544.  
I will try to include this in 0.24.2.
