### ISSUE TITLE
API: ExtensionArray "serialize" and "from_serialized" methods for defining roundtripping behavior

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#25347]
xref https://github.com/pandas-dev/pandas/pull/25308#discussion_r257468179

When EAs go through cython routines, they need to be converted to numpy arrays (and dtypes) first and then recast to the correct EA. This recast may require specific logic. For example, `DatetimeTZDtype`s need to be localized to UTC first before applying the dtype.

The proposal is for (optional) internal `_serialize` and `_from_serialized` methods that defines specific recasting logic for the EA. @jreback proposed something like:

```
serialized, dtype = EA._serialize()
original = EA._from_serialize(serialized, dtype)
```
 Thoughts @jorisvandenbossche @TomAugspurger @jbrockmendel

**Comment by TomAugspurger** [comment]
I don't quite follow the proposal. At least, I don't think the proposed behavior matches the names `_from_serialized and `_serialize`. I think serialization is typically used for a protocol / byte-level representation of an object.

IIUC, the desire is for a pair of methods that will be called before and after a (NumPy?) numeric operation. Do we have examples other than datetime-tz?

- Categorical: something like `.codes` and `.from_codes`, but Categorical also needs to specially handle how the code `-1` is handle *in the op*, so that doesn't quite fit.
- Period: ordinals. Should be similar to datetime
- Sparse: Probably doesn't want to implement `._serialized` if an ndarray is the required type
- Interval: No idea

How does `_serialize` differ from `_ndarray_values` (whose behavior isn't really defined yet)?

**Comment by mroeschke** [comment]
"serialize" is a bit of a misnomer (just a placeholder name). Your follow-up examples are closer to the spirit of the idea.

`_serialize` I think would be essentially the same as `_ndarray_values` with additionally saving extension dtype so the pair could be passed to `_from_serialized`

**Comment by jreback** [comment]
this doesn't necessarily need a method on EA, maybe all we need are a pair of functions for internal use something like; we can use this when we need to go to a performant representation and back (e.g. pretty much anytime we use cython).

```
def to_internal_tranform(arr):
   if is_extension_array_dtype(arr):
         return arr._ndarray_values, arr.dtype, arr.na_value
   return arr, arr.dtype, np.nan

def from_internal_transform(arr, dtype, na_value):
      if is_extension_dtype(dtype):
             arr = dtype.array_type()._from_sequence(arr)
             arr = arr.astype(dtype, copy=False)
      return arr
```

**Comment by jbrockmendel** [comment]
since _ndarray_values is gone, i think this is closeable

**Comment by jreback** [comment]
we still need this general functionality though 
we currently have a lot of scattered logic which converts arrays to cython types and then reconstructs the original

groupby, window, algos and nanops all do this

**Comment by jbrockmendel** [comment]
We do it for datetimelike (though even that not really in window) but thats about it.  there isnt a realistic way to do this for the general case

**Comment by mroeschke** [comment]
It sounds like this use case isn't practical so closing.
