### ISSUE TITLE
ERR: excel styler tests failing recently

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#25351]
https://travis-ci.org/pandas-dev/pandas/jobs/494493327

xref @jnothman

**Comment by jnothman** [comment]
I'm not seeing it. Under pandas-ci/pip I see errors in
test_terminal_unknown_dimensions

**Comment by jreback** [comment]
no on that CI

look on the one i linked

or just pull master and run the test (i installed latest openpyxl)

**Comment by jnothman** [comment]
Confused. I saw a different page when I clicked that. Might have put in an
extra click by accident

**Comment by jnothman** [comment]
This corresponds to an openpyxl update (2.6.0).

It seems to affect the default styling of cells, at least in theory. Basic
outputs

I can't see any obvious correspondence to the openpyxl change log.

Many of the differences seem negligible in practice. I'm most concerned by
b (bold) differing from False to True.

The fact that the xlsxwriter test fails as well as openpyxl indicates that
some of this change happens in the openpyxl reader, rather than the writer.

I don't have time to delve in further now.

**Comment by mroeschke** [comment]
Dont think we've been seeing this test fail in the CI recently. Might have been a dependency bump that fixed this. Closing but we can reopen if we see it again

**Comment by attack68** [comment]
Reopening.
The tests for styler.to_excel all xfail - this was added to get CI working but the test is pointless since the function is actually broken (e.g. border styles bug on #42276).

I need to add a test for #41995, so I will see if I can patch these, or at least get some useful tests in place.
