### ISSUE TITLE
CI: Use the latest pep8speaks and remove custom configuration

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#25605]
Until now, pep8speaks used independent settings, and not the setuptools standard `setup.cfg`. This has been addressed in the latest version of pep8speaks, and we shouldn't need to repeat our configuration anymore: https://github.com/pandas-dev/pandas/blob/master/.pep8speaks.yml#L10

More info about the problem can be found here: https://github.com/OrkoHunter/pep8speaks/issues/95#issuecomment-470887715

Not sure how pep8speaks is integrated, but we should upgrade to the latest version if it's not automatic, and we should remove the duplicated configuration in `.pep8speaks.yml` (which is already present in `setup.cfg`).

**Comment by OrkoHunter** [comment]
> Not sure how pep8speaks is integrated, but we should upgrade to the latest version if it's not automatic

The update is automatic with GitHub app, hence no upgrade is required. This issue can be solved by just removing the duplicate from `.pep8speaks.yml`.

**Comment by alimcmaster1** [comment]
Hey @datapythonista , I was thinking we could actually just remove all warnings/errors we ignore from .pep8speaks.yml. As I imagine that most of the stuff we ignore in setup.cfg/.pep8speaks is most likely due to legacy reasons opposed to a pep8 rule we don't care about. 

That way when reviewing code we can see that we are not increasing the occurrences of any particular warnings/errors. Say for example if I increase occurrences of `E731` it is down to the reviewer to spot this?

As if setup.cfg and pep8speaks.yml are kept consisting a change can increase occurrences of any of these errors without anything highlighting so on the PR. We can keep   `diff_only: True` set as per than current set up. I personally think there is more value in this, as otherwise pep8speaks and flake8 running in CI are just telling us the same thing. What do you think?
