### ISSUE TITLE
Using OrderedDict in GroupBy Module(s)

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25692]
Spurred by conversation in https://github.com/pandas-dev/pandas/pull/25224#discussion_r264786749 right now we are using plain old dictionaries in most of the groupby aggregation functions. For Py35 this makes the order of the returned result non-deterministic.

We could theoretically make a stronger assertion around the order here by replacing those dicts with OrderedDicts

**Comment by alexander-ponomaroff** [comment]
Since I've already been working with this, I will also continue with this issue. I'll make a simple WIP PR right now and will continue working on it. I'm thinking of changing the simple dicts to OrderedDicts in the aggregation functions of groupby and writing some tests in order to test the ordering.
