### ISSUE TITLE
Can't explain a "Error tokenizing data. C error: Expected.."

### ISSUE THREAD

**Issue by IzzyHibbert** [pandas-dev/pandas#25724]
Hi guys,
I have a curious case I can't explain.
The error : 
**Error tokenizing data. C error: Expected 65 fields in line 3, saw 91**

when using 
`data = pd.read_csv("/Users/me/Projects/ML/Isolated.csv", header=0, escapechar='\\' )`

#### Problem description
My csv has header and three lines.
The third line of the file is the issue. That line has 22 columns as the header.
The second line also comes in 22 columns.

I can't explain why the error, as the `,` is a delimiter. 
The weird thing : **taking the third line and moving it up as second line, the error disappear... same file, same data**... just different order helps..

Of course also the header comes in 22 columns, same delimiter.

My csv file is available here:
https://send.firefox.com/download/c0992396d7/#xsEsxH6tlHbtt7edDYsaZQ

Thanks in advance for any precious help and hint.

**Comment by WillAyd** [comment]
Your file has two literal backslashes but an `escapechar` can only be one character. The fact that you send two backslashes as an argument is required only to escape it as a single character.

I don't think this is a bug as much as a mismatch in expectations. Since `escapechar` only supports one character you'll most likely have to choose a different escape char for your csv file, or cleanse it before reading into pandas

**Comment by IzzyHibbert** [comment]
Hi @WillAyd 
Before closing, can you explain why "switching the lines order" just work, without considering `escapechar` and all the rest of your explanation ?
When you look it from this prespective, I see a bug. If not, at least I'd need for an explanation for a bizarre behavior.

**Comment by WillAyd** [comment]
Sorry forgot to mention but I wasn't able to reproduce that on my end. If you can provide a self-contained code example to replicate (i.e. doesn't require external CSV or manual efforts) then please provide
