### ISSUE TITLE
iterating pandas dataframe difference between python 3.5.6 and 3.7.3 

### ISSUE THREAD

**Issue by kfrendrich** [pandas-dev/pandas#26481]
Hi.

I realized a difference when I am iterating the dataframe in python 3.5.6 and 3.7.3 and I can't decide if it is good or bad.

```python
import pandas as pd
class Something(object):
    def __init__(self, data):
        self.data = data

data = {
    'col1': [1, 2, 4],
    'col2': [3, 4, None],
    'col3': ['-', None, 2.4],
    'Time': [0, 0.1, 0.5],
}

df = pd.DataFrame(data=data, index=['a', 'b', 'c'])

something = Something(df)

ret = []
for i in something.data:
    ret.append(i)

print(ret)

```
#### Problem description

**3.5.6**: always return with: [**'Time', 'col1', 'col2', 'col3']** (it looks the pandas **sorts** the keys?)

**3.7.3**: always return with: **['col1', 'col2', 'col3', 'Time']** (it looks the pandas **preserves** the original order? (in python3.6+ it is the default behavior with dicts)

So... my problem is that with Python **3.5.6** when I iterated the dataframe I always got the keys in the same **sorted** order, but with Python 3.7.3 I got the keys **in the order of the dict definition.**

Could you please help me if it is an issue or not?

**Comment by jorisvandenbossche** [comment]
You are constructing the DataFrame from a dictionary. So in python >= 3.6, we are using the order of the dictionary for the column order, but for older python versions, since the order is random, pandas sorts the keys to have a consistent output. 
You can provide a `columns=` keyword to the DataFrame constructor if you want a consistent order across python versions.

**Comment by kfrendrich** [comment]
Thanks for the clarifications.
