### ISSUE TITLE
Setup python 3.8 builds

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#26626]
As the python 3.8 release date draws closer ( currently [scheduled](https://www.python.org/dev/peps/pep-0569/#release-schedule) for October this year ).

I was wondering if we want to set up python3.8 builds?

Given the 3.8 dev branch is available on [travis](https://docs.travis-ci.com/user/languages/python/) and shortly [azure](https://github.com/Microsoft/azure-pipelines-image-generation/issues/905).

Might be abit early for this - but it will mean we can catch any potential issues early + support python 3.8 upon release date.

Related issues: https://github.com/pandas-dev/pandas/issues/22714

I am happy to work on this - but would be good to get people's thoughts first.

Thanks!

**Comment by jreback** [comment]
we need it available on conda 

as numpy needs to build

**Comment by alimcmaster1** [comment]
Looks like @h-vetinari kindly started doing this here: https://github.com/conda-forge/python-feedstock/pull/259

**Comment by jreback** [comment]
well need python numpy and cython then it’s possible
certainly u can push folks

note that once python and cython exists it’s possible to build numpy from source

**Comment by h-vetinari** [comment]
> @alimcmaster1: Looks like @h-vetinari kindly started doing this here: conda-forge/python-feedstock#259

I have been following up on this for a [while](https://github.com/conda-forge/python-feedstock/issues/254) with the express idea of doing Python 3.8 testing as early as the betas.

Python 3.8.0a3 (conda-forge/python-feedstock#258) worked because one of the maintainers basically did all the work. Although I did a bit more for 3.8.0a4 this time, I haven't had time to properly investigate the build failures - there's a config file that's not found - maybe it moved...? Help is of course appreciated; the conda-forge maintainers have not responded so far (aside from some side issues about 3 weeks back).

In any case, I'll try to pick up the process again as soon as 3.8.0b1 comes out.

**Comment by jreback** [comment]
lgtm; marked for 0.25.2; merge when ready

should have a follow up issue to integrate with the regular ci scripts when possible
