### ISSUE TITLE
CI: Avoid two steps to access azure-pipelines logs

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26895]
When we are in a PR, we got the list of all CI checks:
![azure1](https://user-images.githubusercontent.com/10058240/59569871-aaad9c80-9087-11e9-992c-0eb887120b1c.png)

If we click in travis, it takes us to the travis log build, which seems reasonable. But when we click in one of the azure-pipelines builds, it takes us to this "Checks" tab, that how we have configured azire-pipelines, it provides literally no value, at least to me (never seen any useful information there):

![azure2](https://user-images.githubusercontent.com/10058240/59569872-aaad9c80-9087-11e9-840e-f708b9409069.png)

Then what afaik we all do, is immediately click on the `View more details on Azure Pipelines `, so we go to azure-pipelines, and we can see the errors (if we have them highlighted, like for the linting), or we can click in the step and see the log:

![azure3](https://user-images.githubusercontent.com/10058240/59569873-ab463300-9087-11e9-9f81-09b6ab874ca1.png)

I guess we have something configured incorrectly, because the second step (the "Checks" tab) doesn't add any value, it's just making things more complex for no reason.

@davidstaheli @vtbassmatt do you mind helping us here? What are we missing? It's not only us, checked numba and scikit-learn, and they've got the same as us. Thanks!

**Comment by davidstaheli** [comment]
Hi @datapythonista .  Sorry for the inconvenience with this.  Unfortunately, Azure Pipelines doesn't have much control over it.  When a **GitHub App** (the recommended, new kind of app supported by GitHub) posts checks status to GitHub Checks, GitHub causes the link to point to the Checks tab which in turn links to the logs.  The reason this doesn't happen with Travis and some others is because they're based on a GitHub **OAuth App** that doesn't use GitHub Checks.  We're looking at ways to improve this for the Azure Pipelines GitHub App, like by putting the full logs in the Checks tab so that clicking the 2nd link isn't necessary.

**Comment by datapythonista** [comment]
That makes sense, thanks a lot for the information @davidstaheli. Will report it to GitHub then.

**Comment by datapythonista** [comment]
I've been told:

> They can continue to [create a commit status](https://developer.github.com/v3/repos/statuses/) instead of creating a check with GitHub Apps

Not sure if that makes sense, not an expert on the GitHub API myself.

**Comment by datapythonista** [comment]
We're not using azure pipelines anymore, closing.
