### ISSUE TITLE
TST: Split test_offsets.py

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#27085]
xref https://github.com/pandas-dev/pandas/pull/26628#issuecomment-500166805

It would be good to create:

`pandas/tests/tseries/offsets/test_business_offsets.py` for business offsets
`pandas/tests/tseries/offsets/test_date_offsets.py` for all offsets that subclass `DateOffset`

and converting the tests to pytest idioms.

**Comment by dhirensr** [comment]
@mroeschke : is it seperating the tests which use DateOffset into a new created file test_date_offsets.py?

**Comment by mroeschke** [comment]
Yes

**Comment by Hiyorimi** [comment]
Can I work on this one ?)

**Comment by Raalsky** [comment]
Is anyone in active development about these issue? Could I spend awhile upon it? @Hiyorimi

**Comment by Raalsky** [comment]
Does anyone was thinking about the way we can split `fixtures` for `test_offsets`? -> https://github.com/pandas-dev/pandas/blob/07efdd4448c9a1b83e5260ff764f24b93e0c803d/pandas/tests/tseries/offsets/conftest.py#L7
I mean it's necessary in case we iterate over the list of classes from `tseries.offsets.__all__`. Is it ok if we have logic about filtering Business/Non-Business classes within two different fixtures? Or we want to separate them in `pandas.tseries.offsets` in some way?

**Comment by jreback** [comment]
there are already some fixtures defined look in pandas/contest.py and see how they r used

**Comment by felixDulys** [comment]
take

**Comment by felixDulys** [comment]
It's been a minute since this issue was worked on! Taking a look--

> It would be good to create:
> 
> `pandas/tests/tseries/offsets/test_business_offsets.py` for business offsets

Comparing what we have in master now with what tests looked like with the [xref comment timeframe](https://github.com/pandas-dev/pandas/tree/14788455be25031f9787fb7b2333d18d6bacf1a5/pandas/tests/tseries/offsets), there are some improvements. We have a few new business offset files (ex. `test_business_day.py` and `test_business_hour.py`), but there still seems to be a healthy chunk of work. The file `test_offsets.py` still has a few business functions in there (even if in name only)...

> `pandas/tests/tseries/offsets/test_date_offsets.py` for all offsets that subclass `DateOffset`
> 

...this is still seemingly available...

> and converting the tests to pytest idioms.

...and I think there is some good to do here as well, still. 

This could be a lot for one PR, so I will try and break off pieces of this in a meaningful way.

**Comment by mroeschke** [comment]
This looks sufficiently completed so closing
