### ISSUE TITLE
EA: Make validate_fill_value part of interface

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#27316]
We defined validate_fill_value for DTA/TDA/PA and I'm thinking it may be worth requiring more generally and using on `ExtensionBlock`.  In particular, `ExtensionBlock._can_hold_element` ATM unconditionally returns `True`.  _can_hold_element isn't well-documented, but my intuition as to what it _should_ mean more or less matches what _validate_fill_value means.

**Comment by jorisvandenbossche** [comment]
So should we rather make better use of `_can_hold_element`, since that already exists?

**Comment by jbrockmendel** [comment]
I've got a couple of branches going that are cleaning up the usage of can_hold_element and related methods.  The issue is that ExtensionBlock._can_hold_element should defer to the EA

**Comment by jorisvandenbossche** [comment]
Ah, looking at the code, the existing `_can_hold_element` is only at the Block level right now (missed that). So we would need something new on the EA anyway, I see. 

But wondering: I don't see many actual usages of `_can_hold_element`. One example is `setitem`. But for that one, couldn't this also be `EA.__setitem__` itself that does the validation, instead of the Block needing to do it on a higher level?

**Comment by jbrockmendel** [comment]
> But wondering: I don't see many actual usages of `_can_hold_element`

There are a handful in internals.blocks and one in core.indexing.  Also I'm in the process of trying to replace the pattern:

```
try:
    self._try_coerce_args(value)
except (ValueError, TypeError):
    self.foo(...)
else:
    self.bar(...)
```

with

```
if self._can_hold_element(value):
    self.bar(...)
else:
    self.foo(...)
```

> couldn't this also be EA.__setitem__ itself that does the validation, instead of the Block needing to do it on a higher level?

Possibly.  I'm still trying to figure out what can_hold_element is really intended to do.
