### ISSUE TITLE
CategoricalDtype.update_dtype fails with Categorical

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#27338]
ref https://github.com/pandas-dev/pandas/pull/27318#discussion_r302265250 it appears that CategoricalDtype might want to accept a Categorical as an argument but fails to handle that properly. Not sure intent here but we either want to fix to allow Categorical or alternately simplify and only allow `str/CategoricalDtype` input

**Comment by jorisvandenbossche** [comment]
Looking at the base implementation:

https://github.com/pandas-dev/pandas/blob/5a7a8e1decf7154f396adf42860780b15221df4b/pandas/core/dtypes/base.py#L232-L269

there is a `dtype = getattr(dtype, "dtype", dtype)`, so it seems rather on purpose that it accepts not only dtype objects itself, but also containers that have a dtype.

(personally I don't really like this polymorphism, I think it would be cleaner to just allow dtype objects and have the called to `obj.dtype` if necessary)

**Comment by jorisvandenbossche** [comment]
cc @jschendel

**Comment by jschendel** [comment]
I think only accepting `CategoricalDtype` is fine.  The docstring states that the input should be a `CategoricalDtype`, with no mention of `Categorical`/`CategoricalIndex`, and the behavior is only tested for `CategoricalDtype`.  If `Categorical` worked in the past it was only due to happenstance, likely due to `is_dtype` being a bit confusing in that it returns `True` for things that aren't actually dtypes (though it appears this is the intended behavior for `is_dtype`).  Is there a tangible benefit to explicitly supporting `Categorical` here?

**Comment by TomAugspurger** [comment]
Anything to do here for 1.0, or OK to push

**Comment by TomAugspurger** [comment]
FWIW, on master, this does succeed

```python
In [31]: pd.CategoricalDtype(['a']).update_dtype(pd.Categorical(['b'], ordered=True))
Out[31]: CategoricalDtype(categories=['b'], ordered=True)
```

**Comment by mroeschke** [comment]
Could use a test for the behavior above.

**Comment by pratyushprakash** [comment]
@mroeschke Is this up for grabs. If it is I'd like to work on it

**Comment by pratyushprakash** [comment]
take
