### ISSUE TITLE
Why read_sas is converting strings to float?

### ISSUE THREAD

**Issue by SqrtPapere** [pandas-dev/pandas#27450]
#### Code Sample
```python
import pandas as pd
df = pd.read_sas('test.sas7bdat', format='sas7bdat', encoding='utf-8')

```
#### Problem description

I am trying to read a `.sas7bdat` file using `read_sas` and I am having a hard time because the module is converting strings values that look like a number into `float`.

For example, if I have a telephone number like `'348386789'` and I read it with the code I posted the output obtained is `348386789.0`.

I noticed the same problem in the `read_csv` function but there you can use the argument `dtype` to manually set the type for each column (es. dtype={'number': str)}).

#### Expected Output

`'348386789'`

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 19.1.1
setuptools: 41.0.0
Cython: None
numpy: 1.16.3
scipy: None
pyarrow: 0.13.0
xarray: None
IPython: 7.4.0
sphinx: 2.1.2
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: 3.5.2
numexpr: 2.6.9
feather: 0.4.0
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.4
bs4: None
html5lib: None
sqlalchemy: 1.3.5
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by TomAugspurger** [comment]
cc @kshedden @Winand if you have thoughts.

**Comment by kshedden** [comment]
Try as below and confirm that the columns in the SAS file are numeric (type 'd') not string (type 's').

```
rdr = pd.read_sas("test.sas7bdat", iterator=True) 
print(rdr.column_types())
```

**Comment by TomAugspurger** [comment]
@SqrtPapere can you follow up on this?

**Comment by Winand** [comment]
I cannot reproduce this with 0.24.2.
[test.sas7bdat.zip](https://github.com/pandas-dev/pandas/files/3420333/test.sas7bdat.zip)
```
import pandas as pd
df = pd.read_sas('test.sas7bdat', format='sas7bdat', encoding='utf-8')

       NumCol     StrCol
0  34838678.0  348386789
1         0.0  000000000
2  12345678.0  123456789

NumCol    float64
StrCol     object
dtype: object
```
<details><summary>INSTALLED VERSIONS</summary><p>

commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: ru_RU.UTF-8
LOCALE: None.None

pandas: 0.24.2
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.6
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: 1.8.5
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: 1.5.1
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.2
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.1
pymysql: None
psycopg2: 2.8.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</p></details>

**Comment by SqrtPapere** [comment]
Sorry for my late reply...anyway

@kshedden : output of your code is pretty weird:

`[b'd' b'd' b'd' b'd' b'd' b'd' b'd' b'd' b's' b's' b's' b's' b's' b'd'
 b's' b's' b's' b'd' b'd' b'd' b'd' b'd' b'd' b's' b's' b'd' b'd' b'd'
 b's' b'd' b's' b'd' b'd' b'd' b'd' b'd' b'd' b'd' b's' b'd' b'd' b'd'
 b'd' b'd' b's' b'd']`

I guess it's caused by `iterator=True`.

Could it be useful to post my sas file anywhere so you can try it yourself?

**Comment by kshedden** [comment]
The 'd' values correspond to numeric or date columns, 's' corresponds to string columns.  The elements of the array are the same order as the columns will appear in the final data frame.  Please confirm that the columns you are having trouble with have an 's' code not a 'd' code.  If they have a 'd' code then we are doing the right thing by making them numeric, since this is the format that they have in the SAS file itself.

**Comment by SqrtPapere** [comment]
@kshedden how is converting dates to numeric the right thing?

Unfortunately, I don't have a SAS license, so I have no way to check the codes for the columns... But I know the meaning of the data and I know what format they should be.

For example, reading the file using this online [tool](http://dumbmatter.com/sas7bdat/), I get this output (these are just the first 11 columns):

![16E1AEB](https://user-images.githubusercontent.com/17984266/61696344-78055c80-ad35-11e9-88f2-44ceda8df409.PNG)

Which is correct, because the first column is a code, so it should be read as a string, the second is a date, but I think is stored as a string using the date format (YYYYMMDD) and so on...

The output of `read_sas` instead is:

```
NDG_GRUPPO  DT_DECORRENZA  ...  SEGMENTO_RISCHIO_CG  NOTCH_IG
11.0         20190129.0    ...                  NaN       NaN
```

Again, if you want the data I can post it anywhere you want.

**Comment by Winand** [comment]
I think, your dates are just numeric values which look like dates 🤔

**Comment by SqrtPapere** [comment]
@Winand Yes, I absolutely agree with you. 

But don't you think there should be a way of reading it as you like?
Or the problem is at the source and I should be asking the owner of the data to convert the column to the right type?

**Comment by kshedden** [comment]
If a SAS string is being magically converted to a number, or vice versa, that is a bug and we should fix it.  However it remains unclear if that is the issue, or if you are just asking for the facility to do a type conversion on-the-fly inside the SAS reader.  Using the `column_types` parameter that I mentioned before, you can see what the actual internal SAS type is.  That should correspond to the Pandas type (SAS 'd' becomes Pandas float64 or datetime, SAS 's' become Pandas string or byte array).

The SAS file structure is complex and secret.  Efforts like this are based on reverse engineering.  As far as we know, internally a SAS7BDAT file only contains two types of data: floats and strings.  The floats aren't even modern floats, they are an archaic float format from the 1970s.  Dates are actually floats, with an extra formatting code that tells SAS how to interpret the float as a date.

The goal of Pandas `read_sas` is to read a SAS file into a Pandas dataframe that is close as possible to holding the data as SAS sees it.  This means that strings become strings (or byte arrays), numbers become IEEE floats, and there is some provision for date conversions (since the SAS date type is not standard and it would be difficult to do the conversion on your own).  Once the data is in a Pandas dataframe, you can do whatever else you want to do with it, but I don't think we should reimplement that type of functionality inside the SAS reader.

If your file is large and you need to do conversions on-the-fly, use the iterator pattern to read it by chunk.  Each chunk can be small, say 10 million lines, and you do the conversions by chunk and reassemble everything at the end.

**Comment by SqrtPapere** [comment]
Ok, I appreciate the clarification and understand the effort about the sas file reader. 
I'll try implementing the converter as you suggested but performances are going to be a problem for sure ...

Thanks!

**Comment by Winand** [comment]
@SqrtPapere
```
In [10]: dt = 20190129.0
In [11]: dt, day = divmod(dt, 100)
In [12]: year, month = divmod(dt, 100)
In [13]: year, month, day
Out[13]: (2019.0, 1.0, 29.0)
```

**Comment by RajeshSivadasan** [comment]
How is SAS reader (https://github.com/dumbmatter/sas7bdat-js) able to find the correct datatype, in this case integer and show it as integer although it is stored as float? I am also facing this issue where integer column is read into dataframe as float but the SAS reader is able to display it properly as integer.
