### ISSUE TITLE
Move json_normalize to pd namespace

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#27586]
This function I think gets a good amount of usage but people tend to import from `pandas.io.json`. ref #27522 I think we should move this to the top level

cc @bhavaniravi

**Comment by bhavaniravi** [comment]
I totally agree.

**Comment by vishwakftw** [comment]
I'd like to contribute to this patch. If I understand correctly, I'll have to import `json_normalize` in `__init__.py`, right?

Are there any additional warnings (future / deprecation) that need to be added for this change?

**Comment by WillAyd** [comment]
Start with that and a whatsnew. We may also want to throw a FutureWarning when someone tries importing from pandas.io.json; not sure best way to do that so can maybe just submit first part and we can discuss from there

**Comment by jorisvandenbossche** [comment]
> We may also want to throw a FutureWarning when someone tries importing from pandas.io.json

Is this needed? We have always consistently documented it to be imported from there (and we also have other public functionality in that submodule), so this just gives code churn for not much reason I think.  

Of course for `json_normalize`, the argument can be that it is used often enough to warrant a top-level entry (I can't really judge that), and keeping it in two locations is also confusing, so that would be an argument to deprecate the other.

There is also `pd.io.json.build_table_schema` which ideally lives in the same place, but I am not sure this warrants a top-level function as well.

(see also the comment I made in https://github.com/pandas-dev/pandas/issues/27522 about json_normalize being far from the only public non-top-level function, although it might be the most used one, I don't know)

**Comment by amcnulty93** [comment]
Is this still being worked on? If not I can pick it up!

**Comment by vishwakftw** [comment]
It is being worked on in #27615.
