### ISSUE TITLE
DOC: instructions for installing C Compiler are missing

### ISSUE THREAD

**Issue by ncernek** [pandas-dev/pandas#27707]
#### Excerpt from [Contributing to pandas](https://dev.pandas.io/development/contributing.html#installing-a-c-compiler)
>Pandas uses C extensions (mostly written using Cython) to speed up certain operations. To install pandas from source, you need to compile these C extensions, which means you need a C compiler. This process depends on which platform you’re using. Follow the [CPython contributing guide](https://devguide.python.org/setup/#compile-and-build) for getting a compiler installed. You don’t need to do any of the ./configure or make steps; you only need to install the compiler.

#### Problem description

The link to CPython contributing guide doesn't explain how to set up a C Compiler.

What is needed is an OS-specific explanation for how to set up a C Compiler, or an explanation for how to check that one already has a compiler.

**Comment by jbrockmendel** [comment]
What platform are you using?

**Comment by WillAyd** [comment]
The steps are there but I think a reorg of the target maybe makes it less clear. For example the macOS section mentions installing Xcode and Windows visual studio. I assume Unix is intentionally left out because it really depends on distro

This might have been in one section in the past so maybe just need to change wording to highlight that better. We liberally accept documentation improvements so if you have a suggestion feel free to make a PR

**Comment by jorisvandenbossche** [comment]
Even though the mac section somewhere mentions xcode, and the windows section mentions Visual Studio, those mentions are such burried in a long document with a lot of irrelevant content, that linking to that page is simply confusing IMO.

For me, the minimum is removing that link even without replacement. 

Other options: https://cython.readthedocs.io/en/latest/src/quickstart/install.html, although for Windows that seems a bit outdated. 

I am wondering if https://anaconda.org/conda-forge/compilers would be interesting, since our development explanation is already largely based on conda (although this might be conda-forge specific). 
But someone should try it out on Mac or Windows then to see how that goes.

**Comment by jorisvandenbossche** [comment]
The long list of links about Windows (just below the quoted paragraph, https://dev.pandas.io/development/contributing.html#installing-a-c-compiler) could also use a clean up. I assume quite some of them are nowadays no longer relevant or outdated.

**Comment by TomAugspurger** [comment]
We have a PR up for using the conda compilers I think.

But we'll presumably still want something for people using their own Python & virtualenv.

IMO, the best action for us right now is to link windows devs directly to https://devguide.python.org/setup/#windows and Mac devs to https://devguide.python.org/setup/#macos-and-os-x.

**Comment by ncernek** [comment]
> What platform are you using?

@jbrockmendel I'm on OSX.


> For me, the minimum is removing that link even without replacement.

I agree with this, and would be happy to make a PR to remove it.

**Comment by TomAugspurger** [comment]
What's wrong with linking to the platform specific section?

**Comment by iamgauravg** [comment]
I would like to help with this issue if its still open. This would be my first attempt to contribute.

**Comment by ncernek** [comment]
@TomAugspurger I think that's fine too - that said I'm getting a 403 Forbidden on both those links.

**Comment by iamgauravg** [comment]
@ncernek I see the same 403 error

**Comment by jorisvandenbossche** [comment]
> What's wrong with linking to the platform specific section?

Eg the windows one says:

> Your first build should use the command line to ensure any external dependencies are downloaded:
> 
> PCBuild\build.bat

 I suppose that is already python specific? 

I think for a newcomer, it is very unclear until where in that page the instructions should be followed.
>

**Comment by TomAugspurger** [comment]
Those 403s are likely a transient issue.
