### ISSUE TITLE
Standardize pandas distribution lists

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#27903]
As the project and the community grows, I think it'd be good to keep some consistency among the different channels to communicate. Currently we have:
- pydata@googlegroups.com (broader than pandas, but it's kind of our users list)
- pandas-dev@python.org
- pandas-core-team@googlegroups.com
- pydata/pandas on Gitter for IM (I guess it's more intended for devs, but a mix of dev/users in practice)

I don't have a preference on the platform (google groups, mailman, discourse if it's free for open source projects,...), but I think it'd make things simpler and better if we had:
- pandas-users@...
- pandas-contributors@...
- pandas-maintainers@...

And same channels in Gitter. The pandas-maintainers ones should be private for the active maintainers (both the list and the gitter channel).

I think the names would make it clear what's expected to be discussed, and should help keep each of them focused (I'd avoid pandas-dev, since I think for beginners it can be ambiguous if a pandas dev is a person working with pandas or on pandas).

CC: @pandas-dev/pandas-core

**Comment by TomAugspurger** [comment]
Agreed it'd be nice to simplify the pandas-dev / pydata@googlegroups split across two systems.

On the subject of discourse, there's been talk of creating a discourse for NumFOCUS projects (so that not every project has to create their own). I suspect we could have pandas-users & pandas-contributors boards on that.

**Comment by datapythonista** [comment]
@Dr-G do you know if the NumFOCUS discourse is something we can expect in the short-term? Thanks!

**Comment by TomAugspurger** [comment]
I should have been clearer. By "there's been talk" I meant very early suggestions of "this is a thing we could do". cc @jcrist if you've reached out to anyone at NumFOCUS or discourse about this.

**Comment by Dr-G** [comment]
FWIW, we used to have a NumFOCUS Discourse instance. No one used it, but I think that's because there was no "reason" for people to use it. I imagine that if projects moved their discussion groups there, it would be different. Let us know if this is something you want to pursue for pandas in future.

**Comment by jcrist** [comment]
I have not yet, I was hoping to collect potential buy-in from a few projects before bothering them.

The general idea here is that projects like CPython, Jupyter, etc... have been having success curating conversation on Discourse. Dask is looking at using Discourse for non-user-issue discussion (instead of gitter, which isn't searchable). Instead of having a Discourse-per-pydata-project, we figured it might be nicer for users to have a big Discourse instance shared among common projects (each project getting a sub-channel). We though NumFOCUS would be a potentially good org to host this under.

> Let us know if this is something you want to pursue for pandas in future.

@Dr-G, would this be something we could restart? Who at NumFOCUS should we talk to about this?

**Comment by Dr-G** [comment]
@jcrist yes, we could definitely restart it. Please reach out to leah@numfocus-dot-org and andy@numfocus-dot-org to discuss.

**Comment by datapythonista** [comment]
There was no interest in moving the old lists to our domain, so closing this.
