### ISSUE TITLE
Remove customizations to isort formatting

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#28321]
We customize the display of pandas imports in setup.cfg for isort. This is documented in the contributing guide:

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#import-formatting

To provide an example, isort would naturally order imports to be something like:

```python
from pandas.api import DataFrame
from pandas.core.dtypes.inference import is_list_like
```

Though our customization would do this:

```python
from pandas.core.dtypes.inference import is_list_like

from pandas.api import DataFrame
```

I personally have found the alphabetic rule much easier to grok and am sometimes surprised by the logic of our imports. 

Is there an actual value add to the way we do this (avoiding circular imports?) or would we consider getting rid of the customizations and just letting isort do the work

I think @jbrockmendel and @datapythonista might have some insights into historical reasoning

**Comment by jbrockmendel** [comment]
I've pushed for the current config based on dependency structure arguments (if this isn't clear in the contributing docs, I can try to flesh that out).

The standard ordering (both in isort and in the ecosystem more generally) is `__future__`, stdlib, 3rd_party, 1st_party, same_directory.

pandas has a big codebase and a complicated dependency structure that we have been trying to simplify.  The isort config is intended to reflect parts of the dependency structure that are non-circular (with caveats).  e.g. pandas._config can be treated _almost_ like 3rd_party, so is ordered after 3rd_party but before everything else.

side-note: same_directory isn't really respected because AFAICT isort expects those to be relative imports, which we mostly don't use.

**Comment by jbrockmendel** [comment]
I'm going to try to rephrase here more clearly before trying to add anything to the docs.

When looking at the imports of module X, I want to know what X relies on and what relies on X.  What parts of the code may be affected if I make an edit in module X.  The import order is designed to make this visually obvious.  Standard library and 3rd party modules are obviously not affected by module X.  Similarly, other pandas modules that are strictly above X in the import order are not affected by X.

(With some caveats that the dependency structure is not as one-way as we might like)

Is that clearer?

**Comment by alimcmaster1** [comment]
I think that’s clear! 

It’s quite common in java to group imports by dependency structure. 

We could potentially add some visualisation using: https://github.com/thebjorn/pydeps to show dependency structure.

**Comment by WillAyd** [comment]
Thanks @jbrockmendel for the explanation
