### ISSUE TITLE
pd.read_json and orient="index" sorts results

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#28557]
Note that the order of input is not maintained with orient="index"

```python
>>> df = pd.DataFrame(range(3), index=range(3, 0, -1))
>>> df
   0
3  0
2  1
1  2
>>> df.to_json(orient="index")
'{"3":{"0":0},"2":{"0":1},"1":{"0":2}}'
>>> pd.read_json(df.to_json(orient="index"), orient="index")
   0
1  2
2  1
3  0
```

This is not necessarily a problem as by definition JSON objects are unordered, but preserving the order here would be a logical follow up to #27309

**Comment by KimDoubleB** [comment]
Hi !
If this issue is not assigned, I would like to make PR for this :)

This is the result you expected, right?
`
...
>>> pd.read_json(df.to_json(orient="index"), orient="index")
    0
3  0
2  1
1  2
`

**Comment by WillAyd** [comment]
Yes that's correct, at least for Py36 and above. The lines where this is happening is here:

https://github.com/pandas-dev/pandas/blob/ffe6cfdbf82d663c3f77567bde11f1666de1df38/pandas/io/json/_json.py#L1114

So for now look in pandas.compat for the PY35 directive and only sort for that. Py36 and above won't need extra handling.

We'll eventually be ripping out Py35 by the time this gets released but good to do it that way so the subsequent clean up is easily recognizable.

**Comment by KimDoubleB** [comment]
I have completed the code modification to resolve the issue you mentioned. However, an error occurs because the existing test file is checking the sorting at Py36 and above.
https://github.com/pandas-dev/pandas/blob/4fb853f62e5dd1b42a8054e930bd9cacbe9baa0f/pandas/tests/io/json/test_pandas.py#L171-L173

Therefore, can I modify the test file to solve the errors, and then move on to PR?

**Comment by WillAyd** [comment]
Yep the text will need to change to only sort on Py35
