### ISSUE TITLE
max_rows option is broken

### ISSUE THREAD

**Issue by jtiscione** [pandas-dev/pandas#28654]
#### Code Sample, a copy-pastable example if possible
pd.set_option("display.max_rows", 100)
print(display)

Displays this:
<img width="391" alt="Screen Shot 2019-09-27 at 6 55 04 AM" src="https://user-images.githubusercontent.com/5413726/65770716-e0850700-e0f3-11e9-904f-f13e73d17687.png">

I need to see more than 12 rows.

**Comment by jschendel** [comment]
This is the expected behavior.  Your dataframe has more rows (120) that what you're setting as the max (100), so the truncated repr will still be displayed.  You either need to increase `max_rows` to at least 120, or set it as `None` for unlimited rows.  Alternatively you could increase `min_rows`, although you may still need to adjust `max_rows` to be larger than `min_rows`.

See the docs on the [available options](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html#available-options) for more details.
