### ISSUE TITLE
Include/exclude using multiple columns

### ISSUE THREAD

**Issue by amirhosseindavoody** [pandas-dev/pandas#28740]
This is a proposal for two new methods that makes filtering dataframe rows easier based in value of two or more column values.

In my use of pandas there is often need to filter (exclude or keep) all the rows that meet a certain condition on multiple column **simultaneously**. For example column A is equal to 1 and column B is equal to 2. I know that I can write a code like the following

```python
new_df = df[(df['A'] == 1) & (df['B'] == 2)]
```

but this seems too much of writing for a simple task, especially if the number of conditions gets larger or the names are not as concise as df, A, and B.

I have written the following two methods to accomplish the task for arbitrary number of conditions and have registered it as native functions using pandas_flavor library. I was wondering if there is attractions/thoughts from others to incorporate this into the original pandas package

``` python
@pf.register_dataframe_method
def include(df, **kwargs):
    '''
    Include only the rows that match the input condition simultaneously.

    Parameters:
    -----------
    df : pandas.DataFrame
        input dataframe
    **kwargs : keyword arguments
        The name of column and the value that are being checked

    Returns:
    --------
    pandas.DataFrame that the matching rows are kept

    Example:
    --------
    Assume df is a dataframe with the following columns: column1, column2, column3
    Then we can only keep the rows that have column1 = value1 and column2 = value2 simultaneously by following command

    include(df, column1=value1, column2=value2)
    '''
    arg = np.ones(shape=(len(df),)).astype(bool)
    for key, value in kwargs.items():
        arg &= (df[key] == value)
        
    return df[arg]

@pf.register_dataframe_method
def exclude(df, **kwargs):
    '''
    Exclude the rows that match the input condition simultaneously.

    Parameters:
    -----------
    df : pandas.DataFrame
        input dataframe
    **kwargs : keyword arguments
        The name of columns and their values that are being checked

    Returns:
    --------
    pandas.DataFrame that the matching rows are excluded

    Example:
    --------
    Assume df is a dataframe with the following columns: column1, column2, column3
    Then we can exclude the rows that have column1 = value1 and column2 = value2 simultaneously by following command

    exclude(df, column1=value1, column2=value2)
    '''
    arg = np.ones(shape=(len(df),)).astype(bool)
    for key, value in kwargs.items():
        arg &= (df[key] == value)
        
    return df[~arg]
```

**Comment by stevennic** [comment]
My personal opinion is that although I agree about the verbosity problem, this does not look like the right solution to me because you would need a different method for each Boolean operator. It also wouldn't cover complex Boolean operations. It's a good temporary shortcut, but if pandas were to be redesigned to improve this problem, my vote would be to focus on eliminating the repetition of `df` inside the expression. 

Of course the way it is now allows us to do Boolean indexing based on any series, not just for columns belonging to `df`, but in my experience 99% of the time we are indexing on a series of the dataframe itself, so it would be worth inventing a shortcut that assumes `df` if a dataframe reference is missing. Something like this, with parentheses made optional and, consistent with all mathematical expressions, necessary only to influence operation precedence:

```python
new_df = df[A == 1 & B == 2]
```

I'm sure it's a non-trivial problem because A and B are not themselves valid identifiers but a smart nut could figure a way to wire them to resolve to df['A'] and df['B'] respectively. This way we wouldn't sacrifice Boolean expression complexity.

**Comment by dsaxton** [comment]
Why not use `DataFrame.query`?  The syntax is pretty compact.

**Comment by stevennic** [comment]
I think `query` doesn't provide access to the `Series` object, so you can't use the full feature set, such as `isna()`, all the Accessors (`.str`, `.dt`, `.cat`), etc. If somehow `A` and `B` in the example above were wired to `df['A']` and `df['B']`, they would be first-class `Series` objects.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but as this overlaps with the functionality of boolean indexing, I would be -1 to add another API for the same functionality.

Since there hasn't been much engagement from the core devs or community for this feature, going to close. But happy to reopen if there's more collective interest
