### ISSUE TITLE
DOC: Syntax highlight not always working

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#28796]
Looks like something is wrong while rendering the documentation, regarding syntax highlighting of code blocks.

See for example: https://dev.pandas.io/docs/user_guide/reshaping.html#multiple-levels

The first block code has no colors, just black. The next block is coloring the `In[27]`, the literals.

Checking the markdown in `doc/source/user_guide/reshaping.rst` I can't see any obvious difference among them. But for some reason Sphinx just highlights one.

CC: @jorisvandenbossche not sure if this is related to the new theme, or was happening before

**Comment by jorisvandenbossche** [comment]
I recently had a similar issue on the geopandas docs: https://geopandas.readthedocs.io/en/latest/missing_empty.html (also some code blocks not rendering properly, while I could not see any difference in the source code), which is using the readthedocs theme. So I would *guess* that it is not due to the new theme, but something else.

It's difficult to check if this was also the case yesterday with the old theme, as we overwrite it in the repo. But in any case the stable docs that were built manually don't have it: https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html#multiple-levels 
(although, there is also one "Out [26]" that is strangely not colored)

**Comment by jorisvandenbossche** [comment]
Also, those code blocks are generated by sphinx itself (the theme only decides which colors to use for which constructs), so this has to be something with sphinx / ipython directive.

The code block that is not colored in html looks like:

```
<pre class="literal-block">
In [23]: columns = pd.MultiIndex.from_tuples([
   ....:     ('A', 'cat', 'long'), ('B', 'cat', 'long'),
   ....:     ('A', 'dog', 'short'), ('B', 'dog', 'short')],
   ....:     names=['exp', 'animal', 'hair_length']
   ....: )
   ....: 
...
</pre>
```

while the one that is working looks like

```
<div class="highlight-ipython notranslate">
  <div class="highlight">
  <pre><span></span>
<span class="gp">In [27]: </span><span class="n">df</span><span class="o">.</span><span class="n">stack</span><span class="p">(</span><span class="n">level</span><span class="o">=</span><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">])</span>
<span class="gh">Out[27]: </span><span class="go"></span>
<span class="go">exp                          A         B</span>
<span class="go">  animal hair_length                    </span>
<span class="go">0 cat    long         1.075770 -0.109050</span>
...
</pre></div>
</div>
```

so it is sphinx for some reason generating different html ..

**Comment by jorisvandenbossche** [comment]
It's a IPython problem generating adding null bytes (`\x00`) in the output, and sphinx apparently cannot handle that. Why it only happens for certain cells, no idea, and why it happens at all, also no idea. See the issue I opened on the IPython side: https://github.com/ipython/ipython/issues/11904

There is an "easy" patch to have it solved:

```patch
--- a/IPython/sphinxext/ipython_directive.py
+++ b/IPython/sphinxext/ipython_directive.py
@@ -502,8 +505,11 @@ def process_input(self, data, input_prompt, lineno):
             ret.append(rest)
 
         # Fetch the processed output. (This is not the submitted output.)
         self.cout.seek(0)
         processed_output = self.cout.read()
+        processed_output = processed_output.strip('\x00')
         if not is_suppress and not is_semicolon:
             #
             # In IPythonDirective.run, the elements of `ret` are eventually

```

but since we don't vendor the IPython.directive anymore, it is not that easy to apply such a patch in our doc building temporarily. Anyway, of course ideally solved upstream.

**Comment by jorisvandenbossche** [comment]
To update this: at the time, I created a PR in IPython to get this fixed: https://github.com/ipython/ipython/pull/11905 (but not yet merged)

**Comment by jorisvandenbossche** [comment]
This is solved with the latest IPython release.
