### ISSUE TITLE
Style problem using Styler.set_table_styles

### ISSUE THREAD

**Issue by Tiarles** [pandas-dev/pandas#29397]
I am using the pd.Styler to style tables and render a HTML/CSS code from him.

But this python code has some problems:

```python
import pandas as pd

x = [0, 1]
y = [0, 1]

data = [[2, 3], [5, 6]]

df = pd.DataFrame(data, index=x, columns=y)

def detailedTableConfig():
    table = {
        "border-collapse": "collapse",
        "border": "1px solid black",
    }
    
    return [dict(selector="table", props=list(table.items()))]

s = df.style.set_table_styles(detailedTableConfig())

with open('table.html', 'w') as fhtml:
    print(s.render(), file=fhtml)
```

I am trying to put border around the table. But this python code generates this HTML/CSS code:

```html
<style  type="text/css" >
    #T_60255858_ff24_11e9_9c6a_988389d0b304 table {
          border-collapse: collapse;
          border: 1px solid black;
    }</style><table id="T_60255858_ff24_11e9_9c6a_988389d0b304" ><thead>    <tr>        <th class="blank level0" ></th>        <th class="col_heading level0 col0" >0</th>        <th class="col_heading level0 col1" >1</th>    </tr></thead><tbody>
                <tr>
                        <th id="T_60255858_ff24_11e9_9c6a_988389d0b304level0_row0" class="row_heading level0 row0" >0</th>
                        <td id="T_60255858_ff24_11e9_9c6a_988389d0b304row0_col0" class="data row0 col0" >2</td>
                        <td id="T_60255858_ff24_11e9_9c6a_988389d0b304row0_col1" class="data row0 col1" >3</td>
            </tr>
            <tr>
                        <th id="T_60255858_ff24_11e9_9c6a_988389d0b304level0_row1" class="row_heading level0 row1" >1</th>
                        <td id="T_60255858_ff24_11e9_9c6a_988389d0b304row1_col0" class="data row1 col0" >5</td>
                        <td id="T_60255858_ff24_11e9_9c6a_988389d0b304row1_col1" class="data row1 col1" >6</td>
            </tr>
    </tbody></table>
```

But this does not work:

![image](https://user-images.githubusercontent.com/13910905/68141076-a2a5aa80-ff0b-11e9-93bf-7126f5c2914f.png)

This HTML/CSS snippet work only if

```html
<style  type="text/css" >
    #T_60255858_ff24_11e9_9c6a_988389d0b304 {
          border-collapse: collapse;
          border: 1px solid black;
...
```

or:

```html
<style  type="text/css" >
    table{
          border-collapse: collapse;
          border: 1px solid black;
...
```
and still:

```html
<style  type="text/css" >
    table#T_60255858_ff24_11e9_9c6a_988389d0b304 {
          border-collapse: collapse;
          border: 1px solid black;
...
```

**Comment by gfyoung** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
What's the issue? You can't use an id selector and the `table` selector?

**Comment by Tiarles** [comment]
Hi,

If you want to modify attributes of the table, the parameter “table” in the ‘selector=’ argument does not render properly the table like I shown in the snippet code.

Warm regards,

Tiarles da Rocha Moralles Guterres

Computer Engineering
Academic of Electrical Engineering Master (UFSM)
RAS IEEE Member
Federal University of Santa Maria

________________________________
De: Tom Augspurger <notifications@github.com>
Enviado: Wednesday, November 6, 2019 6:21:10 PM
Para: pandas-dev/pandas <pandas@noreply.github.com>
Cc: Tiarles Guterres <tiarlesmoralles@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [pandas-dev/pandas] Style problem using Styler.set_table_styles (#29397)


What's the issue? You can't use an id selector and the table selector?

**Comment by Sup3rGeo** [comment]
@TomAugspurger the css generated by pandas has the selector like `#T_60255858_ff24_11e9_9c6a_988389d0b304 table`, which fails to apply the style to the table with that id.

It seems to be that the right way of selecting using the *tag* and *id* is, instead, `table#T_60255858_ff24_11e9_9c6a_988389d0b304`, which works.

We could be missing something here as we are not experts in CSS/HTML

**Comment by TomAugspurger** [comment]
Yeah, that was my question.

So set_table_styles only works with *class* and not *object* selectors, is
that correct? And `table` is an object selector?

**Comment by Tiarles** [comment]
With my poor knowledge in HTML/CSS  I think that in this case the table is a kind of selector, a general one. You must to be able to edit properties in the headers ('th' and 'tr'), in the data ('td') and in the general part of the table, using 'table{ ... }', "#*id* { ... }" or still 'table#*id*{ ... }'.

I don't know if I answered properly your question.

**Comment by attack68** [comment]
This is **not a bug**, and it works precisely as it should.

In CSS the general practice is that a `css-id` should be unique for a given `html-element`, and used once per page. The pandas styler creates unique ids for all the elements it wants to Style.

In CSS you will typically style elements directly and their **children**. There is **no parent styling**. So the concept behind Styler is to identify an element and then apply styles to it or its children, based on the `selector` you apply.

Consider the HTML:

```
<style  type="text/css" >
 #A {background-color: yellow;}
 #A p {color: red}
 #A p:nth-child(2) {color: blue}
</style>
<div id="A">
  <p>Red</p>
  <p>Blue</p>
  <p>Red</p>
</div>
```

Here the element with `id="A"`, which is a `<div>`, will have its background set to yellow, and there are css combinations to effect the children elements of the div.

For the specific issue referenced here the obvious solution is to remove the `table` selector and use blank so that the styles are directly applied to the table which has the specified `id`:

1) **Using no selector**. If you ignore the `selector` and instead of "table" use space or empty string then the css will be applicable to just an `id`. Since each id of each element is unique by design, the `table id` will affect this specific table tag

`return [dict(selector=" ", props=list(table.items()))]`

There are two additional work arounds for this issue giving greater flexibility in the current Pandas Styler.

2) **Using inline-styles**. For almost all purposes these will be suitable, where the css code is directly specified in the table tag. For some websites with strict content security policies (CSPs) inline styles are not permitted:

```
df = pd.DataFrame(data, index=x, columns=y)
s = df.style.set_table_attributes('style="border-collapse: collapse; border: 1px solid black;"')
```

3) **Using external css class**. If the table is to be appended to an existing website it is likely it will have an external style sheet. A class with relevant properties can be added there and referenced from the pandas output.

```
df = pd.DataFrame(data, index=x, columns=y)
s = df.style.set_table_attributes('class="external-css-reference"')
```

In each case the result HTML is different but the effect will be the same.

**Comment by TomAugspurger** [comment]
Thanks @attack68, sounds like this is working as intended.

**Comment by verisence** [comment]
@attack68 This worked for me. Thank you.
