### ISSUE TITLE
CI Error AttributeError: 'ExcelFile' object has no attribute 'engine'

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#30217]
Showing up in 

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=22986&view=logs

```python
Traceback (most recent call last):
  File "D:\a\1\s\pandas\io\excel\_base.py", line 907, in __del__
    self.close()
  File "D:\a\1\s\pandas\io\excel\_base.py", line 890, in close
    if self.engine == "openpyxl":
AttributeError: 'ExcelFile' object has no attribute 'engine'
```

Looks to be caused by changes in #30096 - I think need to make it `self.reader.engine`. But definitely shows this code getting hit

@jbrockmendel

**Comment by jbrockmendel** [comment]
yah, ive been seeing that locally ocassionally.  last time i looked at it i concluded that `self.engine` is correct, and best guess is that since this is happening inside `__del__`, something weird is going on with `__dict__` getting cleared out.  Hopefully I'm wrong on this and changing `self.engine` -> `self.reader.engine` fixes it.

**Comment by WillAyd** [comment]
Hmm actually that's a good point. I misread that `engine` was never an attribute of the ExcelFile but that's not true

**Comment by jorisvandenbossche** [comment]
I think the code in the `__del__` function can be wrapped in a try / except to hide those errors. When python is cleaning up, you are not exactly sure about the order, so certain variables that are accessed in the `__del__` method can already be deleted before the parent object is (see warning box at https://docs.python.org/3/reference/datamodel.html#object.__del__)
