### ISSUE TITLE
CLN: move update to BlockManager method (and just call from frame)

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#3025]
promotes consistency, see #3021, #3016, #9065

**Comment by jbrockmendel** [comment]
Can this be closed as Sufficiently Stale?  If not, -1 on moving anything _in_ to internals.

**Comment by jbrockmendel** [comment]
@jreback closeable?

**Comment by jreback** [comment]
no .update should be moved to intervals for sure
it’s pretty much the only method outside

**Comment by TrigonaMinima** [comment]
@jreback could you guide me here. If I understand this correctly, the required changes are in `pandas/core/frame.py` and `pandas/core/internals/manager.py`. Will there be any other files where the modification will be required? I guess test files too.

**Comment by jbrockmendel** [comment]
The presence of filter_func in DataFrame.update means we have to operate column-wise instead of block-wise when it is present.  We _could_ also have a blockwise implementation as a Manager method, but i dont think its worth the duplication.

The Series.update signature doesn't match DataFrame.update.  Would be nice to get those aligned.

**Comment by jbrockmendel** [comment]
Closing as infeasible for reasons described above.
