### ISSUE TITLE
Builtin loading of files from multi-file zip archives

### ISSUE THREAD

**Issue by abmyii** [pandas-dev/pandas#30262]
Could a solution be implemented to simplify loading a dataset from a multi-file zip archive? I know it is a bit insignificant compared to most other issues (especially since there are workarounds), but I'd be happy to implement it myself if I'm given the go-ahead so as to not waste your time.
Thanks for this amazing library!

**Comment by TomAugspurger** [comment]
My initial reaction is that this is out of scope for pandas. It seems hard to make a clean API to handle all the variety of what could be contained in an archive.

**Comment by abmyii** [comment]
Sorry I meant that you'd still have to specify a file, not automatic loading.

**Comment by abmyii** [comment]
I was thinking that the file could be specified like so: `pd.read_csv('data.zip/data.csv')`

**Comment by AlexKirko** [comment]
On one hand, we allow reading csvs that have been zipped. The user might expect to be able to read a csv from a zip. And they might expect pandas to treat a zip transparently as a folder.
On the other hand, I beleive that the intention of `read_csv` is to read a file. zip in this case is just another format for a csv file added for convenience, since we can compress data files to save on space.
There is also the matter of implementing support for reading from an arbitrary zip file everywhere else (such as `read_pickle`).
I just don't know how valuable it would be for users to be able to work with an entire compressed data folder. It's never come up in my work, since it's very inconvenient to have all the data sets compressed into one file when you need to replace one of them.

**Comment by abmyii** [comment]
The dataset I am using, geonames, provides zips with a `readme.txt` and then one (or in some cases) two or three data files. Currently I have to delete the extraneous files manually before being able to load it into pandas. If the proposed method was implemented then I would be able to load a file without having to worry about modifying the zips beforehand, nor having to extract them, which is unwieldy.

**Comment by TomAugspurger** [comment]
> If the proposed method was implemented then I would be able to load a file without having to worry about modifying the zips beforehand

That's what concerns me. Pandas would have no idea that `readme.txt` would need to be skipped, but some other file (or files) would need to be read.

@abmyii I'd recommend using `zipfile.ZipFile` to open your archive and get the filehandle for just the file / files you need, and pass that to pandas.

**Comment by abmyii** [comment]
> That's what concerns me. Pandas would have no idea that readme.txt would need to be skipped, but some other file (or files) would need to be read.

@TomAugspurger My suggestion implementation would require the specification of the file(s) to load from the zip - not an automatic indexer/loader.

> @abmyii I'd recommend using zipfile.ZipFile to open your archive and get the filehandle for just the file / files you need, and pass that to pandas.

This is a temporary solution I have implemented and everything else works fine, but I would like to see `pandas` abstract this step in the future.

**Comment by abmyii** [comment]
I decided to make a *very basic* POC where the file is specified after the `@` symbol (i.e. `data.zip@data.txt`).
https://github.com/abmyii/pandas/tree/multifile_zip

**Comment by abmyii** [comment]
Ping.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it seems like there's not much appetite to include this in pandas. Closing.

**Comment by abmyii** [comment]
No worries, hope you'll reconsider this feature in the future.
