### ISSUE TITLE
ADMIN: display issue metrics 

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#30576]
came across this blog / repo which shows nice issue metrics for matplotlib - should be very easy to create one for pandas 

https://github.com/LaurenceMolloy/RepoDash

cc @pandas-dev/pandas-core 
@tacaswell

**Comment by mroeschke** [comment]
While this looks a little more insightful than https://github.com/pandas-dev/pandas/pulse, it looks like https://github.com/LaurenceMolloy/RepoDash hasn't been developed since 2020 and I'm not sure how actionable this dashboard would be with the maintenance effort of the dashboard.

Closing for now, but we can reconsider in the future.
