### ISSUE TITLE
CLN: Fix FutureWarnings in the benchmarks

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#30780]
I see couple of `FutureWarning` in the benchmarks that can be fixed by simply updating the code to the proposed version.

```
·· /home/runner/work/pandas/pandas/asv_bench/benchmarks/algorithms.py:8: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
     from pandas.util import testing as tm
   /home/runner/work/pandas/pandas/asv_bench/benchmarks/sparse.py:5: FutureWarning: The pandas.SparseArray class is deprecated and will be removed from pandas in a future version. Use pandas.arrays.SparseArray instead.
     from pandas import MultiIndex, Series, SparseArray, date_range
```
See for example: https://github.com/pandas-dev/pandas/pull/30746/checks#step:13:21

**Comment by TomAugspurger** [comment]
Joris is handing the pandas.util.testing part.

**Comment by jorisvandenbossche** [comment]
Part of the SparseArray is also being fixed.

In general, we should be careful with "fixing" such warnings in the benchmarks. Fixing should typically not mean to use the new way, but either have some compatibility layer for older versions or catch/ignore the warnings, because we want to keep the benchmarks runnable by older pandas versions as well.
