### ISSUE TITLE
_BaseOffset's parameter `n` should be prevented from being 0

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#31184]
The docstring says
```
        Require that `n` be a nonzero integer.
```
but the "nonzero" condition isn't enforced.

Enforcing it would prevent the undesired behaviour noticed in #29901 , whereby
```
cbh = pd.offsets.CustomBusinessHour(start='07:00', end='01:00')
time = pd.Timestamp('2019-03-06 13:00:00')
time + 0*cbh
```
was returning
```
2019-03-07 07:00:00
```

**Comment by Liam3851** [comment]
Offset 0 is still officially docced as a rollforward, see https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.tseries.offsets.DateOffset.html#pandas.tseries.offsets.DateOffset.

```
Zero presents a problem. Should it roll forward or back? We arbitrarily have it rollforward:
date + BDay(0) == BDay.rollforward(date)
Since 0 is a bit weird, we suggest avoiding its use.
```

This has been in the doc as "discouraged" for a long time, but has also been docced as the behavior of offset 0 since time immemorial. Does this need a deprecation in code or has the "discouraged" been in long enough that this can be considered already deprecated (in which case the doc needs to be updated)?

**Comment by MarcoGorelli** [comment]
That's a good point, thanks - I'd imagine the core would want a deprecation warning first

**Comment by jbrockmendel** [comment]
I think determined in #31185 that n=0 needs to be allowed (lest `period - period` raise), so the doc should be updated

**Comment by jbrockmendel** [comment]
The docstring no longer says "nonzero".  closing.
