### ISSUE TITLE
DEPR: DataFrame.__getitem__[str] sometimes slices on index

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#31476]
xref #31334, #9595 

- This is a tiny corner case, at least as measured by tests cases (2 tests reach this)
- With this removed, the `__getitem__` API becomes much simpler to describe: "DataFrame.__getitem__` is always column-based"

**Comment by jorisvandenbossche** [comment]
@jbrockmendel Can you be more clear or specific in the description of the issue? And give some examples of the behaviour you want to deprecate?

For example: do you want to deprecate all slicing in `__getitem__`, or only the slicing with a single string? Because in https://github.com/pandas-dev/pandas/pull/31334, you never mentioned it is only about "single string" slicing, while the title here suggest otherwise.

> With this removed, the __getitem__ API becomes much simpler to describe: "DataFrame.getitem` is always column-based"

Assuming you only mean "partial datetime string slicing with a single string", note that `__getitem__` still does row-based access (normal slicing, boolean masks). So the "getitem is always column-based" is a bit confusing. I suppose you mean: when passing a single label, it is always column-based.
