### ISSUE TITLE
BUG display.max_colwidth do not accept -1 for unlimited width

### ISSUE THREAD

**Issue by glemaitre** [pandas-dev/pandas#31532]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
pd.set_option("display.max_colwidth", -1)
```
#### Problem description

There is a regression with `"display.max_colwidth"`. In the past, it was only accepting integer. The way to no limit the size was to pass `-1`. In pandas 1,0, this option becomes more consistent and not limiting the width should be set with `None`. However, the support for negative integer was removed.

Thus, one would need to either set to `-1` or `None` depending on the pandas version. It would be best to support both options. Potentially, support for negative integer could be removed with a deprecation cycle.

**Comment by MarcoGorelli** [comment]
>  It would be best to support both options. Potentially, support for negative integer could be removed with a deprecation cycle.

@jorisvandenbossche Is this what we're going for then - add support for `-1` back in, but raise a FutureWarning alerting the user that it'll no longer work in a future version?

It reminds me of the `header` argument in `read_csv`, whereby `header=-1` used to work in 0.24, then in 0.25 it didn't (see #27779) and so we now raise
```
ValueError: Passing negative integer to header is invalid. For no header, use header=None instead
```

Perhaps the current ValueError could just have an extra line specifically instructing to use `None` instead of `-1`, in the case that `-1` is passed?

**Comment by glemaitre** [comment]
I made a PR to reverse the support and add a deprecation cycle.
