### ISSUE TITLE
pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.   from pandas.util.testing import assert_frame_equal

### ISSUE THREAD

**Issue by LLancelot** [pandas-dev/pandas#31682]
Does anyone could help?

**Comment by jorisvandenbossche** [comment]
Please show a full code example where you get this warning.

Either the warning is coming from another library, and then you can ignore it. Or either you are importing `from pandas.util.testing import assert_frame_equal` yourself, and then you can change it with `from pandas.testing import assert_frame_equal`

**Comment by andreamoro** [comment]
I've got the same error a moment ago when importing Seaborn. I've previous notebook where this working fine, and the only variable changed since then is the new version of Pandas now move into the 1.X side.

I'd assume that future warning is due to Pandas then, with Seaborn referencing some that will be sooner dismissed. 
I cannot see an harm in the short term, but somebody managing the Seaborn package should update the reference. 

This is happening with Seaborn 0.10, the most recent available as far as I can tell.

**Comment by jorisvandenbossche** [comment]
Yes, on the short term, this is nothing to worry about (although annoying to see), as it are warnings not errors. 
But it's seaborn that will need to update their imports to fix this (and I see you already opened an issue there).

**Comment by jorisvandenbossche** [comment]
Going to close this issue, as there is no action to be taken by pandas.

**Comment by jamesbloom100** [comment]
I was having the same issue, and agree it is not a pandas issue. I was able to resolve this issue by making sure pandas was version 1.0.4, seaborn was 0.10.1, and statsmodels was 0.11.1.

**Comment by parkershamblin** [comment]
Same issue just reverted back to pandas version 1.0.4

**Comment by amber1rn14is015** [comment]
I had the same issue. Resolved it.

Just open in editor
C:\Users\Amber\AppData\Local\Programs\Python\Python37\Lib\site-packages\pandas_datareader\compat_init_.py

Replace:

`from pandas.util.testing import assert_frame_equal`

with

`from pandas.testing import assert_frame_equal`

**Comment by vishwajitvishnu** [comment]
Just remove the 'cmap' from the seaborn.heatmap or you could use the solutions in the comments above.
