### ISSUE TITLE
API: df.loc(axis=0)[key] works differently from df.loc[key]

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#31858]
I would expect these to behave identically, but, from tests.indexing.multiindex.test_slice.TestMultiIndexSlicers.test_loc_axis_arguments:

```
def _mklbl(prefix, n):
    return ["{prefix}{i}".format(prefix=prefix, i=i) for i in range(n)]

index = MultiIndex.from_product(
            [_mklbl("A", 4), _mklbl("B", 2), _mklbl("C", 4), _mklbl("D", 2)]
        )
columns = MultiIndex.from_tuples(
            [("a", "foo"), ("a", "bar"), ("b", "foo"), ("b", "bah")],
            names=["lvl0", "lvl1"],
        )
df = (
            DataFrame(
                np.arange(len(index) * len(columns), dtype="int64").reshape(
                    (len(index), len(columns))
                ),
                index=index,
                columns=columns,
            )
            .sort_index()
            .sort_index(axis=1)
        )

>>> result = df.loc(axis=0)["A1":"A3", :, ["C1", "C3"]]   # <-- currently in the test, works

>>> result2 = df.loc["A1":"A3", :, ["C1", "C3"]]
pandas.core.indexing.IndexingError: Too many indexers
```

**Comment by jorisvandenbossche** [comment]
I don't think those should behave the same, as that is exactly one of the differences (or reasons) in using `loc(axis=0)`: you know you are only indexing one axis, so you are already past the "interpret the indexer as potentially indexing two axes"-step. 
So to me it is logical there *can* be a difference.

With your example, the thing that should be equivalent is `df.loc[("A1":"A3", :, ["C1", "C3"]), :]` (making it clear how the split up the row and column indexer). But since that is not valid python syntax, we have IndexSlice, so the equivalent is: `df.loc[pd.IndexSlice["A1":"A3", :, ["C1", "C3"]], :]`

**Comment by jbrockmendel** [comment]
That makes sense, thanks.
