### ISSUE TITLE
Add test for MultiIndex Construction with pd.NA

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#31883]
Discovered in #31799

```python
>>> pd.MultiIndex.from_product([np.array([0., np.nan], dtype="object"), ["a", "B"]])
MultiIndex([(0.0, 'a'),
            (0.0, 'B'),
            (nan, 'a'),
            (nan, 'B')],
           )
>>> pd.MultiIndex.from_product([np.array([0., pd.NA], dtype="object"), ["a", "B"]])
*** TypeError: boolean value of NA is ambiguous
```

May be the same root cause as #31881

**Comment by jorisvandenbossche** [comment]
> May be the same root cause as #31881

I think it is rather due to the factorization/hashtable not handling pd.NA, similarly to the creating of a Categorical: https://github.com/pandas-dev/pandas/issues/31927

**Comment by TomAugspurger** [comment]
This was effective fixed by https://github.com/pandas-dev/pandas/pull/31939 and https://github.com/pandas-dev/pandas/pull/31799. #31939 was backported, so this should be working on 1.0.2

I think we have a test for it at https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/multi/test_indexing.py#L412-L414, which is xfailed. Removing that test will give us the coverage we want.

**Comment by WillAyd** [comment]
Thanks for the insights @TomAugspurger. Adding good first issue label as well to see if a new contributor wants to remove the xfail

**Comment by MillanSharma** [comment]
take

**Comment by sumanau7** [comment]
@MillanSharma you are still working on it ?
