### ISSUE TITLE
DOC: Consolidate pages under /docs/getting_started

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#32308]
Another piece of feedback from the CZI EOSS kickoff meeting that @WillAyd and I attended:

In https://pandas.io/docs/getting_started/index.html, we link to the following pages in the left side:

<img width="1429" alt="Screen Shot 2020-02-27 at 11 09 33 AM" src="https://user-images.githubusercontent.com/10647082/75478083-2e779280-5952-11ea-9cf9-d49c308a69f1.png">

We got feedback to:

1. Have a dedicated link to the pandas cheat sheet: https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf
2. Consolidate `Getting started tutorials`, `Tutorials`, and `10 minutes to pandas` (which is linked already in `Tutorials`) into a singular `Tutorials` page

**Comment by WillAyd** [comment]
Also from the home page clicking “Getting Started” in the nav bar will take you to a different target than clicking the “Getting Started” link that shows under the “Getting Started” bullet points on the left hand side of the home page

**Comment by WillAyd** [comment]
Sorry noticed you have above comment of mine already addressed in #32307

**Comment by jorisvandenbossche** [comment]
The current "Tutorials" are mostly (outdated) external tutorials, so I am not sure I would combine it into one of the other pages. Another option could also to rename it to eg "External tutorials" or something like that to make the name clearer. 
What was the concrete idea? To put it as one of the additional pages under "Tutorials" or to put it on a tutorials/index.rst landing page?

I am not fully sure what best to do with the "10min to pandas", personally. 

Good idea about adding a more visible link to the cheatsheet.

BTW, IMO we should also move "Essential basic functionality" and "Intro to data structures" back to the user guide (since those are not written as introductory getting started material)
