### ISSUE TITLE
DOC: `contributing` page isn't rendered properly

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#32732]
As shown below, seems contributing page is not rendered as correctly as other pages.

I am not sure if this is the good place to post this issue, or maybe should I post it on `pydata-bootstrap-sphinx-theme`?

![Screen Shot 2020-03-15 at 7 55 20 PM](https://user-images.githubusercontent.com/9269816/76708437-15633580-66f7-11ea-98b5-b900cc2feac7.png)

**Comment by jorisvandenbossche** [comment]
This is tracked in the theme: https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/issues/118 (and https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/issues/125), and the fix is needed there, not here.  
But let's keep it open for now until it actually fixed (we might want to rebuild the 1.0.2 docs with a fix).

**Comment by jorisvandenbossche** [comment]
Closing, this has been fixed in the theme.
