### ISSUE TITLE
Feature request:  series.fillna('mean')

### ISSUE THREAD

**Issue by bhishanpdl** [pandas-dev/pandas#33030]
I would request pandas devs to implement various nans filling methods.
For example:
- mean
- median
- max
- random forest regressor
so on.

Output:
`df['A'].fillna('mean')`

**Comment by TomAugspurger** [comment]
As proposed, this would create an ambiguity between filling with the mean value, and fliling with the string `'mean'`. I'd prefer to recommend people use `series.fillna(series.mean())`, which doesn't seem much worse to type.

**Comment by bhishanpdl** [comment]
I agree with Tom, but If it was implemented with arguments like:
`method='mean'` or `value='mean'`,
then there would be less ambiguity.

**Comment by TomAugspurger** [comment]
We do have `method='bfill/ffill'` already, but that's a bit different I think. Those are strategies where the fill value isn't a scalar like mean / max. For scalars, passing the scalar value as the `value` works well.

Random Forest is out of scope, since we don't have a RF implementation in pandas.

Thanks for the suggestion, but I think we'll pass.
