### ISSUE TITLE
BUG: DataFrame.mode index dtype is not type stable

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33321]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

The `.index.dtype` is not stable for DataFrame.mode. It depends on whether the DataFrame is empty and possible the dtypes

```python
In [60]: pd.DataFrame([], columns=['a', 'b']).mode().index.dtype
Out[60]: dtype('O')
```

#### Problem description

The index dtype should always be Int64, to match the non-empty case

#### Expected Output

```python
In [61]: pd.DataFrame({"A": ['a']}).mode().index.dtype
Out[61]: dtype('int64')
```

**Comment by gregorylivschitz** [comment]
@TomAugspurger 

This is happening because the empty dataframe returns an empty index and therefore the dtype is dtype('o'):
```
pd.DataFrame([], columns=['a', 'b']).index.dtype
dtype('O')
```

```
pd.DataFrame({"A": ['a']}).index.dtype
dtype('int64')
```

So there are 2 solutions I can think of.
1) We change mode when it's an empty dataframe to return a dataframe where the mode for that is actually NaN.
So go from:
```
pd.DataFrame([], columns=['a', 'b']).mode()
Empty DataFrame
Columns: [a, b]
Index: []
```

To something like:
```
pd.DataFrame([], columns=['a', 'b']).mode()
   a    b      
0  NaN  NaN
```

2) We change what empty dataframe returns when index is called.

Do you like any of those solutions?

**Comment by TomAugspurger** [comment]
We can construct an empty index with the right dtype (int64)

```python
In [5]: pd.DataFrame(columns=['a', 'b'], index=pd.Index([], dtype='int64')).index.dtype
Out[5]: dtype('int64')
```
