### ISSUE TITLE
DEPR: deprecate _data when getting BlockManager

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#33333]
we renamed `_data` -> `_mgr` to provide more clarity on the internals; we should add a `DeprecationWarning` on calling this from the pandas objects (`DataFrame/Series`) to have downstream update to use `_mgr` at some point: https://github.com/pandas-dev/pandas/pull/33054#issuecomment-609948311

**Comment by jorisvandenbossche** [comment]
I personally don't think there is much value in going through a deprecation cycle here. 

We only did this rename to make searching in our code base easier, and not because something is broken or it is a wrong name or something else we are trying to solve, I don't see a reason why we should bother ourselves and downstream packages with a deprecation cycle since it is not "fixing" anything. 

If we wanted to discourage the use of accessing the BlockManager (and at the same time while renaming it would, stipulate that the new name `_mgr` is really private now and shouldn't be accessed), that's something else. But right now we are not changing anything but the name (eg we don't provide an alternative API to get the blocks). So downstream packages, who might have legitimate use cases for getting the blocks, would just add some compatibility code to use the old/new name depending on the version, complicating their code for not much reason?

**Comment by jbrockmendel** [comment]
We did the renaming to make it easier to identify places where we access the BlockManager, but without a deprecation warning it will be easy for uses of `._data` to sneak back in.

w/r/t downstream projects, I think we _do_ want to wean most of them off of accessing the BlockManager.
