### ISSUE TITLE
PERF/DISC: restrict inputs to is_foo_dtype

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#33368]
xref #33364

A lot of the overhead in is_foo_dtype (which we call _a lot_) comes from checking for dtype objects, arrays, and strings.  We could tighten these to be e.g.

```
def is_extension_arrray_dtype(obj):
     return isinstance(obj, ExtensionDtype)
```

The trouble with this is some of these are user-facing, so this would require a deprecation cycle, and in the interim the `warnings` call would actually hurt performance.

**Comment by TomAugspurger** [comment]
> The trouble with this is some of these are user-facing, so this would require a deprecation cycle, and in the interim the warnings call would actually hurt performance.

It'll be a bit of work, but we can define

```
is_extension_array_dtype(obj):
    # flexible stuff...
    # deprecation checks...
    return _is_extension_array_dtype(dtype)
```

And internally we use the strict `_is_extension_array_dtype`. That's probably worth doing regardless of whether we deprecate the flexible stuff, and only accept dtype instances.

**Comment by jbrockmendel** [comment]
> And internally we use the strict `_is_extension_array_dtype`

Makes sense.  Should keep the names public (no underscore, not in the public API), maybe some abbreviation `is_ea_dtype`, `is_dt64_dtype`, ...

**Comment by jorisvandenbossche** [comment]
Big +1 to deprecate passing values instead of dtypes.

I am not sure it needs to hurt performance to include the deprecation? (as long as internally we change all occurrences to call this with a dtype of course).

Right now, we eg have have this function to get the dtype:

https://github.com/pandas-dev/pandas/blob/70086c53b980e8d8db9dc931f7ea52dfd1bcb17c/pandas/core/dtypes/common.py#L1594-L1607

So there is a check to see if the object has a "dtype" attribute. Adding a deprecation warning *inside* that if block shouldn't impact performance when passing dtypes to it?
