### ISSUE TITLE
DEPR: weekofyear

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#33503]
Now that `isocalendar` is available on `Timestamp`, `DatetimeIndex` and the `dt` accessor, `weekofyear` already exists in `isocalendar` and can be deprecated.

**Comment by jorisvandenbossche** [comment]
Is such a deprecation needed? 

Yes, it gives some duplication in functionality, but:

- Those existing attributes have been around for a long time, and people have been happily using them.
- Personally, I think `weekofyear` is more accessible (more logical to think of, easier findable with tab completion) than through `isocalendar`
- `isocalendar` is also doing more work (and thus slower) if all you need is the week number

**Comment by mgmarino** [comment]
I'm ok with not deprecating, but I have a few comments:

- Just because they're used a lot doesn't mean they're used correctly and I would argue that `weekofyear` leads to a lot of hidden issues.  That is, people don't realize that it's the ISO week and might not realize that `year` doesn't always match up with it.  Indeed a quick search through the issues here yields a number of reported "bugs". By deprecating, it becomes harder to mess up: you would force people to actively choose the ISO calendar.  Also, if they need a week with some other definition (starting on e.g. Sunday), then they can use the period functionality to do this.  
- Regarding slowness, if this is an issue than maybe it could be addressed some other way (e.g. caching).

**Comment by jreback** [comment]
perf is a non issue here 

the only issue is cost of deprecation va correctness

eg realize that u r using iso

+1 on actually having an informative api
