### ISSUE TITLE
API: copy(deep=False) -> view?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#33823]
These should behave the same, shouldn't they?  If so, we should use the more standard usage (view).

Ditto for `_shallow_copy()` with no args.

**Comment by jorisvandenbossche** [comment]
About what object are you talking? 
I suppose `Series` or `Index`, since ExtensionArrays don't have a deep keyword (this was removed https://github.com/pandas-dev/pandas/pull/27083). 

For `Series`, based on a quick look, a difference right now is that `copy(deep=False)` reuses the same array object, while `view` always takes a view of the array. 
(not saying this is necessarily a good difference, to be clear, just looking at what potential differences in implementation right now are)

**Comment by jbrockmendel** [comment]
> I suppose Series or Index

Yes.
