### ISSUE TITLE
API: implement ObjectIndex to take place of Index

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#34238]
Then we would never actually return an Index object.

We could then make ABCIndex behave like ABCIndexClass, and get rid of the latter.

Briefly discussed in #34159

**Comment by jorisvandenbossche** [comment]
Are there advantages of this? (except being able to remove the ABC, which alone doesn't warrant such a change IMO)

**Comment by jbrockmendel** [comment]
As mentioned in #34159, there are places in the code where we see an Index object and assume that it is object-dtype.  This would make that assumption more explicit, and would allow #34159 to avoid running into it.

**Comment by TomAugspurger** [comment]
> there are places in the code where we see an Index object and assume that it is object-dtype

@jbrockmendel what do these checks look like? Is it `type(obj) is pd.Index`? Or more like an `isinstance(obj, ABCIndex)`?

IMO, adding an ObjectIndex feels like patching over an internals issue by exposing it to the end user.

**Comment by jbrockmendel** [comment]
> what do these checks look like? Is it type(obj) is pd.Index? Or more like an isinstance(obj, ABCIndex)?

IIRC its more along the lines of methods in Index that are overridden by all extant subclasses assume its object dtype (or just non-EA).

This is mostly relevant in the context of #34159

**Comment by jorisvandenbossche** [comment]
> its more along the lines of methods in Index that are overridden by all extant subclasses assume its object dtype (or just non-EA).

But those places that assume that Index is object dtype would need to be updated anyhow, in context of #34159, or when introducing ObjectIndex ? 
(it might be useful to give a concrete example, because now it's a bit vague discussion)

> IMO, adding an ObjectIndex feels like patching over an internals issue by exposing it to the end user.

+1. And that is also the reason that I would prefer adding EA support in the base Index class instead of a new ExtensionIndex class (certainly given that it would not have dtype-specific methods, like eg DatetimeIndex right now has, there doesn't seem to be much value to have a separate class *for he user*).

**Comment by jbrockmendel** [comment]
> And that is also the reason that I would prefer adding EA support in the base Index class instead of a new ExtensionIndex class

I'm still not wild about that, but we can discuss that separately.  This idea clearly isn't gaining traction, so closing.
