### ISSUE TITLE
pd.set_option("io.excel.xlsx.reader", "openpyxl") does not work

### ISSUE THREAD

**Issue by simonm3** [pandas-dev/pandas#34252]
This works fine for an xlsx file:

`pd.read_excel(path, engine="openpyxl")`

However if i try using set_option then read_excel fails:
```
pd.set_option("io.excel.xlsx.reader", "openpyxl")
pd.read_excel(path)
```
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/blob/c3c4ccf0f6be346534a5df0c73a1d82b594986e3/pandas/io/excel/_base.py#L813-L814 looks buggy. That should probably be taking the engine from the pandas config.

@simonm3 can you look into it?

**Comment by WillAyd** [comment]
Thanks @TomAugspurger for the link. I think there's generally an issue with the reader and respecting options.

Some historical context - maybe a year and a half ago we only had xlrd as a reader, so it was a non-issue. But we've since added openpyxl, pyxlsb, and odfpy as readers, I think without using machinery similar to the writer side for respecting options.

Certainly could some review and improvement if @simonm3 something you are interested in

**Comment by lithomas1** [comment]
take
