### ISSUE TITLE
BUG: No version exists that can be used with Python 3.5 and Python 3.8

### ISSUE THREAD

**Issue by wvxvw** [pandas-dev/pandas#34289]
Since the codebase started using f-strings around version 1.0.0, the only latest version that can be used with Python 3.5 is 0.25.3.

On the other hand, if another package specified dependency as `pandas==0.25.3`, PyPI will not have a pre-compiled Wheel for that (only source distribution). However, compiling those sources fails with modern GCC / CLang and Python 3.8.

Our code must support Python 3.5 because that's what in most currently supported Linux distributions. (eg. Ubuntu 16 LTE). And will have to, at least for a few years.

---

As an aside, I believe f-strings to be a horrible idea, but I cannot force my opinions on you... I'd still wish there was a way to at least remove them from `setup.py`, so that I could install the package using old version of Python (and, hope that I won't hit the code path that uses f-strings when using the library).

**Comment by jreback** [comment]
i am not of the point of this issue. we dropped 3.5 as did the community. you are welcome to fork or support it privately.

**Comment by wvxvw** [comment]
This is super rude... What if I actually wanted to fork, might you at least give some pointers, you know, some commits I'd have to revert to undo this change etc?

Also, what about if I wanted to patch 0.23.5 to get it to work with newer Python. Would you at least care to tell me if you'd accept patches against this version?

I mean, of course you are well aware that no not upstream fork of the library this big is going to survive. So, your "fork it if you need it" is, essentially, a slightly more polite version of "fuck you n00b", but more condescending...

Also, your idea of "community" is... based on what? Are the people who support long-term support Linux distributions are automatically excluded from your "elite" community?

**Comment by jreback** [comment]
@wvxvw the community has moved on from 3.5. We are all volunteers and are not supporting it any longer. As I said (nicely) above, you can do what you want. Even providing help is out of scope for this. We in fact DID provide some support for folks who wanted to continue providing patches for 2.7, but that was not picked up by anyone.

Volunteer projects (pretty much the entire ecosystem) can support what they deem as most appropriate versions. We don't support 2.7 or 3.5. Vendors may do this but is completely out of scope for an open-source non-paid supported project.

> Also, what about if I wanted to patch 0.23.5 to get it to work with newer Python. Would you at least care to tell me if you'd accept patches against this version?

I could tell you how to do this, and I'd even accept a patch, but it would be not very useful because then WE would have to actually release this. That is burdensome and not likely to happen w/o dedicated (paid) support to do this.
