### ISSUE TITLE
ENH: should users be able to adjust subplot parameters?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#34353]
Noticed this while reviewing #34343

Currently, the example in the doc would look like this:
![image](https://user-images.githubusercontent.com/33491632/82753854-0799f280-9dc1-11ea-9675-7716dd75162f.png)

IMO there's insufficient separation between the subplots. If we change [this line](https://github.com/pandas-dev/pandas/blob/cb35d8a938c9222d903482d2f66c62fece5a7aae/pandas/plotting/_matplotlib/boxplot.py#L427) to
```python
        fig.subplots_adjust(bottom=0.15, top=0.9, left=0.1, right=0.9, wspace=0.2, hspace=.5)
```
then this example would look like this
![image](https://user-images.githubusercontent.com/33491632/82754046-44b2b480-9dc2-11ea-97ad-a13b58d0d218.png)

It seems these subplot adjustments aren't adjustable by the user.

So, should the user be allowed to pass in these parameters (e.g. `hspace`), or should the fix here be to just hardcode `hspace=.5` into the line mentioned above, and if users want extra customisability they can use matplotlib directly?

**Comment by charlesdong1991** [comment]
IMO, I think this is a bit out of scope for pandas, otherwise pandas is gonna have so many more kwargs so as to match with matplotlib. Right now it is using those constants which is not optimal i agree, but is enough for a lot of people to quickly get their plots. If users really want to have nice and beautiful plots, they could just use matplotlib to refine the plot.

And regarding this issue, i _think_ (haven't tried out) if using a different/bigger figsize could solve this overlapping issue: e.g. `figsize=(10, 12)`?

**Comment by MarcoGorelli** [comment]
> IMO, I think this is a bit out of scope for pandas, otherwise pandas is gonna have so many more kwargs

True - OK, let's just go with making the figure in that issue larger
