### ISSUE TITLE
BUG: inplace parameter will not perform the operation in place on multi column-sliced DataFrame

### ISSUE THREAD

**Issue by dgun-y** [pandas-dev/pandas#34359]
Environment: Python 3.7.7 / NumPy 1.18.4 / Pandas 1.0.3

I have been testing the `inplace=True` parameters for a couple of functions, including `DataFrame.fillna()` and `DataFrame.clip()`.
When I use the inplace parameter on a multi-column slicing of a DataFrame, it will not alter the original DataFrame.

For instance, using the simple DataFrame below,
```python
df = pd.DataFrame({'A':[1,None,5],'B':[3,4,-1]})
print(df)
Out: 
     A  B
0  1.0  3
1  NaN  4
2  5.0 -1
```
the code
```python
df.loc[:, ['A','B']].fillna(0, inplace=True)
# or df.loc[:, 'A':'B'].fillna(0, inplace=True)
# or df.iloc[:,[0,1]].fillna(0, inplace=True)
# or df.iloc[:,0:2].fillna(0, inplace=True)
print(df)
```
will produce
```python
Out: 
     A  B
0  1.0  3
1  NaN  4
2  5.0 -1
```
as opposed to
```python
Out: 
     A  B
0  1.0  3
1  0.0  4
2  5.0 -1
```
Strangely enough, the parameter works perfectly when I'm slicing out just a single column
```python
df[:, 'A'].fillna(0, inplace=True)
print(df)
Out:
     A  B
0  1.0  3
1  0.0  4
2  5.0 -1
```
or when I'm using the position-based slicing method `.iloc` without specifying the first column
```python
df.iloc[:,:2].fillna(0, inplace=True)
print(df)
Out:
     A  B
0  1.0  3
1  0.0  4
2  5.0 -1
```

Let me know if this is the accepted/expected behavior or if there is a workaround.
Thanks!

**Comment by vampypandya** [comment]
Please let us know all the version details as mentioned in the Github Bug documentation.

**Comment by jorisvandenbossche** [comment]
@dgun-y Currently, selecting multiple columns of a dataframe returns a copy, and not a view (and hence, the inplace is working on a copy, and not filling the original dataframe)

The basic reason is that selecting multiple columns with a list is "fancy" or "advanced" indexing in numpy's terms, which makes a copy (on the other hand, "slicing" gives a view). Now, pandas has some additional complexity due to the BlockManager layout (https://uwekorn.com/2020/05/24/the-one-pandas-internal.html), which makes that even those numpy rules don't always apply for pandas. 

Related issues: https://github.com/pandas-dev/pandas/issues/33780, https://github.com/pandas-dev/pandas/issues/16529

**Comment by dgun-y** [comment]
I suspected as much, thank you for the response.

> Now, pandas has some additional complexity due to the BlockManager layout (https://uwekorn.com/2020/05/24/the-one-pandas-internal.html), which makes that even those numpy rules don't always apply for pandas.

By this, should I assume for the worst in the future, that even slices of single columns may exhibit similar behavior?

**Comment by jorisvandenbossche** [comment]
No, slicing a single column will always be a view, AFAIK

**Comment by dgun-y** [comment]
> No, slicing a single column will always be a view, AFAIK

Got it, thanks!
