### ISSUE TITLE
BUG: Mixed DataFrame with Extension Array incorrect aggregation

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#34520]
Surprised to not get an aggregation for "b" with the Int64 dtype

```python
>>> df = pd.DataFrame([["a", 1]], columns=list("ab"))
>>> df.sum()
a    a
b    1
dtype: object
>>> df.astype({"b": "Int64"}).sum()
a    a
dtype: object
```

**Comment by jorisvandenbossche** [comment]
This is actually a regression on master, as this "worked" until recently:

```
In [6]: df.astype({"b": "Int64"}).sum() 
Out[6]: 
a    a
b    1
dtype: object

In [7]: pd.__version__ 
Out[7]: '1.0.3'
```

There are still many things not correctly working for DataFrame reductions with EA columns, which I am trying to fix in https://github.com/pandas-dev/pandas/pull/32867

Now, the specific regression here is related to `nansum` / maybe to the fact that we now added an `IntegerArray.sum` method:

```
In [8]: pd.core.nanops.nansum(pd.Series(pd.array([1])))
...
ValueError: the 'dtype' parameter is not supported in the pandas implementation of sum()
```

This works in pandas 1.0.3, because we just convert the IntegerArray to a numpy array there, but apparently we stopped doing that. 
That's maybe something to fix on its own, but for the DataFrame reduction, the actual fix is to never call `nansum`, but to call the actual IntegerArray-specific reduction (which is what https://github.com/pandas-dev/pandas/pull/32867 is trying to do)

**Comment by simonjayhawkins** [comment]
This bug only occurs for numeric_only=None, the default.

```
>>>
>>> df.astype({"b": "Int64"}).sum(numeric_only=True)
b    1
dtype: int64
>>>
>>> df.astype({"b": "Int64"}).sum(numeric_only=False)
a    a
b    1
dtype: object
>>>
```

**Comment by simonjayhawkins** [comment]
> This works in pandas 1.0.3, because we just convert the IntegerArray to a numpy array there, but apparently we stopped doing that.

it appears #32950 caused the regression

b8385083b2e6d98638fe7e9ea25ad5065fb97c26 is the first bad commit
commit b8385083b2e6d98638fe7e9ea25ad5065fb97c26
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Mon Mar 30 15:43:04 2020 -0700

    REF: move mixed-dtype frame_apply check outside of _reduce try/except (#32950)
