### ISSUE TITLE
DOC: documentation link to whatsnew v1.0.4 not working

### ISSUE THREAD

**Issue by CloseChoice** [pandas-dev/pandas#34541]
#### Location of the documentation

full whatsnew link on
https://github.com/pandas-dev/pandas/releases/tag/v1.0.4

#### Documentation problem

The link to https://pandas.pydata.org/docs/whatsnew/v1.0.4.html is not working though https://pandas.pydata.org/docs/whatsnew/v1.0.3.html works

**Comment by jorisvandenbossche** [comment]
The whatsnew is already available at https://pandas.pydata.org/pandas-docs/version/1.0.4/whatsnew/v1.0.4.html

There is a problem with updating the "stable" docs at  https://pandas.pydata.org/docs/, so that is still showing the docs from 1.0.3 (see https://github.com/pandas-dev/pandas/issues/33300#issuecomment-636933791)

**Comment by jorisvandenbossche** [comment]
I am going to keep this issue open, and I "pinned" it, in the hope it is more visible (and people don't keep opening new issues for this)

**Comment by TomAugspurger** [comment]
I'll hopefully have time to debug this on Friday.

**Comment by TomAugspurger** [comment]
Fixed now.
