### ISSUE TITLE
DOC/BUG: correlation between series of different lengths

### ISSUE THREAD

**Issue by matanmazor** [pandas-dev/pandas#34602]
Hi,
Is it intentional that pandas does not through an error message when computing a correlation between two series of different lengths?
e.g. pd.Series([1,2,3]).corr(pd.Series([3,2]))
Thanks,
-Matan

**Comment by daskol** [comment]
It seems like proper behaviour. Internally, `pandas` aligns serieses with [.align()][1] method and then uses `numpy` or `scipystats` in order to estimate correlation coefficients. Such behaviour is convinient if serieses have indexes.

I think that docs should be updated with note about series alignment.

[1]: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.align.html#pandas.Series.align

**Comment by vedazeren** [comment]
take

**Comment by jackgoldsmith4** [comment]
`pd.Series([1,2,3]).corr(pd.Series([1,2,3,55]))` returns `1.0` because the 55 is removed after the inner join `align()`. This doesn't seem like correct behavior. Also, the underlying `nancor` method requires both objects to be the same length. Wouldn't it make more sense to tell the user that the objects should be the same length (via an error message) rather than altering the given objects before finding a correlation?

**Comment by jreback** [comment]
this is correct; all pandas operations align

this ticket is about updating the docs to make this even more obvious

**Comment by jackgoldsmith4** [comment]
take
