### ISSUE TITLE
QST: value assignment by using '.loc' with boolean and label indexing

### ISSUE THREAD

**Issue by jaydu1** [pandas-dev/pandas#35204]
- [Yes] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [No] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

To assign values from one column of a dataframe to another column with boolean and label indexing, I found the following code works. But I didn't find any document about it, so I am wondering if this method is proper/safe to use? 
Thanks.

```python
df = pd.DataFrame({'A':np.arange(5),
                 'B':[0,1,0,1,0],
                 'C':-np.ones(5)})
print(df)
df.loc[df['B']==1, 'A'] = df['C']
# Value error if we use 
# df.loc[df['B']==1, 'A'] = -np.ones(5)
print(df)
'''
Output:
   A  B    C
0  0  0 -1.0
1  1  1 -1.0
2  2  0 -1.0
3  3  1 -1.0
4  4  0 -1.0
     A  B    C
0  0.0  0 -1.0
1 -1.0  1 -1.0
2  2.0  0 -1.0
3 -1.0  1 -1.0
4  4.0  0 -1.0
'''
```

**Comment by tomaszps** [comment]
This fits into the standard usage of loc as far as I understand.
`df['B'] == 1` gives a boolean array of the same length as B
'A' is just a column label
So, following the docs [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) you should expect the assignment to happen on column A, wherever df['B'] == 1 is true. Which is exactly what happens.

`# df.loc[df['B']==1, 'A'] = -np.ones(5)` fails because there are only two places where 'B' == 1. The assignment

`df.loc[df['B']==1, 'A'] = df['C']` is only assigning the values from df['C'] for the corresponding labels that .loc is accessing.

**Comment by simonjayhawkins** [comment]
Thanks @jaydu1 for the question. closing as answered by @tomaszps 

> ```python
> # Value error if we use 
> # df.loc[df['B']==1, 'A'] = -np.ones(5)
> ```

to assign values from a NumPy array matching the length of the DataFrame without adding as a column you could use the Series.where method.

```
>>> df = pd.DataFrame({"A": np.arange(5), "B": [0, 1, 0, 1, 0], "C": -np.ones(5)})
>>> df["A"] = df["A"].where(~(df["B"] == 1), -np.ones(5))
>>> df
   A  B    C
0  0  0 -1.0
1 -1  1 -1.0
2  2  0 -1.0
3 -1  1 -1.0
4  4  0 -1.0
>>>
```
although note that the dtype of column A remains int in this case, whereas in the example given, it is cast to float.
