### ISSUE TITLE
nan + nan = 0 when  skipna=True or when groupby().sum()

### ISSUE THREAD

**Issue by raholler** [pandas-dev/pandas#35263]
**Disclaimer**: Not sure whether this is expected behavior. I would have not expected it though and it is always bad in my use cases (survey data).

Example:
```python
data = pd.DataFrame(
    data = {
        "var1": [np.nan, 1000, 2000],
        "var2": [np.nan, 100, np.nan],
        "hh_id" : [1, 2, 2] 
    }
)
```

**Normal sum**
```
data[["var1", "var2"]].sum(axis=1)
```

Expected output:
```
0      np.nan
1    1100.0
2    2000.0
dtype: float64
```

Output:

```
0       0.0
1    1100.0
2    2000.0
dtype: float64
```

**Groupby sum**
```python
data.groupby("hh_id")["var2"].sum()
```

Expected output:
```

hh_id
1      np.nan
2    100.0
Name: var2, dtype: float64


```

Output
```

hh_id
1      0.0
2    100.0
Name: var2, dtype: float64


```

**Comment by jorisvandenbossche** [comment]
See the explanation of the `min_count` argument of `sum`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html?highlight=min_count (this is for DataFrame, but the same is true for groupby's sum)

So, although sometimes surprising depending on your use case, this is the expected behaviour, and can be configured with the `min_count` keyword.
