### ISSUE TITLE
REGR: reindex with sparse data

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#35286]
See discussion at https://github.com/pandas-dev/pandas/pull/34158#issuecomment-636641583 and below. There was some discussion on the PR, but I think we didn't yet create an issue to track this regression.

The PR introduced a regression in `reindex` when having sparse data. Based on the linked discussion, there doesn't seem to direct / easy solution (but I didn't look into it again). So we might want to revert the PR for 1.1 until we figure out a correct solution.

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Thanks for following up. I'll look at this a bit today, and revert if I don't find an easy solution.

**Comment by TomAugspurger** [comment]
I think I'm just going to revert #34158 for now. It looks to have a few issues. Some places in https://github.com/pandas-dev/pandas/blob/492e3e97a01ec5abc1c2f0b0034e62f119b02522/pandas/core/arrays/sparse/array.py#L874-L899 are likely using `self.fill_value` rather than `fill_value` (that's why we get 0s instead of NaNs). A simple change didn't look locally, and I'm not planning to look more today.

**Comment by scottgigante** [comment]
I might have time to take a stab at this in the next couple weeks (but if anyone else feels the urge to give it a go don't wait for me.)
