### ISSUE TITLE
ENH: parse_dates in read_csv should not fail silently

### ISSUE THREAD

**Issue by metazoic** [pandas-dev/pandas#35520]
#### Is your feature request related to a problem?

If `timestamp.csv` contains a malformed timestamp in the column `timestamp`, then
```python
df = pandas.read_csv('timestamp.csv', parse_dates=['timestamp'])
df.timestamp.dtype
```
results in
```
dtype('O')
```
(corroborated in the documentation). Because of the silent fail, every `read_csv()` with `parse_dates` must be followed by a `dtype` check.

#### Describe the solution you'd like

By contrast,
```python
pandas.to_datetime(df.timestamp)
```
results in an explicit error with an informative message:
```python
ParserError: Unknown string format: 11:22:33:44
```

#### API breaking implications

If one performs a `datetime` operation on any `parse_dates` column, then it will error if the column is of `object` type. I'm asking for a more informative error to occur in `read_csv()` instead (just like `to_datetime()`).

#### Describe alternatives you've considered

`to_datetime()` behaves as expected.

**Comment by simonjayhawkins** [comment]
Thanks @metazoic for writing this up (xref https://github.com/pandas-dev/pandas/issues/35430#issuecomment-665559559)

**Comment by phofl** [comment]
I think this would break a lot of code, if we make this strict. Especially because currently it is clearly documented, that the column won't be altered if it can not get converted to datetime-format. Addind another parameter to read_csv isn't desirable either.

**Comment by mroeschke** [comment]
Thanks for the suggestion. Agreed that this has been the behavior for a while, documented, and I think `read_csv`'s goal is just to be flexible in getting data into a `DataFrame`; later validation can be done once the `DataFrame` object has been created.

Since there hasnt been much support for this change from the community and other core devs, going to close, but happy to reopen if theres renewed interest

**Comment by PhilippeFerreiraDeSousa** [comment]
The issue is that the program is either going to crash in the next few lines or return the wrong answer. People are going to sort by date and it will sort with the order on strings or something like that. It will make people waste their time debugging the program instead of telling people where the bug comes from.

In my case I am trying to understand why dates are parsed correctly up to "2262-04-11" and then starts silently giving strings. We are Aug 12th 2021 so the behavior fails silently if the date is exactly 240 years and 8 months over today's date...

```
import pandas
from io import StringIO

parsed_csv = pandas.read_csv(
StringIO('Date\n2262-04-11'), parse_dates=["Date"], infer_datetime_format=True
    )
print(parsed_csv.dtypes)
```

```
Date    datetime64[ns]
dtype: object
```
vs
```
import pandas
from io import StringIO

parsed_csv = pandas.read_csv(
StringIO('Date\n2262-04-12'), parse_dates=["Date"], infer_datetime_format=True
    )
print(parsed_csv.dtypes)
```

```
Date    object
dtype: object
```
So we can make a deal, if you tell me who hardcoded a number in the parser, I say okay fine you can fail silently?

**Comment by phofl** [comment]
Nobody wrote anything in there. This is a numpy dtype. You can read about the Limits at https://numpy.org/doc/stable/reference/arrays.datetime.html#datetime-units
