### ISSUE TITLE
QST: ExtensionDtype with complex arguments

### ISSUE THREAD

**Issue by vnmabus** [pandas-dev/pandas#35541]
#### Question about pandas

I am trying to add support to store columns of functional data in Pandas. This kind of data requires that the associated dtype store some information, such as the discretization points for discretized functions, which is not as simple as the arguments in other ExtensionDtypes (for example, in this case would be a numpy array). This presents several challenges:

- The `ExtensionDtype` will not be hashable unless I take extra steps to make it so, hashing numpy arrays like in the Categorical dtype.
- If the name of the dtype has to include the value of the arguments it would be unreadable.
- `construct_from_string` should have to parse a lot of structured information (maybe possible using `eval`, but what is the point?). I would prefer that my `ExtensionDtype` could not be constructed from a string. However, at least one test require the dtype to be constructable from its name.

What suggestions do you have to solve these kind of problems?

**Comment by jorisvandenbossche** [comment]
I think it is perfectly valid that your extension dtype would not be constructible from a string (in the end, this is also the case for the categorical dtype, where the categories are not added in the string representation). 

Which test is failing? One of the base extension tests? In that case, those tests are general tests that we think are valid in most cases, but for certain specific dtypes, it's certainly possible you will need to skip some of the tests, if it is not a test covering essential functionality.

**Comment by vnmabus** [comment]
The categorical dtype can construct itself from a string (although with categories set to None). This is simply not possible in my case, as the discretization points are needed for everything. Is it legal to not implement `construct_from_string`, or make it return `NotImplemented` or raise `NotImplementedError`?

Yes, the test I was referring to is `test_construct_from_string_own_name`. Is there an easy way to skip it from the test subclass?

**Comment by TomAugspurger** [comment]
You might want to check out SparseDtype's https://github.com/pandas-dev/pandas/blob/53f6b4711092ebfdf9059bd8224714037d4d5794/pandas/core/arrays/sparse/dtype.py#L188.

You can use pytest markers to skip / xfail tests. There are some in https://github.com/pandas-dev/pandas/blob/master/pandas/tests/extension/test_sparse.py.

**Comment by jorisvandenbossche** [comment]
Yes, it's correct that the categorical dtype can construct itself from a string "category", but you get a king of a non-initialized dtype (so you can't *faithfully* construct it from a string). 
The reason we do that for categorical dtype is to ensure that things like `pd.Series(...., dtype="category"`) (categories get inferred from the data, instead of specifying it on the dtype) and `s.dtype == "category"` (just check it is categorical, ignoring the categories) work. So if you are fine with such use cases not working for your data type, I think it is fine to not implement the from-string-construction.

> Yes, the test I was referring to is test_construct_from_string_own_name. Is there an easy way to skip it from the test subclass?

By overriding it in a subclass and re-defining it as a dummy test or adding a skip/xfail. A bit clumsy, but that's how we also do it internally, see eg https://github.com/pandas-dev/pandas/blob/53f6b4711092ebfdf9059bd8224714037d4d5794/pandas/tests/extension/test_period.py#L73-L76

**Comment by vnmabus** [comment]
It seems to work, although unfortunately I had to also skip `test_from_dtype`, because it assumes that the dtype can be specified as a string.
