### ISSUE TITLE
API/DEPR: casting bool-indexer to slice in dt64/td64/period

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#36210]
We use special logic for dt64/td64/period dtypes that makes view/copy behavior different from other dtypes:

```
dti = pd.date_range("2016-01-01", periods=4, tz="US/Pacific")
key = np.array([True, True, False, False])

ser1 = pd.Series(dti._data)
ser2 = pd.Series(range(4))

res1 = ser1[key]
res2 = ser2[key]

>>> res1._values._data.base is None
False
>>> res2._values.base is None
True
```

cc @jorisvandenbossche IIRC you advocated not doing this special casing.

**Comment by jbrockmendel** [comment]
cc @jorisvandenbossche i havent thought of any nice ways to deprecate this (s.t. we can say "do X to get the future behavior, do Y to get the old behavior").  thoughts?

**Comment by jorisvandenbossche** [comment]
Hmm, I also can't think of any way to deprecate this .. 
It could maybe be done within the more general copy/view discussion, but then it's not something on the short term.

I am inclined to say that in this case it might be fine to simply change (because it's a behaviour that only comes up in rare value-dependent cases, and when it happens can lead to silent bugs).

**Comment by jbrockmendel** [comment]
I checked what happened if I remove this behavior: 26 test failures, all about a freq mismatch.

**Comment by jorisvandenbossche** [comment]
Because the slice keeps the freq per definition, and when doing a mask it always looses the freq?

**Comment by jbrockmendel** [comment]
That was my thought too, but when i tried patching get_getitem_freq to account for that it didnt help

**Comment by jbrockmendel** [comment]
update: got it working, was patching incorrectly in one place
