### ISSUE TITLE
BUG: Read_Table and Read_Csv does not raise when delim_whitespace=True and sep=default is given

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#36583]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import io
f = io.StringIO("a  b  c\n1 -2 -3\n4  5   6")
df = pd.read_table(f, sep="\t", delim_whitespace=True)
df = pd.read_csv(f, sep=",", delim_whitespace=True)

```

#### Problem description

Both statement should raise a ``ValueError``

#### Expected Output

``ValueError``

Must also edit docs. See #36560 for discussion.

cc @simonjayhawkins 

#### Output of ``pd.show_versions()``

<details>

master

</details>

**Comment by OlehKSS** [comment]
Hi, does anyone work on this issue? I want to contribute

**Comment by phofl** [comment]
Hi, not as far as I now. Please check the discussion in the PR mentioned above and the related issues before starting

**Comment by OlehKSS** [comment]
take

**Comment by OlehKSS** [comment]
As far as I see, this bug is due to the fact that in both cases the explicitly provided values of separators are equal/identical to their default values. When pandas compares whether a separator/delimiter value was given, it checks it against these default values.  No `ValueError` was raised in both statements because no default value was changed as if no separator was provided explicitly.

One possible solution might be setting all default values to None and assigning their proper values later. In my opinion, it is possibly going to break automatical detection of separators, i.e. if sep is None, the Python parsing engine (not C) will be used to automatically detect the separator.

**Comment by phofl** [comment]
None won‘t work. Please read the discussions in #36381 and #36560. The Solution is already discussed there

**Comment by OlehKSS** [comment]
Based on those discussions I see that you use [lib.no_default](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/lib.pyx#L2332) as a sentinel object. I'll apply it here
