### ISSUE TITLE
CI: move arm64 build to allow_failures for now

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#36601]
https://travis-ci.org/github/pandas-dev/pandas/jobs/729859284

well at least we detected this early. ideally can investigate and fix, but for now need a green CI.

**Comment by jreback** [comment]
cc @pandas-dev/pandas-core

**Comment by bashtage** [comment]
I've seen similar issues in other projects when test detection takes too long, especially on a lower single-threaded performance ARM cpu. Detection doesn't output anything. It would be nice if there was a way to have a small progress par during detection.  I've also noticed that the output updating on non-AMD64 machines is "lumpy" as if it has a large buffer. This can also lead to failures since the runner doesn't know there has been any output even though something (but not enough) is sitting in the buffer.

**Comment by jreback** [comment]
sure - what is troubling is that this was working a few days ago with the same configuration
