### ISSUE TITLE
CI: Deduplicate linting checks

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#36642]
https://github.com/pandas-dev/pandas/pull/36471 added some linting checks (e.g., black, flake8) to a pre-commit workflow which are duplicated in https://github.com/pandas-dev/pandas/blob/master/ci/code_checks.sh. Once we feel good that the pre-commit checks are right we should go ahead and delete them from `code_checks.sh`.

cc @MarcoGorelli

**Comment by rhshadrach** [comment]
I often like to run some of these checks via `code_checks.sh` even before committing, typically black, isort, and flake8. The first two aren't an issue for me since they don't require command line options. However flake8 requires a lot, is there an easy way to manually run flake8 without doing it via code_checks?

**Comment by rhshadrach** [comment]
I should have googled first... `pre-commit run --all-files` works great.
