### ISSUE TITLE
CI: arm Travis build timing out

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#36719]
I'm seeing this in most but not all builds ATM.

Even if we moved it to allowed-failures, it would still be slowing the Travis turnaround time down a lot.

**Comment by jreback** [comment]
can we ping original implementer of arm support (i don't remember the github id)

also might be helpful to run this build more verbosely to see if can nail down where it's hanging

**Comment by TomAugspurger** [comment]
cc @janaknat from https://github.com/MacPython/pandas-wheels/pull/99 and @odidev from the original issue.

**Comment by janaknat** [comment]
@TomAugspurger @jreback It would help if pandas-dev migrated to travis-ci.com from travis-ci.org.

I did a test run on travis-ci.com using Graviton2: https://travis-ci.com/github/janaknat/pandas/jobs/392535745

travis-ci.com offers Graviton2 instances for building/testing in an ARM64 environment. That will speed things up significantly.
See: https://blog.travis-ci.com/2020-09-11-arm-on-aws

**Comment by odidev** [comment]
I have tested this again and there is inconsistency in build timings in arm64 for each build. So, I have tested with arm64-graviton2 in travis-ci.com, and build ran in 25 mins(almost similar to AMD64). 

To run with arm64-graviton2 tests need to be run in travis-ci.com instead of travis-ci.org(which will be officially closed down completely on December 31st, 2020), need to follow steps mentioned by @janaknat in https://github.com/MacPython/pandas-wheels/pull/99#issuecomment-689707765.

**ARM64-Graviton2 build report:** https://travis-ci.com/github/odidev/pandas/jobs/392555700

**Comment by jbrockmendel** [comment]
Disable until this is sorted out?

**Comment by jreback** [comment]
> @TomAugspurger @jreback It would help if pandas-dev migrated to travis-ci.com from travis-ci.org.
> 
> I did a test run on travis-ci.com using Graviton2: https://travis-ci.com/github/janaknat/pandas/jobs/392535745
> 
> travis-ci.com offers Graviton2 instances for building/testing in an ARM64 environment. That will speed things up significantly.
> See: https://blog.travis-ci.com/2020-09-11-arm-on-aws

I don't think we have an objection to migrate (and seems we need to)

what do we need to do?

**Comment by janaknat** [comment]
@jreback documentation for migrating repos: https://docs.travis-ci.com/user/migrate/open-source-repository-migration. It shouldn't be too much of a hassle.

@mattip has done that for the Macpython/scipy-wheels repo.

@mustafa-travisci and @michal-at-travisci can help with more information.

**Comment by mattip** [comment]
I can do the legwork to migrate the repo (under my alias @multibuilder) if the core maintainers sign off on the idea. This would mean they would now need to sign into travis-ci.com rather than travis-ci.org or ask me in order to manage the build settings: set secrets, stop/start specific builds. Automatic triggering would work as before. We recently migrated the scipy-wheel build to travis-ci.com, so this second migration should be easier.

**Comment by jreback** [comment]
cc @fangchenli 

i moved us to travis-ci.com for this one remaining build 

i think if we run it with for test with a number of cores it would be reasonable

**Comment by fangchenli** [comment]
https://github.com/github/roadmap/issues/95 arm64 runner should be available soon.
