### ISSUE TITLE
How to use nrows along with chunksize in read_json()

### ISSUE THREAD

**Issue by madolmo** [pandas-dev/pandas#36791]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

Why do I need to use _nrows_ when reading large json line files with _chunksize_ option?
Since version 1.1 I'm having troubles with the function _read_json()_ because even if I specify the option _chunksize_ with the correct value (the value that used to work with pandas v.1.0.5), the file seems to be read at once, with a memroy error in my case. If I add the _nrows_ option this doesn't happen but why? And what is the value you have to specify for the _nrows_ parameter in order to load the entire file? Do you have to know in advance the maximum number of rows? Is there any special value for "all rows" like -1 o 0 ?

Thanks

```python

#this raises a Memory Error (with a 4GB file) - this worked on version 1.0.5
reader = pd.read_json(f"{path}map_records.json",orient='records' ,lines=True, chunksize=100000)
chunks=[chunk[(chunk.bidbasket=="BSKGEOALL00000000001")&(chunk.tipomappa == "AULTIPMPS_GIT")][['bidsubzona','idoriginale','bidciv','bidbasket','tipomappa']]  for chunk in reader]

#this works, but it loads up to <nrorws> rows and I have to know the maximum number of rows in advance
reader = pd.read_json(f"{path}map_records.json",orient='records' ,lines=True, chunksize=100000, nrows=20000000)
chunks=[chunk[(chunk.bidbasket=="BSKGEOALL00000000001")&(chunk.tipomappa == "AULTIPMPS_GIT")][['bidsubzona','idoriginale','bidciv','bidbasket','tipomappa']]  for chunk in reader]



```

**Comment by alex-warmath** [comment]
Also ran into this problem and it seems like true bug. According to the documentation, your question should be answered that no nrows argument is necessary. Since version 1.1 however, you have to specify nrows or else get a Memory Error. The current workaround seems to be just putting a massive value for nrows, since anything higher than the true value doesn't matter. You don't have to know the number of rows in advance, just an upper bound.

<img width="568" alt="memory error" src="https://user-images.githubusercontent.com/72525471/100555302-838d5f80-3268-11eb-8177-c722617eef1f.PNG">
<img width="563" alt="no memory error" src="https://user-images.githubusercontent.com/72525471/100555303-8425f600-3268-11eb-8d8a-ff4ef9a455d9.PNG">

**Comment by robertwb** [comment]
This is a duplicate with https://github.com/pandas-dev/pandas/issues/34548 which was caused by a bug when implementing nrows. (The workaround is to set nrows to be a very large number.)
