### ISSUE TITLE
REGR: resample apply fails with KeyError/AttributeError for function that works on DataFrame but fails on Series

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#36951]
A resample `apply` accessing a column of the subsetted dataframe fails (bubbling up the error from first trying the function on a single column, i.e. a Series):

```
In [25]: df = pd.DataFrame({"col": range(10)}, index=pd.date_range("2012-01-01", periods=10, freq="20min"))  

In [26]: df.resample("H").apply(lambda group: len(group['col'].unique()))   
...
KeyError: 'col'

In [27]: df.resample("H").apply(lambda group: len(group.col.unique())) 
...
AttributeError: 'Series' object has no attribute 'col'
```

This seems a regression, or was there a deliberate change in `apply` to only apply it on the columns and no longer on the full DataFrame ? 
cc @jbrockmendel

**Comment by jbrockmendel** [comment]
i dont think this was intentional

**Comment by simonjayhawkins** [comment]
The PR to fix this issues fails on the backport. #37305

since this regression is from 0.25.3 to 1.0.0, we could decide not to backport.

the issue is the index frequency is None on 1.1.x here...

https://github.com/pandas-dev/pandas/blob/055651b99160191df9b3ab13f4f7a6370c32685f/pandas/core/resample.py#L375

@jbrockmendel any ideas where changes in master could have corrected this?

**Comment by simonjayhawkins** [comment]
Note: the regression reported here is probably due to #29077

**Comment by simonjayhawkins** [comment]
maybe #35563 is related but that still fails on master
