### ISSUE TITLE
DOC/PERF: Decide how to handle floating point artifacts during rolling calculations

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#37051]
Currently we have a check here that artificially handles a numerical precision issue in `rolling.var` and `rolling.std` where our rolling variance calculation is carrying forward floating point artifacts. Ideally we should be using a more numerically stable algorithm (maybe Kahan summation) so this check isn't so arbitrary. 

https://github.com/pandas-dev/pandas/blob/601eff1768380313ec452ba8677cc7e825706796/pandas/_libs/window/aggregations.pyx#L305

**Comment by ukarroum** [comment]
Would like to try working on that is possible.

**Comment by ukarroum** [comment]
take

**Comment by ukarroum** [comment]
@phofl : It looks like you have a working PR : https://github.com/pandas-dev/pandas/pull/37055 
so i m gonna unassign myself.

**Comment by phofl** [comment]
@ukarroum Not really, my PR fixes problems with large numbers but not the problem mentioned above

**Comment by ukarroum** [comment]
Oh my bad.

Gonna retake it then.

Thanks

**Comment by ukarroum** [comment]
take

**Comment by ukarroum** [comment]
It looks like (from  PR : #37055) using kahan summations don't solve the issue.
couldn't find another way, so i'm just gonna unassign myself.

**Comment by phofl** [comment]
To summarize the current situation:

Theoretically our implementation is stable for small numbers.

Our implementation is not stable for cases like:
```
s = pd.Series([7, 5, 5, 5])
print(s.rolling(3).var())
```

The following explains why:

We are using Welfords Method (https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance) with Kahan summation. In the third add pass through we have the following values: The current ssqdm is ``2.0``
```
prev_mean = 6.0
new_mean = 5 + 2/3
val=6.0
ssqdm=2 + 2/3
```
ssqm is ``2.666666666666667``

The next pass through removes the following:
```
prev_mean = 5.666666666666667
new_mean = 5.0
val=7.0
ssqdm=2.666666666666667 - 2 - 2/3
```
Theoretically this should lead to ``0``, but because of floating point artifacts this leads to ``8.881784197001252e-16``. So without the line in the op, we would not return 0 here. That is the reason why this check is needed.
The implementation can be found at https://github.com/pandas-dev/pandas/blob/125441c5a3cbf28c5fef53127b000dd13d590864/pandas/_libs/window/aggregations.pyx#L290

result:
```
0         NaN
1         NaN
2    1.333333
3    0.000000
dtype: float64
```

**Comment by mroeschke** [comment]
Thanks for the clear explanation @phofl.

Since these floating point artifacts are unavoidable, we can either:

1. Just document that we round values less than `1e-15` to `0` due to floating point artifacts in our `user_guide/window.rst`
2. Actually remove our artificial `if result < 1e-15:` and let floating point artifacts be apart of our implementation and document that.

**Comment by phofl** [comment]
First one? Don't know. Both have their disadvantages unfortunately...

**Comment by mroeschke** [comment]
Yeah I can see that.

I am also entertaining the second option as well and pushing the responsibility of handing floating point artifacts to the user (in the final result but unfortunately not during the rolling calculation)

**Comment by phofl** [comment]
It is pick your poison. In case of the second alternative, we have to adjust the docstring in 
https://github.com/pandas-dev/pandas/blob/7f2a76884554aad79515138fcc524dd63f4f7f70/pandas/core/window/rolling.py#L641
and
https://github.com/pandas-dev/pandas/blob/7f2a76884554aad79515138fcc524dd63f4f7f70/pandas/core/window/rolling.py#L701

My example was based on that. This would cause doctests to fail otherwise

**Comment by xmatthias** [comment]
crossposting from https://github.com/pandas-dev/pandas/issues/39872#issuecomment-785806575 as i'm not sure that issue is followed any longer.


We are encountering a problem while calculating mean (and std) on top of Crypto asset prices (which can become very low numbers (1e-7)).

The release-logs for pandas 1.2 mention this change, however there's no mention of this side-effect to  low value numbers. 

I don't think the below example should be impacted by this - as the expected results are 1e-9 - so nowhere near the mentioned threshold of 1e-14.

A very simple example:

``` python
import pandas as pd

print(pd.__version__)

df = pd.DataFrame(data = {'data':
    [
        0.00000054,
        0.00000053,
        0.00000054,
     ]}
    )

df['mean'] = df['data'].rolling(2).mean()
df['std'] = df['data'].rolling(2).std()
print(df)
```

with pandas < 1.2.0, the return is as follows:

```
1.1.5
           data          mean           std
0  5.400000e-07           NaN           NaN
1  5.300000e-07  5.350000e-07  7.071068e-09
2  5.400000e-07  5.350000e-07  7.071068e-09
```

while 1.2.0 returns:

```
1.2.0
           data          mean  std
0  5.400000e-07           NaN  NaN
1  5.300000e-07  5.350000e-07  0.0
2  5.400000e-07  5.350000e-07  0.0
```

The values are nowhere near the mentioned threshold of 1e-15.

**Comment by phofl** [comment]
The relevant result if the variance, which is used to calculate the std. The variance is e-17, meaning the threshold is met

**Comment by xmatthias** [comment]
you're right, it's the variance that's this low.

I do still see this as a regression bug in Pandas - as the version update from 1.1.5 to 1.2.0 broke the calculation of a calculation that was correct beforehand.

**Comment by bashtage** [comment]
> I do still see this as a regression / bug in Pandas - as the version update from 1.1.5 to 1.2.0 broke the result of a calculation that was correct beforehand.

a hard threshold definitely seems like a bug. It seems that it has to be the case that `df.rolling(3).var()` is the same as `10**10(df/(10**10)).rolling(3).var()` up to some rounding. The threshold should be relative to the previous value I would think (or no threshold at all, which is what NumPy does).
