### ISSUE TITLE
DOC: update PeriodArray docstring

### ISSUE THREAD

**Issue by arw2019** [pandas-dev/pandas#37237]
AFAICT we currently don't have dedicated pages for these methods in the API reference. 

When we add them we also want add links on the `pd.PeriodArray` [page](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.arrays.PeriodArray.html) (and possibly in other places)

**Comment by jorisvandenbossche** [comment]
I think we should actually update the docstring of PeriodArray, because `period_array` is not public. As far as I know, the recommendation would be to either use `pd.period_range(..)` or `pd.array(..)`.

The PeriodIndex docs are listed here: https://pandas.pydata.org/pandas-docs/stable/reference/indexing.html#periodindex
