### ISSUE TITLE
Adding the filename as a Dataframe property

### ISSUE THREAD

**Issue by agcala** [pandas-dev/pandas#37318]
I some complicated programming environments involving Pandas dataframes it would be very useful to be able to recover the dataframe filename from the dataframe object. I am particularly thinking about production environment where the data source would be evolving with time. In such environments being able to recover the underlying filename would be essential to check if the right file is being used.

**Comment by dsaxton** [comment]
You can already attach arbitrary data to a pandas DataFrame: `df.filename = "xyz.csv"`. However this is just Python semantics and relying on it is probably a bad idea. What's the context exactly? To me it seems any guarantees should be built into the general workflow you're using to generate / store the DataFrames, rather than literally in the DataFrames themselves.

**Comment by jorisvandenbossche** [comment]
To attach metadata to a DataFrame, you can now use `attrs`: for example, `df.attrs['filename'] = "xyz.csv"`

**Comment by agcala** [comment]
Well thank you.

Adolph

________________________________
