### ISSUE TITLE
BUG: find_common_type([interval[f8], interval[i8]]) returns object

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#38299]
I would expect it to return interval[f8], analogous to what we'd get with find_common_type([f8, i8])

**Comment by jorisvandenbossche** [comment]
IntervalDtype doesn't have its own specialization of `_get_common_dtype`, so it falls back to the base class implementation, which only looks at exact dtype equality.

So this can be fixed by adding a custom `_get_common_dtype`, and getting the common type of the underlying left/right arrays (the subdtype). 
Now, I am not sure if this would be "better" or expected behaviour or not (not enough actual experience with intervals to judge that)
