### ISSUE TITLE
DEPS: unpin sphinx from doc build

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#38600]
once warnings are fixed in updated sphinx can unpin #38598

**Comment by jreback** [comment]
xref https://github.com/dask/dask/issues/7001

seems 3.4.1 should fix.

**Comment by jorisvandenbossche** [comment]
It's probably not caused by that issue linked there, since the warnings we get is not for methods/attributes that are slots. 
Looking a bit into it, and I think it's caused by https://github.com/sphinx-doc/sphinx/pull/8533. We will have to see if this was intentional change or not on the sphinx side, but for the short term I put up a workaround: https://github.com/pandas-dev/pandas/pull/38657
