### ISSUE TITLE
ENH: concat & merge: return True if left DataFrame is modified

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#38821]
Hi,
This ticket is to propose 2 changes:

1st change: make available `concat` as method of DataFrame (similar to `merge`)
Concat could accept a list of DataFrame, similar to `pd.concat`.

2nd change: whichever `pandas.DataFrame.merge` or (newly implemented) `pandas.DataFrame.concat`
- modify left DataFrame in place
- return a boolean:
   - `True`if left DataFrame has actually been modified
   - `False`if left DataFrame has actually not been modified

Such a feature would prevent the user to make a check `pandas.DataFrame.equals()` to know if the left DataFrame has been modified or not.
Personnally, in my case, the left DataFrame can be a DataFrame I am just reading from a data file, and the right DataFrame, some 'new data' I am thinking it is new and needs to be merged/concatenated to the existing one.

If my merge/concat processing do not result in any change, I will not overwrite the same DataFrame on disk (useless: it has not been modified)

Could this be considered?
Thanks for your help.
Bests

**Comment by mzeitlin11** [comment]
What you want to do here sounds like inspecting the results of a merge - I'd look into the `indicator` argument (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) which tells you about what actually happened in the merge. Inplace operations can be problematic in general, but this in particular would be a massive API change for little benefit - consider the very common case of 
`merged = x.merge(y)` - not modifying the left dataframe `x` is important because what if the user still wants to use `x`?

**Comment by jreback** [comment]
yeah not really sure what you hope to accomplish here. Adding *anything* inplace is -100. Adding api is -1 for me.

**Comment by yohplala** [comment]
Hi, thanks for the tip @mzeitlin11 . I did not know about indicator.
I could also see an informative [related SO](https://stackoverflow.com/questions/49583500/how-to-add-an-indicator-column-for-concat-in-pandas) question for `concat` case.
Ok closing, I think that dealing with indicator is the best way to go.
Thanks again!
