### ISSUE TITLE
BUG: Banklist.html was removed, failure on master

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#38988]
**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

The banklist.html file was removed from "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/
#38987 marked the tests as xfail and removed the userguide entry.

#### Expected

Replace the xfail tests with a new html file url and adjust the userguide appropriately.

**Comment by venaturum** [comment]
Looks like it moved
https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/

That url seems to work with the code in the io guide.

**Comment by jreback** [comment]
apparently this was just moved to a new URI.

**Comment by phofl** [comment]
The URL I posted above is the new one, but the html file is no longer there. It is now stored as a csv file

**Comment by john-sandall** [comment]
The current documentation here is a little confusing as of present: https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#reading-html-content

`Read a URL with no options:` references a new `spam.html` introduced in this commit (https://github.com/pandas-dev/pandas/commit/68db2d26ddb5f95de4254d61b850d3dcaf6ce717) but then immediately below says `Read in the content of the “banklist.html” file` which is confusing.

I suspect this should either:
- Reference `banklist.html` everywhere like in https://github.com/raspbian-packages/pandas/commit/e51b2c11f25c71abafe98679bc95f6af33f5e8cb
- Reference `spam.html` everywhere including in the sections below.

As a sidenote, I use this section for teaching regularly and reading from a url like https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/html/banklist.html is "less real" for students, it looks like (and literally is) test data. The previous example was great because it referenced a real website, people can go to https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/ and see an HTML table in one place, and then the same data in a pandas DataFrame. People _love_ this the first time they do it.

It'd be nice to reference https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/ or otherwise something like https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population for this part of the docs.

**Comment by phofl** [comment]
Could you provide a PR for this?
