### ISSUE TITLE
ENH/SQL: Allow 'dtype' argument in to_sql() to take dictionary including a default datatype

### ISSUE THREAD

**Issue by nabelekt** [pandas-dev/pandas#39013]
Related to #11886

Could we modify the dictionary interpretation in `to_sql()` so that the datatype specified by a key like `'default'` would apply to all other columns not already specified in the dictionary? Or, alternatively, we could break this out to two different arguments: a dictionary for specific columns and a datatype for all the rest?

Instead of choosing between specifying every column having a specific type and using one datatype for all columns, I need a hybrid of the two.

**Comment by jreback** [comment]
-1 we don't do this anywhere else 

just construct a dtype dict yourself

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that pandas tries to promote explicitness, so having a `default` dtype setting would detract from that goal (add maybe overlap with a column with whatever key we would standardize around). Since there hasn't been much support for this functionality from other core developers, closing, but happy to reopen if there's revived interest from the team
