### ISSUE TITLE
CI: add sdist test for PRs

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#39417]
In #38852, we talked about adding CI job to build and test sdist. So we could discover relevant errors sooner. xref https://github.com/pandas-dev/pandas/pull/38852#discussion_r552490251

**Comment by jorisvandenbossche** [comment]
Given the recent problems we had with #41977, #41981 (originally from changes in #38852), it might be good to actually add this as a workflow in our CI. 

@simonjayhawkins if I understand correctly, you have a workflow for this in your fork that you use for testing the release branch (or RC) regularly? If that's the case, it might not be a lot of work for you to move that to the main repo's CI? 
(otherwise, #38852 also temporarily contained such a workflow: https://github.com/pandas-dev/pandas/pull/38852/commits/e3b0cd2930987c68fdbc35c0bee743c667ea984a, or that might actually be the same as yours)

**Comment by jorisvandenbossche** [comment]
Whoops, I only notice now that @fangchenli already opened a PR for it: https://github.com/pandas-dev/pandas/pull/41685

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins if I understand correctly, you have a workflow for this in your fork that you use for testing the release branch (or RC) regularly?

yes it picked up the problems in #41977, but missed the setuptools issue (ignore that the conda-test has been failing for the last week) as setuptools was in the test container and also missed the wheel size issue.

**Comment by simonjayhawkins** [comment]
The wheels still built on pandas-wheels after #41977, an alternative to a ci workflow in pandas, is to build the wheels from the sdist on pandas-wheels instead of the github source, problems would be picked up on the nightly builds, or if a last minute change, before release.
