### ISSUE TITLE
TYP: Mypy failures with new numpy

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#39513]
Mypy raises a lot of errors since the new numpy is available on conda-forge. What is the best approach here? Adding ignores for everything and fixing them step by step afterwards?

cc @simonjayhawkins

**Comment by simonjayhawkins** [comment]
> Adding ignores for everything and fixing them step by step afterwards?

#36092 is basically doing that (needs an update)

in the short term we should just pin numpy on ci and checks while we discuss.

another option could be remove any problematic type annotations from type signature, return types or variable annotations, they are likely incorrect in some cases which is why mypy is reporting errors

https://github.com/pandas-dev/pandas/pull/39067#discussion_r555094196

**Comment by simonjayhawkins** [comment]
#39526 has been backported to get ci green on 1.2.x but that PR changes environment.yaml.

I don't think we want to release with that change, so labelled as blocker for now.

**Comment by simonjayhawkins** [comment]
moving to 1.2.3. will be merging #39641 before 1.2.2 release to avoid blocking.

**Comment by simonjayhawkins** [comment]
> > in the short term we should just pin numpy on ci and checks while we discuss.
> 
> #39526 has been backported to get ci green on 1.2.x but that PR changes environment.yaml.
> 
> I don't think we want to release with that change, so labelled as blocker for now.

#39998 disables checking site packages (i.e. numpy and pytest) so no longer a blocker to 1.2.x releases, have removed the blocker tag, but will want to sort this before 1.3.

**Comment by simonjayhawkins** [comment]
> What is the best approach here? Adding ignores for everything and fixing them step by step afterwards?

merge that so will close this issue and open a new issue for the fix-up
