### ISSUE TITLE
QST: Publish my personal modification of the official pandas cheat sheet

### ISSUE THREAD

**Issue by OliEfr** [pandas-dev/pandas#39724]
Hi all,

I found that the official cheat sheet could be optimized a bit.

I created my personalized version of the pandas cheat sheet and published it on my github [here](https://github.com/OliEfr/pandas_cheat_sheet).

Is this alright? I mentioned all sources and inspireations and chose the same license.

If you like the sheet, I can create a PR.

Let my know if I violate any license rights or if you feel uncomfortable with me publishing this.

**Comment by rhshadrach** [comment]
One of the things I noticed is that yours contains links to the documents, which I think is a great addition. I'm +1 here.

The other changes I see are swapping out sections for new ones, and some minor refactoring of sections that doesn't add/remove content. These seem to be of more questionable value to me in that there are pros and cons.

My recommendation would be to detail the major changes here so that they can be discussed, and put up a PR for (a) links and (b) any edits that correct or clarify the presentation (these are non-controversial).

**Comment by OliEfr** [comment]
I actually figured the thing with the links as well - that's why I created a seperate PR for them and this was merger already (so that would be (a)) :)

Yes, the other changes are more controversial. I'll keep validating my changes for myselft for now and will create a PR later :)
