### ISSUE TITLE
ENH: reverse like parameter for DataFrame.filter() method

### ISSUE THREAD

**Issue by sroener** [pandas-dev/pandas#39773]
#### Is your feature request related to a problem?

I am able to filter columns of dataframes by using `df.filter(like="COLUMNNAME",axis=1)` and I would like to do the reverse, excluding these columns.

#### Describe the solution you'd like

I think a possible solution would be the implementation of a not_like argument. Alternatively, an operator similar to `~` in the `.loc[]` method.

#### API breaking implications

-

#### Describe alternatives you've considered

The alternative for achieving this goal is either using ´.filter()´ with an appropriate regex or using ´.loc[:,~df.columns.str.contains("COLUMNNAME")´. Both methods are feasible, but either more complicated or less readable than the proposed method.

**Comment by rhshadrach** [comment]
Filter takes a regex argument, does this suit your needs?

**Comment by mroeschke** [comment]
Agreed, that the regex argument provides the most flexible and generic version of `not_like` in this case, so I would be -1 on adding a new parameter to this function. Ideally, pandas should avoid having multiple ways of performing similar operations as possible.

Since there hasn't been much support for this feature from the core team or community, going to close, but happy to reopen if there is revived interest.

**Comment by marcuslehr** [comment]
How about adding a regex argument to .drop()? Figuring out how to negate strings in regex is a PITA and hard to remember. Otherwise you have to do some insanity like `df.drop(columns=df.filter(regex='string i don't want').columns)`. In addition to being uncouth, this syntax does not lend itself to method chaining. New syntax would be `df.drop(regex='string i don't want', axis=1)`

**Comment by rhshadrach** [comment]
@marcuslehr - can you open a new issue.
