### ISSUE TITLE
API: decide what to return from plotting functions

### ISSUE THREAD

**Issue by cpcloud** [pandas-dev/pandas#4020]
most plotting functions return an `Artist` instance whereas a few return something else. for example, `boxplot` returns a `dict` and `scatter` returns a `tuple`. they should at least return a `matplotlib.artist.Artist` subclass (usually either a `Figure` or `Axes`) or an array of `Artist`s.

this has been brought up before but it would be nice to make a decision here.

[mailing list thread](https://groups.google.com/d/topic/pystatsmodels/biNlCvJPNNY/discussion) and #3474.

**Comment by tacaswell** [comment]
[disclaimer, speaking for my self, not mpl here]

It is better to return the `Artist` objects added to the plot rather than the `Axes`.  If the artists are not returned it is impossible (fine, very difficult and unreliable) to tell what the artists associated with your data is which makes doing anything interactive with the artists later impossible. For example, wanting to toggle the lines from a given column of a data frame on/off by clicking on it.  If the end-user has the `Line2D` objects drawn this is very easy (just register on on-click call back which inverts the visible property).

If the user did not pass in an `Axes` object, then they can get to the axes through `plt.gca()` or just using the pyplot api.  If the user passed in `ax` as an argument they already have a reference to it and don't need it back.  All artists also have an `ax` property which is the axes they are currently associated with.

Returning artists from plotting commands would also bring the pandas API in line with the upstream mpl api.

I would also advocate moving all of the pandas plotting methods to be functions in a top level module with signatures like `artists = pd.plot.lines(ax, df, style_kwargs)` or `arts = pd.plot.bar(ax, df, style_kwargs)`

All of these changes will make it easier to (eventually) move pandas aware plotting to an mpl umbrella organization project.
