### ISSUE TITLE
ENH: pandas.read_json Add skip error line

### ISSUE THREAD

**Issue by iwantmyway** [pandas-dev/pandas#40273]
It will be great if pandas.read_json have skip error line like pandas.read_csv do.

**Comment by ParfaitG** [comment]
Can you post an example? [JSON](https://www.json.org/json-en.html) follows industry formatting [standards](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/). Hence a problematic line would not make it valid JSON. And allowing invalid json text in `pandas.read_json` can raise many side effects. Arguably, too, with the key/value mapping construct of JSON, lines are not the same connotation as CSV lines since skipping can disrupt the serialization. A whole JSON doc can be on one line!

**Comment by MarcoGorelli** [comment]
closing, will reopen if you address the above

**Comment by TLeitzbach** [comment]
@MarcoGorelli I believe the functionality which the OP requested is described by the [SO question](https://stackoverflow.com/questions/78648426/skip-lines-with-json-document-that-cause-valueerror-unexpected-character-found) I just asked. 
Let me know if you would like to elaborate on the example there.
