### ISSUE TITLE
BUG: Clearing a `Styler` should clear all

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#40484]
Currently `Styler.clear()` will clear the styles built up with the `apply` `aaplymap` and `where` method. It will clear class from the `set_td_classes` method and it will clear tooltips set with `set_tooltips`.

It does not clear table styles, and it does not clear formats. It does not reset hidden index or hidden columns.

Thoughts and PR into what this should do and how it should it be documented, as well consistency with `Styler.copy` are welcome..

**Comment by bsun94** [comment]
hi there, I'm still new around here, but would like to help take on this issue. I'd love to help look into the issue more - would you mind pointing me to the relevant section of the code base to start taking a look?

**Comment by attack68** [comment]
All items relating to `Styler` are in `pandas/io/formats/style.py` - there you will find the discussed class methods.
Tests are in `pandas/tests/io/formats/style/..`

**Comment by bsun94** [comment]
thank you!

**Comment by bsun94** [comment]
I took a look at the module, I think changing the state of the `self.hidden_index` and `self.hidden_columns` attributes in the `clear()`, `apply()`, etc. methods is relatively straightforward - changing the values back to their `__init__()` defaults in the `clear()` and adding lambda expressions in the `self._todo` for the others.

Resetting the `self.table_styles` may depend - if we just want to "reset" it to an empty list every time, then that's also straightforward. But if we'd want to reset it back to whatever the user may have input into the `__init__()`, then we may need a second init variable to store that initial state, to refer back to. Which approach would be preferred here?

**Comment by attack68** [comment]
I think go with the most straight forward option initially, which is a good first step, and defer the decision about replicating the `__init__` state until after, personally I probably just prefer clearing to default `None`, rather than back to the `__init__` state.

I think clearing `hidden_columns`, `hidden_index`, `_todo`, `ctx` `cell_context` `Tooltips` and `format` `table_styles` back to (empty) default are all probably necessary

**Comment by bsun94** [comment]
Thanks attack, I've updated the `clear` to include `_todo`, `hidden_index`, `hidden_columns` and `tooltips`. Since both `format` and `table_styles` are dependant upon parameters that the user may input into the `__init__`, I've left those out for now. I'll try to write some tests for these as a next step before pushing.

As for #22851 referenced here, from what I can tell at least, exporting styles entirely rely on what's included in `_todo`, which is only executed in the `_compute` method. One solution I can think of is 1) append to `_todo` in each of the styling methods e.g. `hide_index`, but using a differently-lengthed tuple and 2) repurposing the for loop in `_compute` to use `_apply` and `_applymap` as it currently does if the `_todo` tuple in the current iteration has len = 3, else assume the tuple indicates an instance state change (from one of the above styling methods) and simply alter the value of the indicated instance variable.

**Comment by attack68** [comment]
> As for #22851 referenced here, from what I can tell at least, exporting styles entirely rely on what's included in _todo, which is only executed in the _compute method. One solution I can think of is 1) append to _todo in each of the styling methods e.g. hide_index, but using a differently-lengthed tuple and 2) repurposing the for loop in _compute to use _apply and _applymap as it currently does if the _todo tuple in the current iteration has len = 3, else assume the tuple indicates an instance state change (from one of the above styling methods) and simply alter the value of the indicated instance variable.

I don't really understand. If the goal is to get `export` extended to include exporting the hidden index parameter then it is a simply a matter of changing both the `use` and `export` functions to be compatible.

Currently:

```
def export:
    return self._todo

def use:
    self._todo.extend(input)
```

Just export something else: like a dict: `{'todo': self._todo, 'hidden_index': self.hidden_index}`
And just read it in use:
```

def use:
    if input['hidden_index']:
        ...
    etc.
```

I don't think you want to tinker with the apply and _compute mechanics just to get export to work.

**Comment by attack68** [comment]
Im going to link this to #40675
