### ISSUE TITLE
pandas series append will lost original name if new series name is different

### ISSUE THREAD

**Issue by randomseed42** [pandas-dev/pandas#40936]
#### Question about pandas

pandas series append will lost original name if new series name is different, probably can improve by adding an arg like retain_name=True?

```python
# Your code here, if applicable
s1 = pd.Series([1,2,3], name='A')
s2 = pd.Series([4,5,6], name='B')
s3 = pd.Series([7,8,9])
s4 = pd.Series([10,11,12], name='A')
print(s1.append(s2).name)
print(s1.append(s3).name)
print(s1.append(s4).name)
```

**Comment by mzeitlin11** [comment]
Thanks for the report @randomseed42! This is one reason why using `concat` is suggested instead of `append` - `append` makes it seem like anything you append is just being added to that existing series, but it's really just a wrapper to creation of a new series as `concat((s1, s2))` (which is why the name is lost, since `concat` doesn't know which name to prefer).

That being said, I think retaining the name of the series the method is applied to makes sense, and could be patched relatively simply (I think) by replacing 

```
return concat(
            to_concat, ignore_index=ignore_index, verify_integrity=verify_integrity
        )
```
with 
```
return concat(
            to_concat, ignore_index=ignore_index, verify_integrity=verify_integrity
        ).__finalize__(self)
```
here https://github.com/pandas-dev/pandas/blob/84d9c5ed7965b3cc667b5a3a61d5911b1748af49/pandas/core/series.py#L2845

**Comment by joonlimeecs** [comment]
Hi I'm new here, am I allowed to contribute on this issue?

**Comment by mzeitlin11** [comment]
Sure, that would be awesome! I'll assign you now

**Comment by randomseed42** [comment]
Thank you 😄 @mzeitlin11 @joonlimeecs
