### ISSUE TITLE
QST: Only the first 100 columns are suggested in tab completion

### ISSUE THREAD

**Issue by TheDerivator** [pandas-dev/pandas#40938]
The [:100] in the following code implies that tab completion which relies on dir( ) will only consider the first 100 columns.

- Is there a reason for the magic number? Why not remove it?
- Alternatively, make it optional with something like pd.set_option('display.max_dir_items', None)?

Which is better?

https://github.com/pandas-dev/pandas/blob/88df92f221a6f7634a825125a54937f1ad01b919/pandas/core/indexes/base.py#L760

**Comment by mzeitlin11** [comment]
Thanks for the report @TheDerivator! This issue has come up a few times (the reason for the magic number is performance-related). I agree that something like an option might make more sense - if you have interest in improving this, let's move the discussion to #37996, since it contains a few of the issues and comments that provide some more context
