### ISSUE TITLE
API: Should isna return a copy for nullable types?

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#40935]
This came up in #40651, seems worth resolving.  Right now `BaseMaskedArray` just directly returns `self._mask` in the implementation of `isna`. This could lead to some unintuitive user-facing behavior like:
```
>>> ser = pd.Series([1, 1, 1], dtype="Int64")
>>> mask = ser.isna()
>>> mask[:] = True
>>> ser
0    <NA>
1    <NA>
2    <NA>
dtype: Int64
```
Seems like `isna` should return a copy instead to avoid this. One potential downside is losing an API-supported way to obtain 0-cost access to the mask (xref #34873).

**Comment by jreback** [comment]
yeah this should return a copy

aside from that we could implement public methods that provide access with 0 copy

**Comment by jbrockmendel** [comment]
could do a readonly view

**Comment by mzeitlin11** [comment]
Readonly view seems like a good solution, only concern would be the inconsistency of
```
In [1]: import pandas as pd

In [2]: ser = pd.Series([1, 1])

In [3]: mask = ser.isna()

In [4]: mask[:] = True

In [5]: ser = pd.Series([1, 1], dtype="Int64")

In [6]: mask = ser.isna()

In [7]: mask[:] = True   # raises, ValueError: assignment destination is read-only
```
Are readonly views returned anywhere else? Copy-on-write view would be nice, but don't think that's easy w numpy.

**Comment by jorisvandenbossche** [comment]
Let's leave possible read-only / copy-on-write optimizations for later. The fact that it right now doesn't return a copy is simply a bug. Modifying the resulting array shouldn't modify the original.

BTW another question here is whether `isna()` shouldn't rather return a nullable boolean array instead of a numpy array (I know that the result of `isna()` will never have missing elements by definition, but still we typically return new nullable arrays from methods on nullable arrays, except for where there is an explicit conversion to numpy).
