### ISSUE TITLE
DOC: Improve describe() doc in getting started

### ISSUE THREAD

**Issue by NicoLoco** [pandas-dev/pandas#40972]
In the "getting started tutorial" here: https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html

The following sentence is incorrect
Many pandas operations return a DataFrame or a Series. The describe() method is an example of a pandas operation returning a pandas **Series**.

It should say "The describe() method is an example of a pandas operation returning a pandas **DataFrame**"

Steps to reproduce
>>> import pandas as pd
>>> df = pd.DataFrame({
... "Name" : ["Ally", "Bob", "Charly"],
... "Age" : [15,25,36],
... "Cash": [1000,5000, 20000]});
>>> d = df.describe()
>>> type(d)
<class 'pandas.core.frame.DataFrame'>

**Comment by mzeitlin11** [comment]
Thanks for the report @NicoLoco! Could you please edit your issue title to reflect the content? 

Agreed that this is wrong, though it's not quite so clear because `describe` can return a `Series` if applied to a `Series`. Clarification would certainly be helpful here since in the example usage the result is a `DataFrame`, not a `Series`.

**Comment by Bharat123rox** [comment]
take
