### ISSUE TITLE
WEB: Remove https://pandas-docs.github.io/pandas-docs-travis/ ?

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#41050]
https://pandas-docs.github.io/pandas-docs-travis/ looks to be stuck on a 0.25 develop branch. Is there any reason to keep it around when we also have https://pandas.pydata.org/pandas-docs/stable/index.html?

**Comment by jorisvandenbossche** [comment]
The equivalent is now https://pandas.pydata.org/pandas-docs/dev/index.html? ("dev" and not "stable", the pandas-docs github pages were previously used to host the latest master docs)  
But indeed, now we have the dev docs on the main pandas.pydata.org website, we should retire/remove those old github pages. 

Would it be useful to first still have a redirect? (I don't know how many links are out there using this URL ..)

I seem to have the access rights to delete https://github.com/pandas-docs/pandas-docs-travis, so I can do that.

**Comment by mroeschke** [comment]
Thanks for the clarification. A redirect would be user friendly I suppose but I would be +1 for just removing this repo and link outright.

**Comment by datapythonista** [comment]
I did a grep, and I could only find one link to the url you mention, in the README file I'm deleting here: #41735

I guess all inks to that url in the web were already replaced, so closing this. Feel free to reopen if I'm wrong @mroeschke 

@jorisvandenbossche +1 on removing that repo (I'd delete the whole `pandas-docs` organization, since there is nothing else. I don't have permission to that organization, but I created #41736 so we have an issue for it.

**Comment by jorisvandenbossche** [comment]
> I guess all inks to that url in the web were already replaced, so closing this.

I suppose you mean URLs on our own website? Because there certainly are links to it "out there" on the web. For example checking on stackoverflow: https://stackoverflow.com/search?q=https%3A%2F%2Fpandas-docs.github.io%2Fpandas-docs-travis%2F

Now, of course, if we never remove that, it will also never get fixed, so that's not necessarily a reason to keep the docs alive. 
But changing it to redirect to the correct URL for a while first would still be helpful I think?

**Comment by datapythonista** [comment]
Sorry, not sure why I thought this was about removing links in our website, not about removing the github pages themselves.

We're not talking about a single page, but about a whole mirror of our docs if I understand correctly. Replacing each page by a redirect one seems a lot of work, for in my opinion, zero benefit, if these links won't likely be fixed, and we'll eventually delete the whole site.

Up to you. But I've got better things to do than all that work for the redirects and I'm sure you too. So, since I doubt anyone will, and having a 2 year old copy of the docs may be more harmful than the broken links, I'd simply delete that repo now, and assume that if users are smart enough to use pandas, they'll be smart enough to quickly find the right page. :)

**Comment by jorisvandenbossche** [comment]
Yeah, I didn't necessarily think about the practical details when mentioning the "redirect" option .. ;)

As you say, you probably need to have each page be replaced by its own redirect, and you can't have a "global" redirect at the root level? (I suppose that's not how surfing HTML webpages works ..)

**Comment by datapythonista** [comment]
If it was our own server we could do what you say via nginx. But that's Github pages, so html is the only option, and each page is independent, if we just redirect the root, that won't be triggered for any other path.

Otherwise a single html redirect would be trivial, and I had it ready with less time than writing this comment. ;)

**Comment by mroeschke** [comment]
Thanks @jreback for disabling this site. Closing
