### ISSUE TITLE
VTKF files in pandas?

### ISSUE THREAD

**Issue by gmmfarrow** [pandas-dev/pandas#41080]
Hi there,

I'm a huge fan on pandas, but I primarily use vtkf files (.vti mostly) and analyse them in Paraview. I hate paraview, and would much rather use pandas, so was wondering if there's any way to include the capabilities of something like vtkf explorer within pandas to allow people to read in vtk files as dataframes

**Comment by attack68** [comment]
I do not believe this is currently available.

Also, as an opinion, I suspect that this kind of functionality is extensive enough to be considered its own package, i.e. say pandas-vtk, whose sole objective would be to convert both ways.

The different formats of vtk files, as described here: https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf, are complex enough that a reasonable amount of unit tests and consideration into how best to represent the data (for each structure type) should be made - it may not be obvious which way is the best for different cases.

**Comment by mroeschke** [comment]
Agreed, I have personally never heard of this file format, but I believe with a variable format specification is best for a specialized library to handle parsing such that pandas can import a structured result. Closing since this enhancement request hasn't gotten much support from the core team and community .
