### ISSUE TITLE
ENH: read_sql_table for views

### ISSUE THREAD

**Issue by frafra** [pandas-dev/pandas#41094]
#### Is your feature request related to a problem?

I cannot create DataFrames based on SQL view tables:

```
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(...) schema 'ml_dataset': (dataset)
```

#### Describe the solution you'd like

It would be great to be able to read views. `SELECT * FROM table;` does not behave differently if `table` is a table, a view, a materialized view or a foreign table.

#### API breaking implications

No backward compatible changes.

#### Describe alternatives you've considered

Instead of extending `read_sql_table` a new function could be created, like `read_sql_view`

#### Additional context

Workaround:

```python

df = pandas.read_sql_query("select * from sampletable", viltkamera_postgres)
```

**Comment by frafra** [comment]
Sorry @mzeitlin11, I forgot to set a title :)

There is nothing wrong in the workaround, but I could argue that even `read_sql_table` could be considered just a nice addition. Having different ways to handle tables, depending on their kind, makes me pushing toward writing only SQL queries, making `read_sql_table` less useful.

**Comment by mzeitlin11** [comment]
> but I could argue that even `read_sql_table` could be considered just a nice addition. 

Agreed :)

I like the `read_sql` query solution because it works generally for both tables and views, so you wouldn't have to worry about separately dispatching to `read_sql_table` or `read_sql_view` depending on what the data is. 

pandas has a very high bar for adding new API because the API is so large already, so I would hesitate to add a view specific function. I do wonder though how difficult it would be for `read_sql_table` to figure out that what you're requesting is a view and handle that accordingly. At the very least, if `read_sql_table` raises on views, that should be documented

**Comment by mroeschke** [comment]
Agreed that I don't think this warrants a whole API functionality since the workaround is idiomatic. Thanks for the suggestion but closing since this hasn't gotten much support from the team, but happy to reopen if there is revived interest

**Comment by AndreaFanta** [comment]
Hi, in version pandas 1.3.4 read_sql_table works also for views while in version pandas 1.4.2 it works only for tables.
Anybody knows why latter version changed this way?
