### ISSUE TITLE
DEPS: remove distutils

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#41199]
distutils is deprecated in Python 3.10, it will be removed in 3.12. 

https://www.python.org/dev/peps/pep-0632/ has a section about migration.

xref #41113

**Comment by jorisvandenbossche** [comment]
We mostly use distutils for its version checking, and the alternative for that is `packaging`. That's however not a standard library module, but an external package that would either need to be added as a dependency, or otherwise be vendored (just the `packaging.version` submodule, which is only a few hundred lines of python code)

**Comment by bashtage** [comment]
What is the rush?  Won't there will be a Python-provided equivalent of LooseVersion before distutils is removed?
