### ISSUE TITLE
ENH: Indexes with any numpy int/uint/float dtype

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#41272]
I've made a (draft) PR in #41153 that implements an index class for all the normal numpy numeric dtypes (int64/32/16/8, uint64/32/16/8 an dfloat65/32). There was some discussion in that PR how the public API for this should be, so I'm opening this issue for discussing that.

My plan is to get #41153 merged when its ready, possibly without any public-facing API changes. The public-facing changes would then come afterwards, and after there is an conclusion on how the API should be.

## Summary of the options

As I see it the options for the API is:

|Nr.|Option | Is backwards compat. | complexity |
--- |--- | --- | ---
|1.| Have a single, public `NumericIndex` class for all numeric index types | Yes | Easy |
|2.|Have dtype-specific subclasses (`Int8Index`, `Int16Index`, `Int32Index`, etc), and those can still be backed by a single internal `NumIndex` |Yes|Easy|
|3.| Use the existing, general-purpose `Index` class for these numeric numpy dtypes | No | Harder |
|4.| Use the existing, numeric  index classes for these numeric numpy dtypes, so e.g. `Int64Index` can take int32 etc. | No | Easy |

Options 1. and 3. would mean that the existing `Int64Index`, `UInt64Index` and `Float64Index` would be deprecated and removed in pandas 2.0, because their functionality would bw covered by the other index classes.

Option 2. would increase the number of numeric index classes.

Options 4. would extend the functionality of the existing numeric index classes.

So there are quite a few possibilities. Hopefully we can come to a common conclusion.

@pandas-dev/pandas-core

**Comment by topper-123** [comment]
My opionin:

The current index types are very ingrained in pandas, and I think we should prioritize backwards compatibility in pandas 1.x, even at the possible cost of having a worse API short-term. The "optimal" API could then be implemented for pandas 2.0.

In that light I would prefer different short-term and long-term choices:

Short-term: Implement a seperate `NumericIndex`, i.e. keeping `Int64Index` etc. working unchanged, but deprecate them in due time for pandas 2.0.
Long-term: For pandas 2.0, integrate the numeric indexes into the base `Index` and removing `Int64Index`, `NumericIndex` etc.

I think new index classes should only be implemented for differing API and there will not be API differences between working on the various indexes with different numpy numeric dtypes. So having a index class for each dtype subtype is IMO excessive, and in e.g. in `Float32Index(..., dtype="float32")`  the dtype parameter would be superflous and doesn't add value to the API because the dtype is encoded in the index class.

**Comment by toobaz** [comment]
> Short-term: Implement a seperate `NumericIndex`, i.e. keeping `Int64Index` etc. working unchanged, but deprecate them in due time for pandas 2.0.

I agree, with the existing numeric indexes being actually implemented as `NumericIndex`



>  Long-term: For pandas 2.0, integrate the numeric indexes into the base `Index` and removing `Int64Index`, `NumericIndex` etc.

I still fail to see why e.g. `NumericIndex` should be integrated inside `Index` but not `RangeIndex`, `IntervalIndex`... maybe there is a clear (and easily documentable) API distinction... but I'm failing to see it, and hence I don't like this idea. Sure, one could argue that `IntervalIndex` is different because its elements are (in some sense) "not scalar", but already the distinction with `RangeIndex` is more in terms of implementation... and what about strings?!

In general, while I understand that aggregating in `Index` more functionalities allows to clean the API, i think it's not a consistent approach in particular now that types and implementations are becoming more modular. What about alternative (even third-party) indexes that store numbers in different ways (like EA for values)? What becomes the rule of "what `Index` does?" if it's not just about `object`, nor about "indexing with numbers" (`RangeIndex` does too and possibly more in the future)?

**Comment by jbrockmendel** [comment]
> Use the existing, numeric index classes for these numeric numpy dtypes, so e.g. Int64Index can take int32 etc.

My kneejerk reaction is very negative on the idea of Int64Index holding anything other than int64.

> Use the existing, general-purpose Index class for these numeric numpy dtypes

In 2.0, if we could get combine all Index subclasses back into Index, that'd be pretty neat.  Failing that, having only a handful of dtypes return the base class seems klunky.

> Have dtype-specific subclasses (Int8Index, Int16Index, Int32Index, etc), and those can still be backed by a single internal NumIndex

The proliferation of classes is unfortunate, but this is the most straightforward option.

> Have a single, public NumericIndex class for all numeric index types

I'd be fine with this.

**Comment by jorisvandenbossche** [comment]
> I still fail to see why e.g. `NumericIndex` should be integrated inside `Index` but not `RangeIndex`, `IntervalIndex`... maybe there is a clear (and easily documentable) API distinction... but I'm failing to see it

@toobaz there is indeed a very clear API distinction between `Index` and `IntervalIndex`: `IntervalIndex` has *additional* public methods and properties compared the base `Index` class, and it wouldn't make sense to add those interval-specific methods and properties to the base class.  
The different numeric Index classes (`Int64Index`, `UInt64Index`, `Float64Index`) have no such API distinction with the base Index class. So basically swapping NumericIndex with Index doesn't have any user-visible impact, *except* for the repr being `"Index([..., dtype='int64')"` instead of `"NumericIndex([...], dtype='int64')"`.

> What about alternative (even third-party) indexes that store numbers in different ways (like EA for values)?

IMO that's actually a good reason to use the base `Index` class for other dtypes than just object dtype. That way, a third-party EA can actually be used as Index using the `Index` class (currently this is not possible, and we convert the EA to a numpy array when storing it in the index)

**Comment by toobaz** [comment]
> @toobaz there is indeed a very clear API distinction between `Index` and `IntervalIndex`: `IntervalIndex` has _additional_ public methods and properties compared the base `Index` class, and it wouldn't make sense to add those interval-specific methods and properties to the base class.

You have a point, and one that in principle is also easy to document ("it's a separate class iff it provides additional methods").

I'm a bit afraid (in terms of implementation, but also of users expectations) of deciding that whether a given type/storage mechanism is supported by ``Index`` has _nothing_ to do with the code actually implementing it below the surface. But it's true that as long as we state that any type/storage mechanism will be supported only via EA, it's just a matter of supporting EA.

> a third-party EA can actually be used as Index using the `Index` class (currently this is not possible, and we convert the EA to a numpy array when storing it in the index)

I'm a bit confused by what ``pd.core.indexes.extension.ExtensionIndex`` is for. Isn't it able to keep the EA as such?

Notice that if ``Index`` will need to support EA, some ``Index`` subclasses might also have to (think about an EA providing an alternative implementation of datetimes, or intervals). But maybe this is not too difficult by doing inheritance right.

**Comment by jorisvandenbossche** [comment]
> I'm a bit confused by what `pd.core.indexes.extension.ExtensionIndex` is for. Isn't it able to keep the EA as such?

It's (currently) only meant as a base class for a few of our own existing Index subclasses that are backed by an ExtensionArray (i.e. CategoricalIndex, IntervalIndex, Datetime/Timedelta/PeriodIndex), but you currently can't use it for any EA (it could be extended for this use case, or we could simply use `Index` for that, which relates to point 1) in https://github.com/pandas-dev/pandas/issues/39133)

**Comment by toobaz** [comment]
> you currently can't use it for any EA

I see. And now that I think about it,

>  some `Index` subclasses might also have to (think about an EA providing an alternative implementation of datetimes, or intervals). But maybe this is not too difficult by doing inheritance right.

Inheritance _must_ be done right, because we might legitimally want to have different subclasses (i.e., with specific methods) to support EA. So whether or not we merge as much as possible in ``Index``, we would like ``Index`` and any of its subclasses to support EA.

Still not a fan of the merge, but I finished my arguments ;-) @jorisvandenbossche your general API distinction makes sense, I still think it complicates the codebase but it might be worth it. Bonus points if `Index` learns to manage non-predefined numpy dtypes (e.g. fixed length strings - clearly not as an alternative to #35169 ).

**Comment by jbrockmendel** [comment]
> there is indeed a very clear API distinction between Index and IntervalIndex: IntervalIndex has additional public methods and properties compared the base Index class, and it wouldn't make sense to add those interval-specific methods and properties to the base class.

If we wanted to get down to a single Index class, one option for these methods/properties would be to hide them behind an accessor.

**Comment by toobaz** [comment]
> If we wanted to get down to a single Index class, one option for these methods/properties would be to hide them behind an accessor.

I guess we would loose in terms of simplicity of implementation and syntax... but I see the possible important gain in writing all dtype-specific attributes/methods for `Series` which work on `Index` without any further effort (and vice-versa) by just registering the accessor on both.

**Comment by topper-123** [comment]
Having thought about this a bit, I think having the base Index hold numeric dtypes is not possible short-term, as the return value of pd.Index(arr, dtype=“int32”) is a Int64Index. That can’t be changed without breaking the API or adding a key word, which is ugly IMO (requires the keyword peppered around the pandas code base).

I suggest we short term (pandas 1.x) go with NumericIndex and for pandas 2.0 we can merge that into Index(or not, if we don’t like that and line to keep NumericIndex).

**Comment by jorisvandenbossche** [comment]
@topper-123 do you have thoughts on the issue?

**Comment by topper-123** [comment]
I'm ok with both. I'm -1 on implenting it myself, as I'm mostly interested in having this functionality and am ok with `NumericIndex`. If someone wnts to integrate it, I would be ok with that :-)

More generally though, I'm thinking if all the index classes are really needed. It's a messy having `CategoricalIndex`, `TimeDeltaIndex` and all the other variants. Couldn't we make something smarter, so all array types could be the base `Index` class? All array types can already be contained in series, so why in `Index`?

**Comment by jbrockmendel** [comment]
@topper-123 what you're describing sounds a lot like #43002

**Comment by jorisvandenbossche** [comment]
> I'm mostly interested in having this functionality

And is it important to have it "right now", or are you fine with waiting until 2.0 (until after the deprecation cycle)? 

Because AFAIK that's the main difference: with the `NumericIndex` approach you will be able to call `pd.NumericIndex(..)` in 1.4 to create an index with specific dtype, while `pd.Index(..)` will continue to return (u)int64/float64 for backward compatibility. So if we remove the public exposure of `NumericIndex`, there is no longer a way to get the behaviour now. 
As I mentioned above, I personally find this only a minor inconvenience (most of the time, you get your index from reading data, or from calling `set_index` implicitly or explicitly, .., and all those cases will _also_ keep using the int64/float64 indices for now). But if people find this important, there are other ways to expose the new functionality (such as a keyword in `pd.Index(..)`)

**Comment by topper-123** [comment]
I think the end game should be something like decribed by @jbrockmendel, where we have one index container for many array types. Currently, we already have many different index classes (`CategoricalIndex` etc.) and I don't see a big issue having `NumericIndex` also until / if(?) #43002 gets implemented. I think we should have indexes of all numpy int/uint/float types in 1.4.

**Comment by jorisvandenbossche** [comment]
> I don't see a big issue having NumericIndex also until / if(?) #43002 gets implemented

My issue with this is that we are now pointing users to switch to a class that we are not yet sure about whether we want to keep it (and moreover for a class that doesn't add any value on itself; there are no additional methods like other index subclasses).

Also note that the `Index` class will already be able to hold multiple dtypes with https://github.com/pandas-dev/pandas/pull/43930 as well. So it's not that this would be the only case of that. 

> I think we should have indexes of all numpy int/uint/float types in 1.4.

An alternative would be a keyword in the `Index` constructor to indicate to preserve the dtype of the input data?

**Comment by jorisvandenbossche** [comment]
To bump this discussion, I opened a PR to start removing NumericIndex just from the public top-level namespace (IMO the minimal short-term change for 1.4): https://github.com/pandas-dev/pandas/pull/44819

**Comment by jreback** [comment]
closing this, the actual conversions can be handled in other issues.
