### ISSUE TITLE
ENH: Incorporate inplace and subset parameters into pandas.DataFrame.apply

### ISSUE THREAD

**Issue by LM-Frank** [pandas-dev/pandas#41314]
I would love to see pandas.DataFrame.apply incorporate the inplace and subset parameters.  Normal operations when inplace is not in use would still apply.  Subset should only be used if inplace=True is provided.

My lame examples of how the function would look if implemented.  

```
import numpy as np
import pandas as pd

# Set the seed for a reproducible sample
np.random.seed(0)  

df = pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE'))

df.apply(lambda x: x + 2*x, inplace=True) # would apply x + 2*x to each column
df.apply(lambda x: x + 2*x, inplace=True, subset=['A','B']) # would apply x + 2*x to each column, 'A' and 'B'
```

**Comment by mzeitlin11** [comment]
Thanks for the request @LM-Frank. In general, mutating an object you are iterating over is very much not recommended, so would be very hesitant about this. 

I don't see what being able to include `inplace=True` gives you other than thinking you might save memory, but for user-defined functions being passed to apply, it probably be infeasible to guarantee intermediate copies aren't made even with `inplace=True`.  Also for your subset argument, you could subset the dataframe itself, eg `df[["a, b"]]` instead of specifying a subset.

**Comment by LM-Frank** [comment]
> Thanks for the request @LM-Frank. In general, mutating an object you are iterating over is very much not recommended, so would be very hesitant about this.
> 
> I don't see what being able to include `inplace=True` gives you other than thinking you might save memory, but for user-defined functions being passed to apply, it probably be infeasible to guarantee intermediate copies aren't made even with `inplace=True`. Also for your subset argument, you could subset the dataframe itself, eg `df[["a, b"]]` instead of specifying a subset.

You are correct.  I forgot that I can do df[['A','B']].apply(lambda x: x*2), mimicking what i am doing with my subset request.  

I suddenly remember that I used to do that all the time, especially when dealing with two columns of ECEF coordinates that I wanted to get a difference vector of, such that df['vector_ECEF'] = df[['source_ECEF','dest_ECEF']].apply(lambda x: np.array(x.iloc[0]) - np.array(x.iloc[1]),axis=1).

Not sure why I forgot that.

**Comment by jreback** [comment]
-1 on adding inplace (we are deprecating this at some point anyhow)

subset is superfluous as indicated

**Comment by rhshadrach** [comment]
-1 as well. @LM-Frank sounds you're good here. If not, just reply here and can reopen.
