### ISSUE TITLE
Docs issue for pd.concat

### ISSUE THREAD

**Issue by softwaredevPK** [pandas-dev/pandas#41518]
Hi,

I was recently updating my pandas from 0.24.2 to 1.1.5 and future warning informed me that default value for sort has changed from None to False. It said that to present current behavior I should change it to sort=True. After i updated my package, I checked if sort=None is still accessible and it is, while docs says it accepts only bool.

May I understand that I can still use sort=None to present old behavior? Or should it be depreciated and raise Error?

![image](https://user-images.githubusercontent.com/71095058/118462242-c0f28600-b6fe-11eb-8a7d-dfd45ec40c3c.png)

**Comment by mzeitlin11** [comment]
Thanks for the report @softwaredevPK! Since the docs and all the type hints along this path specify `sort` as a bool, I don't think `sort=None` is meant as a legal input. Based on the code, I'd guess `sort=None` will happen to be equivalent to `sort=False` since that gives the same behavior for a check like `if sort:`

Seems like an easy fix would be to use  https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/pandas/util/_validators.py#L213
to explicitly disallow `None` as an input

**Comment by phofl** [comment]
@mzeitlin11 would you be ok with raising a FutureWarning in 1.3 to remove the None behavior in 2.0? The Message kinda suggests that  None may be a valid input (which doesn‘t really makes sense of course, but I don‘t know how people use this)

**Comment by softwaredevPK** [comment]
With colleague of mine we performed few tests to check if there is any difference between sort=None vs sort=False vs sort=True.
As You can expect sort=None vs sort=True has completely different behavior but when you compare None with False it become interesting.
Test was made on few simple DF. When we were using sort=False each result was not sorted. Fort sort=None we found that it was sorting result while indexes wheren't same.

So in my opinion none shouldn't be allowed ;-)

**Comment by mzeitlin11** [comment]
> @mzeitlin11 would you be ok with raising a FutureWarning in 1.3 to remove the None behavior in 2.0? 

Sounds good to me!
