### ISSUE TITLE
QST: Unable to install the pandas into the linux environment (Raspberry Pi 4)

### ISSUE THREAD

**Issue by jaskiratsingh2000** [pandas-dev/pandas#41581]
Hey, I am using the linux environment on the raspberry pi 4 device and trying to install the pandas. I had ran almost these following commands one by one but none of them worked for me.

Command 1:
`sudo apt-get install python-pandas`

Command 2:
`python -m pip install pandas --upgrade`

Command-3: 
`sudo pip3 install pandas`

It always throw the error and I am getting this following error https://gist.github.com/jaskiratsingh2000/a05789458a2cca2594cb947e414cd4d1

Please help me out in this. Thanks!

**Comment by ZurMaD** [comment]
I saw that you're running python3.9

Acording to this issue https://stackoverflow.com/questions/64038673/could-not-build-wheels-for-which-use-pep-517-and-cannot-be-installed-directly there are libraries that have problems with ARM-based architectures

**Comment by kordian2k** [comment]
Running [Raspberry Pi OS based on Debian Bullseye ARM64](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-11-08/) seems to resolve this issue. In order to install pandas from the Debian repository, run
`sudo apt-get install python3-pandas`

If you need a more recent pandas version you may switch the repository to unstable.

pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.63-v8+
Version          : #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021
machine          : aarch64
processor        :
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.3.4
setuptools       : 52.0.0
Cython           : None
pytest           : 6.0.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : None
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.2.1
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : 1.3.0
numba            : None

**Comment by mroeschke** [comment]
Seems like this is an issue with an unsupported version of pandas now so closing. We can reopen if this is happening with a newer version of pandas
