### ISSUE TITLE
QST: difference using ['column'] or .column?

### ISSUE THREAD

**Issue by ivangvi** [pandas-dev/pandas#41629]
Hi All,

I was wondering if you have any guidelines as to when it is possible to just go for df.column instead of df['column'], as I prefer the former for code styling, but I recall it gave me some issues before. I'm not sure I understand the specific difference between one and the other, is there any?

For now, what I do is only use ['column'] when declaring a new column and then always go for .column.

Thank you,
Iván.

**Comment by ZurMaD** [comment]
Hello there,

There is a external blog that details the differences and why or why not to use one of them

https://medium.com/dunder-data/select-a-single-column-of-a-pandas-dataframe-with-the-brackets-and-not-dot-notation-a5ec981cbae6

If you can't see the post, open the link in incognito mode

**Comment by jreback** [comment]
that's a nice post 
would take a PR to link it in the docs

**Comment by LukeTonin** [comment]
take

**Comment by ivangvi** [comment]
Thank you @ZurMaD!
It looks like #5 was what confused me in the first place:

![image](https://user-images.githubusercontent.com/30244899/119271771-58614880-bbd9-11eb-8755-52dc3bbbae34.png)

And now I understand why I was confused. I guess my way of using [] when declaring new columns and then .column as much as possible, works just fine... all the other points mentioned I already knew about.

**Comment by LukeTonin** [comment]
Hi all,

I'm thinking of adding a line to the _Attribute access_ section of the [_Indexing and selecting data_](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html) page of the documentation.

Unless I'm told otherwise, I'll probably go with:

While attribute access will work in many cases, bracket indexing is the recommended syntax for indexing a DataFrame. For 10 reasons why, please check [this post](https://medium.com/dunder-data/select-a-single-column-of-a-pandas-dataframe-with-the-brackets-and-not-dot-notation-a5ec981cbae6) on attribute vs bracket indexing.

**Comment by mroeschke** [comment]
As mentioned in https://github.com/pandas-dev/pandas/pull/41645#issuecomment-848394071, this is already documented in https://pandas.pydata.org/pandas-docs/dev/user_guide/indexing.html#attribute-access. Closing
