### ISSUE TITLE
QST: Apple M1, arm64

### ISSUE THREAD

**Issue by beaverden** [pandas-dev/pandas#41787]
- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

What is the current state of amd64 compilation? Docker pip installation takes ages and I'm having trouble installing it on my macos with apple m1 chip.

Is there anything I can do to help provide precompiled binaries for release on this platform?

**Comment by lithomas1** [comment]
Hi @beaverden, I believe you mean arm64 not amd64(amd64 is for Intel/AMD chips). We currently don't publish wheels on PyPI because pandas fails a couple of tests on the arm64 architecture(and we don't have free CI infrastructure for arm64 yet), but you should be able to get pandas via conda if you have it(https://anaconda.org/conda-forge/pandas).

**Comment by beaverden** [comment]
I'm sorry. You're right about arm64. Is there a way to help on the tests?

**Comment by phofl** [comment]
They are listed in #41740, not sure where we are exactly there

**Comment by lithomas1** [comment]
Hi @beaverden, just giving you a heads-up that I'm going to be trying to add M1 support through universal2 wheels. 
I'm going to be closing this issue for now to keep discussion in one place there, but please feel free to chime in on the universal2 wheels issue(#39053).
