### ISSUE TITLE
pandas.notnull documentation showing code examples from pandas.notna

### ISSUE THREAD

**Issue by jenkc** [pandas-dev/pandas#41855]
The code examples are from the previous page in the documentation. Need examples for using notnull please.
Thanks!

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.notnull.html

**Comment by mzeitlin11** [comment]
Thanks for pointing this out @jenkc! This happens because `notnull` is purely just an alias for `notna` (the same problem exists for `isnull`, and the associated `Series`/`DataFrame` methods). To avoid duplicating examples, I'd guess some of the shared doc machinery could be used to generalize over `isna/isnull` and `notna/notnull`

**Comment by jenkc** [comment]
Thanks for the clarification! Was trying to use these for the first time and did not know that notnull and isnull are aliases.

**Comment by simonjayhawkins** [comment]
> Thanks for pointing this out @jenkc! This happens because `notnull` is purely just an alias for `notna` (the same problem exists for `isnull`, and the associated `Series`/`DataFrame` methods). To avoid duplicating examples, I'd guess some of the shared doc machinery could be used to generalize over `isna/isnull` and `notna/notnull`

or maybe add a basic docstring to the alias to let users know it's an alias and link to the other.

**Comment by koukyo1994** [comment]
take
