### ISSUE TITLE
API: loc indexing with nested sequence raise on missing

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#41975]
I think the current behavior is left over from the long long ago.

```
mi = pd.MultiIndex.from_product([range(3), ["A", "B"]])
ser = pd.Series(len(mi), index=mi)

>>> ser.loc[1, ["A", "B", "not a key"]]
1  A    6
   B    6
dtype: int64

>>> ser.loc[[99999], ["A", "B"]]
Series([], dtype: int64)

>>> ser.loc[[99999]]
KeyError: '[99999] not in index'
```

I think we should deprecate this and eventually raise like we would with any other missing label.

**Comment by attack68** [comment]
@pholf and I have an on going discussion re: this [here](https://github.com/pandas-dev/pandas/issues/39424#issuecomment-837863439). For what its worth I typed up how I believe many of the different cases should intersect, and pholf is rightfully challenging a few of those ideas.

Pertinent to your example, I propose:

`ser.loc[1, ["A", "B", "not a key"]]`  would raise since `"not a key"` is not part of the `level1_elements`.<br>
but
```
ser2 = ser.reindex(["A", "B", "not a key"], level=1)
ser2.loc[1, ["A", "B", "not a key"]]
``` 
would not raise since `"not a key"` is now an `unused_level1_element`, i.e.<br>
```
>>> ser2.index.levels  
FrozenList([[0, 1, 2], ['A', 'B', 'not a key']])
>>> ser2
0  A    6
   B    6
1  A    6
   B    6
2  A    6
   B    6
dtype: int64
```

This allows for complex vector product or scalar broadcasting of level slices, without having to explicitly check if all the parts of your level slice will be accepted (and therefore be forced to remove any before using `loc` to avoid KeyErrors)

**Comment by jbrockmendel** [comment]
@attack68 thanks for the link, ill work my way through the thread today.  I take it this issue is redundant and can be closed?

**Comment by attack68** [comment]
> @attack68 thanks for the link, ill work my way through the thread today. I take it this issue is redundant and can be closed?

yes I believe it to be a duplicate, with this and other cases under consideration elsewhere,
