### ISSUE TITLE
CLN: Combine checknull/checknull_old

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#42191]
Is there a reason that both checknull and checknull_old are separate functions? It seems like they could be combined into one function with a parameter inf_as_na. This duplication also seems to be present with the  isnaobj/isnaobj_old functions.

I'm asking since having this be unified would greatly simplify my work in #42147

**Comment by mzeitlin11** [comment]
+1 on this definitely, only concern would be if the additional conditional has a perf penalty (since in a bunch of algos `checknull` is called on every step of loops). Hopefully wouldn't make a difference though since `inf_as_na` could effectively be known at compile time so the check might be optimized out.

**Comment by jbrockmendel** [comment]
If perf is OK then id be fine with this.

**Comment by mzeitlin11** [comment]
Closed by #44541
