### ISSUE TITLE
BUG: inconsistent behaviour when grouping DataFrame by week and month, as compared to minutes, hours and days??

### ISSUE THREAD

**Issue by xuancong84** [pandas-dev/pandas#43093]
In computer science, we always try to design algorithms and procedures in a logically consistent manner so that other people can follow easily without making wrong assumptions. For example, when we group dates into intervals, for every group we can choose to use either the left or the right boundary to label that group. So if you decide to choose the left timestamp to label every interval, then you should do it for all types of intervals.

However, this is not so in Pandas.
```
>>> stmp=pd.to_datetime('2021-01-01 09:31:04.34')
>>> [print(sc, list(pd.DataFrame({'a':0}, index=[stmp]).groupby(pd.Grouper(freq=sc)))[0][0]) for sc in ['s', 'min', 'H', 'D', '7D', 'W', 'M']]
s 2021-01-01 09:31:04
min 2021-01-01 09:31:00
H 2021-01-01 09:00:00
D 2021-01-01 00:00:00
7D 2021-01-01 00:00:00
W 2021-01-03 00:00:00
M 2021-01-31 00:00:00
```
As you can see above, when grouping into seconds, minutes, hours, days, weeks and months respectively:
- for seconds, minutes, hours and days, the group time label lies to the left of the sample
- but for weeks and months, the group time label lies to the right the sample
In general, we can group dates by arbitrary interval, e.g., 10.5 days or 1.5 weeks (some astronomical events monitoring can leads to such use case). This inconsistency is going to cause errors in applications based on human assumption because who the hell will know that for weeks and months, the library decide to do it differently from the rest??

**Comment by mroeschke** [comment]
Since the `Grouper` call is equivalent to a `resample`, it's documented behavior in that docstring https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html

As for why, it's probably because these frequencies are anchored at the end of the interval by default https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects and this behavior I believe was adopted by scikits-timeseries. Since this behavior has existed for quite some time, I doubt this is very unlikely to change.

**Comment by xuancong84** [comment]
Well, my justification is still valid, just that the convention has been adopted long time ago and many software have already been developed based on this wrong convention. Thus, it is too late to change now, or will break too many things. It can only be changed when the current Pandas library gets abandoned and a new replacement library has been developed.
