### ISSUE TITLE
CI: Posix / pytest failing in test_unique.py

### ISSUE THREAD

**Issue by johnzangwill** [pandas-dev/pandas#43429]
Posix / pytest (actions-38-minimum_versions.yaml, not slow and not network and not clipboard) failing at test_unique.py::test_unique_bad_unicode[idx_or_series_w_bad_unicode0]

    `UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83d' in position 84: surrogates not allowed`

(I believe that  \ud83d is a smily face character...)

**Comment by phofl** [comment]
Is this failing consistently? We have a few flaky tests

**Comment by johnzangwill** [comment]
Don't know yet. I just made a small change to #42947 to force a rebuild, but the ci workflows are awaiting approval...

**Comment by jbrockmendel** [comment]
I occasionally see failures (sometimes even segfaults i think) on the CI pointing to this test, have never been able to reproduce locally

**Comment by lithomas1** [comment]
Yup, this shows up a ton on the repo where we build wheels(MacPython/pandas-wheels) where it crashes the entire build. Its flaky and annoying.

**Comment by jreback** [comment]
let's try to move this test to the single process mode in pytest (we have a decorator for that)?

**Comment by johnzangwill** [comment]
I haven't seen this for a while so I will close it.
That is not to say that there are not other intermittant CI failures. e.g. 60 minute timeouts, HTTP errors getting reference files, ...

**Comment by johnzangwill** [comment]
This is still happening:
https://github.com/pandas-dev/pandas/runs/4407103184

**Comment by jbrockmendel** [comment]
I've found a way to reproduce it locally.  In test_unique.py if I replace the parametrized `null_obj` with `nulls_fixture` in _both_ test_unique_null and test_nunique_null, then run the tests for the whole file, I get this failure in  `test_unique_bad_unicode` (in addition to a bunch of failures for test_unique_null and test_nunique_null).

Subsequent pytest runs do _not_ produce the failure.  I have to make another edit or directly remove the `__pycache__` in order to produce the failure again.

Before I spend more time on this: can anyone else reproduce this behavior?

**Comment by phofl** [comment]
Will have a look tomorrow

**Comment by phofl** [comment]
Can not reproduce, have only a bunch of failures in test_unique_null and test_nunique_null. I am running on ubuntu 20.04

**Comment by mroeschke** [comment]
Looks like this is not appearing in the CI failures anymore so clsoing
