### ISSUE TITLE
BUILD: Incorrect filenames on pypi

### ISSUE THREAD

**Issue by cmdawson** [pandas-dev/pandas#43451]
### 

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-4.15.0-144-generic-x86_64-with-glibc2.27

### Installation Method

pip install

### pandas Version

latest

### Python Version

3.8

### Installation Logs

Files on  https://pypi.org/project/pandas/#files appear to have a duplicated platform tag e.g.
```pandas-1.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl```
instead of
```pandas-1.3.2-cp38-cp38-manylinux_2_17_x86_64.whl```

So pip installs are not able to match and will attempt to build from source.

**Comment by lithomas1** [comment]
Hi @cmdawson, can you elaborate a little more? 
(FWIW, numpy seems to name their files similarly.
e.g. one of the names is numpy-1.21.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl .)

One thing that may be causing the issue is that our wheels are now built with manylinux 2014. Can you check that you have a pip version recent enough to install pandas(pip>19.3)?

Thanks.

**Comment by cmdawson** [comment]
Oh my apologies, it is an out of date pip. I thought I'd checked the numpy naming.
