### ISSUE TITLE
DEPR: Dropping nuisance columns in core.apply

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#43740]
Ref: https://github.com/pandas-dev/pandas/pull/41475, https://github.com/pandas-dev/pandas/issues/39993#issuecomment-926281200

To keep the API consistent between groupby / non-groupby UDF methods (apply, agg, transform), we should not allow silent failure in `core.apply`.

 - [ ] transform_dict_like #43743 
 - [ ] agg_list_like - #43741

**Comment by rhshadrach** [comment]
Thanks for the feedback here @emirkmo.

> Can I ask why this and other silent drops are being deprecated? 

Others may have different/additional reasons. For me, when it comes to methods such as `agg` and `apply` that can take a user-defined function, how can pandas tells when a column is a nuisance column? Currently, we essentially define a "nuisance column" as one that raises a TypeError. This can lead to silent (unintended) failure and odd behaviors.

From a user standpoint, I think a user should be surprised if the following code does not result in a DataFrame with index 'a' and columns 'b' and 'c'.

```
df[['a', 'b', 'c']].groupby('a').sum()
```

With silent drops, that may not be the case. Internally, not being able to rely on an output shape gives rise to edge cases (e.g. all columns are nuisance columns) and is a source of bugs.

**Comment by emirkmo** [comment]
Thanks for the response, the reasons for dropping make a lot of sense. It seems like there is no ideological opposition to adding a method to keep the current behavior as an unsupported (depreciation notice or warning) compatibility compromise? It has existed for so long that it has become part of the expected output of Pandas operations. Many codes rely on it. 

Now every single pandas read in literally hundreds of scripts just in my case will require me to go back and add in often complicated logic for dropping certain dtypes. Having a convenience function for backward compatibility doesn't seem like a bad idea? At least to extend the transition period. 

Do you think I should put this an issue? I would appreciate your feedback.

**Comment by CAM-Gerlach** [comment]
I'm also not sure if this is the place (happy to open an issue), but I concur with @emirkmo ; this seems likely to break a large amount of existing user code (including a substantial amount of my own) without offering (or at least clearly describing) a straightforward alternative that replicates the previous behavior for the many use-cases that rely on it.

For example, I heavily rely on this behavior when doing feature extraction/generation for ML, to automatically generate means, sums, and custom aggregated metrics only on input columns where these operations are numerically sensible. Without this feature, I'd have to manually filter the data to just columns with supported data types before every call, which is tedious, verbose and potentially less robust and performant than the current BTAFTP approach.

Similarly, I'll often use groupby and apply including as part of interactive data exploration, sometimes even on-demand with other members of my research team, which gives me a quick way of summarizing more specific data and columns, and running "crosstab"-style analyses on various factors. This would make it far more time-consuming and high-friction to use particularly in an interactive setting, greatly slowing down the feedback loop for data exploration.

Is it possible to add a parameter as part of the API...somewhere...to select the desired behavior, instead of completely removing useful functionality?

**Comment by rhshadrach** [comment]
Thanks for the feedback here @CAM-Gerlach and @emirkmo. Does

``df.select_dtypes(exclude='object')``

satisfy the needs here?

**Comment by CAM-Gerlach** [comment]
Thanks @rhshadrach . It covers one common case, that of strings and other objects with the most common built-in aggregation functions, but doesn't cover the many other numpy/pandas datetypes that are not compatible with such functions (datetimes, timedeltas, periods, categoricals, fixed-length strings, etc), and neither does it cover other and custom aggregation functions, which may expect different data types or have different constraints.

`df.select_dtypes(include=["number", "bool"])` should more or less handle the first set of cases much more completely than the initial suggestion (AFAIK, but there may still be cases I didn't think of that it doesn't cover), but it doesn't address the second, and still substantially increases code verbosity and required complexity (particularly for quick data exploration, one of the primary use cases of groupby) while increasing fragility. And of course, users need to know and memorize it, which gets to be a lot of boilerplate for what was previously a relatively simple and elegant invocation.

**Comment by rhshadrach** [comment]
> and still substantially increases code verbosity and required complexity

An example where it substantially increases code verbosity would also be helpful. I see it as a single additional call (column selection in some form), and your comment above suggests to me this might be mistaken.

> which gets to be a lot of boilerplate for what was previously a relatively simple and elegant invocation

By ignoring any TypeError that occurs, we are _guessing_ that the user didn't want to aggregate a particular column. This is especially true with user-provided functions (as opposed to e.g. "mean"), where a TypeError could be an issue with the function implementation rather than desired behavior. Having users tell us what they want to aggregate avoids silent failure, which can be hard to debug. I agree this puts more onus on the user, which when viewed alone in isolation is negative, but I would not describe this as boilerplate.

**Comment by jbrockmendel** [comment]
@rhshadrach what's the status here?  the two PRs linked in the OP are both merged

**Comment by rhshadrach** [comment]
@jbrockmendel - I believe I left this open because there was some opposition to the changes. I'm still behind the deprecation, and it seems like conversation has ceased. I'm going to close for now, and can reopen if anyone would like to continue the discussion.
