### ISSUE TITLE
ENH:

### ISSUE THREAD

**Issue by MMCMA** [pandas-dev/pandas#43795]
#### Is your feature request related to a problem?

Not really, there are ways around (as always).

#### Describe the solution you'd like

Allow `df.pipe()` to accept strings for pd.DataFrame built-in methods . For example, it would be very helpful to simply call
a pipeline as follows:
 `df.pipe(f, arg_1=1).pipe("rank", ascending=True)`

I know I can call explicitly invoke the method

 `df.pipe(f, arg_1=1).rank(ascending=True)`

but this feature could enable a more general usage of pipelines as outlined below:

```
pipes= [
    (fun_1, dict(arg_1=0)),
    (fun_2, dict(arg_1=1)), 
    ("rank", dict(ascending=True))
] 

for fun, kwargs in pipes:
    df = df.pipe(fun, **kwargs)
```

#### API breaking implications

Not sure what to add here. 

#### Describe alternatives you've considered

I can re-write most methods as standalone function but why if the built-in is so reach in features.

#### Additional context

see example above.

**Comment by attack68** [comment]
Not sure this is of any benefit since you can do this:

```
pipes= [
    ("pipe", (fun_1), dict(arg_1=0)),
    ("pipe", (fun_2), dict(arg_1=1)), 
    ("rank", (), dict(ascending=True))
] 

for fun, arg, kwargs in pipes:
    df = getattr(df, fun)(*arg, **kwargs)
```

**Comment by Liam3851** [comment]
I agree with @attack68. Another currently-available alternative is to use the unbound rank method in your pipe. Since an unbound method takes the object to act on as the first parameter, and pipe passes self as the first parameter to the called method, this should work for all standard DataFrame methods. Versus the original suggestion it has the added benefit of being symmetric across all three calls in the pipe (i.e. each element of the "pipes" list is a tuple of (function, dict)).

```python
pipes= [
    (fun_1, dict(arg_1=0)),
    (fun_2, dict(arg_1=1)), 
    (pd.DataFrame.rank, dict(ascending=True))
] 

for fun, kwargs in pipes:
    df = df.pipe(fun, **kwargs)
```

**Comment by MMCMA** [comment]
@attack68 and @Liam3851 thanks for the suggestions. This is useful, especially what @Liam3851 suggested. However, I still think an additional string interpration of `pipe()` could be helpful.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that this enhancement doesn't provide too much value-add as a convenience API. pandas is trying to move away from multiple way to perform the same operation.

Closing since this feature hasn't gotten much support from the core team, but happy to reopen if there is a change of heart from the team.
