### ISSUE TITLE
BUG: cannot write xml with nullable dtypes

### ISSUE THREAD

**Issue by dmyersturnbull** [pandas-dev/pandas#43903]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import logging
import numpy as np
import pandas as pd
import pytest

logger = logging.getLogger("test")

class XmlTest:

    def test_to_xml_dtypes(self):
        dtypes = [
            pd.StringDtype(),
            pd.BooleanDtype(),
            pd.Float64Dtype(),
            pd.Float32Dtype(),
            pd.Int64Dtype(),
            pd.UInt64Dtype(),
            pd.Int32Dtype(),
            pd.UInt32Dtype(),
            pd.Int16Dtype(),
            pd.UInt16Dtype(),
            pd.Int8Dtype(),
            pd.UInt8Dtype(),
            pd.StringDtype(),
        ]
        data = [
            pd.Series({"abc": 1, "xyz": pd.NA}),
            pd.Series({"abc": pd.NA, "xyz": 0}),
        ]
        failed = {}
        for dtype in dtypes:
            df = pd.DataFrame(data).astype(dtype)
            try:
                df.to_xml()
            except TypeError as e:
                logger.error(dtype, exc_info=True)
                failed[str(dtype)] = str(e)
        assert failed == [], f"Failed on dtypes: {failed}"

if __name__ == "__main__":
    pytest.main()
```

### Issue Description

`to_xml` fails with nullable dtypes provided by Pandas like `Float64Dtype`. Example from a test run in CI; it fails on Ubuntu too.

### Expected Behavior

Output valid xml that can be read with `read_xml` to get approximately the same DataFrame.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.9.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.3.0
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 2021.07.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : 1.0.8
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None
None
</details>

**Comment by ParfaitG** [comment]
Conversion of nullable types in `read_xml` is not yet supported. Good item to add to IO XML enhancements tracker. The best avenue I see would be in the [`_data_to_frame`](https://github.com/pandas-dev/pandas/blob/52c9181de6c23fa2e0143937f282fe2fde0fc6b3/pandas/io/xml.py#L636) method that uses [`TextParser`](https://github.com/pandas-dev/pandas/blob/52c9181de6c23fa2e0143937f282fe2fde0fc6b3/pandas/io/parsers/readers.py#L1183) from `pandas.io.parsers` to infer data types. Possibly, only this external parser (shared by other IO methods) would need to be adjusted to infer nullable types.

As workaround, since all text nodes in XML documents are actually text types you can convert columns to `object` types before calling `to_xml()`.

Currently, your reproducible example outputs the following:

```python
df
    abc   xyz
0     1  <NA>
1  <NA>     0
```

Converting all columns to `object` types then allows `to_xml()` to run without error:

```python
xml_str = df.astype('str').to_xml(index=False)
print(xml_str)
<?xml version='1.0' encoding='utf-8'?>
<data>
  <row>
    <abc>1</abc>
    <xyz>&lt;NA&gt;</xyz>
  </row>
  <row>
    <abc>&lt;NA&gt;</abc>
    <xyz>0</xyz>
  </row>
</data>
```

However, reading back in requires users to convert to needed types. Floats are generated here since it allows `NaN` values:

```python
new_df = pd.read_xml(xml_str)

new_df
   abc  xyz
0  1.0  NaN
1  NaN  0.0
```
