### ISSUE TITLE
BUILD: Unable to compile on Windows 10 with Python 3.10

### ISSUE THREAD

**Issue by TimeHorse** [pandas-dev/pandas#44136]
When downloading the tar ball and executing “py setup.py develop” most of the build succeeds until you ge to the step where it tries to build pandas._libs.indexing, because indexing.c is not in the _libs directory, the build fails with the following error:

Exception: Cython-generated file ‘pandas\_lib/indexing.c’ not found.
    Cython is required to compile pandas from a development branch.
    Please install Cython or download a release package of pandas.

For the record, there is no official release of Pandas for Python 3.10 on Windows or Macintosh, only Linux.

cython is installed:

py -c “import cython; print(cython.__version__)”
0.29.24

**Comment by lithomas1** [comment]
Why are you using python setup.py develop instead of doing ``pip install pandas``? Is there a problem with accessing pypi.org from your office?

If you still want to try to install from source, try cleaning your installation folder with ``python setup.py clean``, followed by ``python setup.py install``. The c files are auto-generated by Cython, so I assume something went wrong there.

**Comment by lithomas1** [comment]
> I've milestoned 1.3.5 for now. However we will probably be able to create Windows wheels for 1.3.4 (and upload to PyPI) now that numpy 3.10 wheels for windows are available (numpy-1.21.3-cp310-cp310-win_amd64.whl) @lithomas1 ?

I have a PR for macOS and Windows wheels ready on the MacPython repo. (Merge first MacPython/pandas-wheels#159, then MacPython/pandas-wheels#156, the second one might need a rebase).  I think it would be better to just upload everything to 1.3.5. Installs using pip seem to work for me at least, and there were some changes to the macOS wheels(they became universal2.) so just lower risk to wait.

**Comment by simonjayhawkins** [comment]
> No further comments here, so will upload shortly.

done.

**Comment by jorisvandenbossche** [comment]
Thanks Simon!

**Comment by lithomas1** [comment]
It turns out we don't have thin wheels for x86_64 macOS users for Python 3.10, because of a multibuild limitation. So someone with Intel Mac will install the universal2 wheel which is ~2x bigger. Recently, multibuild allowed building the thin x86_64 macos wheels for Python 3.10.

I have opened MacPython/pandas-wheels#163 accordingly. @simonjayhawkins Can you merge that PR? (the failures can be ignored cuz they were fixed on changes that were backported but only in 1.3.5 not 1.3.4)

I am not sure whether it is too close to 1,3,5 to upload the wheels, though. I'll leave that decision to the rest of @pandas-dev/pandas-core

**Comment by simonjayhawkins** [comment]
> I am not sure whether it is too close to 1,3,5 to upload the wheels, though. I'll leave that decision to the rest of @pandas-dev/pandas-core

Once 1.3.5 wheels are up, the 1.3.4 wheel will probably only be downloaded if specifically requested. Probably best to leave as is although I've not gone through the process of changing build number for PyPI release so not sure what is required.

**Comment by simonjayhawkins** [comment]
> I have opened [MacPython/pandas-wheels#163](https://github.com/MacPython/pandas-wheels/pull/163) accordingly. @simonjayhawkins Can you merge that PR? (the failures can be ignored cuz they were fixed on changes that were backported but only in 1.3.5 not 1.3.4)

done.

We will have an additional wheel `pandas-1.3.4-cp310-cp310-macosx_10_9_x86_64.whl` which could be uploaded? and the `pandas-1.3.4-cp310-cp310-macosx_10_9_universal2` (and others) will now be re-built with a later version of multibuild so cannot be uploaded to PyPI unless the build number is changed?

**Comment by lithomas1** [comment]
Yeah. The config for the other wheels should have remained the same. The only question is whether to upload ``pandas-1.3.4-cp310-cp310-macosx_10_9_x86_64.whl``.

**Comment by simonjayhawkins** [comment]
no further comments here so let's close and leave 1.3.4 as is.
