### ISSUE TITLE
DataFrames should have a name attribute.

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#447]
was: should DataFrames have a name attribute?

@y-p

**Comment by denfromufa** [comment]
in ipython notebook and similar REPL, it would make sense to display dataframe name or more generally custom metadata, like in Excel toolbar.

**Comment by summerela** [comment]
When saving results of an analysis, resulting in several different outputs, it would be so nice to automatically save and name your output: 

def save_results(df, df_name):
    if len(df) > 0:
        print "Saving {} {} variants to current working directory".format(len(df), df_name)
        df.to_csv('{}.csv'.format(df_name), header=True, encoding='utf-8', index=False)
    else:
        print "No {} variants to save.".format(df_name)

**Comment by summerela** [comment]
Ohhh. I see now from [StackExchange](http://stackoverflow.com/questions/14688306/adding-meta-information-metadata-to-pandas-dataframe) that I can do something like this: 
    import pandas as pd
    df = pd.DataFrame([])
    df.df_name = 'Binky'

**Comment by denfromufa** [comment]
@Summer Rae, great finding! Thanks for sharing.

Also computed properties are contained in .describe()

**Comment by abc123634** [comment]
@summerela  wonderful finding!

**Comment by wesm** [comment]
Adding a `name` attribute to DataFrame would add a lot of complexity. The benefits (compared with the benefits of named Series) to me are less clear. Closing for now

**Comment by mortonjt** [comment]
I realize that this is a year out of date, but I'd like to pitch in a use case where having a name for a data frame can be really useful.

When performing multi-block analysis (i.e. multi-block partial least squares), it would be awesome if we could specify R style formulas via patsy and run this sort of analysis as something like as follows

`result = pls_multiblock(formula="Z ~ X + Y + U + V", blocks=(Z, X, Y, U, V) ) `

where `Z`, `X`, `Y`, `U`, `V` are all matrices (represented as pandas data frames).
Representing these objects as pandas data frames is advantageous, since we can keep track of the ordering of the index/column names.  But more importantly, if we have information about the naming, and flexibility concerning what sort of models we want to construct on the fly.  The implications of having the `DataFrame.name` being consistent with the `Series.name` is not clear to me, but having consistent unique identifiers for the DataFrames themselves can easily enable these sorts of analyses.

**Comment by shoyer** [comment]
@mortonjt For this sort of multi-dimensional data analysis, I would consider using xarray, which *does* already support a `name` attribute on `DataArray` objects. Note that we are deprecating `pandas.Panel`.

**Comment by mortonjt** [comment]
I totally forgot about xarray ...  Thanks @shoyer!

**Comment by Jacob-Stevens-Haas** [comment]
Hey, since this thread is linked across a few places on SO and GH, wondering whether there are issues with name metadata beyond serialization?  I use the name attribute frequently in data cleaning since it's assigned by `DataFrameGroubpy.apply()`.  Useful in cases like:
```python
df = pd.DataFrame({'part_no':[1,1,2,2], 'system':['fax machine', None, 'fax machine', 'truck'])
gb = df.groupby('part_no')
gb.apply(validate_individual_parts)
def validate_individual_parts(df: pd.DataFrame) -> None:
    if (df['system'].unique()) > 1:
        logging.warning(f'Unable to determine system for part {df.name})
```

So currently in tests, we have to assign `df.name = '1234'`, which is fine even if it feels a bit ad hoc.  Wondering though if there's a better answer.

**Comment by jreback** [comment]
these are support via the `.attrs` accessor: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.attrs.html?highlight=attrs (not a whole lot of docs though :-<)
