### ISSUE TITLE
BUG: concat unwantedly sorts DataFrame column names if they differ

### ISSUE THREAD

**Issue by smcinerney** [pandas-dev/pandas#4588]
When concat'ing DataFrames, the column names get alphanumerically sorted if there are any differences between them. If they're identical across DataFrames, they don't get sorted.
This sort is undocumented and unwanted. Certainly the default behavior should be no-sort.

``` python
df4a = DataFrame(columns=['C','B','D','A'], data=np.random.randn(3,4))
df4b = DataFrame(columns=['C','B','D','A'], data=np.random.randn(3,4))
df5  = DataFrame(columns=['C','B','E','D','A'], data=np.random.randn(3,5))

print "Cols unsorted:", concat([df4a,df4b])
# Cols unsorted:           C         B         D         A

print "Cols sorted", concat([df4a,df5])
# Cols sorted           A         B         C         D         E
``'
```

**Comment by rasbt** [comment]
Just stumbled upon this same issue when I was concatenating `DataFrames`. It's a little bit annoying if you don't know about this issue, but actually there is a quick remedy:

say `dfs` is a list of `DataFrames` you want to concatenate, you can just take the the original column order and feed it back in:

    df = pd.concat(dfs, axis=0)
    df = df[dfs[0].columns]

**Comment by rasbt** [comment]
Just stumbled upon this same issue when I was concatenating `DataFrames`. It's a little bit annoying if you don't know about this issue, but actually there is a quick remedy:

say `dfs` is a list of `DataFrames` you want to concatenate, you can just take the the original column order and feed it back in:

    df = pd.concat(dfs, axis=0)
    df = df[dfs[0].columns]

**Comment by maximilianr** [comment]
I believe `append` causes the same behavior, FYI

**Comment by tompicking** [comment]
It's the default behaviour across the board. For example, if you apply a function, f, to a groupby() that returns a varying number of columns, the concatenation taking place behind the scene also auto-sorts the columns.
> df.groupby(some_ts).apply(f)

Likely because the known order of the columns is open to interpretation.

However, this also happens for MultiIndices and all hierarchies in MultiIndices. So you can concat dataframes that agree on level0 columns and all bar one level1 columns, and all levels of the MultiIndices will be autosorted because of one mismatch within one level0 column. I don't imagine that is desirable.

I'd love to help, but unfortunately fixing this issue is beyond my ability. Thanks for the hard work all.

**Comment by vitalyisaev2** [comment]
+1 for this feature

**Comment by ashishsingal1** [comment]
Agreed, +1. Unexpected sorting happens all the time for me.

**Comment by scyllagist** [comment]
+1, this was an unpleasant surprise!

**Comment by Zenadix** [comment]
+1, I hate having the columns sorted after every `append`.

**Comment by summerela** [comment]
+1 from me, as well. 

Because even if I did want to manually re-order after a concat, when I try to print out the 60 + column names and positions in my dataframe: 

     for id, value in enumerate(df.columns):
          print id, value

All 60+ columns are output in alphabetical order, not their actual position in the data frame. 

So that means that after ever concat, I have to manually type out a list of 60 columns to reorder. Ouch. 

While I'm here, does anyone have a way to print out column name and position that I'm missing?

**Comment by jmwoloso** [comment]
+1 for this feature, just ran across the same deal myself.

@summerela Get the column index and then re-index your new dataframe using the original column index

```
# assuming you have two dataframes, `df_train` & `df_test` (with the same columns) 
# that you want to concatenate

# get the columns from one of them
all_columns = df_train.columns

# concatenate them
df_concat = pd.concat([df_train,
                       df_test])

# finally, re-index the new dataframe using the original column index
df_concat = df_concat.ix[:, all_columns]

```

Conversely, if you need to re-index a smaller subset of columns, you could use this function I made. It can operate with relative indices as well. For example, if you wanted to move a column to the end of a dataframe, but you aren't sure how many columns may remain after prior processing steps in your script (maybe you're dropping zero-variance columns, for instance), you could pass a relative index position to `new_indices` --> `new_indices = [-1]` and it will take care of the rest.

```
def reindex_columns(dframe=None, columns=None, new_indices=None):
    """
    Reorders the columns of a dataframe as specified by
    `reorder_indices`. Values of `columns` should align with their
    respective values in `new_indices`.

    `dframe`: pandas dataframe.

    `columns`: list,pandas.core.index.Index, or numpy array; columns to
    reindex.

    `reorder_indices`: list of integers or numpy array; indices
    corresponding to where each column should be inserted during
    re-indexing.
    """
    print("Re-indexing columns.")
    try:
        df = dframe.copy()

        # ensure parameters are of correct type and length
        assert isinstance(columns, (pd.core.index.Index,
                                    list,
                                    np.array)),\
        "`columns` must be of type `pandas.core.index.Index` or `list`"

        assert isinstance(new_indices,
                          list),\
        "`reorder_indices` must be of type `list`"

        assert len(columns) == len(new_indices),\
        "Length of `columns` and `reorder_indices` must be equal"

        # check for negative values in `new_indices`
        if any(idx < 0 for idx in new_indices):

            # get a list of the negative values
            negatives = [value for value
                         in new_indices
                         if value < 0]

            # find the index location for each negative value in
            # `new_indices`
            negative_idx_locations = [new_indices.index(negative)
                                      for negative in negatives]

            # zip the lists
            negative_zipped = list(zip(negative_idx_locations,
                                       negatives))

            # replace the negatives in `new_indices` with their
            # absolute position in the index
            for idx, negative in negative_zipped:
                new_indices[idx] = df.columns.get_loc(df.columns[
                                                          negative])

        # re-order the index now
        # get all columns
        all_columns = df.columns

        # drop the columns that need to be re-indexed
        all_columns = all_columns.drop(columns)

        # now re-insert them at the specified locations
        zipped_columns = list(zip(new_indices,
                                  columns))

        for idx, column in zipped_columns:
            all_columns = all_columns.insert(idx,
                                             column)
        # re-index the dataframe
        df = df.ix[:, all_columns]

        print("Successfully re-indexed dataframe.")

    except Exception as e:
        print(e)
        print("Could not re-index columns. Something went wrong.")

    return df
```

**Comment by patricktokeeffe** [comment]
I encountered this (with 0.13.1) from an edge case not mentioned: combining dataframes each containing unique columns. A naive re-assignment of column names didn't work:

```python
dat = pd.concat([out_dust, in_dust, in_air, out_air])
dat.columns = [out_dust.columns + in_dust.columns + in_air.columns + out_air.columns]
```

The columns still get sorted. Using lists intermediately resolved things, though:

```python
dat.columns = [list(out_dust.columns) + 
               list(in_dust.columns) + 
               list(in_air.columns) + 
               list(out_air.columns)]
```

**Comment by bejondshao** [comment]
Could there be a parameter when creating dataFrame about order column? like order=False. Thanks a lot

**Comment by MikeTam1021** [comment]
just ran into this while creating a dataframe from a dictionary. Totally surprised me, was counterintuitive and defeated my whole purpose...

column names should be for clarity and the location of columns near each other is an organizational choice of the user to maintain coherency

**Comment by brycepg** [comment]
@patricktokeeffe 
Thanks for the pointer to `join`. Series objects don't have that method so I ended up writing a function:

    def concat_fixed(ndframe_seq, **kwargs):
        """Like pd.concat but fixes the ordering problem.

        Converts Series objects to DataFrames to access join method
        Use kwargs to pass through to repeated join method
        """
        indframe_seq = iter(ndframe_seq)
        # Use the first ndframe object as the base for the final
        final_df = pd.DataFrame(next(indframe_seq))
        for dataframe in indframe_seq:
            if isinstance(dataframe, pd.Series):
                # Convert Series objects into DataFrames since
                # series objects do not have a join method
                dataframe = pd.DataFrame(dataframe)
            # Iteratively build final table
            final_df = final_df.join(dataframe, **kwargs)
        return final_df

**Comment by MikeTam1021** [comment]
How's the efficiency on this?

**Comment by brycepg** [comment]
@MikeTam1021 

I'm not going to benchmark it atm, but I think it would be a function of the size of your DataFrames and the amount of them. It works fine for me for me, but I'm using a small amount of `ndframes` (around 10) and relatively small amount of records for each ndframe (around 100 rows).

My goal is to include all records from every dataframe while preserving order of those records, even if not all ndframes contain data for a given record.

**Comment by nackerley** [comment]
I can't see why preserving column order (as much as possible) isn't the default behaviour of concat().

My workaround uses `unique_everseen` from the [Itertools Recipes](https://docs.python.org/3/library/itertools.html#recipes).

```python
columns = unique_everseen([column for df in dfs for column in df.columns])
df = pd.concat(dfs)[columns]
```

**Comment by h-vetinari** [comment]
+1, very annoying behaviour (especially for `append` - who could reasonably expect that this permutes the columns in the `DataFrame`?!).

**Comment by mrTsjolder** [comment]
Any updates on the status of this thread? I am currently using version 0.22.0 and there still seems to be no proper solution. Procrastination seems to be quite an issue here... 

I would also like to note that similar behaviour can be found when concatenating columns, i.e. `axis=1`, but only when passing the dataframes in a dictionary:

```
>>> df4a = DataFrame(columns=['C','B','D','A'], data=np.random.randn(3,4))
>>> df4b = DataFrame(columns=['C','B','D','A'], data=np.random.randn(3,4))
>>> df5  = DataFrame(columns=['C','B','E','D','A'], data=np.random.randn(3, 5))

>>> pd.concat([df4a, df5], axis=1).columns
Index(['C', 'B', 'D', 'A', 'C', 'B', 'E', 'D', 'A'], dtype='object')
>>> pd.concat({'df4a': df4a, 'df4b': df4b}, axis=1).columns.levels
FrozenList([['df4a', 'df4b'], ['C', 'B', 'D', 'A']])
>>> pd.concat({'df4a': df4a, 'df5': df5}, axis=1).columns.levels
FrozenList([['df4a', 'df5'], ['A', 'B', 'C', 'D', 'E']])
```

**Comment by TomAugspurger** [comment]
> Any updates on the status of this thread?

Still open.

> Procrastination seems to be quite an issue here...

Procrastination?

**Comment by smcinerney** [comment]
@jtratner: in case it wasn't obvious from my examples at the top, I'd expect the order to be:

- shared columns, unsorted
- columns unique to df1, unsorted (i.e. in order in which they occur in df1)
- columns unique to df2, unsorted (i.e. in order in which they occur in df2)

This is what you get in other packages or languages, e.g. SQL. There should never be an unwanted automatic sort. If the user wants to sort the column names, let them do that manually.

**Comment by MikeTam1021** [comment]
Hey guys, 2 things. 1) Welcome to pandas! I suggest just using more python native types like dictionaries. Stop trying to turn python (or any language) into SQL. 2) This is not technically a bug. It is just an unwanted effect of the code. You can easily overcome it outside the context of the package, and that is what I would think is the correct answer unless someone here takes it upon themselves.

**Comment by jmwoloso** [comment]
@MikeTam1021 please explain how to overcome this outside the context of the package. Thanks.

**Comment by MikeTam1021** [comment]
I’m pretty sure that’s exactly what people in this thread have been discussing. I see lots of good solutions above that should work.

**Comment by h-vetinari** [comment]
@MikeTam1021 It's not about turning pandas into SQL (heaven forbid!), but I couldn't agree more with:
> There should never be an unwanted automatic sort. If the user wants to sort the column names, let them do that manually.

Concatenating DataFrames should have the same effect as "writing them next to each other", and that implicit sort definitely violates the principle of least astonishment.

**Comment by MikeTam1021** [comment]
I agree. It shouldn’t. It also assumes an order to the columns, which is SQLish, and not pure computer science. You should really know where you’re data is.

I hardly use pandas anymore after discovering this and many other issues. It has made me a better programmer.

**Comment by armant** [comment]
+1 on this

**Comment by bcucek** [comment]
This works for me:

`cols = list(df1)+list(df2)
df1 = pd.concat([df1, df2])
df1 = df1.loc[:, cols]`

**Comment by DavidEscott** [comment]
I have to bitch about how this patch is rolled out. You have simultaneously changed the function signature of `concat` AND introduced a warning about the usage. All within the same commit.

The problem with that is that we use pandas on multiple servers and cannot guarantee that all servers have the exact same version of pandas at all times. So now we have less technical users seeing warnings from programs they have never seen before, and are uncertain if the warning is a sign of a problem.

I can readily identify WHERE the warning is coming from, but I can't add either of the suggested options because that would break the program on any server running an older version of pandas.

It would have been preferable if you put the sorting capability in to 0.23, and added the warning to some later version. I know its a pain, but it's rather obnoxious to assume that the users can immediately update all deployments to the latest code.

**Comment by DavidEscott** [comment]
@TomAugspurger There are a multitude of ways that we on our side can deal with this. Certainly filtering warnings is one. Its not great because the mechanics of warnings filters are a bit ugly... 

1. I would have to add the filter to multiple programs
2. Not a great way to specify a specific warning to filter:
 * I can filter by module and lineno, but that isn't a stable reference, 
 * I can filter by module and `FutureWarning` but then I wouldn't get any warnings at all from pandas and would be surprised by other changes, 
 * or I can filter by your long multi-line message
3. And then remember to take that filter out when everything is upgraded and it no longer matters.

In any case the deficiencies in the `warnings` module are certainly not something I can put at the foot of the pandas team.

Nor is it your fault that we have an older server we can't easily upgrade, so that would be the other thing I can do (just upgrade all the damn deployments). Ultimately, I recognize that I have to do that and that it is my responsibility to try and keep our deployments close together.

It just seems a bit bizarre to me that you were so concerned about a possible change in user visible end behavior that you added this sort option to what was previously an underspecified API, and yet have simultaneously thrown a warning at the programmer... both the warning and the proposed change in sort behavior constitute "user visible behavior" in my book, just of different severities.

**Comment by SHi-ON** [comment]
I've [answered](https://stackoverflow.com/a/56737702/3782119) a related question on SO.
