### ISSUE TITLE
TYP: returning None for __init__

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#46337]
xref https://github.com/pandas-dev/pandas/pull/44677#discussion_r771575699

we originally had a decision not to type annotate returning None for __init__

can other folks weigh in here? We have a number of PRs which do exactly this (I merged one or 2 then saw the comments)
e.g. https://github.com/pandas-dev/pandas/pull/46283 and a few others.

cc @simonjayhawkins @twoertwein @Dr-Irv @phofl

**Comment by twoertwein** [comment]
I'm in favor of adding `-> None` (but wouldn't object for not adding it either)

From PEP 484:

> (Note that the return type of __init__ ought to be annotated with -> None. The reason for this is subtle. If __init__ assumed a return annotation of -> None, would that mean that an argument-less, un-annotated __init__ method should still be type-checked? Rather than leaving this ambiguous or introducing an exception to the exception, we simply say that __init__ ought to have a return annotation; the default behavior is thus the same as for other methods.)

As far as I understand it: we should definitely add `-> None` if we have an `__init__` that otherwise wouldn't have any type annotations.

**Comment by Dr-Irv** [comment]
Looking at `numpy`, it seems they have done this, and since they are way ahead on typing than we are, we should follow in the footsteps of giants and thus I favor adding `-> None` to the return types for `__init__()` throughout the code, probably as one big PR.

**Comment by simonjayhawkins** [comment]
I think that now we are looking to make the pandas types public, we should probably add the `None` since the assumed return type was a mypy thing and users type checking their code may use other type checkers, so we should probably now follow the pep.

In the early days, before we had `check_untyped_defs=True`, adding the `None` ensured that the function body was checked for `__init__` methods with no arguments to type, so there would have been some advantage to adding it selectively, but it was decided that in general it was redundant and therefore not needed.

**Comment by simonjayhawkins** [comment]
> but it was decided that in general it was redundant and therefore not needed.

from https://github.com/pandas-dev/pandas/pull/27418#discussion_r304044443

> pseudo-standard internally not to add

so maybe why not formalized in https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#style-guidelines.

**Comment by jreback** [comment]
ok i am going to merge the existing PRs.

let's close this issue with an update for the style guide. (and ideally change everything in a small number of PRs)
