### ISSUE TITLE
Question: why use Azure for CI?

### ISSUE THREAD

**Issue by jonashaag** [pandas-dev/pandas#46351]
What’s the reason that pandas uses GHA alongside Azure? What does Azure provide that GHA doesn’t?

**Comment by jreback** [comment]
it's not that

we used azure for everything before GHA existed

we switched a bunch over recently

cc @mroeschke

**Comment by mroeschke** [comment]
Legacy mostly I think since Azure was available before GHA.

One thing to note is that since the project uses the free plan, we can only run 20 GHA jobs concurrently (although 1 push already runs 20+ jobs), so migrating the 7 Azure jobs would add a little pressure to that. https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

That being said, I don't think Azure has anything novel compared to GHA so I'd be +1 to just move them to GHA despite the above so our CI configs can be more consistent

**Comment by jonashaag** [comment]
Great to hear.

**Comment by jonashaag** [comment]
IMO for non-enterprise projects Azure is strictly worse than GHA. Only good thing is that it has 3 vCPU vs 2 in GHA
