### ISSUE TITLE
Randomly select specific value in dataframe using sample methods

### ISSUE THREAD

**Issue by soap945** [pandas-dev/pandas#46438]
#### Issue Context

I found it is hard for me to retreive specific value by using the pd.DataFrame.Sample methods. One of the case I am working on is to retreive 20% of 'Windows' term from a column first, and then replace 'Windows' by 'Apple'. However, so far, it seems that I am unable to filter 'Windows' in sample methods, which only samples all the values in the column including 'Apple' and 'Windows'. 

#### Describe the solution you'd like

I feel like it is necessary to have one parameter within this sample methods to assign given values. Or if there is an optional way that I should know, I appreaciate your kindly help.

#### API breaking implications

Not sure about API thing here

#### Alternatives

So far, I didn't figure solutions on this one by trying many ways, including regularization, random.chocies, random.sample. None of them works for me. Maybe I still need to learn to figure this out. But, it would be so much easier to have one parameter be set up within the sample function.

```python

#DataFrame random sample 
ran_df = df['ran_dt'].sample(n=43, replace=False)

print(ran_df)

rep_df = ran_df.replace('Windows','Apple', inplace=True)

print(df['DeviceType'].value_counts())

```

**Comment by attack68** [comment]
This example is not great because you are aware of your context and problem whereas no one else is. It is difficult to see what you are trying to do without a clear example. It would be best to create a minimalist example (say a dataframe with 4 rows and sample 2 of them)

Saying that i think i know what you are trying to do and believe your code is buggy or you are simply not using the correct methods. However I will reserve judgement until a clearer example is posted.

**Comment by soap945** [comment]
Appreciate your replying. I figure out how to solve this issue which is a simple question in final. Your are right, there is logic issue of my previous codes.
