### ISSUE TITLE
BUG: iterparse on read_xml overwrites with attributes on child elements 

### ISSUE THREAD

**Issue by bailsman** [pandas-dev/pandas#47343]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
from tempfile import NamedTemporaryFile
import pandas as pd

XML = '''
<issue>
  <type>BUG</type>
  <reporter type="newbie">Emanuel</reporter>
</issue>
'''.encode('utf-8')

with NamedTemporaryFile() as tempfile:
    tempfile.write(XML)
    tempfile.flush()
    df = pd.read_xml(tempfile.name, iterparse={'issue': ['type']})
    issue_type = df.iloc[0]['type']
    print(f"issue_type: expecting BUG, got {issue_type}")
```

### Issue Description

The parsing code parses attributes on all child elements, rather than just on the main element.

This is probably unintentional - in the example above, the user is most likely interested in the type of the incident rather than the type attribute on some child element.

This feature is planned for 1.5.0 and not yet released. See: https://github.com/pandas-dev/pandas/pull/45724#issuecomment-1154200083

### Expected Behavior

Attributes are parsed only on the toplevel element.

### Installed Versions

5465f54f7640cbb4be9b223846823d4935142431

**Comment by ParfaitG** [comment]
Interesting side effect and possibly an edge case. Parser builds a dictionary using element or attribute names as keys. Since same named attribute is after the same named element, dictionary retains the last value. Reverse the reporter and type nodes and you will then return `BUG`. 

Since iterparse does not know levels (i.e., parent, child) but indiscriminately walks down the tree parsing then discarding each element, behavior should align more with `names` argument which is supported in iterparse but after parsing not during like XPath. Per [docs](https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html) with emphasis:

> Column names for DataFrame of parsed XML data. Use this parameter to rename original element names and _distinguish same named elements_.

So, one thought is the user should pass *names* to rename duplicate XML names.
```python
df = pd.read_xml(tempfile.name, iterparse={'issue': ['type', 'type']}, names=["type_elem", "type_attr"])

df
  type_elem type_attr
0       BUG    newbie
```

However, given how iterparse iterates down the tree, passing same names causes it to repeatedly overwrite the dictionary value. Will give this some thought. For now, if XML really isn't that large and users are using `iterparse` in lieu of `xpath`, consider running XSLT via `stylesheet` argument to rename the same named items then `iterparse` the document.

**Comment by bailsman** [comment]
You have to be very careful to put your names in the correct order (maybe someone will say 'Well... obviously!') - but once you do that it works perfectly! Thanks!
