### ISSUE TITLE
BUG: cannot safely cast non-equivalent float64 to Int64

### ISSUE THREAD

**Issue by BabakAmini** [pandas-dev/pandas#47353]

**Comment by TohidN** [comment]
This error still exists and the error message is not very helpful.

This is usually caused by either passing a number beyond scope of your target(here int64) or possibly converting an NA, check the minimum and maximum number you can fit into an int64 here:
min = -9223372036854775808
max = 9223372036854775807
according to:
```python
import numpy as np
print(np.iinfo(np.dtype('int64')))
```
then search for maximum number in the column you are converting to see if it fits.
