### ISSUE TITLE
DOC: Malformed list in sphinx output and other problems with "ExcelWriter" doc

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [pandas-dev/pandas#47526]
https://github.com/pandas-dev/pandas/blob/e8093ba372f9adfe79439d90fe74b0b5b6dea9d6/pandas/io/excel/_base.py#L762-L766

The list is not shown in the [sphinx output](https://pandas.pydata.org/docs/reference/api/pandas.ExcelWriter.html). But I am not a sphinx expert so I don't know the solution.

There are some more problems with that section.
- The DataFrame.to_excel should be formated as code and as a link to the [relevant doc section](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html).
- The three terms "xls", "xlsx" and "ods" should be rename into "xls files", "xlsx files" and "ods files".
- The suggested modules ("xlwt", "xlsxwriter", "openpyxl", "odf") should be formated as `code`.
- The three modules should also point to there related package. e.g. "`odf` (package [`odfpy`](https://pypi.org/project/odfpy/)) for ods files".

**Comment by datapythonista** [comment]
Thanks for reporting this @Codeberg-AsGithubAlternative-buhtz. I think we should remove the space before the colon in the first line, and leave blank lines before and after the list.

The rest of the suggestions sound good to. Sphinx is using restructuredtext, you have the basic syntax here. If you want to open a pull request addressing all those, that would be amazing. Ping me when it's ready, or if you have any problem. Thanks!

**Comment by datapythonista** [comment]
You have information on how to set up a development environment here: https://pandas.pydata.org/docs/development/contributing.html

**Comment by noatamir** [comment]
take

**Comment by noatamir** [comment]
👋 @datapythonista 
1. I noticed that later in the docstring `odswriter` is mentioned as the keyword for ods. But in the issue `odfpy` was suggested as the link for the odf related package. Should I continue with `odfpy` or change to `odswriter`?
2. FYI, in docstrings I can either make the modules be links to the PyPI packages, or appear as code, but not both at the same time. I was going to go with the links because I think it provides more helpful information than just formatting. Unless you know how I can implement a [Parsed-Literal block](https://docutils.sourceforge.io/docs/ref/rst/directives.html#parsed-literal-block) in a dcostring? I haven't found an example for that yet and from a quick look around the Pandas docs it seems like it's either or. 
3. Same goes for the `DataFrame.to_excel`, but here I opt to keep it as code highlight to stay consistent with the format of the docstrings which favor code highlight for internal methods to links.
