### ISSUE TITLE
Why does `index.fillna()` have different arguments than `series.fillna()`? 

### ISSUE THREAD

**Issue by alexlenail** [pandas-dev/pandas#47663]
In particular, why can't `index.fillna()` have a inplace argument? 

- [`index.fillna`](https://pandas.pydata.org/docs/reference/api/pandas.Index.fillna.html)
- [`series.fillna`](https://pandas.pydata.org/docs/reference/api/pandas.Series.fillna.html)

**Comment by Aditya-Tripuraneni** [comment]
If I understand this question correctly, `series.fillna()` has different arguments than `index.fillna()` because with _series_ you can specify the **method** you want to use along with the limit. The limit will simply see how many elements are being affected. I believe since it is _series_ that is why you can specify the **method** and **limit** as arguments vs  `index.fillna()` where you are simply replacing holes with a scalar value.   

I think the reason that `index.fillna()` does not have an _inplace_  can be found here. [Pandas won't fillna()](https://stackoverflow.com/questions/21998354/pandas-wont-fillna-inplace)

**Comment by phofl** [comment]
Index is immutable, hence inplace does not make sense.
