### ISSUE TITLE
ENH: Support partitioning by index (especially multi-index columns) in to_parquet

### ISSUE THREAD

**Issue by gwerbin** [pandas-dev/pandas#47797]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

In a data frame with a multiindex, with a slowly-varying "outer" index level, one might want to partition by that index level. This is currently not possible without resetting and un-resetting the index upon saving, because `partition_cols=` in `to_parquet` only supports "data" columns and not "index" columns.

### Feature Description

Unsure at this time; I am not clear on where the "separation of responsibility" lies between Pandas and PyArrow/FastParquet.

### Alternative Solutions

Is it possible to implement this "unilaterally" inside PyArrow, without making changes to Pandas itself?

**Comment by mroeschke** [comment]
Thanks for the request. I believe this would need to be implemented by PyArrow. `to_parquet` just converts the `pandas.DataFrame` to a `pyarrow.Table` via https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.from_pandas then utilizes `pyarrow.parquet.write_table` https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html#pyarrow.parquet.write_table

Since the handling of a MultiIndex is done on the Arrow side, closing as in scope for PyArrow instead

**Comment by gwerbin** [comment]
Thanks @mroeschke , I created a feature request on the PyArrow issue tracker <https://issues.apache.org/jira/browse/ARROW-17200>.
