### ISSUE TITLE
WEB: Review donation options for pandas

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#47960]
In #47931 @logankilpatrick suggested that we add support for GitHub sponsors to pandas. I don't know much about it, but seems like we've got it enabled, but just providing links to our donations page and tidelift. I guess we can set it up to receive donations directly.

Besides it, we've got now https://opencollective.com/pandas which also handles donations, and I think it's intended to replace the current salsa donations we're currently using in our website.

Also, maybe we want to discuss whether out [Contribute](https://pandas.pydata.org/contribute.html) page has the visibility and the options that we want. I think naming the section `Contribute` may sound to much as helping pandas with coding. Renaming it to `Donate` may sound as just giving individual donations. Would it make sense to rename it to something else where it's more clear for visitors of the website that they can contribute code, corporate sponsorship, money... Not sure if something like `Help pandas`, `Get involved`... Probably native English speakers can find something better. Also, would it be worth adding Tidelift to the options in that page? Or anything else?

**Comment by attack68** [comment]
As someone who has only recently started reading into this, it strikes me either that the information isn't there or that I'm particularly poor at parsing it.

If I was interested in funding pandas you can assume that I know nothing about funding of open source and I would want to know:

- What are the different channels that pandas receives funding. If I'm reading specifically it seems like Donations page gives rise to specific grants from organisations such as Tidelift, and NumFocus, and there are channels for indiviudals to make smaller donations via web forms? 
- I think that anyone who has made a grant should be listed somewhere with their Name, donation amount and possibly intended use (unless for any reason they request it to be anonymous). Since the project is open source I also assume that the accounting is publicly available so there is no reason to keep any of the figures confidential.
- I think there is much scope to better advertise for funding also. Confusing "contributing" with code contributions and monetary contributions is a bad idea. I think this should be much clearer. Phrases such as "Pandas needs your help to continue to develop" or otherwise and trying to promote funding I think should be a focus on the site. Today, the money may not be fully utilised, but down the line when the software is mature / saturated and requires more maintenance it might be more necessary to have it to pay dedicated maintainers.

If I was a major contributor I would expect to be able to see a history and governance of previous grants so that I feel confident my grant will not be abused or subject to fraud, from any rogue member (or ex member) with spurious account permissions etc. So a comment in this regard might be useful too (or some link to governance principles, which might exist already?).

**Comment by mroeschke** [comment]
This file sets up sponsorship links for the repo and all repos under our org: https://github.com/pandas-dev/.github/blob/master/FUNDING.yml

Personally, I don't think it's great that we have 3 links to make a monetary donation. IMO we should just use the https://opencollective.com/pandas since it's very transparent documenting money coming in & out.

If we want to encourage more financial contributions though the website instead of the, we should probably make https://pandas.pydata.org/about/sponsors.html it's own tab (`Sponsor`?) to reduce the click through to make a monetary donation.

**Comment by datapythonista** [comment]
Superseeded by #60360
