### ISSUE TITLE
CI: setuptools 64.0.0 breaks our builds

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48046]
This is one of the failing builds:

https://github.com/pandas-dev/pandas/runs/7795489269?check_suite_focus=true

setuptools 64.0.0 is installed there. Previously we had 63.4.3

Edit: https://setuptools.pypa.io/en/stable/history.html#breaking-changes

https://github.com/pypa/setuptools/issues/3501

**Comment by jorisvandenbossche** [comment]
They already made a fix to setuptools itself (https://github.com/pypa/setuptools/pull/3506), avoiding us to update the vendored versioneer files (although that might still be useful to do as well at some point). And it seems this is already released as setuptools 64.0.2

**Comment by phofl** [comment]
Oh nice.

Should we add something to avoid the buggy versions?

**Comment by jorisvandenbossche** [comment]
I don't think that's needed (I _think_ we have had versions of setuptools in the past that broke something and which got fixed in a bug fix release, and we are also not excluding those versions explicitly). 
Although including it temporary on the short term could avoid some people running into it and not understanding what is happening? (for people that might have installed setuptools in those two days where that was the latest version)

**Comment by phofl** [comment]
Yes, we pinned them temporarily too I think and removed it after some time. But since they fixed it that quick it might be more trouble than it's worth? Not sure...

**Comment by mroeschke** [comment]
I don't think it's needed either IMO. In theory we should have specified our setuptool version to avoid all the breaking versions, but I think that ship has sailed and our general assumption is to use the latest version

**Comment by phofl** [comment]
Closing, since it seems to work consistently
