### ISSUE TITLE
DOC: Styler.to_latex link is broken in DataFrame.to_latex documentation

### ISSUE THREAD

**Issue by FrnRmn** [pandas-dev/pandas#48089]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_latex.html

### Documentation problem

In the See Also section of [DataFrame.to_latex](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_latex.html) documentation the element Styler.to_latex has broken internal reference link.

### Suggested fix for documentation

It could be fixed by adding the[ Styler.to_latex link](https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_latex.html) to the corresponding element in the See Also section. This would make the doc more complete.

**Comment by attack68** [comment]
PRs to fix are very welcome

**Comment by samrao1997** [comment]
take

**Comment by samrao1997** [comment]
I have made a PR that updates the "See Also" of `DataFrame.to_latex` to have a corrected link to `Styler.to_latex`. 

I attempted to make the text just `Styler.to_latex` but the link remained broken after some investigation, I noticed that it was a submodule. I then imitated how the link to the `Styler` is displayed in [DataFrame.style](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.style.html) in the "See Also" section. 

This is my first contribution so I spent some time attempting to figure out how the links work. I discovered the link assume a prefix path of the module of the page you are on. What I mean by that, is the links in the "See Also" section of [Styler.text_gradient](https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.text_gradient.html#pandas.io.formats.style.Styler.text_gradient) only needs `Styler.background_gradient` because it assumes the prefix is `io.formats.style` so the link remains good. However, in the "See Also" section of [Styler](https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.html) the link to `DataFrame.style` doesn't work because it doesn't live at the same submodule path.

That is why I hade to add `io.formats.style` to the text of the `DataFrame.to_latex()` because it assumes that path is at the highest level.


Let me know if I am misunderstanding anything here. This is my first contribution and am a noob to open-source development.


Oh and I attached a screen shot of the update to the text with working links.
<img width="1552" alt="Screen Shot 2022-08-15 at 17 55 45" src="https://user-images.githubusercontent.com/29559404/184765440-f0ee72ee-e8af-4c1c-bb5d-a3507a0eb745.png">

**Comment by datapythonista** [comment]
Excellent, I didn't know that was the problem, but makes sense, thanks for the research. If you find a way to validate in the CI that there are no more broken links in the see also section, that would be very useful. I think numpydoc is what should be complaining when rendering. Maybe there is a parameter or something that we can use.
