### ISSUE TITLE
CI: Mambaforge upgrade base image to 3.10 in docker build

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48382]
Mambaforge upgraded the python version to 3.10 in their image causing our builds to fail. The first affected version is 4.14.0-0

Failing build:
https://github.com/pandas-dev/pandas/runs/8171619523?check_suite_focus=true

**Comment by mroeschke** [comment]
Generally, it's probably got great that in our Dockerfile that we're trying to update the `base` 3.10 environment with our 3.8 `environment.yml` as it appears conda/mamba is still trying to use 3.10 packages to update the environment.

A guess also is that downgrading certifi here (because of installing `environment.yml`?) is also probably not good.
```
  - certifi                                2022.6.15  py310hff52083_0     conda-forge                   
  + certifi                                2022.6.15  pyhd8ed1ab_1        conda-forge/noarch       158kB
```
