### ISSUE TITLE
API: find_common_type([dt64tz1, dt64tz2]) -> UTC

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#48453]
ATM find_common_type between two different DatetimeTZDtypes gives object.  But there are a bunch of places where, if we find mismatched tzs, we cast to UTC.  Would it make sense to make this the result of find_common_type?

Locations where we use this pattern (WIP, will update):
- generic._align_as_utc
- merge/join, specifically _factorize_keys
- DTI._maybe_utc_convert (only used in union_many, which is deprecated)
- Index._maybe_promote
- Index._deprecate_dti_setop

**Comment by mroeschke** [comment]
Curious how this would affect external API behaviors e.g. `to_datetime([dt64tz1, dt64tz2]) -> object`. IIRC I addressed cases like this (resolving >1 tz from inputs) to coerce to object because otherwise a transformation would be lossy.

But I realize a lot of other operations like setops convert the result to UTC, so if we generally want to head in that direction for all ops for consistency that would make sense.
