### ISSUE TITLE
Governance: pandas workgroups

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#48462]
xref #47694, #47706

I think the organization of the core development team would be more efficient if we have small workgroups with well defined responsibilities, and there is a clearer expectation on who is going to take care of different things.

Personally, I'd limit most workgroups to 3 people, with a leader or chair. This would make sure it's clear who is expected to take care of things, while ensuring there are backups in all workgroups. I think members of most workgroups should be core devs (e.g. people who needs the credentials to servers, or have access to manage the project finances). Things can probably be structured in different ways, but one idea could be (feedback very welcome):

**finance**
(not sure if splitting grants and sponsors into different workgroups would be better)
- approve project payments and contracts
- manage grant proposals (CZI, NF small dev grants)
- manage sponsors

**infrastructure**
- manage the credentials and permissions for pandas systems
- make sure servers (website, benchmarks) are properly managed (set up, updates, monitoring, backups or whatever needed)
- manage pandas distribution lists
- manage CI systems (ask github for feedback, possibly manage paid plans with providers)

**communications**
- make announcements and publish about pandas in the different channels (distribution lists, twitter, telegram...)
- coordinate with NumFOCUS (send project updates, communicate pandas devs about relevant NumFOCUS announcements...)
- coordinate with other projects

**coc**
(I think this group can and probably should have people not in the core team, and diversity in the workgroup should be enforced)
- manage coc reports to the project
- make sure the project coc stays updated and relevant
- maybe write reports about coc incidents and responses

Other ideas welcome, but I think this would make our work more efficient. If people has interest in joining one of these groups, please comment in the issue.

CC: @pandas-dev/pandas-core

**Comment by attack68** [comment]
I think thats a really good idea.

I think you could have 1 or two more people in some groups (so that an absence here or there would not dramatically reduce concensus)

I would recommend some guidelines so that chairs in one workgroup tend to adopt similar working practices. Setting a schedule for members to check in every so often etc.

I think each group should maintain some core purpose docs and there should be a centralised (permissioned) store for maintaining these so that transitioning to new members is smooth.

I would also recommend that new members have to be aware of any time commitments. Personally, I have very little time and therefore even if I wanted to or was invited to be a part of a working group, depending upon the time commitment I would have to decline. I think this is important for creating functioning groups.

**Comment by datapythonista** [comment]
Thanks for the feedback @attack68, that sounds great. Maybe it makes things easier to create the workgroups first, and let them work on the guidelines, docs... But either way, it sounds very useful.

I think most of the tasks of the workgroups require little time. I personally wouldn't ask for a time commitment, as even couple of hours per month can make a difference (in approving invoices, tweeting, rebooting a server...). I think it's more important that tasks are done, and that they are not forgotten because everybody expects someone else to take care of them. That's why I think smaller groups are better.

There is the exception of the CoC, where having more point of views can be beneficial to make better decisions.

In any case, I'm surely open to have groups with 4 or 5 people, and to have guidelines for time commitments.

**Comment by datapythonista** [comment]
We have some workgroups reasonably defined now. Updating or creating new workgroups is an ongoing task that will keep happening, but closing this issue, since there is no specific action to take. And probably better to create a new issue with the exact topic when there is the need.
