### ISSUE TITLE
BUG: pd.Series.unstack with mixed names types

### ISSUE THREAD

**Issue by gravesee** [pandas-dev/pandas#48763]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

arrays = [["a", "a", "a", "a"], [1, 1, 2, 2], ["red", "blue", "red", "blue"]]

# create multi-index with mixed name types
idx = pd.MultiIndex.from_arrays(arrays, names=("letter", 0, "color"))
s = pd.Series([1,2,3,4], index=idx)

print(s.unstack('letter'))

# output does not show the 'letter' level unstacked
#> 0             1  2
#> letter color
#> a      blue   2  4
#>        red    1  3

# change the name to a string
idx = pd.MultiIndex.from_arrays(arrays, names=("letter", "0", "color"))
s = pd.Series([1,2,3,4], index=idx)

print(s.unstack('letter'))

# output shows the correct level unstacked
#> letter   a
#> 0 color
#> 1 blue   2
#>   red    1
#> 2 blue   4
#>   red    3
```

### Issue Description

When calling pd.Series.unstack using a multi-index with mixed string and integer names, the incorrect level is unstacked when referencing a string level. When all of the levels are string, however, the correct level is unstacked.

### Expected Behavior

pd.Series.unstack should always unstack the requested level regardless of the types of the level names in the multi-index

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_United States.1252

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 57.4.0
pip              : 21.2.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by JanTinbergen** [comment]
After some investigation, I think I have found the issue:

1. The documentation of pandas.MultiIndex.from_arrays states that the provided names should be a sequence of strings. However, evidently, at no point is this enforced in said function. Moreover, in the constructor of the MultiIndex it does not happen either (handled by the function _set_names). 

2. The reason that this is problematic stems from reshape.py [line 473-475]:
```
if not is_integer(level) and not level == "__placeholder__":
     print('not integer')
     level = obj.index._get_level_number(level)
```
in combination with reshape.py [line 104-106 in the _Unstacker class]:

```
self.index = index.remove_unused_levels()

self.level = self.index._get_level_number(level)
```
where the same logic is repeated. The function `_get_level_number` attempts to find the list-index of the provided level(name). In your case, after the first code snippet the level becomes 0 as 'letter' is the first element in the names. However, after the second code snippet the level becomes 1 as 0 is the second element in the provided names. As such, the unstack function eventually unstacks based on the second level rather than the first. 

3. Therefore, the clear solution is to enforce the documentation provided by pandas.MultiIndex.from_arrays, namely that the input argument names should be a sequence of strings.

I will look into making an PR for this.

**Comment by JanTinbergen** [comment]
take

**Comment by gravesee** [comment]
This came up when I performed a groupby on a series using a data frame with mixed column name types.
