### ISSUE TITLE
BUG: pd.compare does not recognize differences with the nullable Int64 data type

### ISSUE THREAD

**Issue by sergiykhan** [pandas-dev/pandas#48939]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

x = pd.Series([1, 2, np.NaN], dtype='Int64')
y = pd.Series([1, 2, 3], dtype='Int64')
x.compare(y)
```

### Issue Description

`.compare` does not return the difference between two Series

Result:

```
     self  other
```

### Expected Behavior

```
     self  other
2    NaN   3
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.9.14.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0
numpy            : 1.23.2
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.0.0
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.40
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2022.2

</details>

**Comment by vamsi-verma-s** [comment]
Hi @phofl 
I would like to contribute. 

I see this issue is somewhat related to https://github.com/pandas-dev/pandas/issues/44014 

the problem seems to be that the mask value evaluated like below ends up having NA values - 
https://github.com/pandas-dev/pandas/blob/e25aa9d313dc372c70d826e3c57c65b6724190e5/pandas/core/generic.py#L9264

I think, since the mask here is to simply determine if there are differences, if a comparison has an `NA` result, we can consider it as a difference instead of missing/ignoring this comparison result. 

A naive solution I have is to fill `NA` values in the mask as `True` to mark the values as different. 

Making this change currently fails one test that was added to fix -  https://github.com/pandas-dev/pandas/issues/44014 

https://github.com/pandas-dev/pandas/blob/e25aa9d313dc372c70d826e3c57c65b6724190e5/pandas/tests/frame/methods/test_compare.py#L241-L254
When comparing the below dataframes - 


df1 
```
     a    b
0  4.0  1.0
1  4.0  2.0
```
df2
```
      a    b
0     1  1.0
1  <NA>  2.0
```

the test expects the result to be - 

```
     a          b
  self other self other
0  4.0     1  NaN   NaN
1  NaN  <NA>  NaN   NaN
```

I think it should be - 

```
     a          b
  self other self other
0  4.0     1  NaN   NaN
1  4.0  <NA>  NaN   NaN
```

please let me know if this makes sense and I can go ahead with PR or if there is something I'm missing here

**Comment by phofl** [comment]
Yep makes sense. The test if off. Please also add tests with pd.NA and pd.NA, I think this should be considered different, but not 100% sure.

**Comment by vamsi-verma-s** [comment]
an existing test compares having 2 `NaN` values and expects it to be considered same. is there any reason `pd.NA` should behave differently?

https://github.com/pandas-dev/pandas/blob/e25aa9d313dc372c70d826e3c57c65b6724190e5/pandas/tests/frame/methods/test_compare.py#L94-L109

**Comment by vamsi-verma-s** [comment]
@phofl could you please review the PR. I have added additional tests for `pd.NA` . Let me know if anything else is required.
