### ISSUE TITLE
BUG:  testing for "in pd.array" with mixed types throws an error

### ISSUE THREAD

**Issue by liquidcarbon** [pandas-dev/pandas#48930]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
Python 3.10.6 (main, Aug 24 2022, 17:56:58) [GCC 10.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.


In [1]: import numpy as np; import pandas as pd; pd.__version__
Out[1]: '1.5.0'

In [2]: n = np.array(['__contains__', 1]); p = pd.array(['__contains__', 1])

In [3]: '__contains__' in n
Out[3]: True

In [4]: '' in n
Out[4]: False

In [5]: '' in p
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 '' in p

File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pandas/core/arrays/base.py:442, in ExtensionArray.__contains__(self, item)
    438         return False
    439 else:
    440     # error: Item "ExtensionArray" of "Union[ExtensionArray, ndarray]" has no
    441     # attribute "any"
--> 442     return (item == self).any()

File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pandas/core/ops/common.py:72, in _unpack_zerodim_and_defer.<locals>.new_method(self, other)
     68             return NotImplemented
     70 other = item_from_zerodim(other)
---> 72 return method(self, other)

File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pandas/core/arraylike.py:43, in OpsMixin.__eq__(self, other)
     41 @unpack_zerodim_and_defer("__eq__")
     42 def __eq__(self, other):
---> 43     return self._cmp_method(other, operator.eq)

File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pandas/core/arrays/numpy_.py:406, in PandasArray._cmp_method(self, other, op)
    404 other = ensure_wrapped_if_datetimelike(other)
    405 with np.errstate(all="ignore"):
--> 406     result = pd_op(self._ndarray, other)
    408 if op is divmod or op is ops.rdivmod:
    409     a, b = result

File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pandas/core/ops/array_ops.py:287, in comparison_op(left, right, op)
    284     return invalid_comparison(lvalues, rvalues, op)
    286 elif is_object_dtype(lvalues.dtype) or isinstance(rvalues, str):
--> 287     res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
    289 else:
    290     res_values = _na_arithmetic_op(lvalues, rvalues, op, is_cmp=True)

File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pandas/core/ops/array_ops.py:75, in comp_method_OBJECT_ARRAY(op, x, y)
     73     result = libops.vec_compare(x.ravel(), y.ravel(), op)
     74 else:
---> 75     result = libops.scalar_compare(x.ravel(), y, op)
     76 return result.reshape(x.shape)

File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pandas/_libs/ops.pyx:32, in pandas._libs.ops.scalar_compare()

ValueError: Does not understand character buffer dtype format string ('w')
```

### Issue Description

Testing for the presence of a string in an array works for
- `np.array`
- `pd.Series` (not shown)
but not for `pd.array`

### Expected Behavior

Same behavior as for numpy array and pandas series

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0
numpy            : 1.23.2
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.2.0
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by NaveenMargam** [comment]
Hi @liquidcarbon 
In pandas, In case of array operation

<html>
<body>
<dt style="box-sizing: border-box; font-weight: 700; color: rgb(50, 50, 50); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bolder;">dtype</strong><span class="classifier" style="box-sizing: border-box; font-style: oblique;"> str, np.dtype, or ExtensionDtype, optional</span></dt><dd style="box-sizing: border-box; margin-top: 3px; margin-bottom: 10px; margin-left: 30px; color: rgb(50, 50, 50); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 0px; font-size: 1em; color: var(--pst-color-text-base);">The dtype to use for the array. This may be a NumPy dtype or an extension type registered with pandas using<span> </span><a class="reference internal" href="https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.register_extension_dtype.html#pandas.api.extensions.register_extension_dtype" title="pandas.api.extensions.register_extension_dtype" style="box-sizing: border-box; color: var(--pst-color-link); background-color: transparent; text-decoration: none;"><code class="xref py py-meth docutils literal notranslate" style="box-sizing: border-box; font-family: var(--pst-font-family-monospace); font-size: 13.125px; color: inherit; overflow-wrap: break-word; background-color: var(--pst-color-surface); font-weight: bold; padding: 0.1rem 0.25rem; border: 1px solid var(--pst-color-on-surface); border-radius: 0.25rem;"><span class="pre" style="box-sizing: border-box; hyphens: none; white-space: nowrap;">pandas.api.extensions.register_extension_dtype()</span></code></a>.</p><p style="box-sizing: border-box; margin: 0px; font-size: 1em; color: var(--pst-color-text-base);">If not specified, there are two possibilities:</p><ol class="arabic simple" style="box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; list-style: decimal;"><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin: 0px 0px 0.25rem; font-size: 1em; color: var(--pst-color-text-base);">When<span> </span><cite style="box-sizing: border-box;">data</cite><span> </span>is a<span> </span><a class="reference internal" href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series" title="pandas.Series" style="box-sizing: border-box; color: var(--pst-color-link); background-color: transparent; text-decoration: none;"><code class="xref py py-class docutils literal notranslate" style="box-sizing: border-box; font-family: var(--pst-font-family-monospace); font-size: 13.125px; color: inherit; overflow-wrap: break-word; background-color: var(--pst-color-surface); font-weight: bold; padding: 0.1rem 0.25rem; border: 1px solid var(--pst-color-on-surface); border-radius: 0.25rem;"><span class="pre" style="box-sizing: border-box; hyphens: none; white-space: nowrap;">Series</span></code></a>,<span> </span><a class="reference internal" href="https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index" title="pandas.Index" style="box-sizing: border-box; color: var(--pst-color-link); background-color: transparent; text-decoration: none;"><code class="xref py py-class docutils literal notranslate" style="box-sizing: border-box; font-family: var(--pst-font-family-monospace); font-size: 13.125px; color: inherit; overflow-wrap: break-word; background-color: var(--pst-color-surface); font-weight: bold; padding: 0.1rem 0.25rem; border: 1px solid var(--pst-color-on-surface); border-radius: 0.25rem;"><span class="pre" style="box-sizing: border-box; hyphens: none; white-space: nowrap;">Index</span></code></a>, or<span> </span><code class="xref py py-class docutils literal notranslate" style="box-sizing: border-box; font-family: var(--pst-font-family-monospace); font-size: 13.125px; color: var(--pst-color-inline-code); overflow-wrap: break-word; background-color: var(--pst-color-surface); font-weight: bold; padding: 0.1rem 0.25rem; border: 1px solid var(--pst-color-on-surface); border-radius: 0.25rem;"><span class="pre" style="box-sizing: border-box; hyphens: none; white-space: nowrap;">ExtensionArray</span></code>, the<span> </span><cite style="box-sizing: border-box;">dtype</cite><span> </span>will be taken from the data.</p></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin: 0px; font-size: 1em; color: var(--pst-color-text-base);">Otherwise, pandas will attempt to infer the<span> </span><cite style="box-sizing: border-box;">dtype</cite><span> </span>from the data.</p></li></ol><p style="box-sizing: border-box; margin: 0px; font-size: 1em; color: var(--pst-color-text-base);">Note that when<span> </span><cite style="box-sizing: border-box;">data</cite><span> </span>is a NumPy array,<span> </span><code class="docutils literal notranslate" style="box-sizing: border-box; font-family: var(--pst-font-family-monospace); font-size: 13.125px; color: var(--pst-color-inline-code); overflow-wrap: break-word; padding: 0.1rem 0.25rem; background-color: var(--pst-color-surface); border: 1px solid var(--pst-color-on-surface); border-radius: 0.25rem;"><span class="pre" style="box-sizing: border-box; hyphens: none; white-space: nowrap;">data.dtype</span></code><span> </span>is<span> </span><em style="box-sizing: border-box;">not</em><span> </span>used for inferring the array type. This is because NumPy cannot represent all the types of data that can be held in extension arrays.</p><p style="box-sizing: border-box; margin: 0px; font-size: 1em; color: var(--pst-color-text-base);">Currently, pandas will infer an extension dtype for sequences of</p>

Scalar Type | Array Type
-- | --
pandas.Interval | pandas.arrays.IntervalArray
pandas.Period | pandas.arrays.PeriodArray
datetime.datetime | pandas.arrays.DatetimeArray
datetime.timedelta | pandas.arrays.TimedeltaArray
int | pandas.arrays.IntegerArray
float | pandas.arrays.FloatingArray
str | pandas.arrays.StringArray or pandas.arrays.ArrowStringArray
bool | pandas.arrays.BooleanArray

</dd>
</body>
</html>

**Input Code :(Above table shows different dtypes available in pandas)**
```python
import pandas as pd;
p = pd.array(['__contains__', 1])
print(p)
for val in p:
    print(type(val))
```
**Output :**
```python
<PandasArray>
['__contains__', '1']
Length: 2, dtype: str672

<class 'numpy.str_'>
<class 'numpy.str_'>
```
**Note: dtype inferenced as str672 by pandas which is not any valid type. All array elements are converted to string type.**

**Input Code : when we give dtype explicitly as object type, then it would be treated as object with different data types and it would not give error when we check**
````python
> import pandas as pd;
> p = pd.array(['__contains__', 1],dtype=object)
> "" in p
False
````
```python
import pandas as pd;
p = pd.array(['__contains__', 1],dtype=object)
print(p)
for val in p:
    if val in p:
        print(type(val),val)
```
**Output :**
```python
<PandasArray>
['__contains__', 1]
Length: 2, dtype: object
<class 'str'> __contains__
<class 'int'> 1
```
**If we want to add custom data type to pandas, you can refer the following page in pandas doc**
https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.register_extension_dtype.html#pandas.api.extensions.register_extension_dtype
or https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionDtype.html#pandas-api-extensions-extensiondtype

**Coming to Series operator, it creates array with data as values and index is as per user defined(custom or default)**
```python
import pandas as pd;
p = pd.Series(['__contains__', 1])
print(p)
for val in p:
    print(val)
```
**Output :**
```python
0    __contains__
1               1
dtype: object
__contains__
1
```
**Series Operation is inferring dtype to Object implicitly. For Array operator custom dtype should be added or make it as object explicitly. I am not sure about this behaviour , why it's been done this way**

I am just adding my view, hope it helps with your query.

**Comment by Aloqeely** [comment]
Thanks for the report! Sorry for the late response but this is fixed on main.
Going to close, feel free to reopen if you still see the issue after v3.0 is released.
