### ISSUE TITLE
DOC: to_html(notebook=bool) seems to have no effect

### ISSUE THREAD

**Issue by janosh** [pandas-dev/pandas#49953]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_html.html

### Documentation problem

Based on the doc str

> Whether the generated HTML is for IPython Notebook.

I was expecting the generated HTML when setting `notebook=True` to look more similar in the browser to how the `Styler` looks looks in Jupyter.

```py
import pandas as pd

df = pd.util.testing.makeDataFrame()

df.style.format("{:.2}").background_gradient(cmap="viridis").to_html(
    "notebook=False.html", notebook=False
)

df.style.format("{:.2}").background_gradient(cmap="viridis").to_html(
    "notebook=True.html", notebook=True
)
```

What I actually get is `notebook=True.html` and `notebook=False.html` looking identical.

| Jupyter (expected) | Browser actual (with `notebook=True/False`) |
| --- | --- |
| ![Screenshot 2022-11-28 at 17 10 58](https://user-images.githubusercontent.com/30958850/204414206-c936b5e1-abb9-4bab-8e4f-f18240d9a726.png) | <img width="348" alt="Screenshot 2022-11-28 at 17 13 58" src="https://user-images.githubusercontent.com/30958850/204414237-0647464c-f3a1-4059-a8db-50077569f8df.png"> |

### Suggested fix for documentation

Would be great if the doc string could be more specific on what effect setting to `notebook=True` is supposed to have.

**Comment by janosh** [comment]
Ah, my bad. Is it deliberately missing from `Styler.to_html`? If not, could this issue be reopened and turned into a feature request?

**Comment by attack68** [comment]
Yes it is deliberately missing from Styler because it is an old argument that used to provide minor data alignment for text in columns. If you compare the output from DataFrame.to_html with the only difference visible in the HTML is,
```
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }
    .dataframe tbody tr th {
        vertical-align: top;
    }
    .dataframe thead th {
        text-align: right;
    }
</style>
```
`Styler` has a `set_table_styles` and other methods available to completely customise the entire table CSS, not just include this very specific block of code (which I believe is now out of date with the behaviour of newer Jupyter and Colab notebooks anyway).

You seem to be suggesting that `notebook=True` makes the HTML automatically look the same as the Jupyter notebook display. It doesn't. Jupyter has its own custom CSS for rendering tables within its cells. Different versions of Jupyter and Colab use different settings and will result in different looking tables. There is no point in creating a setting in pandas that attempts to copy the CSS styles of another software that can change their visual look in a new version. The objective is to give users the ability to define their own.

If you are interested in exploring some different CSS attrubute value pairs, here are those that JupyterNotebook attributes to tables, observed with Chrome element inspectior:
![Screenshot 2022-11-29 at 17 23 20](https://user-images.githubusercontent.com/24256554/204586028-0e6dafcf-7473-47a9-bfc1-3cf6436b3ea0.png)

**Comment by attack68** [comment]
As documented you can actually do this.
```python
styles = {"": "color: red;", "th": "font-weight: bold;}
s.set_table_styles([{"selector": k, props: v} for k, v in styles.items()])
```
The dict version is reserved for allowing users to specific column only styles which is also useful.

A lot of things in `df.to_html` should be deprecated. It has been difficult to get concensus on changing the whole thing.

**Comment by janosh** [comment]
Ah, I missed that CSS strings are supported. Should have tried that. Thanks for pointing it out.

> The dict version is reserved for allowing users to specific column only styles which is also useful.

I see. There could be a flag `as: Literal['columns', 'selectors']`:

```py
styles = {
    "": "font-family: sans-serif; border-collapse: collapse;",
    "td, th": "border: 1px solid #ddd; text-align: left; padding: 8px;",
}
df_styled.set_table_styles(styles, as='selectors')

styles = {
    "col_1": "background: black; color: white;",
    "col_2": "font-weight: bold;",
}
df_styled.set_table_styles(styles, as='columns')
```

**Comment by attack68** [comment]
There could be, and actually that might even be better. But I'm not sure its better to introduce a new format after 6 years, with many stackoverflow questions following the current format. Also Im not sure we would get round to changing this before 2.0, which is the only sensible version where this change could be introduced.

**Comment by janosh** [comment]
Should I open a new issue to discuss adding `as: Literal['columns', 'selectors']` in v2?
