### ISSUE TITLE
API should empty `._get_bool_data` have RangeIndex?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50862]
This came up in #50636

```python
In [9]: Series([], dtype='bool').index
Out[9]: RangeIndex(start=0, stop=0, step=1)

In [10]: Series([], dtype='bool')._get_bool_data().index
Out[10]: NumericIndex([], dtype='int64')
```

cc @topper-123

**Comment by jbrockmendel** [comment]
I'd expect it to always have the same index type as the original DataFrame

**Comment by topper-123** [comment]
> I'd expect it to always have the same index type as the original DataFrame

+1.

**Comment by topper-123** [comment]
I've looked a bit into this. The underlying issue is that `_get_bool_data()` does an implicit slice and slicing a `RangeIndex` always returns a `NumericIndex[dtype=int64]`.

```python
>>> import pandas as pd
>>> ri = RangeIndex(0)
>>> ri[[]]
NumericIndex([], dtype='int64')  # soon Index([], dtype='int64')
```
I think the above is correct, i.e. slicing a `RangeIndex` should always return the same index type, i.e. a `NumericIndex`, even if its has length 0. SO IMO `RangeIndex` behaves correctly.

So the issue here seems to be in `BaseBlockManager._combine` where the use of slicing the index is forced, which does seems to be not needed in this case. So the question is maybe if slicing there should be not done in some case (especially where there is only 1 block).
