### ISSUE TITLE
REF: de-duplicate iterate_slices

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#51186]
```
# From DataFrameGroupBy
    def _iterate_slices(self) -> Iterable[Series]:
        obj = self._selected_obj
        if self.axis == 1:
            obj = obj.T

        if isinstance(obj, Series) and obj.name not in self.exclusions:
            # Occurs when doing DataFrameGroupBy(...)["X"]
            yield obj
        else:
            for label, values in obj.items():
                if label in self.exclusions:
                    continue

                yield values
```

Iterating over self._selected_obj but then excluding self.exclusons seems a lot like just iterating over self._obj_with_exclusions.  I checked that using obj_with_exclusions _does_ break things, but didn't figure out why.

it'd be nice if we could simplify this, or at least document why we need a third thing.  cc @rhshadrach 

If it were just obj_with_exclusions, then in DataFrameGroupBy._indexed_output_to_ndframe we could just use self._obj_with_exclusions.columns instead of re-constructing an Index (i think this re-construction is largely leftover from a time when we dropped nuisance columns)

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by rhshadrach** [comment]
I'm seeing 1 test in groupby fail due to this behavior

```
df = pd.DataFrame({'a': [1, 1, 2], 'b': [3, 3, 4], 'c': [5, 6, 7]})
gb = df.groupby(['a', 'b'])
result = gb.sum()
print(result)
#       c
# a b    
# 1 3  11
# 2 4   7

gb2 = gb[['a', 'b', 'c']]
result2 = gb2.sum()
print(result2)
#      a  b   c
# a b          
# 1 3  2  6  11
# 2 4  2  4   7
```

In the 2nd example, `'a'` is in the exclusions but this is ignored since `_obj_with_exclusions` is determined via `_selection` in this case:

https://github.com/pandas-dev/pandas/blob/74d5c1950088c2dc0d7cefea382566ea42128765/pandas/core/base.py#L214-L228

When using `.sum()`, we never hit `_iterate_slices`. Within `agg`, `_iterate_slices` causes inconsistent behavior:

```
result3 = gb2.agg(lambda x: x.sum())
print(result3)
#       c
# a b
# 1 3  11
# 2 4   7
```

To get consistent behavior, I think we can just replace `_selected_obj` with `_obj_with_exclusions` and remove any use of `exclusions`.

**Comment by jbrockmendel** [comment]
nice!  thanks for tracking this down
