### ISSUE TITLE
DEV: reduce merge conflicts by sorting whatsnew notes by issue number?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#51712]
@jbrockmendel noted [here](https://github.com/pandas-dev/pandas/pull/50275#issuecomment-1448499430) that whatsnew notes are a major source of merge conflicts. @rhshadrach also mentioned it in Slack once.

I have an idea for how to address this - we require that, within each block, the issues be sorted by issue number. Then, the chances of two people modifying the same line of code should be greatly reduced compared with if everyone is appending to the end of the block

It should be pretty straightforward to write a check for this - any objections?

**Comment by jbrockmendel** [comment]
Misc pre-coffee thoughts:

1) I'm a bit wary of adding scripts.  Every so often I do a `git pull upstream main` and see a bunch of new files and get vaguely uneasy.  This isn't a real concern, just a "grumpy old man" muttering.
2) Often we (at least I) want to collect lines within a section e.g. deprecation enforcements so that all of the non-keyword deprecations are together.  This would disallow that?  I guess we could just do that collection once at release-time.
3) I think the merge conflicts happen most often in a brand new file, where i don't think this would make a difference
4) IIRC we've discussed and decided against using [towncrier](https://pypi.org/project/towncrier/) but there might be something along those lines out there?
