### ISSUE TITLE
BUG: Series.rename(scalar, copy=False) still copies data

### ISSUE THREAD

**Issue by kandersolar** [pandas-dev/pandas#52450]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

s1 = pd.Series([1])
s2 = s1.rename(None, copy=False)
s2.loc[:] = 100
print(s1)  # original series not modified
```

### Issue Description

`Series.rename`  does not consider the `copy` kwarg when passing scalar `index`:

https://github.com/pandas-dev/pandas/blob/478d340667831908b5b4bf09a2787a11a14560c9/pandas/core/series.py#L4848-L4865

If `inplace=False`, the call to `self._set_name` eventually leads to a call to `self.copy()` which leaves the default `deep=True`, meaning the data gets copied.

### Expected Behavior

I expect setting `copy=False` to prevent data from being copied regardless of which branch in `Series.rename` is taken.

### Installed Versions

The versions below are with pandas 2.0.0, but I observe this issue in 1.x as well.

<details>

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.9.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.1.11-76060111-generic
Version          : #202302091138~1675975749~22.04~f771a7f SMP PREEMPT_DYNAMIC Thu F
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.0
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 61.2.0
pip              : 22.1.2
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.2
numba            : 0.55.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by dannyi96** [comment]
take

**Comment by dannyi96** [comment]
the gist of the issue is that `_set_name` ( in the else portion ) doesn't support `copy` param and solely relies on `inplace` param.
Hence the `copy` param supplied to rename is just ignored in this case.

Some possible solutions here would be -
1. In the else portion, determine `inplace` based on `copy` ( in the case where `inplace` is False ) and then invoke `_set_name`
2. Support `copy` and `inplace` in `_set_name` and change its implementation similar to `rename`

I guess approach 1 might work/be better ( subject to review ) and will raise a PR for the same.

**Comment by lithomas1** [comment]
Hi,
Thanks for reporting this. I believe that this is intended behavior. copy=False always returns a new pandas dataframe (same as copy=True). 
The fact that renaming does a copy=False still makes a copy is a bug, though. I don't think there is a plan to fix it, as the copy keyword is going to be deprecated. 

Instead you should turn on Copy on Write(read this to understand how it works https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html) if you want to save memory, and do something like this.

```
import pandas as pd
pd.options.mode.copy_on_write = True
s1 = pd.Series([1])
# s2 = s1.rename(None) # automatically same behavior as copy=False
# s2.loc[:] = 100 # Don't do this! This is not allowed by Copy on Write rules, so you will not be able to modify s1 (you will trigger a copy of s1's values in s2)
s1 = s1.rename(None)
s1.loc[:] = 100 # Only way of modifying s1 is through s1 under Copy on Write
```

If you did not want to modify s2, you could see that it should shares values with s1
```
import pandas as pd
import numpy as np
pd.options.mode.copy_on_write = True
s1 = pd.Series([1])
s2 = s1.rename(None)
assert np.shares_memory(s1.values, s2.values)
```

**Unfortunately**, this doesn't work right now due to the aformentioned bug (``Series.rename`` should also support copy=None).
I will raise a PR.
