### ISSUE TITLE
DOC: Doc version slider is broken (no options)

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#53180]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Any page with the version slider, e.g
https://pandas.pydata.org/docs/development/contributing_codebase.html

### Documentation problem

<img width="201" alt="image" src="https://github.com/pandas-dev/pandas/assets/47963215/92b25aa1-4469-497f-bc95-c08612b731ac">

### Suggested fix for documentation

I should be able to select other versions of pandas from the slider.

@datapythonista Any idea whats going on here?

**Comment by datapythonista** [comment]
The cause seems to be moving the `versions.json` file from the website directory to the docs directory in https://github.com/pandas-dev/pandas/pull/53029/files. @mroeschke I think the file should be moved backed to where it was. Anything I'm missing?

**Comment by mroeschke** [comment]
So I remember why this was added here:

In pydata-sphinx-theme, `json_url` for these versions needs to be discoverable within `doc/` since the url is specified as `https://pandas.pydata.org/versions.json` https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#configure-switcher-json-url

In main, is https://pandas.pydata.org/versions.json an allowed URL route?
