### ISSUE TITLE
ENH: Histogram axis labels

### ISSUE THREAD

**Issue by sorenwacker** [pandas-dev/pandas#53281]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

How about improving the labels on the generated histograms? 
```

df = pd.DataFrame(dict(a=np.random.normal(size=100), b=np.random.normal(size=100)+100, c=np.random.choice(['A', 'B'], size=100)))
df
```

![image](https://github.com/pandas-dev/pandas/assets/3391614/5d0f5a01-792d-4cfb-9e50-7dba9c619494)

![image](https://github.com/pandas-dev/pandas/assets/3391614/97fca773-4ee1-4d96-b80d-50dd1bba289a)

Using the series object, the figure has no labels at all.

`df[['a']].hist()`

![image](https://github.com/pandas-dev/pandas/assets/3391614/7bebbea7-8b6f-474f-98bf-0e6a7363319b)
When using the a dataframe objet, the subplots titles are the variable names.

Actually, the x-axis correspond to the values of variable a, instead of the title the name of the axis shoud be the x-axis label.
Since we have a histogram, the y-axes should be labeled with 'Counts'.

And using `by=` should add a legend to know which color is for what label.

`df.hist(by='c')
`
![image](https://github.com/pandas-dev/pandas/assets/3391614/efedd3bd-0a72-49fc-9582-6fd7437122c9)

This plot also should look more like this:

![image](https://github.com/pandas-dev/pandas/assets/3391614/bcbf8b0b-b2e5-464b-9941-4aaa64346d29)

The labels do not make sense anymore since value from A and B 

### Feature Description

Instead of using title(column-name) use xlabel(column-name). Set 'Count' as y-label by default.

### Alternative Solutions

Allow seaborn as backend?

**Comment by topper-123** [comment]
Yes, the current output for frames could be improved...

**Comment by Rylie-W** [comment]
take

**Comment by Rylie-W** [comment]
Hello @topper-123 ,

I have two questions during the implementation:
1. According to [the documentation of `matplotlib.pyplot.hist()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html#matplotlib.pyplot.hist), setting the `label` parameter does not conflict with adding a legend. However, in pandas, it is not allowed to set both simultaneously. Some users may want to change the label without modifying the original DataFrame instance, so it might be necessary to implement this functionality.
https://github.com/pandas-dev/pandas/blob/ef58af319f5c6d9fd859f6deada7d23335e7ca7c/pandas/plotting/_matplotlib/hist.py#L482-L483

2. From the following two code snippets, `pandas.DataFrame.hist()` currently only supports drawing histograms for numeric or datetime data. 
https://github.com/pandas-dev/pandas/blob/ef58af319f5c6d9fd859f6deada7d23335e7ca7c/pandas/plotting/_matplotlib/hist.py#L510-L512
https://github.com/pandas-dev/pandas/blob/ef58af319f5c6d9fd859f6deada7d23335e7ca7c/pandas/plotting/_matplotlib/hist.py#L271-L305
Should we support drawing histograms for non-numeric data, such as the column 'd', similar to [`matplotlib.pyplot.hist()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html#matplotlib.pyplot.hist)? Otherwise, we should consider removing the numeric_only parameter, as it has a default value of True and cannot be specified by the user.
```python
import pandas as pd
import numpy as np
import matplotlib as plt

df = pd.DataFrame(dict(a=np.random.normal(size=100), b=np.random.normal(size=100)+100, c=np.random.choice(['A', 'B'], size=100), d=np.random.choice(['A', 'B'], size=100)))
df.hist(by='c')
plt.pyplot.show()

plt.pyplot.hist(df.iloc[:,3])
plt.pyplot.show()
```
