### ISSUE TITLE
BUG: astype not effective if using .loc to assign

### ISSUE THREAD

**Issue by Yuanjimengmengda** [pandas-dev/pandas#53589]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame([[20230101, 1500.0]], columns=["Date", "Time"])
df.loc[:, "Time"] = df["Time"].astype(int)
print(df)
df["Time"] = df["Time"].astype(int)
print(df)
```

### Issue Description

Assume I have a dataframe look like below
```Python
df = pd.DataFrame([[20230101, 1500.0]], columns=["Date", "Time"])
```
Now I want to convert the column "Time" from `float` to `int`. 
As a legitmate way to do this in older versions like below now fails.
```Python
df.loc[:, "Time"] = df["Time"].astype(int)
```  
You will find 'Time' is still of dtype `float`.
However, the following way works.
```Python
df["Time"] = df["Time"].astype(int)
```
To my understanding (may not be correct, correct me if I'm wrong), `loc` wiil return the view of the data and thus assigning value to it should still works.

### Expected Behavior

```Python
df.loc[:, "Time"] = df["Time"].astype(int)
```  
Will convert dtype of column "Time" to `int`, changes should be applied to the original dataframe `df`

### Installed Versions

<details>

2.0.2

</details>

**Comment by thakurns** [comment]
I have run the code in pandas==1.5.3, here it is showing a Deprecation Warning.

**Warning** _"C:\Users\91889\AppData\Local\Temp\ipykernel_27544\240076025.py:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, "Time"] = df["Time"].astype(int)"_

I think deprecating this feature resulted in this behavior. Pandas==2.0.2 is preserving the datatype of the column as it is setting the values inplace instead of setting a new array.


![image](https://github.com/pandas-dev/pandas/assets/103310839/99c6cb94-b395-4cdb-8ebd-19ee29277765)

**Comment by Yuanjimengmengda** [comment]
> I have run the code in pandas==1.5.3, here it is showing a Deprecation Warning.
> 
> **Warning** _"C:\Users\91889\AppData\Local\Temp\ipykernel_27544\240076025.py:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)` df.loc[:, "Time"] = df["Time"].astype(int)"_
> 
> I think deprecating this feature resulted in this behavior. Pandas==2.0.2 is preserving the datatype of column as float for int values.
> 
> ![image](https://user-images.githubusercontent.com/103310839/244872668-99c6cb94-b395-4cdb-8ebd-19ee29277765.png)

Hi @thakurns,

It's good to know that!

Thx.
