### ISSUE TITLE
BUG: DataFrame.stack with `sort=True` and unsorted MultiIndex levels

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#53636]
Ref: https://github.com/pandas-dev/pandas/pull/53282#discussion_r1227313154

```
levels = ((0, 1), (1, 0))
stack_lev = 1
columns = MultiIndex(levels=levels, codes=[[0, 0, 1, 1], [0, 1, 0, 1]])
df = DataFrame(columns=columns, data=[range(4)])
df_stacked = df.stack(stack_lev, sort=True)
#      0  1
# 0 1  0  2
#   0  1  3

# Expected
#      0  1
# 0 0  1  3
#   1  0  2
```

When the MultiIndex levels are not sorted in ascending order, `DataFrame.stack` with `sort=True` does not sort the values in the result.

**Comment by rhshadrach** [comment]
This was a misunderstanding of what `sort=True` is supposed to do. I plan to clarify the docs here.

**Comment by jorisvandenbossche** [comment]
To be honest, I don't even really understand your last sentence ;) 
What do you mean with the "levels get sorted"? Do you mean the labels of one level (eg `df_stacked.index.levels[-1]`), or the integer codes of the levels (`df_stacked.index.codes[-1]`) while keeping the labels the same?

The above example might also not be the best, because I don't see any difference between `sort=True` vs `sort=False`
