### ISSUE TITLE
API/DEPR: interpolate with object dtype

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#53631]
```python
import pandas as pd
import numpy as np

ser = pd.Series([1, np.nan, 2], dtype=object)

>>> ser.interpolate()
0      1
1    NaN
2      2
dtype: object
```

ATM if we have object-dtype, interpolate is incorrectly a no-op.  (In the DataFrame case we have a weird check that raises on all-object).

If we disable the check in Block.interpolate `if m is None and self.dtype.kind != "f":` that short-circuits, then the OP case raises in np.interp when trying to cast to float64.

The viable options I see are:

1) Raise on object dtype, tell users to do .infer_objects() before calling interpolate.
2) Check if there the array has any NaNs.  if not, short-circuit as in the status quo. Otherwise goto 1).

I lean towards "do 2) immediately and 1) with a deprecation cycle".

(I haven't checked the scipy paths, just the numpy one)

**Comment by topper-123** [comment]
Sounds good to me.

**Comment by verglasz** [comment]
I am currently using `resample().interpolate()` on a dataframe with a datetime index and which has some numeric columns and some columns with python strings, and the current (deprecated) behaviour is very convenient, I can fill the `NaN`s left in the string column with appropriate information based on the interpolation or other details or call some other method like `bfill`/`ffill` to take care of those.
Once this will error, what would be the approach to achieve the same result? Separate the numeric and object columns and call separately `resample().interpolate()` on the first and `resample().fillna()` on the second, then put the df back together? 
Imho it would be nice to keep some way of accessing the current behaviour (maybe some kind of `allow_objects` option?) so that the code can remain neater and not fiddle with individual columns (which is even more of a pain when writing utility function where the columns aren't known beforehand).

**Comment by spawn-guy** [comment]
@verglasz i think you are correct in your idea :( 

my code
```
temp_df = temp_df.resample(date_delta).interpolate(method="linear")
```

becomes
```
# resample at needed resolution
temp_df = temp_df.resample(date_delta).asfreq(fill_value=np.nan)
# and now interpolate non-object columns
temp_df_non_obj = temp_df.select_dtypes(include=['number']).interpolate(method="linear")
# and forward-fill object columns
temp_df_obj = temp_df.select_dtypes(exclude=['number']).ffill()
# combine the two
temp_df = pd.concat([temp_df_non_obj, temp_df_obj], axis=1)
```
i am not even sure about interpolating datetime's :(
