### ISSUE TITLE
VOTE:  Voting Issue for PDEP-10: Add pyarrow as a required dependency

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#54106]
This is the issue where we will track votes for PDEP-10.

Pull request with discussion is here:  https://github.com/pandas-dev/pandas/pull/52711

Rendered PDEP for easy reading:   https://github.com/pandas-dev/pandas/blob/2db0037b10aaa14994b307cbe64ff82b7c1dc260/web/pandas/pdeps/0010-required-pyarrow-dependency.md

Cast your vote in a comment below. 

- +1: approve.
- 0: abstain.
  - Reason: A one sentence reason is required.
- -1: disapprove
  - Reason: A one sentence reason is required.
A disapprove vote requires prior participation in #52711 .

Voting will close in 15 days, i.e., on July 28.

@pandas-dev/pandas-core

**Comment by MarcoGorelli** [comment]
+1

**Comment by phofl** [comment]
+1

**Comment by Dr-Irv** [comment]
+1

**Comment by rohanjain101** [comment]
+1

**Comment by jbrockmendel** [comment]
+1

**Comment by bashtage** [comment]
+1

**Comment by mroeschke** [comment]
+1

**Comment by WillAyd** [comment]
+1

**Comment by lukemanley** [comment]
+1

**Comment by jreback** [comment]
+1

**Comment by rhshadrach** [comment]
+1

**Comment by simonjayhawkins** [comment]
+1

**Comment by jorisvandenbossche** [comment]
+1

Longer version: 
Big +1 on using pyarrow for string data by default.    
+0 on "requiring" pyarrow for that, because I personally think we could relatively easily make pyarrow only a "default" dependency (i.e. users get it by default when pip/conda installing pandas) while still allowing to run pandas without having pyarrow installed (as long as we still have alternative data types for the arrow-based ones, that feels like a better first step). 
But I know I disagree about the impact on development while I am also not doing much day-to-day maintenance myself, so I'll give more weight to the string feature argument ;)

**Comment by alimcmaster1** [comment]
+1

**Comment by attack68** [comment]
-1

I have waited until the close of the vote to post because I did not want to submit a vote that would cause this to not be accepted. This vote has already been won and therefore my addition does not change the outcome.

In the discussion there are a number of references that suggest pyarrow makes life better for (possibly) 99% of users but there were a number of comments made by people who are not able to vote that were not as keen.

PyArrow dependency breaks my own workflow.
I use pandas, and have for many years, within microservices web APIs that peform numpy tensor calculations, usually 2-4 dimensions <200 elements in length, primarily in a financial calculation/optimization context. I use pandas for its indexing capability to dynamically arrange and slice these arrays for a better UI display.
I do not use strings and do not need pyArrow for large data, and its addition prevents my microservices provider from building becuase it takes up too much space - I am already using 80% disk space.

I think it is reasonable for this vote to be well accepted but to have on record some objection which I suspect we might all agree reflects some small proportion of users.

**Comment by twoertwein** [comment]
0

I understand the benefits but also the risks. I don't feel comfortable voting +1 or -1 but I want to help reach the minimum quorum (if we haven't already reached it).

**Comment by Dr-Irv** [comment]
Final vote tally Yes/Abstain/No:   14/1/1

PDEP-10 is now approved.

**Comment by phofl** [comment]
Cosing
