### ISSUE TITLE
Gitpod is not allowing to push code to forked repo.

### ISSUE THREAD

**Issue by ggold7046** [pandas-dev/pandas#54255]
I'm having the following trouble using gitpod. Though I have given gitpod the read/write permission.

<Details>

`gitpod@pandasdev-pandas-4uhxurlgnuc:/workspace/pandas$ git push origin modified_linkchek` # modified_linkchek is the branch 
 name I created

Enumerating objects: 10088, done.
Counting objects: 100% (10088/10088), done.
Delta compression using up to 16 threads
Compressing objects: 100% (3356/3356), done.
Writing objects: 100% (9183/9183), 2.36 MiB | 6.54 MiB/s, done.
Total 9183 (delta 7975), reused 6977 (delta 5798), pack-reused 0
remote: Resolving deltas: 100% (7975/7975), completed with 841 local objects.
To https://github.com/ggold7046/pandas.git
 ! [remote rejected]       modified_linkchek -> modified_linkchek (refusing to allow an OAuth App to create or update workflow `.github/workflows/cache-cleanup.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/ggold7046/pandas.git'

</Details>

I even tried to remove the changes :
```
git rm .github/workflows/cache-cleanup-weekly.yml
git commit -m "Remove cache-cleanup-weekly workflow"
git push origin modified_linkchek
```

But the problem persists.

**Comment by theuerc** [comment]
my understanding is that you have to fork the repo first, and then you can create a new branch in gitpod.

**Comment by ggold7046** [comment]
Thanks for the reply @theuerc . I already have pandas fork before I started the gitpod.

**Comment by theuerc** [comment]
This is how I typically update a fork branch to be current when using gitpod: 
<img width="552" alt="Screen Shot 2023-07-30 at 2 20 13 PM" src="https://github.com/pandas-dev/pandas/assets/60138157/6a23f0ee-1ef4-4bc7-8bd8-18da90f72299">

I think there are other ways that work, like running the commands here when in the workspace for the fork:

https://stackoverflow.com/questions/40983514/most-efficient-way-to-keep-a-fork-up-to-date

Maybe there could be a note in the documentation about how to update fork branches when working with gitpod, but I'm not sure it's worthwhile to put much effort toward this because other methods work.
