### ISSUE TITLE
TST: div/truediv with PyArrow duration types

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#54315]
Looks like they implemented ``__truediv__`` for more types.

https://github.com/pandas-dev/pandas/actions/runs/5707046701/job/15463354529

**Comment by mroeschke** [comment]
https://github.com/pandas-dev/pandas/pull/54327 doesn't not effectively compare the result to the equivalent numpy operation because `pd.Timedelta / pd.NA` raises a `TypeError`. Would be good to have dedicated tests for this

**Comment by prasad-yashdeep** [comment]
take

**Comment by Rollingterminator1** [comment]
Hi @prasad-yashdeep are you still working on this?

**Comment by ccccjone** [comment]
take

**Comment by JackCollins91** [comment]
Hi @ccccjone  are you still working on this? if not, may I take?

**Comment by droussea2001** [comment]
Hello @ccccjone are you still working on it ?

**Comment by droussea2001** [comment]
Ok thanks !

**Comment by droussea2001** [comment]
Hello,

I am a total beginner in open source and I am not sure to understand the issue. :-)

If my understanding is correct the issue appears from the following test functions:
```
- test_arith_series_with_scalar
- test_arith_frame_with_scalar
- test_arith_series_with_array
```

"_#54327 doesn't not effectively compare the result to the equivalent numpy operation because pd.Timedelta / pd.NA raises a TypeError_" because:
 `_get_arith_xfail_marker `set a pytest xfail with a `TypeError` before the operation (further in `floordiv_compat`)

So the trick would be to:
- desactivate the xfail in `_get_arith_xfail_marker `for specific "#54327 div / truediv operations
- set a correct exception in the `_get_expected_exception ` function called by `check_opname` 
- consequently `pytest.raises(exc) `in `_check_op` would catch the correct exception
 
@mroeschke: is it correct ? 
 

Thanks in advance,
