### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by jamesjohns01** [pandas-dev/pandas#55103]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

data = {
    "ticket":   ['A/5 21171', '113803', 'STON/O2. 3101282', '211536']
}

df = pd.DataFrame(data)

df[['T1','T2']] = df['ticket'].str.split(' ', expand=True)
df[['T3','T4']] = df['ticket'].str.rsplit(' ', expand=True)

df
```

### Issue Description

It appears that the split() and rsplit() functions return the same result.  My reading of the rsplit() documentation indicates that the values the split() returns in the T1 & T2 columns should be in the T3 and T4 columns but reversed.

BTW this is my first attempt at reporting an issue.  Please forgive errors and omissions. 

### Expected Behavior

IMHO this is what the behaviour should be

| |ticket|T1|T2|T3|T4
|---|--------------------|-----------|----------|----------|----------|
| 0 | A/5 21171 | A/5 | 21171 | 21171 | A/5 |
| 1 | 113803 | 113803 | None | None | 113803 |
| 2 | STON/O2. 3101282 | STON/O2. | 3101282 | 3101282 | STON/O2. |
| 3 | 211536 | 211536 | None | None | 211536 |

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Australia.1252

pandas           : 2.0.3
numpy            : 1.24.3
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.2.1
Cython           : None
pytest           : 7.4.0
hypothesis       : None
sphinx           : 5.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.15.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : 2023.4.0
gcsfs            : None
matplotlib       : 3.7.2
numba            : 0.57.1
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.4.0
scipy            : 1.11.1
snappy           : 
sqlalchemy       : 1.4.39
tables           : 3.8.0
tabulate         : 0.8.10
xarray           : 2023.6.0
xlrd             : None
zstandard        : 0.19.0
tzdata           : 2023.3
qtpy             : 2.2.0
pyqt5            : None

</details>

**Comment by kshitiz305** [comment]
take

**Comment by kshitiz305** [comment]
![image](https://github.com/pandas-dev/pandas/assets/38988779/cb2ebbc0-a8da-41c5-8359-e80029f17733)

I tried to replicate the issue but everything seems to work

**Comment by crocks4123** [comment]
take

**Comment by crocks4123** [comment]
With respect to #55103 @jamesjohns01 Here is the hardcoded fix, this working. Additionally can do a PR for this issue?

```import pandas as pd

data = {
    "ticket": ['A/5 21171', '113803', 'STON/O2. 3101282', '211536']
}

df = pd.DataFrame(data)

df[['T1', 'T2']] = df['ticket'].str.split(' ', 1, expand=True)
df[['T3', 'T4']] = df['ticket'].str.split(' ', 1, expand=True)
df['T3'] = df['T4'].copy()
df['T4'] = df['T1']
df

           ticket       T1        T2       T3       T4
0       A/5 21171     A/5     21171    21171     A/5
1          113803  113803      None     None  113803
2  STON/O2. 3101282  STON/O2.  3101282  STON/O2.  3101282
3          211536   211536      None     None   211536

**Comment by jamesjohns01** [comment]
Sorry this is my first Pandas bug so I don't know the language. What is a PR?  I am happy to help verify your change.

**Comment by jamesjohns01** [comment]
I can't tell if your change has worked because these statements
df['T3'] = df['T4'].copy()
df['T4'] = df['T1']

Replace the results of the two original statements and so the required information is gone.  Can you test again without those two statements please.

**Comment by crocks4123** [comment]
Sure I will try to solve it without replacing original statements. PR is pull request but since it is not in a repository so i don't think you can create one, but i will try to solve it after my academics. Thanks.

Your Sincerely,
Chirag Devgade NMIMS MPSTME,
(Class Representative)
B.tech in Artificial Intelligence and Machine Learning 3rd Year
Email: ***@***.***

**Comment by JoschD** [comment]
Hey @jamesjohns01, I stumbled by chance about this thread and I think the problem here is a misunderstanding of the difference between `split` and `rsplit`, which has not been addressed in the previous comments.

`rsplit` does not invert the order of the split parts! 
It only looks for the character to split from the end of the string (instead of the beginning). 
A good example what this means is shown in the documentation: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.rsplit.html
e.g.

```
>>>s = pd.Series(["this is a regular sentence",])

>>>s.str.split(n=2)
0                     [this, is, a regular sentence]
dtype: object

>>>s.str.rsplit(n=2)
0                     [this is a, regular, sentence]
dtype: object
```

as you can see, it finds the first two blanks either from the left (`spit`) or from the right (`rsplit`) of the string and splits there. 
It still keeps the same order of words as in the string.
What you want instead is:
```
df[['T3', 'T4']] = df['ticket'].str.split(' ', expand=True).iloc[:, ::-1]
```
where the `iloc`-part leaves the indices as-is (`:` before the comma) but reverses the column order (`::-1` after the comma) of your resulting `DataFrame` containing the split elements of your string.

I hope this helps! :)

Cheers!

**Comment by jamesjohns01** [comment]
Hi JoschD,
thanks so much.  I am a newbie and getting information overload with learning pandas.  Apologies for taking up your time when I should have had a closer read of the documentation.

James
