### ISSUE TITLE
DEPR: is_decimal, is_interval

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#55264]
These are aliases for isinstance checks, don't seem necessary.

**Comment by Cappuchinoo** [comment]
Hey, I'm a new contributor to pandas, and this seems to be a pretty simple issue to take on. I'll wait for the core team discussion to start working on it but for now I'll take it if that's ok.

**Comment by Cappuchinoo** [comment]
take

**Comment by Cappuchinoo** [comment]
take

**Comment by Cappuchinoo** [comment]
So I've been trying to figure this issue out today but I've been having a hard time. Hasn't this deprecation already been done? is_interval already has a warning saying it has been deprecated since version 2.0.0, and is_decimal isn't being defined in the file is_interval is (pandas\core\indexes\base.py). I'm still new here, so am I missing something?
