### ISSUE TITLE
BUG: groupby.transform with a reducer and unobserved categories coerces dtype

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#55326]
The implementation of groupby.transform with a reduction like `sum` or `min` calls the corresponding reduction and then reindexes the output to the input's index in `_wrap_transform_fast_result`. However, when there are unobserved categories, their presence can induce NA values in the reduction, coercing the dtype to float. This results in unnecessarily coercing the result to float as well.

```
df = pd.DataFrame({'a': pd.Categorical([1, 1, 2], categories=[1, 2, 3]), 'b': [3, 4, 5]})
gb = df.groupby('a', observed=False)
result = gb.transform('min')
print(result)
#      b
# 0  3.0
# 1  3.0
# 2  5.0
```

The expected output of column `b` here should be [3, 3, 5] rather than floats.

**Comment by banorton** [comment]
@rhshadrach Did you mean, `b` should be [3, 3, 5] rather than floats?

**Comment by rhshadrach** [comment]
Yes - thanks. I've updated the OP.

**Comment by undermyumbrella1** [comment]
Hi I made a pr for this, the implementation uses remove_nan boolean flag that is bubbled down to call_cython_ops, that uses result mask to filter out any nan values, hence type is not coerced. I placed the fix there as it is where type coercion is done. If it is placed in other places e.g `_wrap_transform_fast_result`, the type coercion may be caused by other reasons and not solely because of the presence of NaN. Do let me know if it should be done elsewhere. Thank you!
