### ISSUE TITLE
DEPR: axis keyword in DataFrame.transform, apply, aggregate

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#55470]
It looks like under the hood these methods all do a transpose-operate-transpose, which is pattern we should try to avoid.  Better to tell users to do the transpose themselves (and warn them it is potentially copying).

cc @rhshadrach

**Comment by rhshadrach** [comment]
DataFrame.apply doesn't use a transpose I believe.

I don't understand why we should avoid it while telling users they should do it. Is it just that they are made aware of what is going on?

I find this syntax much more enjoyable than having to transpose before and after an operation, somewhat common to use, and unlike the situation with groupby, I think it doesn't require much effort to develop and maintain. Open to being convinced otherwise.

Because of the current behavior of agg, it isn't a perfect replacement:

```
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})

print(df.agg(list, axis=1))
# 0    [1, 4, 7]
# 1    [2, 5, 8]
# 2    [3, 6, 9]
# dtype: object

print(df.T.agg(list).T)
#    a  b  c
# 0  1  4  7
# 1  2  5  8
# 2  3  6  9
```

**Comment by jbrockmendel** [comment]
> I don't understand why we should avoid it while telling users they should do it. Is it just that they are made aware of what is going on?

The scenario i have in mind is where a user does a bunch of operations in a row with axis=1 that could be improved by transposing once up-front.

**Comment by rhshadrach** [comment]
Indeed, that's a good point. One thing I have trouble with is balancing nudging users to more performant methods vs ease of use for the user who doesn't care (e.g. working with small data). This doesn't seem to me to be a case where the performance justifies the removal, but that is very much colored by my personal experience.

**Comment by jorisvandenbossche** [comment]
> I find this syntax much more enjoyable than having to transpose before and after an operation, somewhat common to use, and unlike the situation with groupby, I think it doesn't require much effort to develop and maintain.

+1 on this sentiment.

In the "deprecate apply" PDEP discussion, I think it also came up that `DataFrame.apply` with axis=1 is actually one of the cases where there is no clear alternative.

**Comment by jbrockmendel** [comment]
Closing as No Action.
