### ISSUE TITLE
ENH: Add SAS7BDATReader and XportReader to `pandas/api/typing/__init__.py`

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#55689]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

These classes can be returned by `read_sas(..., iterator=True/chunksize=...)`

### Feature Description

Adding `from pandas.io.sas.sas_xport import XportReader` and `from pandas.io.sas.sas7bdat import SAS7BDATReader` to `pandas/api/typing/__init__.py`

### Alternative Solutions

None

**Comment by twoertwein** [comment]
It could(?) be sufficient to export the abstract base class.
https://github.com/pandas-dev/pandas/blob/074ab2f87d2aeb9586c90b7266f7f1f4488f1db0/pandas/io/sas/sasreader.py#L35
The concrete classes should probably(?) contain only implementation details.


If we go that route, we probably should let ReaderBase inherit from Iterator instead of the child classes.
