### ISSUE TITLE
BUG: pandas 2.1.2 changes how `copy` works

### ISSUE THREAD

**Issue by flying-sheep** [pandas-dev/pandas#55763]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

class Sub(pd.DataFrame): pass

assert not isinstance(Sub().copy(), Sub)
```

### Issue Description

Since very long ago, calling `.copy()` on a DataFrame subclass returned a DataFrame object. This should be changed in a major release, not a feature release, and definitely not a patch release.

### Expected Behavior

The above assert statement to succeed

### See also

- Probably related: https://github.com/pandas-dev/pandas/issues/55120
- Downstream bug report: https://github.com/scverse/anndata/issues/1210

### Installed Versions

pandas 2.1.2 or 2.2.0.dev0+447

**Comment by flying-sheep** [comment]
We’re pinning Pandas to !=2.1.2.

Can we rely on Pandas 2.2.0 to fix this?

**Comment by ivirshup** [comment]
I believe this was specifically caused by the changes to: `_constructor_from_mgr` in #54922. Previously (`2.1.1`), this looked like:

```python
    def _constructor_from_mgr(self, mgr, axes):
        df = self._from_mgr(mgr, axes=axes)

        if type(self) is DataFrame:
            # fastpath avoiding constructor call
            return df
        else:
            assert axes is mgr.axes
            return self._constructor(df, copy=False)
```

But now it looks like:

```python
    def _constructor_from_mgr(self, mgr, axes):
        if self._constructor is DataFrame:
            # we are pandas.DataFrame (or a subclass that doesn't override _constructor)
            return self._from_mgr(mgr, axes=axes)
        else:
            assert axes is mgr.axes
            return self._constructor(mgr)
```

Behaviour changed for other methods, like `.groupby`, as well.

I believe we were relying on the constructor being called for our subclass, since we want to coerce to a`pd.DataFrame` here. However, it's unclear if there is any mechanism for doing that because we would want `._constructor`  to be `pd.DataFrame`, which is specifically branching here.

I've opened a draft PR which may fix this: 

* #55764 

This PR reverts the branching logic to check the class being passed in instead of the class of `_constructor`. It seems to work locally, but I'm not sure I totally understand why the bug inducing change was made.

Would appreciate a look from @jorisvandenbossche.

**Comment by jorisvandenbossche** [comment]
Thanks for the detailed report and analysis, @flying-sheep and @ivirshup ! 
It's unfortunate that the fix for a recursion error in one subclass caused a recursion error in a different subclass ..

But yes, this is something we definitely should fix. I didn't consider the case of subclasses that don't get preserved but always return a plain pandas object for each operation.
