### ISSUE TITLE
DEPR: Series and Index shouldn't do inference on pandas objects

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#56012]
The following changes the dtype, which is unexpected:

```
idx = pd.Index(pd.date_range("2015-01-01 10:00", freq="D", periods=3), dtype=object)
pd.Index(idx).dtype
```

this returns ``datetime64[ns]``

Doing inference on a pandas object is pretty weird, this makes stuff very complicated with the new string option. Set_Index can change the dtype, e.g.

```
df = pd.DataFrame({"a": pd.Series(pd.date_range("2015-01-01 10:00", freq="D", periods=3), dtype=object), "b": 1})
df.dtypes

a    object
b     int64
dtype: object


df.set_index("a").index.dtype
datetime64[ns]
```

Users can just call infer_objects if they want to do inference. We should keep the inference logic for non-pandas objects

cc @jbrockmendel

**Comment by jbrockmendel** [comment]
I'm ambivalent here.  I agree with phofl that idempotency is an attractive property for the constructors.  The flip side is the code/api complexity involved with treating Index[object] differently from ndarray[object].

The only strong opinion I have is that pd.Index, pd.Series, pd.array, pd.DataFrame should all have analogous behavior (not withstanding intentional differences in pd.array returning nullable that The Ice Cream Agreement will eventually smooth out)

To the extent that set_index is a pain point, can we just pass `dtype=arr.dtype` to the Index constructor somewhere along the way?

**Comment by phofl** [comment]
My concern is that I am guessing that there are numerous places where we would want to keep the dtypes instead of casting and we would have to take care of passing the correct dtype everywhere (annoying)

I agree that all of them should be consistent, note that DataFrame keeps the dtype if you do:

```
df = pd.DataFrame({"a": pd.Series(pd.date_range("2015-01-01 10:00", freq="D", periods=3), dtype=object), "b": 1})
```

while we infer on the numpy array. That's the behavior I would prefer
