### ISSUE TITLE
BUG: Cannot import pandas when running script is called calendar.py

### ISSUE THREAD

**Issue by Merydian** [pandas-dev/pandas#56609]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas
```

### Issue Description

When trying to import pandas in a script called calendar.py the error `AttributeError: module 'calendar' has no attribute 'day_abbr'` arises. Renaming the file results in an import without errors. 

### Expected Behavior

The import to work without errors. 

### Installed Versions

<details>

Replace this line with the output of pd.show_versions() -> Not possible, since import isn't working. 

Pandas version: 2.1.4

Installed via Anaconda, using conda-forge. 

</details>

**Comment by richardshaju** [comment]
It seems like there's a conflict between your script named `calendar.py` and the built-in `calendar` module in Python.

When you import `pandas`, it might be trying to access attributes from your script instead of the actual `calendar` module. 

By renaming your script to something other than `calendar.py`, you can avoid this conflict

**Comment by mroeschke** [comment]
Yes this a general Python consideration naming files similar to stdlib modules and not a pandas issues so closin
