### ISSUE TITLE
Should pandas preserve NaNs in str methods?

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#5672]
Since the output of the string methods is primarily boolean, do we want to preserve NaNs? Use case. I load in some data, empty strings (i.e., missing data in a column that's string data) gets automatically converted to NaNs. I have to do fillna everywhere first, or I run into situations like this. 

```
dta = pd.DataFrame([["blah"],[np.nan],["foobar"]], columns=['vari'])
dta.vari.str.startswith('f')
dta.ix[dta.vari.str.startswith('f')]
```

Since presumably the primary use case of a boolean series is indexing, do we want to just return False in place of NaNs? Just a thought.

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche could this be closed?

Is this discussion superseded by the new BooleanArray and it's default behaviors or is this orthogonal and we could still consider changing the existing behavior of the str methods so that they always return a boolean array and not object when np.NaN is present?

**Comment by mroeschke** [comment]
I think this could also be superseded by the string extension dtype with NA support. Happy to reopen if we want to continue the original discussion
