### ISSUE TITLE
DEPR: make_block

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#56815]
`make_block` was deprecated and then reverted before the 2.2 release: https://github.com/pandas-dev/pandas/pull/56481

On the dev call today (2024-01-10), it was agreed that a deprecation would be issued during 3.0

**Comment by lithomas1** [comment]
Thinking about this again, I wonder if we need to explicitly deprecate this function, or if this would be auto-deprecated when we deprecate the entirety of core for 3.0.

**Comment by jorisvandenbossche** [comment]
I have been working on a branch for pyarrow testing an alternative `to_pandas` implementation. For the draft code see https://github.com/apache/arrow/pull/40897 (currently it adds a `use_blocks` keyword to toggle the new implementation, that's of course not meant to stay, but just to make the different implementations easier to test alongside each other)

I ran some benchmarks using that implementation, for varying sizes (1 million and 10 million elements) and number of columns (10, 100, 1000). I am using mixed dtypes so the result will have multiple blocks, where the creation of the block array involves a copy (so it's not benchmarking a zero-copy conversion where the python overhead would relatively be bigger). At the same time I am just using int and float, so data types where this conversion is relatively cheap (compared to converting strings to object dtype).

Summary figure ("blocks" is the current implementation, "concat" the new, for varying data sizes. the dark part of each bar is the time of the actual conversion of Arrow memory to numpy arrays, the lighter transparent part of each bar is the additional python overhead to create the final dataframe):

![image](https://github.com/pandas-dev/pandas/assets/1020496/8b0beb7f-8e49-4ee8-9276-c29cc5f80bc9)

For the two left-most cases (1 million elements, 10 or 100 columns) the slowdown is around 2x and 1.5x, respectively. Of course, this is for small numbers (around 1 to 2 ms). For the larger dataframe (10 million elements), the relative slowdown is much smaller.

That is for the default behaviour of `pyarrow.Table.to_pandas` to create a default consolidated pandas.DataFrame. 
There is however a `split_blocks` option that can be enabled to avoid this consolidation and have potentially zero-copy conversions (although that still depends on the dtype and presence of nulls) and less memory increase. 
Right now both `split_blocks` options use the same block+dataframe creation. If we also just use the new implementation for `split_blocks` we are creating a DataFrame (or Series might give a small improvement) for each column, and so that obviously gives quite some overhead:

![image](https://github.com/pandas-dev/pandas/assets/1020496/7cdb5b04-029a-441a-86a0-d80c22e39b93)

Obviously there are alternative ways to create the DataFrame. Just using `DataFrame(dict(zip(names, arrays)), copy=False)` is already faster, but still gives some avoidable overhead. 
We do have `pd.DataFrame._from_arrays` (as was also mentioned in the discussion in https://github.com/pandas-dev/pandas/pull/56422), but the problem right now is that this is 1) also private API, and 2) consolidates (but it could easily not do that by just passing down a keyword).

**Comment by jorisvandenbossche** [comment]
Above is just a description of the testing and benchmarking I did. Now for how to move forward:

For the default consolidated DataFrame creation, two obvious options:

- We are fine with the reported overhead of the subframes+concat+reindex implementation, and this is the recommended way to create a DataFrame from a set of 2D arrays (and pyarrow can do this conditional on the pandas version, i.e. only when running with pandas 3.0)
- We provide a helper function for advanced users that essentially does what pyarrow was doing before (create blocks from the arrays, and combine blocks in a manager). But by implementing it on our side, we can happily use our internals, and external projects that need this don't have to touch blocks or managers. For example, we could expose a `pandas.api.internals.dataframe_from_blocks(..)` that accepts a list of (array, placement) tuples plus index and columns object.

For the non-consolidated (`split_blocks=True`) case, I am also thinking of two options:

- We expose `_from_arrays` publicly as `DataFrame.from_arrays` and ensure that it has a keyword to disable the consolidation (e.g. a `copy=False`). I don't know the details of the current `_from_arrays` implementation enough to judge how "ready" this is to expose publicly, though (like, how robust is it for various user input, PyArrow is fine with a method that requires nicely prepared arrays)
- We expose a form of `_from_arrays` (again without the consolidation or an option to disable it) in a helper function for advanced users. For example (to mimic the above), we could expose a `pandas.api.internals.dataframe_from_arrays(..)` that accepts a list of 1D arrays plus index and columns object.

For this case also `DataFrame(dict)` is an option, although that has some overhead compared to `_from_arrays` (compared to the current situation, it's good enough, but `_from_arrays` gives the option to actually improve performance here).

---

I think my personal preference would be to provide those two helper functions for both cases. They are easy to implement on our side (and should be relatively easy to maintain), provide the fastest option (even though the performance benefit is only minor in the consolidated case, it still cheaply avoids some overhead), and also give convenience to the few users who need this (no need to reimplement this subframes+concat+reindex logic, although not that complex, in multiple places).
