### ISSUE TITLE
DOC: Clarifying Terminology:  "Brackets" vs "Parentheses"

### ISSUE THREAD

**Issue by vertigoa** [pandas-dev/pandas#56972]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/getting_started/intro_tutorials/02_read_write.html

### Documentation problem

![image](https://github.com/pandas-dev/pandas/assets/26881092/124c087c-af1b-4675-85bd-06451f0ba22a)

Note

When asking for the dtypes, no brackets are used! dtypes is an attribute of a DataFrame and Series. Attributes of a DataFrame or Series do not need brackets. Attributes represent a characteristic of a DataFrame/Series, whereas methods (which require brackets) do something with the DataFrame/Series as introduced in the [first tutorial](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented).

### Suggested fix for documentation

I am just learning pandas, so please excuse me if I am incorrect. I wonder if this may be a regional things or matter of convention I am not yet awaare of. The use of the word "brackets" in the pandas documentation to describe parentheses () can be confusing.  "brackets" refer to square brackets [ ], which are used for indexing and selecting data. , while "parentheses" refer to () used when calling methods. It seems that in this particular documentation, the term "brackets" is being used to refer to parentheses.

**Comment by rhshadrach** [comment]
I indeed don't call `()` brackets, but [is used that way in British-English](https://en.wikipedia.org/wiki/Bracket). I think improving the language here with something like `round brackets or parentheses` or even just replacing it with the symbol like `no ``()`` are used` would be welcome.

**Comment by rhshadrach** [comment]
@vertigoa - can you give this issue an informative title? Currently it is `Doc:`.

**Comment by vertigoa** [comment]
> @vertigoa - can you give this issue an informative title? Currently it is `Doc:`.

Thank you for pointing that out, I have edited the title. I hope it makes better sense. Cheers!

**Comment by Deekshita-S** [comment]
take

**Comment by Deekshita-S** [comment]
I'm encountering an issue while building the documentation for pandas. The error message is as follows:

'Exception occurred:
File "C:\virtualenvs\pandas-dev\Lib\site-packages\IPython\sphinxext\ipython_[directive.py](http://directive.py/)", line 584, in process_input
raise RuntimeError(
RuntimeError: Unexpected exception in C:\Users\deeks\pandas-Deekshita\doc\source\user_guide/enhancingperf.rst line 101
The full traceback has been saved in C:\Users\deeks\AppData\Local\Temp\sphinx-err-8zh0n6cs.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!'


This is the line(line 101) referred to in enhancingperf.rst:
  %load_ext Cython
  
I've made no modifications to the file.


Environment:
Python 3.11.6
sphinx-build 7.2.6
ipython 8.20.0

**Comment by noah-asing** [comment]
I wasn't able to reproduce that error, although the `environment.yml` file specifies Python v3.10

Could you try the doc build once more with the provided env/dependencies and see if you still have problems?

**Comment by noah-asing** [comment]
take
