### ISSUE TITLE
Reader accept directory path with suffix check 

### ISSUE THREAD

**Issue by sciencecw** [pandas-dev/pandas#57662]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Most reader methods accept a directory. e.g. `pandas.read_parquet("/home/data/')`

The default behavior goes through every file and subdirectory in the path, regardless of file type. This is inconvenient when the directory includes a single log or metadata txt file 

### Feature Description

When returning a list of files, filter by file suffix 

### Alternative Solutions

N./A

**Comment by rhshadrach** [comment]
Thanks for the request!

> Most reader methods accept a directory. e.g. `pandas.read_parquet("/home/data/')`

parquet does this because of partitioned parquet files, a single parquet "file" can be a directory on disk. pandas is not doing any directory walking itself. Are there other readers that do this?

I'm opposed to using suffixes as information. They are common but not universal conventions.

**Comment by rohanjain101** [comment]
This enhancement should likely be made upstream in arrow, since arrow is doing the directory walking. Unfortunately, datasets in arrow currently recursively walk every file, even if you have 1 file that is not a valid parquet file. Perhaps instead of doing it based on extension, there should be a flag to skip any invalid parquet file in the directory, regardless of extension?

**Comment by sciencecw** [comment]
I agree with @rohanjain101 

I don't know any other reader doing this actually. I am not surprised this is an arrow issue. I second that skipping invalid file is a way forward

**Comment by sciencecw** [comment]
Thanks @rohanjain101 looks like that is what I need

**Comment by phofl** [comment]
closing then
