### ISSUE TITLE
PERF: Saving many datasets in a single group slows down with each new addition

### ISSUE THREAD

**Issue by Ieremie** [pandas-dev/pandas#58248]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

I found a strange behaviour that seems to appear only for PyTabels (Pandas).

Saving many datasets within a single group becomes progressively slower. 
```python
import pandas as pd

df = pd.DataFrame({'A': [1.0] * 1000})  
df = pd.concat([df] * 13, axis=1, ignore_index=True)

size = 5000
timings = []
for i in tqdm.tqdm(range(0, size), total=size):
    key = ''.join(random.choices(string.ascii_uppercase, k=20))

    start = time.time()
    df.to_hdf('test.h5', key=key, mode='a', complevel=9) 
    timings.append(time.time() - start)

plt.plot(timings[10:])
```
<img width="540" alt="image" src="https://github.com/PyTables/PyTables/assets/33784294/8eec4ecf-5d70-4074-b24b-624b74908314">

This is not the case for `h5py`, which can easily write up to 100 more datasets without slowing down.
```python
import h5py

timings = []
size  = 500000
with h5py.File('test2.h5', 'w', libver='latest') as hf:
    group = hf.create_group(f'group')
    for i in tqdm.tqdm(range(0, size), total=size):
        key = ''.join(random.choices(string.ascii_uppercase, k=20))

        start = time.time()
        group.create_dataset(key, data=df.values, compression="gzip", compression_opts=9) 
        timings.append(time.time() - start)

plt.plot(timings[10:])
```
<img width="546" alt="image" src="https://github.com/PyTables/PyTables/assets/33784294/4fda1146-c1b6-4bf1-b67e-2fa4a6fd2f79">

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

### Prior Performance

I have raised this issue in the Pytables repo and it seems it is actually an issue with pandas [https://github.com/PyTables/PyTables/issues/1155](url)

**Comment by rhshadrach** [comment]
Thanks for the report!

Between the first and the last run I'm seeing 0.2ms and 34ms spent in `tables.file.File.create_group` respectively. This is from this line here:

https://github.com/pandas-dev/pandas/blob/6e09e97c10ad7591ffcc7d638075bdf20de8294d/pandas/io/pytables.py#L1916

But I have no familiarity with this code or pytables, so not sure if this is a pandas issue.

**Comment by avalentino** [comment]
@rhshadrach the `create_group` method apparently has an execution time that depends on the number of notes in the hdf5 file.
This is only true for newly opened files because PyTables need to rebuild the internal cache of all nodes. While this behaviour can be debated the obvious workaround is to use an `HDFStore` instead of the filename in the call to `df.to_hdf` (as described in https://github.com/PyTables/PyTables/issues/1155#issuecomment-2053618667).

Unfortunately this doesn't work because apparently the `HDFStore` is converted back to a string ("stringfied") in 

https://github.com/pandas-dev/pandas/blob/6e09e97c10ad7591ffcc7d638075bdf20de8294d/pandas/io/pytables.py#L295-L302

From my point of view this is unexpected and I would be curious to understand if it is really necessary.

**Comment by Ieremie** [comment]
@rhshadrach I've tested this with HDFStore and it doesn't seem that the slow time is due to opening the file for every write.

```python
size = 50000

timings = []
for i in tqdm.tqdm(range(0, size), total=size):
    key = ''.join(random.choices(string.ascii_uppercase, k=20))

    start = time.time()
    with pd.HDFStore("test2.h5", 'w') as store:
        store.put(f'entry/{key}', df) 
    timings.append(time.time() - start)

plt.plot(timings[10:])
```
![image](https://github.com/pandas-dev/pandas/assets/33784294/5e00dfda-6a89-4740-ab9b-ca02c4d3727c)

**Comment by avalentino** [comment]
@rhshadrach in your example you are creating a new HDF3 file at each iteration so the file always has at most one group.
This introduces a constant delay.
Moreover I would not even expect issues when you use the `HDFStor.put` method, because it indeed does not re-open the file.
The problem comes when you move the HDFStore instantiation out of the loop and then use the `df.to_hdf` method.
In that case you have the number of groups increasing in the HDF5 file and, due to the strange behaviour that I highlighted above, and new HDFStore is created at each `to_hdf` call even if passes as input.

https://github.com/pandas-dev/pandas/blob/6e09e97c10ad7591ffcc7d638075bdf20de8294d/pandas/io/pytables.py#L295-L302

In this case you can observe the linear slowdown.

**Comment by Ieremie** [comment]
@avalentino right, my mistake. Opening with` with pd.HDFStore("test2.h5", 'a') as store:` makes things slow again.

**Comment by avalentino** [comment]
SorryI have just realised that I have not tagged the correct person in my previous post.

**Comment by Ieremie** [comment]
@avalentino Just for curiosity, how is the cache computed? I've noticed that if I split the datasets in multiple groups (still increasingly slow), it makes writing much faster even with the file reopening issue.

**Comment by rhshadrach** [comment]
From a quick look, it does appear straight forward to expand `to_hdf` to accept an `HDFStore` instance. If the implementation is indeed easy, I'm +1 on the enhancement. If for some reason it turns out to be much more difficult than I expect, I'm not necessarily opposed, but it will have to be evaluated and weighed against the maintenance burden.

PRs to add are welcome!

**Comment by avalentino** [comment]
@rhshadrach for what I can say both the documentation and the implementation seem to suggest that the `to_hdf` method has been designed to be able to use an `HDFStore` provided in input.
I have created a PR (#58275) that implements a very simple change to avoid systematic re-opening of the hdf5 file at each call to `to_hdf`.
