### ISSUE TITLE
Series.hist() fails for String Series

### ISSUE THREAD

**Issue by jankatins** [pandas-dev/pandas#5876]
Not sure if that's a pandas or a mathplotlib bug.

``` python
import pandas
df = pandas.DataFrame({"year":[1,2,3,4],"name": [u"abc", u"bcd", u"cde", u"abc"]})
df["year"].hist() # Works
df["name"].hist()
TypeError                                 Traceback (most recent call last)
<ipython-input-11-79a5ab7bbbd5> in <module>()
----> 1 df["name"].hist()

C:\portabel\Python27\lib\site-packages\pandas\tools\plotting.pyc in hist_series(self, by, ax, grid, xlabelsize, xrot, ylabelsize, yrot, figsize, **kwds)
   2113         values = self.dropna().values
   2114 
-> 2115         ax.hist(values, **kwds)
   2116         ax.grid(grid)
   2117         axes = np.array([ax])

C:\portabel\Python27\lib\site-packages\matplotlib\axes.pyc in hist(self, x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   8325             # this will automatically overwrite bins,
   8326             # so that each histogram uses the same bins
-> 8327             m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
   8328             m = m.astype(float) # causes problems later if it's an int
   8329             if normed and not stacked:

C:\portabel\Python27\lib\site-packages\numpy\lib\function_base.pyc in histogram(a, bins, range, normed, weights, density)
    174             else:
    175                 range = (a.min(), a.max())
--> 176         mn, mx = [mi+0.0 for mi in range]
    177         if mn == mx:
    178             mn -= 0.5

TypeError: coercing to Unicode: need string or buffer, float found
```

**Comment by themrmax** [comment]
I really want this feature, since most of the data I deal with is categorical, and so I can never use the convenience of `hist`. (This is also relevant to https://github.com/pydata/pandas/issues/8712 and maybe https://github.com/pydata/pandas/issues/10254) Philosophically, I think this type of behaviour could be seen as more like an enhancement for `bar`, rather than `hist` for example in R, by default `geom_bar` will plot the value counts; you only get the actual values if you pass `stat="identity"` (opposite of the behaviour of `pandas.plot.bar`). So maybe this could also be referenced inside `BarPlot` via an optional `value_counts` flag.

I've hacked together something which provides this functionality using the Pandas `DataFrame.plot` API. Would this be suitable for merging into `tools.plotting`? My concern is that `tools.plotting` is mostly written using native calls to `matplotlib`, is it a problem to have calls to a Pandas API inside this library. 

Apologies if this is a dumb question, or if I'm rasing this in the wrong place, this would be my first contribution to Pandas and I'm having trouble wrapping my head around exactly where this fits in.


    def categorical_hist(data,column=None,by=None,layout=None,legend=None,**params):
      """
          Draw a bar plot of value counts. If layout=none, layout will be a square 
          grid, overriding the DataFrame.plot default of a single column of 
          stacked plots

          Parameters
          ----------
          data : DataFrame or Series
          column : object, optional
              the column to plot (only valid if data is a dataframe)
          by : object optional
              if passed, then used to form bar plots for separate groups
          layout : (int,int), optional
              a tuple (width, height) of the subplots grid
          legend : False/True/'reverse'
              place legend on axis subplots
          kwds : other plotting keyword arguments

      """
      from math import sqrt, ceil
      from pandas import DataFrame
      
      if column is None: column = data.name #if data is a Series, need to set this
      data = DataFrame(data) #if data is a series, make it a DataFrame
      
      if by is not None:
        if layout==None:
          s = ceil(sqrt(data[column].unique().size))
          layout = (s,s)
        data = data.groupby(by).value_counts().sort_index().unstack()
        return data[column].plot.bar(subplots=True,layout=layout,
                                     legend=legend,**params)
      return data[column].value_counts().plot.bar(subplots=False,layout=layout,
                                                  legend=legend,**params)

**Comment by datapythonista** [comment]
This doesn't raise an error anymore, it generates a plot. Not sure if the plot is meaningul, it's not equivalent to `df["name"].value_counts().plot(kind="bar")`. May be we can review in a separate issue the content of the plot, if that hasn't already been reported. Closing this issue.

Example output:

`pandas.Series(['a', 'a', 'b', 'b', 'b', 'c'], dtype='object').hist()`

![str_hist](https://user-images.githubusercontent.com/10058240/42401025-b0405b6e-816b-11e8-9506-0fa99b722d34.png)
