### ISSUE TITLE
BUG: pd.api.extensions.take does not accept NumpyExtensionArray

### ISSUE THREAD

**Issue by andrewgsavage** [pandas-dev/pandas#59177]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd 
import numpy as np

arr = pd.arrays.NumpyExtensionArray(np.array([1,2,3]))
pd.api.extensions.take(arr,[2])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\mambaforge\envs\test_py300\Lib\site-packages\pandas\core\algorithms.py", line 1166, in take
    raise TypeError(
TypeError: pd.api.extensions.take requires a numpy.ndarray, ExtensionArray, Index, or Series, got NumpyExtensionArray.
```

### Issue Description

I'd expect NumpyExtensionArray to be considered an ExtensionArray, so compatable with pd.api.extensions.take.

### Expected Behavior

return
```
<NumpyExtensionArray>
[2]
Length: 1, dtype: int32
```

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by Aloqeely** [comment]
Thanks for the report! I'm surprised that `NumpyExtensionArray` fails the `isinstance` check. cc @jbrockmendel

On a separate matter, is there a specific reason you're using `NumpyExtensionArray`? I don't think there are many benefits to using it.

**Comment by mutricyl** [comment]
For the record this issue is linked to pint-pandas development and particularly https://github.com/hgrecco/pint-pandas/pull/239.

New version of `pandas.core.algorithms.take` function introduced in #52981 is very restrictive and I wonder why `NumpyExtensionArray` is not in the list.

`NumpyExtensionArray` is used as  `pd.array` is used in `PintArray` constructor. Depending on provided dtype `pd.array` will result on a `ExtensionArray` subclass or will fall back on `NumpyExtensionArray`.

For example:

```python
>>> pd.array([1+1j,2,3]).dtype  
NumpyEADtype('complex128') # NumpyExtensionArray
>>> pd.array([1,2,3]).dtype    
Int64Dtype() # ExtensionArray
```

There is no build in pandas `ExtensionArray` for complex so pd.array falls back to `NumpyExtensionArray`

**Comment by rhshadrach** [comment]
If the check is disabled, the take operation appears to work without issue. Agreed this should work - PRs to fix are welcome.

**Comment by mutricyl** [comment]
take
