### ISSUE TITLE
BUG: Timestamp.asm8 has different behavior depending on how it was constructed

### ISSUE THREAD

**Issue by Aloqeely** [pandas-dev/pandas#59184]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [2]: ts1 = pd.Timestamp(year=2023, month=1, day=1, hour=10, second=15)

In [3]: ts2 = pd.Timestamp('2023-01-01 10:00:15') #  ts1 and ts2 are equal

In [4]: np.int64(ts1.asm8)
Out[4]: 1672567215000000

In [5]: np.int64(ts2.asm8)
Out[5]: 1672567215
```

### Issue Description

In the [timestamp.asm8 doc](https://pandas.pydata.org/docs/dev/reference/api/pandas.Timestamp.asm8.html) it states "Return numpy datetime64 format in nanoseconds.", but, it has different (wrong) behavior when I construct the timestamp from a string, returning in seconds format. Any thoughts @MarcoGorelli?

### Expected Behavior

I would expect `np.int64(ts2.asm8)` to be equal to `1672567215000000000`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 1b2d39cbfc3db9520e0f5455a4eb3da0f569fa0f
python                : 3.12.1
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : English_United States.1252

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
pip                   : 24.0
Cython                : 3.0.10
sphinx                : 7.3.7
IPython               : 8.23.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : 1.3.8
fastparquet           : 2024.2.0
fsspec                : 2024.3.1
html5lib              : 1.1
hypothesis            : 6.100.1
gcsfs                 : 2024.3.1
jinja2                : 3.1.4
lxml.etree            : 5.2.1
matplotlib            : 3.8.4
numba                 : 0.59.1
numexpr               : 2.10.0
odfpy                 : None
openpyxl              : 3.1.2
psycopg2              : 2.9.9
pymysql               : 1.4.6
pyarrow               : 16.1.0
pyreadstat            : 1.2.7
pytest                : 8.1.1
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 2024.3.1
scipy                 : 1.13.0
sqlalchemy            : 2.0.29
tables                : 3.9.2
tabulate              : 0.9.0
xarray                : 2024.5.0
xlrd                  : 2.0.1
xlsxwriter            : 3.2.0
zstandard             : 0.22.0
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by ritwizsinha** [comment]
I think there is a mistake in the docs here.
ts1.asm returns data in microseconds not nanoseconds, and ts2.asm returns data in seconds not milliseconds. So the return type doesn't follow documentation for both ts1 and ts2.

Moving on and addressing the issue.

The datestring is parsed by a c function [parse_iso_8601_datetime](https://github.com/pandas-dev/pandas/blob/dcb5494e511cee9643ce3748d4450a97ed1a7c03/pandas/_libs/src/vendored/numpy/datetime/np_datetime_strings.c#L110). This function specifies the units based on the precision it encounters in the string. For example:

`ts2 = pd.Timestamp('2023-01-01 10:00:15.000000')` it will give the precision of microseconds, but for 
`ts2 = pd.Timestamp('2023-01-01 10:00:15)` it gives the precision of seconds.


Then after creating the datetime struct from the string we identify its resolution [here](https://github.com/pandas-dev/pandas/blob/dcb5494e511cee9643ce3748d4450a97ed1a7c03/pandas/_libs/tslibs/conversion.pyx#L614) using [get_supported_reso](https://github.com/pandas-dev/pandas/blob/dcb5494e511cee9643ce3748d4450a97ed1a7c03/pandas/_libs/tslibs/dtypes.pyx#L512).

Clearly this function returns resolution of seconds, same as what was determined earlier and thus we print in a precision of seconds in asm8 function because it simply reads the resolution which was set at the time of reading.

For the former case, while creating a tsobject a precision of microseconds is determined [here](https://github.com/pandas-dev/pandas/blob/dcb5494e511cee9643ce3748d4450a97ed1a7c03/pandas/_libs/tslibs/conversion.pyx#L409)
Thus it outputs in microseconds.

Maybe the docs need to be updated for this

**Comment by Anurag-Varma** [comment]
If this is a good first issue can i get it assigned to me

**Comment by Anurag-Varma** [comment]
take

**Comment by Aloqeely** [comment]
The doc of `asm8` says it returns nanoseconds format datetime while the doc of `to_datetime64` says it returns same precision datetime. The problem here is that `asm8` is aliased to `to_datetime64` so why do the docs differ?

I'm leaning towards fixing `asm8` rather than changing the docs and treating it as an alias for `to_datetime64`.

**Comment by jbrockmendel** [comment]
The behavior is correct, the doc needs updating,  ts.asm8 returns a dt64 object with the same unit as ts.unit

**Comment by Anurag-Varma** [comment]
@jbrockmendel But when using `pd.Timestamp(year=2023, month=1, day=1, hour=10, second=15)`

We are mentioning only until seco ds right, but it's returning in micro seconds. Is this also correct  ?
