### ISSUE TITLE
QST: Why Doesn't Pandas Have an Insert Index Function or Method?

### ISSUE THREAD

**Issue by MasonDye** [pandas-dev/pandas#60163]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/69995045/inserting-values-at-an-index-position-in-pandas-df

### Question about pandas

I encountered a problem while trying to insert an index with Pandas. I couldn’t find any built-in function or method in Pandas for inserting an index. In most articles, I only found a few methods listed below, which I find to be cumbersome and potentially problematic in terms of performance. Is there a related function or method in Pandas that allows for direct index insertion?

**Comment by rhshadrach** [comment]
You didn't list any methods, but I'm guessing they are akin to this.

```python
df = pd.DataFrame({"a": [0, 1, 2]})
pos = 1
new_row = pd.DataFrame({"a": 3}, index=[4])
new_df = pd.concat([df.iloc[:pos], new_row, df.iloc[pos:]])
print(new_df)
#    a
# 0  0
# 4  3
# 1  1
# 2  2
```

pandas does not expose such a method because it would be inefficient (all data would need copied, indexes rebuilt). If you are building a DataFrame, it is best to get all the data before making the DataFrame itself. Inserting / appending to a Dataframe is expensive.
