### ISSUE TITLE
Improve documentation for pandas.core.groupby.GroupBy.transform

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#6257]
Currently there is no documentation (other than the signature) for `pandas.core.groupby.GroupBy.transform`.

For example passing the string `"shift"` works and shifts the results.

**Comment by jorisvandenbossche** [comment]
In the meantime, we have a nice docstring for DataFrameGroupby/SeriesGroupby.transform, but it would be nice to put the same docstring in the `GroupBy.transform` method as well, so this one shows up in the online docs: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.GroupBy.transform.html#pandas.core.groupby.GroupBy.transform

Since the docstring already exists, this should be an easy fix.

**Comment by jreback** [comment]
this is already done
