### ISSUE TITLE
NaN values impact binary or operations asymmetrically

### ISSUE THREAD

**Issue by behzadnouri** [pandas-dev/pandas#6528]
I am not sure if this is on purpose, but as far as I know, `or` operation should be symmetric ( I mean `a | b == b | a` ); not in pandas:

```
>>> a = pd.Series( [True] )
>>> b = pd.Series( [np.nan] )
>>> a | b
0    True
dtype: bool
>>> b | a
0    False
dtype: bool
```

is there any reason pandas is treating `NaN` values asymmetrically in here?

also, this is a weird outcome as well:

```
>>> ( b == True ) | ( a == True )
0    True
dtype: bool
```

and this:

```
 >>> b.astype( bool )
 0    True
 dtype: bool
```

this even has internal inconsistency; so before in `b | a`, `NaN` was treated as `False`, but now here it is `True`;

**Comment by h-vetinari** [comment]
Tried to find the most current open issue on this - the others are closed or merged, but this is open even though being milestoned since 0.14?

I asked a question about this on stackexchange, and someone took the time to identify the apparent source of the issue (as well as a work-around): https://stackoverflow.com/a/47664356/2965879

The main issue seems that in pandas.core.ops.wrapper (https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L928), after aligning the series, only `other` is filled (transforming NaN to False), but `self` isn't, which introduces this symmetry break.

**Comment by TomAugspurger** [comment]
I don't expect the behavior of `np.nan` in boolean operations to change, but https://github.com/pandas-dev/pandas/pull/29842 is implementing a new BooleanArray extension type that I think addressees most things. Let us know if there are additional problems in new issues.
