### ISSUE TITLE
MonthOffset() gives increase of 1 day instead of 1 month

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#7707]
From https://github.com/pydata/pandas/pull/7375#issuecomment-48465256:

```
In [67]: from pandas.tseries import offsets

In [69]: d = pd.Timestamp('2014-01-01 09:00:00')

In [70]: d + offsets.MonthOffset()
Out[70]: Timestamp('2014-01-02 09:00:00')

In [71]: offsets.MonthOffset().apply(d)
Out[71]: Timestamp('2014-01-02 09:00:00')

In [72]: d + offsets.Day()
Out[72]: Timestamp('2014-01-02 09:00:00')
```

**Comment by jbrockmendel** [comment]
This is semi-closed by #18375.  MonthOffset should never be used directly, will now raise NotImplementedError if you try the addition or `apply` in the OP.  MonthOffset, QuarterOffset, YearOffset are base classes that should probably be privatized.

Or they could be adapted so that the base classes are non-anchored and just increment by 1, 3, and 12 months respectively.

**Comment by jreback** [comment]
@jbrockmendel ok, can you add this to the API breaking section 

and add some tests that these now raise NotImplementedError (use #18375 issue).

**Comment by jbrockmendel** [comment]
Out of town for a couple days, will address then when no longer typing with thumbs

**Comment by ron819** [comment]
Any chance this will be fixed for the next release?

**Comment by mroeschke** [comment]
Looks like this has been effectively privatized. Going to close.

```
In [4]: In [70]: d + offsets.MonthOffset()
   ...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-c6cd081d9308> in <module>
----> 1 d + offsets.MonthOffset()

AttributeError: module 'pandas.tseries.offsets' has no attribute 'MonthOffset'
```
