### ISSUE TITLE
VIS: DataFrame.plot drops datetime data when kind is scatter

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#8113]
This works fine:

``` python
In [13]: df = pd.DataFrame(np.random.randn(300), columns=['a'])
In [14]: df['dtime'] = pd.DatetimeIndex(start='2014-01-01', freq='h', periods=300).time
In [15]: df.plot(x='dtime', y='a')
Out[15]: <matplotlib.axes._subplots.AxesSubplot at 0x118fd17f0>
```

This raises a `KeyError`

``` python
In [17]: df.plot(x='dtime', y='a', kind='scatter')
```

We call `df._get_numeric_data()` which excludes datetimes.
May happen for other kinds too.

I'll fix this; just have to decide how much refactoring.

Matplotlib is ok with `datetime.time` values, it chokes on `datetime` values.

**Comment by stared** [comment]
@JeffAbrahamson By any chance did you find a way to plot time vs time scatterplots or histograms? (I tried, but failed, and Google brought me here and to [this SO question](http://stackoverflow.com/questions/25570071/pandas-serie-dtype-is-datetime-date-how-to-plot).)

**Comment by JeffAbrahamson** [comment]
Hi, Piotr.

I don't think that's me!  I remember being interested in the question last
year (though I can't remember why just now), but the related but different
question I posted (and answered, with help!) was this one
<http://stackoverflow.com/questions/27001068/plotting-labled-time-series-in-pandas>
.

If you find my involvement in the above, tell me: the date and phrasing
might help me figure out what I was doing and so how I resolved it.  And if
you figure it out, do let me know, I'm sure I'll have need some day!

Regards,

Jeff Abrahamson
+33 6 24 40 01 57
+44 7920 594 255    <-- only if I'm in the UK

http://jeff.purple.com/
http://blog.purple.com/jeff/

**Comment by ajschumacher** [comment]
Hi @TomAugspurger and @jreback! I think it might be worth re-opening this issue; @jaclynweiser (with a few others) and I have been surprised recently by things like this:

```Python
from datetime import datetime
import pandas as pd
df = pd.DataFrame({'x': [datetime.now() for _ in range(10)], 'y': range(10)})
df.plot(x='x', y='y', kind='scatter')
```

This gives `KeyError: 'x'`.

Interestingly, you _do_ get a plot with just `df.plot(x='x', y='y')`; it seems like if you can make a line graph, you should be able to make a scatterplot too.

What do you think? Is there some a good work-around for this? If so, what? It's surprising to me that a datetime scatterplot isn't possible with pandas.

**Comment by TomAugspurger** [comment]
Agreed that it's surprising. Right now time series plots (datetime x axis) are completely separate from everything else. I've had refactoring all that to integrate with all our other plotting code on my todo list for a while. 


Best workaround right now is probably df.plot(x=x, y=y, style=".")

**Comment by ajschumacher** [comment]
Thanks @TomAugspurger!

**Comment by cboettig** [comment]
Yup, found this rather surprising as well, not to be able to scatterplot a datetime object against a numeric object.  (If I've followed the thread correctly, I should be okay with a `datetime.time` object, but it seems `pd.to_datetime` naturally gives a `datetime`, and pandas doesn't give me an equivalent method to get a `datetime.time`?)  

Isn't `df.plot(x, y, style=".")` very misleading?  I mean, scatter plots are meant to show the underlying data, which, for instance, need not be sampled at a regular interval.  `style = "."` is just doing a line plot with dots instead of dashes, right?  This would give a misleading impression about both the regularity and frequency of sampling (which is usually my main motivation for plotting time series as a scatterplot instead of a line plot in the first place).  Seems that explicitly converting the dates decimals would be a better work-around, though it results in much less pretty axis labels (at least without a bit more plot-magic than I can quickly drum up).  

(Also, apologies if I'm off the mark here, am relatively new to pandas.  Thanks for considering).

**Comment by colin-svds** [comment]
Any update on this? As of 0.18, pandas still gives a key error when plot is called with `kind='scatter` and a `datetime` column.

**Comment by jreback** [comment]
@colin-svds this is a closed issue (from quite a while ago). you can open a new one if you would like. but pls read this one for work-arounds. I don't know if @TomAugspurger has anything more.

**Comment by TomAugspurger** [comment]
Nope I haven't ever made progress on it.

**Comment by nehaljwani** [comment]
FWIW, till this issue is fixed people can still use this directly:

```
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
df = pd.DataFrame({'x': [datetime.now() for _ in range(10)], 'y': range(10)})
plt.scatter(df.x.dt.to_pydatetime(), df.y)
plt.show()
```
![figure_1-2](https://cloud.githubusercontent.com/assets/1779189/18180159/3d8d039a-70a3-11e6-905a-cf6094ff9e57.png)

**Comment by RahulRAhhy123** [comment]
Any solution for this as if now @TomAugspurger @jreback ?

**Comment by TomAugspurger** [comment]
It's still open. Let us know if you're interested in working on it.

**Comment by charlesdong1991** [comment]
I think this issue can be closed now. @TomAugspurger @jreback 

Regarding:
> Matplotlib is ok with `datetime.time` values, it chokes on `datetime` values.

Since Tom might test it long ago (PR was made 5 years ago), and matplotlib changed the behaviour, now the situation is opposite: matplotlib is ok with `datetime` values but chokes on `datetime.time` values

And if `datetime` values, i tried on master, and seems look okay to me:
![Screen Shot 2020-01-01 at 1 45 08 PM](https://user-images.githubusercontent.com/9269816/71641480-f4b14500-2c9c-11ea-8327-93c93d6217f3.png)

Although x axis looks different, this is due to pandas has its own datetime formatter, so slightly different than matplotlib's formatter. but this is a different issue to me.

**Comment by jreback** [comment]
@charlesdong1991 can u add a test for the above

**Comment by charlesdong1991** [comment]
@jreback I think the test I used in #30434 is almost identical to this one except for the `freq`, see below which is in test case of 30434:
```python
dates = pd.date_range(start=date(2019, 1, 1), periods=12, freq="W")
vals = np.random.normal(0, 1, len(dates))
df = pd.DataFrame({"dates": dates, "vals": vals})
```

The reason I initially xref (other than closes) this issue was the values of example above was `datetime.time`, and I just tested and found out `datetime.time` was no longer supported by matplotlib, but `datetime` is supported. Therefore, I think this could be directly closed.

Do you still want to have the same test for this? I could add one if you prefer this way, though a bit duplicated compared to the existing one.

**Comment by jreback** [comment]
can u add the test and assert that error; that would be enough to close this i think

**Comment by charlesdong1991** [comment]
ok @jreback  see #30602
