### ISSUE TITLE
Strip header names?

### ISSUE THREAD

**Issue by mrocklin** [pandas-dev/pandas#9067]
In csv files that have odd spacing

```
name,    amount
Alice,100
Bob,200
```

Loaded dataframes can sometimes have column names with leading or trailing whitespace.  Should these column names be stripped by default?

``` Python
In [4]: pd.read_csv('foo.csv').columns
Out[4]: Index([u'name', u'    amount'], dtype='object')
```

**Comment by imadcat** [comment]
This default behavior just wasted me several hours trying to figure out why there's a key error when joining two data frames read from CSVs. It's really difficult to see there are leading spaces in a column's name from python terminal output.

**Comment by gitgithan** [comment]
Could it be a useful feature to add to warn users of leading/trailing spaces in index/column names when using importing functions?

**Comment by rhshadrach** [comment]
I'm -0 here; to me the most expected behavior of `pd.read_csv('filename.csv')` is to read the csv file with no additional processing. Changing the result, even if it's thought to be a very common use case, is unexpected. This agrees with a common [CSV specification](https://tools.ietf.org/html/rfc4180#section-2):

> Spaces are considered part of a field and should not be ignored.

But of course, there is no true standard.

**Comment by phofl** [comment]
duplicate with #14460
