### ISSUE TITLE
BUG: Exception raised for a duplicate MultiIndex level name

### ISSUE THREAD

**Issue by seth-p** [pandas-dev/pandas#9399]
The following two tests seem inconsistent. Why does the first test for a `KeyError` while the second tests for a `ValueError`? Also, the first error message, `Level foo not found`, doesn't seem correct.

`test_index.py`:

```
    def test_duplicate_names(self):
        self.index.names = ['foo', 'foo']
        assertRaisesRegexp(KeyError, 'Level foo not found',
                           self.index._get_level_number, 'foo')
```

`test_frame.py`:

```
    def test_unstack_non_unique_index_names(self):
        idx = MultiIndex.from_tuples([('a', 'b'), ('c', 'd')],
                                     names=['c1', 'c1'])
        df = DataFrame([1, 2], index=idx)
        with tm.assertRaises(ValueError):
            df.unstack('c1')

        with tm.assertRaises(ValueError):
            df.T.stack('c1')
```

**Comment by shoyer** [comment]
I agree -- that first error looks very strange. It's particularly strange that the test is for a private method. We probably should be checking for duplicate names when `index.names` is set, and should be raising `ValueError`.

**Comment by jreback** [comment]
private methods should be explicity tested just as public api methods.

The issue here is this. a ``MultiIndex`` technically can have duplicate names, but in point of fact they are pretty much useless and tend to break / degrade other ops. E.g. stack/unstack, and make your columns duplicate when reset. So I think we should actually raise on construction to solve this entire problem.

So names can be:

- None (where they get defaulted level numbers)
- unique integers / names
- None / mixed integers/names (usually arise from non-named reduction ops).

**Comment by seth-p** [comment]
Sounds good to me!

**Comment by mroeschke** [comment]
Seems like there hasn't been much interest in this feature over the years so closing
