### ISSUE TITLE
Undocumented API changes in groupby.apply

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#9447]
At some time [last year](https://github.com/pydata/pandas/issues/4646#issue-18447522), 

```
pd.DataFrame([[1, 2], [2, 3], [1, 4], [1, 5], [2, 6]]).groupby(0).apply(lambda x: pd.Series(np.arange(len(x)), x.index))
```

would return

```
0    0
1    0
2    1
3    2
4    1
dtype: int64
```

In 0.14, it returns 

```
0
1    0    0
2    1
3    2
dtype: int64
2           1    0
4    1
dtype: int64
dtype: object
```

while in current git snapshot, it returns

```
1  0    0
   2    1
   3    2
2  1    0
   4    1
dtype: int64
```

No nostalgia... but would it make sense to refer to the different behavior in different versions in the documentation of GroupBy.apply()?
Moreover: the (last version of the) docs say "case 2: group DataFrame apply transform function ((f(chunk) -> DataFrame with same indexes) yield DataFrame with resulting chunks glued together", and I think this is the case which applies. However the docs omit to mention "with group axis having group labels", as they do instead for case 1 (f(chunk) -> Series).

I will/would gladly submit a PR to enhance the docs... once I myself understand how things are supposed to work.

**Comment by jreback** [comment]
well this was fixed in 0.14 mentioned here: http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#groupby-api-changes
iirc then needes a bug fix in 0.14.1. there are also big warning sections (in red) that highlite what the different groupby operators are supposed to do

you happened upon a case that is really just a bug and did not do what it states it should have done
so you were relying on the bug

this is the point of the whatsnew and the docs represent a single versions
if u upgrade then it is your responsibility to read the whatsnew 
that is where changes are documented that could break the api

I suppose there could be a bit more of the whatsnew behavior in the current docs

so if u find things unclear then propose a pull request to clarify

**Comment by toobaz** [comment]
I had read the page you linked, but I didn't find anything applying to my case. I see "groupby will now not return the grouped column for non-cython functions (GH5610, GH5614, GH6732), as its already the index"... but in my case it's the index level which appears/is missing, not the column.

Anyway, I will propose a PR for the autogenerated docs (because from the current docs I would expect the behavior of last year, i.e. without group column).

**Comment by jreback** [comment]
you need to actually look at those issues
for the case iirc

**Comment by JohnM-TX** [comment]
Is this issue still relevant? Sounds like it may be resolved.

**Comment by mroeschke** [comment]
Guessing since the change has been in master for 4 years now, not sure if the change need to be documented anymore. Closing.
