### ISSUE TITLE
DOC: merge FAQ / Caveats & Gotchas

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#9809]
xref #9802
- I think making it FAQ would most appropriate
- want to think about the orderings
- need a release note to indicate that these have been merged

**Comment by kay1793** [comment]
that's the wrong issue and...

> need a release not to indicate that these have been merged

your grammer subsystem is acting up. again. :scream_cat:

**Comment by shoyer** [comment]
Agreed, would be nice to consolidate these.

Looking over these pages again, several of the FAQ sections ("Migrating from scikits.timeseries" and "Visualizing Data in Qt applications") look very outdated and could probably be removed.

**Comment by jreback** [comment]
the Visualizing Data is marked as ``deprecated`` already (but its only docs here, can prob just take it out)

**Comment by jreback** [comment]
should also think about the 3 indexing mentions in the Caveats and Gotchas and whether these should really be in one of the indexing sections.
```
- Integer indexing -> move to advanced.rst
- Label-based slicing conventions -> move to indexing.rst
  - Non-monotonic indexes require exact matches
  - Endpoints are inclusive
- Miscellaneous indexing gotchas
  - Reindex versus ix gotchas 
  - Reindex potentially changes underlying Series dtype (needs a note in reindex section / indexing)
```

**Comment by jorisvandenbossche** [comment]
Also agree we can merge these sections. 
Although FAQ is maybe a good name, I also like the 'gotchas' wording, as it really are some typical 'gotchas' (frequently asked questions sounds more oriented to newcomers to me with questions about the project, while the content is not quite like that).

I think we should also move some parts to the actual documentation on that issue, eg the indexing questions that @jreback noted, but I think also the html parsing issues

**Comment by mbirdi** [comment]
In the earlier part of this thread, it mentions parts of the documentation which "look very outdated and could probably be removed."

I don't know if removing parts of the documentation is a novice level task.  I am a novice when it comes to python and pandas, and when I read the documentation of a python library, I generally believe it all.  I have not really thought to myself, this is can be removed when I have read the docs.  I think the difficulty level of this task should be raised to intermediate, since you need to know how things have changed in the different pandas versions over time.
