### ISSUE TITLE
Poor read_csv performance on file with many columns

### ISSUE THREAD

**Issue by tloredo** [pandas-dev/pandas#9969]
A student came to me for help using PyData tools for processing data in many-column CSV files. The files have 2740 rows; the longer file has 50k columns of floats, the smaller has 2740 columns of 0/1 binary data (defining a graph).

She currently is using numpy.loadtxt to read the files; the float file takes ~10 - 15 min to read on various Macs we've benchmarked. I was aware of benchmarks such as these indicating poor performance of loadtxt vs. various alternatives, including Pandas:

Fastest Python library to read a CSV file
http://softwarerecs.stackexchange.com/questions/7463/fastest-python-library-to-read-a-csv-file

A new high performance, memory-efficient file parser engine for pandas
http://wesmckinney.com/blog/a-new-high-performance-memory-efficient-file-parser-engine-for-pandas/

I suggested she try Pandas; she reported it performed _worse_ than loadtxt.  This puzzled me, so I did some benchmarks. I duplicated the benchmarks in the SO post linked above, showing Pandas greatly outperforming loadtxt on a many-row, few-column CSV file; this likely rules out a problem with our installations (we are both using current Anaconda Python 2.7). I also duplicated her poor Pandas performance on the large float file.

I've put a MWE online here:

https://dl.dropboxusercontent.com/u/40075366/BDA2015/CSV_MWE.zip

That unpacks to a benchmark script and two large data files; it's a 500 kB .zip archive but it unpacks to 59 MB (otherwise I would have just posted a Gist). The data files are truncated to 10% of full size. The results on my 2009 quad-core Mac Pro (48 GB RAM) are:

```
loadtxt, float file laps:
  * CSV:  8.576581 s
  * csr_matrix:  180.887938 ms
Total elapsed time = 8.757631 s

loadtxt, graph file laps:
  * CSV:  386.301041 ms
  * csr_matrix:  22.848845 ms
Total elapsed time = 409.296036 ms

pandas, float file elapsed time = 17.595026 s

iopro, float file elapsed time = 473.067179 s
```

Notably, IOPro performs abysmally with the float file.

Perhaps this is just not a use case Pandas was designed to address. Any advice on the fastest way to read such wide CSV files in Python would be appreciated.

**Comment by jreback** [comment]
well here are some timings

File as described
```
In [3]: %timeit read_csv("Downloads/MWE/speech_vectors_short.csv")
1 loops, best of 3: 10.5 s per loop
```
 
Don't interpret NA's; force the dtype
```
In [2]: %timeit read_csv("Downloads/MWE/speech_vectors_short.csv",dtype='float64',keep_default_na=False)
1 loops, best of 3: 7.03 s per loop
```

Here is a transposed version
```
In [7]: df.T.to_csv('test.csv')

In [8]: %timeit pd.read_csv('test.csv')
1 loops, best of 3: 1.93 s per loop
```

so about 3x faster on the transposed. Not suprising at all. Each column individuall get's inferred for its type; this is what takes all the time. 

Very wide tables are not the usual way of string tabular data. I would simply store your data transposed. I am not sure you are going to get much speeds doing anything else. 

On the transposed version I am getting 25 MB/s (which is pretty reasonable given I have a regular disk)
so 3x slowdown for the same data, but stored in a format which needs more work to interpret is ok IMHO.

I was able to make a 1-line change. To have a 2x speedup (from the above), or 3x over existing. However, this may have farther reaching ramifications, eg.. amount of memory used, or perf on row-based. Basically this changes the function for determining how much to read in a single chunk when processing (which is an inverse function of the table size).

```
In [2]: %timeit read_csv("../Downloads/MWE/speech_vectors_short.csv",dtype='float64',keep_default_na=False)
1 loops, best of 3: 2.83 s per loop
```

So if someone wants to profile, would appreciate. Here's the change: https://github.com/pydata/pandas/blob/master/pandas/parser.pyx#L514 (I randomly tried 2**30).

Further I could imagine 2 more enhancements:
- an option to ignore INF/-INF parsing (which might break your data), but could potentially speed it up a lot (cuts about 1s off parsing time)
- an option to just try to astype the entire structure rather than parsing it in-memory (not sure how much of a diff this would make)

**Comment by tloredo** [comment]
@jreback: Thanks for the benchmarks, advice, and parse.py revision!

I should have mentioned that I'd already tried fixing the type, using dtype=float (I'm guessing this is the same as dtype='float64'; the resulting dataframe has float64 dtypes); it had a negligible impact on performance, which really surprised me as I originally thought the performance penalty was at least in part due to type inference. The keep_default_na=False argument was not something I would have thought to try; it has a greater impact on my platform than the dtype setting (best of 3 results):

pandas, vector file laps:
  * No dtype:  15.895569 s
  * float:  15.566296 s
  * float64:  15.780505 s
  * Add default_na:  10.713563 s

I can verify the 3x speedup from your patch:

pandas, vector file laps:
  * No dtype:  4.847848 s
  * float:  5.160179 s
  * float64:  4.986040 s
  * Add default_na:  4.397989 s

Interestingly, the patch appears to make the dtype and keep_default_na settings more or less irrelevant.

Thanks again for looking into this.

**Comment by mroeschke** [comment]
Unsure if there's any actionable follow up here so closing for now
